### ISSUE TITLE
Google and some other client does not recognize invitation updates

### ISSUE THREAD

**Issue by p5n** [nextcloud/calendar#1280] opened 2019-05-16 13:36 UTC
### Steps to reproduce
1. Create even in nextcloud web calendar
2. Add attendies from @gmail.com for example
3. Create event
4. (google has problems even here, it does not show buttons to say that I will attend)
5. After accepting invitation into google calendar update it from nextcloud web calendar
6. Google does not allow to update event

Same steps done from thunderbird works as expected.

### Expected behaviour
Google shows accept buttons

### Actual behaviour
There is no accept buttons. First invite added to calendar somehow, invitation update cannot be added.

### Server configuration
**Operating system**: ArchLinux
**Web server:** Apache
**Database:** Mysql
**PHP version:** 7.3.4
**Server version:** 16.0.1
**Calendar version:** 1.7.0

**Updated from an older installed version or fresh install:** long history of updates from owncloud 6 or so.

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- 3rdparty/sabre/vobject/lib/ITip/Broker.php.my
		- 3rdparty/sabre/vobject/lib/Component.php.my

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [3rdparty/sabre/vobject/lib/ITip/Broker.php.my] => Array
                        (
                            [expected] => 
                            [current] => b26a64e0508036f4c03cebb1c98da2aad40c1ce85b797140d59377fc600781654230bdb8abef2ac91eeeca50e730973e2cd7006be4fa024b687551ae49e9f49b
                        )

                    [3rdparty/sabre/vobject/lib/Component.php.my] => Array
                        (
                            [expected] => 
                            [current] => 3df6f0f3e600a4581119fe2e97092cd5da442f949e73ce0c383b780514aa90c915c5599748f4752f4752906c75d7a512688863729a8a2f176cef4467fdcbf550
                        )

                )

        )

)

```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bookmarks: 1.0.3
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.0
  - notes: 2.6.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.1.6
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - rainloop: 6.0.2
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - social: 0.1.4
  - spreed: 6.0.0
  - support: 1.0.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - user_ldap: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - password_policy
  - survey_client
  - updatenotification
```

**Are you using encryption:** no

```
Nextcloud calendar diff:
$ diff event\ \(1\).ics event\ \(2\).ics 
26,27c26,27
< DTSTART;TZID=Europe/Moscow:20190520T000000
< DTEND;TZID=Europe/Moscow:20190520T010000
---
> DTSTART;TZID=Europe/Moscow:20190519T000000
> DTEND;TZID=Europe/Moscow:20190519T010000

Thunderbird lightning diff
$ diff event\ \(3\).ics event\ \(4\).ics 
17,18c17,18
< LAST-MODIFIED:20190516T132215Z
< DTSTAMP:20190516T132215Z
---
> LAST-MODIFIED:20190516T132302Z
> DTSTAMP:20190516T132302Z
25,26c25,26
< DTSTART;TZID=Europe/Moscow:20190520T170000
< DTEND;TZID=Europe/Moscow:20190520T180000
---
> DTSTART;TZID=Europe/Moscow:20190522T170000
> DTEND;TZID=Europe/Moscow:20190522T180000
27a28,29
> SEQUENCE:1
> X-MOZ-GENERATION:1
```

The problem can be reproduced also from apple mail for example, so may be problem is in caldav server but not in calendar application.

**Comment by georgehrke** [comment] 2019-05-16 14:44
In your diffs, i can see that Thunderbird sets a sequence, but Nextcloud fails to do so. That's probably the reason.

**Comment by p5n** [comment] 2019-05-16 14:55
Maybe, thunderbird also updates LAST-MODIFIED and DTSTAMP

**Comment by vimmerru** [comment] 2019-05-16 14:59
> In your diffs, i can see that Thunderbird sets a sequence, but Nextcloud fails to do so. That's probably the reason.

It is obvious difference, but i am not sure that it is root cause. If you create/update event from Apple Mail using google as CalDav provider it also produces sequence=0, but event update can be handled correctly by any client.

**Comment by p5n** [comment] 2019-05-16 15:06
I compared webcalendar and thunderbird initial invitations and found that webcalendar adds "STATUS:CONFIRMED"

**Comment by georgehrke** [comment] 2019-05-16 15:07
> but event update can be handled correctly by any client.

Yes, but up on an update sequence is supposed to be incremented.

> I compared webcalendar and thunderbird initial invitations and found that webcalendar adds "STATUS:CONFIRMED"

That doesn't matter.

**Comment by p5n** [comment] 2019-05-16 15:11
Initial invitation diff:
```
16,26c16,30
< CREATED:20190516T151935
< DTSTAMP:20190516T151935
< LAST-MODIFIED:20190516T151935
< UID:YPX83MEEP3HMEP3PYPB7ZA
< SUMMARY:rhrthe
< ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUAL;X-NC-GROUP-ID=0:mailto:xxxxxxx@gmail.com
< ORGANIZER;CN=sergej:mailto:yyyyyy@example.com
< CLASS:PUBLIC
< STATUS:CONFIRMED
< DTSTART;TZID=Europe/Moscow:20190520T000000
< DTEND;TZID=Europe/Moscow:20190520T010000
---
> CREATED:20190516T132149Z
> LAST-MODIFIED:20190516T132215Z
> DTSTAMP:20190516T132215Z
> UID:7d6e676b-4aa0-4c05-a8ae-1478a254a762
> SUMMARY:qweqweqwe123123123
> ORGANIZER;RSVP=TRUE;PARTSTAT=ACCEPTED;ROLE=CHAIR;SENT-BY="mailto:yyyyyy@example.com":mailto:yyyyyy@example.com
> ATTENDEE;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mailto:xxxxxxx@gmail.com
> DTSTART;TZID=Europe/Moscow:20190520T170000
> DTEND;TZID=Europe/Moscow:20190520T180000
> TRANSP:OPAQUE
> BEGIN:VALARM
> ACTION:DISPLAY
> TRIGGER;VALUE=DURATION:PT0S
> DESCRIPTION:Default Mozilla Description
> END:VALARM
```

**Comment by p5n** [comment] 2019-05-16 15:13
I see:
CUTYPE=INDIVIDUAL;X-NC-GROUP-ID=0 in ATTENDEE
CLASS:PUBLIC
TRANSP:OPAQUE
and VALARM block

**Comment by georgehrke** [comment] 2019-05-16 15:14
Yes, but when you update the event in Thunderbird again, it updates the sequence.

**Comment by p5n** [comment] 2019-05-16 15:16
Yes, and timestamps. From my experience thunderbird updates sequence on any change and it is most compatible caldav client. All other clients have compatibility issues.

**Comment by vimmerru** [comment] 2019-05-16 16:03
> Yes, but when you update the event in Thunderbird again, it updates the sequence.

Yes, and the problem is that Sabre in CalDav backend doesn't increment the sequence and produces other fields that can't be understand by most popular calendar clients. I tried Google, Outlook, Apple Mail and Lighting. All clients skip update of this event.

Apple Mail is extremely popular in US that makes this problem for us very critical.

**Comment by georgehrke** [comment] 2019-05-16 16:58
The Problem is not in Sabre, it’s in the calendar app itself

**Comment by vimmerru** [comment] 2019-05-17 10:19
> The Problem is not in Sabre, it’s in the calendar app itself

I don't understand why? 

1. We have problem with both Apple Mail and Calendar.
1. In both cases ics  was generated by Sabre as it is mentioned in PRODID field.
1. And in both cases we have exactly same problem.
1. If we use another CalDAV provider it produces correct ics file with Apple Mail.

Logically from this 4 points we can claim that problem at least can be mitigated on Sabre side. It does't mean that clients behaviour is 100% correct according to RFCs sure.

@georgehrke Can you point to someone who clearly understands how calendar app performs scheduling? In this case we can try to fix this bug with our resources and provide PR with fixes, but seems we need some help in root cause understanding.

**Comment by georgehrke** [comment] 2019-05-17 10:37
Please read https://tools.ietf.org/html/rfc5545#section-3.8.7.4 and https://tools.ietf.org/html/rfc5546#section-2.1.4.

```
The "Organizer" CUA MUST increment the sequence number whenever it makes changes to properties ...
```

CUA = Calendar User Agent aka this calendar app / Thunderbird lightning / etc.
Sabre/DAV is the CalDAV server, not a CUA.

**Comment by georgehrke** [comment] 2019-05-17 10:39
If you want to help us fix this by sending a PR, a few pointers:
- add sequence to https://github.com/nextcloud/calendar/blob/master/js/app/models/simpleEventModel.js
- detect significant changes in https://github.com/nextcloud/calendar/blob/master/js/app/controllers/editorcontroller.js
- see the two standards i linked for what's considered a significant change
- update sequence inside the save method after detecting a significant change: https://github.com/nextcloud/calendar/blob/master/js/app/controllers/editorcontroller.js#L109

**Comment by vimmerru** [comment] 2019-05-17 10:47
@georgehrke isn't they use scheduling extensions https://tools.ietf.org/html/rfc6638#section-3.2.5 ?

It says

```
 The server MUST ensure that a "DTSTAMP" iCalendar property is present
   and set the value to the UTC time that the scheduling message was
   generated (as required by iCalendar).

   The server MUST ensure that for each type of scheduling operation,
   the "SEQUENCE" iCalendar property value is updated as per iTIP
```

**Comment by vimmerru** [comment] 2019-05-17 10:51
In my understanding Sabre doesn't send ics file provided by client. For some purpose it sends ics file provided by Sabre on event updated. We need to understand why it is performed before moving to fixes of calendar app as our main interest is fix integration of NextCloud with Apple Mail.

**Comment by georgehrke** [comment] 2019-05-17 11:14
Please see https://github.com/sabre-io/vobject/blob/master/lib/ITip/Broker.php
That's where all the magic in Sabre/DAV happens.

**Comment by vimmerru** [comment] 2019-06-28 10:56
@georgehrke @p5n Seems we found the cause of the issue. 

1. When Apple Mail or Web UI creates an event and updates it it sends PUT request with ics file to /remote.php/dav/calendars/{user}/{cal}/{cal-component-guid}.ics all according to specification and similar to Mozilla

2. The important different is that Mozilla puts LAST-MODIFIED property to VEVENT part of ics, but Apple Mail uses DTSTAMP field only. From specification point of view it is pretty ok as

```
In the case of an iCalendar object that specifies a
"METHOD" property, this property specifies the date and time that
the instance of the iCalendar object was created.  In the case of
an iCalendar object that doesn't specify a "METHOD" property, this
property specifies the date and time that the information
associated with the calendar component was last revised in the
calendar store.

In the case of an iCalendar object that doesn't specify a "METHOD"
property, this property is equivalent to the "LAST-MODIFIED"
property.
```

See https://tools.ietf.org/html/rfc5545#section-3.8.7.2

3. After this Sabre sends scheduling request to recipients by producing and attaching of very similar ics with added `METHOD: Request` and PRODID changed to Sable, but according to the same specification all ics with METHOD preoperty should have LAST-MODIFIED property also, but this property is still missing in ics prepared by Sabre. 

Missed LAST-MODIFIED causes invalid scheduling in the most of popular Calendar clients including Mozilla, Outlook, Google, Apple Mail. 

As a result of investigation Sabre produces invalid ics for scheduling request and. I will look deeper, but fix can be trivial just copy DTSTAMP value to LAST-MODIFIED property if it is missed in ics that was used for event updating.

**Comment by vimmerru** [comment] 2019-06-28 11:12
In theory it can be done in

```
protected function parseEventForOrganizer(VCalendar $calendar, array $eventInfo, array $oldEventInfo)
``` 

in https://github.com/sabre-io/vobject/blob/master/lib/ITip/Broker.php The only issue may be related to processing of DTSTAMP multiple times when sometimes it means creation date and sometimes last modification date that may require some fix in ics storage too.

**Comment by vimmerru** [comment] 2019-06-28 12:10
@georgehrke We can fix this, but as i can see Sabre code base isn't in well maintained state. What will be a right way to provide these changes to mainstream?

**Comment by georgehrke** [comment] 2019-08-25 13:32
Upstream issue. 
Fix upstream: https://github.com/sabre-io/vobject/pull/463
Hotfix in Nextcloud: https://github.com/nextcloud/3rdparty/pull/311

**Closed by georgehrke** 2019-08-25 13:32 UTC
