### ISSUE TITLE
Locale English(Germany) doesn't start on Monday

### ISSUE THREAD

**Issue by Emporea** [nextcloud/calendar#5160] opened 2023-04-22 07:15 UTC
### Steps to reproduce

Okay this seems like a stereotypical german issue, but...

1. Select English(Germany) as your Locale.
2. Read this
![image](https://user-images.githubusercontent.com/21969523/233769133-f71a9e16-6735-4401-b7c6-3830414fb6ee.png)

4. Go to Calendar
5. The first day of the week is sunday

### Expected behavior

The first day of the week in the calendar should be Monday, when the locale is set to English(Germany)

### Actual behaviour

The first day of the week is sunday.

### Calendar app version

4.3.3

### CalDAV-clients used

/

### Browser

Firefox 112

### Client operating system

Arch

### Server operating system

Docker

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

26.0.1

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment] 2023-04-24 10:55
Hi Emporea, I can't reproduce this issue. Can you share your language settings too?

![image](https://user-images.githubusercontent.com/7427347/233976557-15d106fb-a4ef-435e-92c9-e8e122c4185a.png)
 This is what I have set, I also tried English(US) but that also left the week starting Monday.

Can you please also have a look at your dev console in your browser (right click, inspect) to see if there are any JS errors?

**Comment by TeaDrinkingProgrammer** [comment] 2023-07-01 19:45
Can you test again to see if the issue persists? This bug should be fixed by my merge request for Calendar version 4.3 and 4.4. If it is still an issue I am willing to look into it

**Comment by st3iny** [comment] 2023-09-17 08:47
This is working as intended. Please use `Germany (...)` if you want to use a German locale.

The logic had major flaws and we reverted some code. Please refer to https://github.com/nextcloud/calendar/issues/5257#issuecomment-1681054283 and the following comments for more information.

**Closed by st3iny** 2023-09-17 08:47 UTC
Labels: bug, 0 - to triage
