### ISSUE TITLE
Short events are almost invisible

### ISSUE THREAD

**Issue by Derkades** [nextcloud/calendar#2696] opened 2020-11-13 13:13 UTC
### Steps to reproduce
1. Create an event with very short duration (e.g. 1 minute)
2. Observe

### Expected behaviour
Events should show with a minimum length like they did before, for example 15 minutes.

### Actual behaviour
Events are shown with their actual duration, making them almost invisible.
![image](https://user-images.githubusercontent.com/15892014/99075641-1c11b780-25ba-11eb-8747-001dc39d0fa2.png)

It might not seem important (who creates events that short?) but it is useful for those with calendar subscriptions where short calendar events represent deadlines.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1) 2.1.2

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc) None

**Comment by mafgh** [comment] 2020-11-30 16:30
This is also true for 15 Minute durations:
![short](https://user-images.githubusercontent.com/7955944/100636113-a33c8a80-3331-11eb-932b-14c677fdf71d.png)

**Comment by louis-berruyer** [comment] 2020-12-03 15:34
Same problem on my side, it has become simply unreadable!

![Agenda Nextcloud](https://user-images.githubusercontent.com/57601994/101050952-3b7e7d80-3585-11eb-95cf-4c3b5f0cea78.jpg)

**Comment by daCaPo** [comment] 2021-01-12 12:46
Same problem here. And we have **a lot** of "deadline-like" events with no duration (start and end date are equal).

**Comment by daCaPo** [comment] 2021-02-08 20:05
The same symptom was already adressed in issue #221, and there was even a [fix](/nextcloud/calendar/pull/709) for it. Seems it got lost somehow?

The thin lines are caused by the ".014" inset difference between top and bottom. In the example below, `inset: 500px 0% -525px;` would produce a reasonable result:

`<div class="fc-timegrid-event-harness" style="z-index: 1; inset: 500px 0% -500.014px;">...`

Unfortunately, I was not yet able to find the code producing the output.

As a workaround, the CSS

`fc-timegrid-event-harness {
   min-height: 25px;
}`

seems to work.

**Comment by mafgh** [comment] 2021-02-17 16:37
FWIW, 

> `fc-timegrid-event-harness { min-height: 25px; }`

doesn't work for me, however adding

```
.fc-v-event {
    min-height: 2em;
}
```

to `nextcloud/apps/calendar/css/fullcalendar.scs` does.

**Comment by daCaPo** [comment] 2021-03-25 09:32
It's a pitty that this did not make it into the 2.2.0 release.

**Comment by JonathanTreffler** [comment] 2021-04-11 09:53
Duplicate of existing issue: #2644

**Comment by alexanderdd** [comment] 2021-04-11 10:44
> Duplicate of existing issue: #2644

I agree. So close this one here? 
Some of the info here by @daCaPo could be helpful over there at https://github.com/nextcloud/calendar/issues/2644

**Closed** 2021-04-11 11:16 UTC
Labels: 1 - to develop, bug
