### ISSUE TITLE
Series Events only possible to delete all events not one of the series

### ISSUE THREAD

**Issue by Nemofly** [nextcloud/calendar#601] opened 2017-09-14 08:32 UTC
### Steps to reproduce
1. Create new Serial Calender Event
2. only all Serial Events can be deleted
3.In outlook or iOS you can delete only one event from series

### Expected behaviour
Only in the Calender interface in Nextcloud it is not possible to delete obly one of the series events

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.0
**Server version:** (see your admin page)
12.0.2
**Calendar version:** (see the apps page)
1.5.4
**Updated from an older installed version or fresh install:**
updated from 11.0.4

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - announcementcenter: 3.1.0
  - apporder: 0.4.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.4
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - metadata: 0.5.0
  - music: 0.5.1
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocdownloader: 1.5.3
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - radio: 0.6.0
  - rainloop: 5.0.2
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activitylog
  - admin_audit
  - files_external
  - richdocuments
  - survey_client
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes

**Comment by tcitworld** [comment] 2017-09-15 13:05
Duplicate of https://github.com/nextcloud/calendar/issues/7

**Closed by tcitworld** 2017-09-15 13:05 UTC
