### ISSUE TITLE
Invitation keeps accepted even if organiser changes date

### ISSUE THREAD

**Issue by onny** [nextcloud/calendar#4833] opened 2022-12-22 17:19 UTC
### Steps to reproduce

1. Create an event
2. Invite attendee
3. Attendee accepts invitation
4. Owner of event changes the date of the event
5. Invitation state of attendee doesn't change and participation stays accepted

### Expected behavior

Attendee should accept changes to the event again, otherwise participation should change back from "accepted" to "pending"

### Actual behaviour

Participation stays accepted even the date of the event changed

### Calendar app version

4.1.1

### Browser

Librewolf 107.0.1

### Client operating system

NixOS 22.11

### Server operating system

NixOS 22.11

### Web server

Nginx

### Database engine version

SQlite

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
Enabled:
  - activity: 2.17.0
  - calendar: 4.1.0-rc.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/lib\/nextcloud\/nix-apps",
                "url": "\/nix-apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/store-apps",
                "url": "\/store-apps",
                "writable": true
            }
        ],
        "appstoreenabled": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "loglevel": "2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "profile.enabled": false,
        "mail_sendmailmode": "pipe",
        "mail_smtpmode": "sendmail",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "version": "25.0.1.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ]
    }
}
```

**Comment by ChristophWurst** [comment] 2022-12-22 17:24
I'm once again unable to find the ticket but there is an existing one. Somewhere.

**Comment by miaulalala** [comment] 2022-12-27 10:00
Duplicate of https://github.com/nextcloud/server/issues/13862

**Closed by miaulalala** 2022-12-27 10:00 UTC
Labels: bug, 0 - to triage, Feature: Scheduling

**Comment by onny** [comment] 2022-12-27 10:07
Thank you for finding it. Why is this ticket part of the server component? Shouldn't it be tracked here for convenience?

**Comment by miaulalala** [comment] 2022-12-27 11:23
Because the CalDAV component is part of server - but of course tracking it here would also be a possibility.
