### ISSUE TITLE
temporal sorting of different calendar events

### ISSUE THREAD

**Issue by Reini91** [nextcloud/calendar#4592] opened 2022-10-11 10:29 UTC
### Steps to reproduce

Enter multiple calendar entries
<img width="454" alt="Bildschirm­foto 2022-10-11 um 12 26 15" src="https://user-images.githubusercontent.com/79060089/195066433-100bf08b-f123-44d1-b129-0d3805244b69.png">

### Expected behavior

The entries are displayed chronologically

### Actual behaviour

The entries are displayed without sorting (without a pattern)

### Calendar app version

3.5.0

### Browser

Safari, Edge, Firefox

### Client operating system

MacOS, Windows 

### Nextcloud version

24.0.6

**Comment by miaulalala** [comment] 2022-10-11 13:16
Duplicate of https://github.com/nextcloud/calendar/issues/4443

**Closed by miaulalala** 2022-10-11 13:16 UTC
Labels: bug, 0 - to triage
