### ISSUE TITLE
12 AM and 12 PM

### ISSUE THREAD

**Issue by jamesstanw** [nextcloud/calendar#3474] opened 2021-09-15 02:36 UTC
### Steps to reproduce
1. Input into the calendar an appointment starting at 11 AM (use choosing time on pop-up window)
2. Input finish times as 12 PM (using choosing time on pop-up window)

### Expected behavior
Calendar should show an appointment set as 11.00 - 12.00

### Actual behaviour
Result - calendar shows appointment starting at 00:00 and 12.00

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
MacOS Calendar
### Client configuration
Firefox

**Operating system:** (e.g. Arch Linux)

### Server configuration

**Operating system**: Ubunutu 20.x

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 8.x

**Nextcloud Version:** 21

**Updated from an older installed version or fresh install:**
Updated

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

**Comment by joshtrichards** [comment] 2024-08-07 16:08
Looks fixed today (unable to reproduce). Closing, but don't hesitate to reply/reopen if you're seeing this behavior still and I overlooked something.

**Closed by joshtrichards** 2024-08-07 16:08 UTC
Labels: bug, 0. to triage
