### ISSUE TITLE
Unable to download calendars or single events in subscribed calendars

### ISSUE THREAD

**Issue by timholl** [nextcloud/calendar#1875] opened 2020-01-21 10:19 UTC
When i try to download a calendar via the download button next to it, the following URL is opened
```
https://<host>/remote.php/dav/calendars/<user>/<calendar>/?export
```
which says
```
This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.
```
I can not tell if this is a bug of the calendar app generating an invalid URL or the backend blocking a valid download request.

Furthermore, if i try to download a single event
```
https://<host>/remote.php/dav/calendars/<user>/<calendar>/<some-id>.ics?export
```
I get
```
Nextcloud
Not Found
Technische Details

    Entfernte Adresse: <ip>
    Anfragekennung: <some-id>

Nextcloud	
```

Used versions:
 * Calendar app: 2.0.1 (latest version)
 * Server: 18.0.0 (stable)
 * Hosting method: Docker behind Nginx reverse proxy

**Comment by georgehrke** [comment] 2020-01-21 10:20
Please fill the entire [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) and provide the Nextcloud.log

**Comment by georgehrke** [comment] 2020-01-21 10:28
Additionally, do user and calendar in `/<user>/<calendar>/` contain any special character / spaces or just normal characters?

**Comment by georgehrke** [comment] 2020-01-21 11:51
> https://<host>/remote.php/dav/calendars/<user>/<calendar>/<some-id>.ics?export

Single events can be downloaded by simply using `https://<host>/remote.php/dav/calendars/<user>/<calendar>/<some-id>.ics`.

Where did you get that URL with `?export` for single events?

**Comment by timholl** [comment] 2020-01-21 12:31
Sorry, I will add the required information soon.

I forgot to mention, that this problem only occurs with subscribed calendars and with events in those. On "normal" calendars, downloading works just fine.

Furthermore, the download URL looks pretty strange:
```
https://<host>/remote.php/dav/calendars/<user>/httpssomehostcomdpatchphpicalindex/?export
```
like the URL to that iCal was part of the calendar name just without slashes, dots etc.

> Where did you get that URL with `?export` for single events?

Via Event details > Downoad (on an event in a subscribed calendar)

**Comment by georgehrke** [comment] 2020-04-03 14:30
As far as i can tell, this will require server changes.
Moving to 2.1.0

**Comment by GAS85** [comment] 2022-02-24 09:44
Add to the ticket, seem quite old one. This link is provided by UI:
![grafik](https://user-images.githubusercontent.com/6813635/155499250-e6d0e8a0-f013-4361-9414-45d17dd54c00.png)

than link from above is offered: 
```bash
https://<host>/remote.php/dav/calendars/<user>/<calendar>/?export
```
and end up with this error in browser:
```
This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.
```
So UI export feature does not work at all.

**Comment by miaulalala** [comment] 2024-09-16 12:14
Can't reproduce this  - if I use the link provided by the export button it works even if the WebDAV backend is disabled

**Closed by miaulalala** 2024-09-16 12:14 UTC
Labels: 1. to develop, bug
