### ISSUE TITLE
add multiple days to calendar series

### ISSUE THREAD

**Issue by Sherl0ck007** [nextcloud/calendar#910] opened 2018-09-18 07:40 UTC
### Expected behaviour
It would be nice to be able to make one event series that repeats on multiple days of the week.
For example, a training session that occurs twice a week should be one event series, not two.

### Actual behaviour
Currently, in order to create a series for multiple days, you have to create two separate series.

**Comment by georgehrke** [comment] 2018-10-01 18:45
Duplicate of #10

**Closed by georgehrke** 2018-10-01 18:45 UTC
