### ISSUE TITLE
Allow editing location in the simple event editor

### ISSUE THREAD

**Issue by benwaffle** [nextcloud/calendar#817] opened 2018-05-03 16:49 UTC
I tend to fill out the location for most events I add on my calendar. Would be great if i didn't have to click 'more' every time. What do other users/devs think?

**Comment by slideup-benni** [comment] 2018-06-01 08:37
maybe this issue is related to xhttps://github.com/nextcloud/calendar/issues/584

**Comment by benwaffle** [comment] 2018-06-01 15:42
No, it's not the same issue

**Comment by georgehrke** [comment] 2018-07-28 09:01
Duplicate of #680

**Closed by georgehrke** 2018-07-28 09:01 UTC
