### ISSUE TITLE
Update to 2.0.1 ended with t.isBuffer error

### ISSUE THREAD

**Issue by fdeitelhoff** [nextcloud/calendar#2019] opened 2020-02-24 13:48 UTC
I'm on Nextlcoud 17.0.3 and just updated the calendar app to 2.0.1. When opened, the console log of Chrome greets me with the following error:

```
Uncaught TypeError: t.isBuffer is not a function
    at y (<anonymous>:1:2232)
    at f (<anonymous>:1:3275)
    at Object.<anonymous> (<anonymous>:1:928)
    at Object.r (<anonymous>:1:375)
    at Object.emit (<anonymous>:1:694)
    at vuex.esm.js:54
    at new u (vuex.esm.js:357)
    at Module.<anonymous> (index.js:42)
    at i (bootstrap:63)
    at bootstrap:198
```

The calendar screen remains white. I tried removing the app, deactivating/activating, as well as reinstalling. Nothing changes. How can I track down the problem?

**Comment by georgehrke** [comment] 2020-02-24 13:48
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.

**Comment by fdeitelhoff** [comment] 2020-02-24 14:42
I hope this information helps. With Edge the calendar app is working. With Chrome the error remains.

### Steps to reproduce
1. Update the calendar app to 2.0.1
2. Open the app via Chrome

### Expected behaviour
The calendar should be visible.

### Actual behaviour
The page remains white.

### Calendar app
**Calendar app version:** 2.0.1

**CalDAV-clients used:** None

### Client configuration
**Browser:** Chrome 80.0.3987.116 (64-Bit)

**Operating system:** Shared Hoster, CentOS

### Server configuration

**Operating system**: CentOS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.9

**Nextcloud Version:** 18.0.1

**Updated from an older installed version or fresh install:** Updated from 17.0.3

**List of activated apps:**

- Accessibility							
- Activity								
- Calendar								
- Collaborative tags						
- Comments								
- Contacts								
- Deck									
- Deleted files							
- Federation								
- File sharing							
- First run wizard						
- Group folders							
- Log Reader								
- Monitoring								
- Nextcloud announcements					
- Notes									
- Notifications							
- Notifications for calendar event updates
- PDF viewer								
- Photos									
- Privacy									
- Quota warning							
- Recommendations							
- Right click								
- Share by mail							
- Support									
- Tasks									
- Text									
- Theming									
- Update notification						
- Usage survey							
- Versions								
- Video player


```
$CONFIG = array (
  'instanceid' => 'ocmodm9K5UtxO03wfyWe',
  'passwordsalt' => '',
  'secret' => ' ',
  'trusted_domains' =>
  array (
    0 => 'cloud.brickobotik.de',
  ),
  'datadirectory' => '/htdocs/brickobotik/cloud/nextcloud/data',
  'overwrite.cli.url' => 'cloud.brickobotik.de',
  'dbtype' => 'mysql',
  'version' => '18.0.1.3',
  'dbname' => ' ',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => ' ',
  'dbpassword' => ' ',
  'installed' => true,
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'brickobotik.de',
  'maintenance' => false,
  'loglevel' => 2,
  'mail_sendmailmode' => 'smtp',
  'updater.release.channel' => 'stable',
  'updater.secret' => ' ',
  'theme' => '',
);
```

### Logs
#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":0,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Repair::step: Repair step: Remove potentially over exposing share links","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":0,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"Deprecated event type for \\OC\\Repair::info: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Repair::info: Repair info: No need to remove link shares.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":0,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Repair::step: Repair step: Clear access cache of projects","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":0,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Repair::step: Repair step: Switches from deprecated \"production\" to \"stable\" update channel","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":0,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Repair::step: Repair step: Sets the enterprise logo","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":0,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"Deprecated event type for \\OC\\Repair::info: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Repair::info: Repair info: Repair step already executed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":0,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Repair::step: Repair step: Reset generated avatar flag","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:17+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:21+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"17.0.3.1"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:21+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.1.3"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:21+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.1.3"}
{"reqId":"j3tjTAFhUGHQ0F4oyOSi","level":1,"time":"2020-02-24T14:11:21+00:00","remoteAddr":"193.25.22.47","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=HMWVwtQ4Plp4WIaJAjQONE%2Fl3UL6AO7e78GTBCEU0oI%3D%3Ab7DXprJoeCoKK7%2FtbUc6cWCwpSDDNJqZhaDwUENwnNo%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.1.3"}
{"reqId":"FvBeXIbNsPJJilHTBCEB","level":3,"time":"2020-02-24T14:11:42+00:00","remoteAddr":"193.25.22.47","user":"Fabian","app":"PHP","method":"GET","url":"/index.php/css/core/c5cb-ca9a-results.css?v=6242da423869cc19c1c7289381bcb35b-c1087f0f-22","message":"Directive 'track_errors' is deprecated at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.1.3"}
{"reqId":"cAhQAjtWFSHg0PPy7sXy","level":3,"time":"2020-02-24T14:11:42+00:00","remoteAddr":"193.25.22.47","user":"Fabian","app":"PHP","method":"GET","url":"/index.php/css/files/9eeb-ca9a-merged.css?v=6242da423869cc19c1c7289381bcb35b-c1087f0f-22","message":"Directive 'track_errors' is deprecated at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.1.3"}
{"reqId":"5ZKosOz0XXwDpaMQ22sG","level":3,"time":"2020-02-24T14:11:44+00:00","remoteAddr":"193.25.22.47","user":"Fabian","app":"PHP","method":"GET","url":"/ocs/v2.php/core/whatsnew?format=json","message":"Undefined index: changelogURL at /data/web/1/000/029/466/83503/htdocs/brickobotik/cloud/nextcloud/core/Controller/WhatsNewController.php#91","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.1.3"}
                                                                                    
```

#### Browser log
```
Insert your browser log here, this could for example include:

DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
tooltip.js:22 JQMIGRATE: Migrate is installed, version 1.4.1
notifications.js?v=26d2a105-22:21 Proxying an event bus of version 1.1.2 with 0.2.1
t @ notifications.js?v=26d2a105-22:21
(anonymous) @ notifications.js?v=26d2a105-22:21
n @ bootstrap:19
(anonymous) @ notifications.js?v=26d2a105-22:21
n @ bootstrap:19
(anonymous) @ notifications.js?v=26d2a105-22:21
n @ bootstrap:19
(anonymous) @ lodash.js:285
n @ bootstrap:19
(anonymous) @ notifications.js?v=26d2a105-22:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=26d2a105-22:1
main.js?v=26d2a105-22:1082 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ main.js?v=26d2a105-22:1082
get @ main.js?v=26d2a105-22:1082
e.default @ notifications.js?v=26d2a105-22:21
(anonymous) @ notifications.js?v=26d2a105-22:21
n @ bootstrap:19
(anonymous) @ bind.js:3
n @ bootstrap:19
(anonymous) @ notifications.js?v=26d2a105-22:21
n @ bootstrap:19
(anonymous) @ notifications.js?v=26d2a105-22:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=26d2a105-22:1
VM2379:1 Uncaught TypeError: t.isBuffer is not a function
    at y (<anonymous>:1:2232)
    at f (<anonymous>:1:3275)
    at Object.<anonymous> (<anonymous>:1:928)
    at Object.r (<anonymous>:1:375)
    at Object.emit (<anonymous>:1:694)
    at vuex.esm.js:54
    at new u (vuex.esm.js:357)
    at Module.<anonymous> (index.js:42)
    at i (bootstrap:63)
    at bootstrap:198
y @ VM2379:1
f @ VM2379:1
(anonymous) @ VM2379:1
r @ VM2379:1
emit @ VM2379:1
(anonymous) @ vuex.esm.js:54
u @ vuex.esm.js:357
(anonymous) @ index.js:42
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ calendar.js?v=26d2a105-22:2
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map

```

**Comment by georgehrke** [comment] 2020-02-24 14:53
The fact, that out of all browsers, it works in Edge but not in Chrome, sounds very suspicious. Do you have any Chrome extensions installed, which might modify the webpage?

**Comment by fdeitelhoff** [comment] 2020-02-24 14:57
Yes, I was suspicious, too and deactivated the Vue.js devtools 5.0.0. Without it, it's working fine.

**Comment by georgehrke** [comment] 2020-02-24 14:59
I'm not able to reproduce this when Vue.js devtools 5.3.3 are enabled. Can you try updating the extension?

**Comment by fdeitelhoff** [comment] 2020-02-24 15:08
Seems to be finde with 5.3.3.

**Comment by georgehrke** [comment] 2020-02-24 15:33
Okay, in that case i will go ahead and close this issue. I assume there was some breaking change in Vue.js that required users to update to the newest version of Dev tools.

**Closed by georgehrke** 2020-02-24 15:33 UTC
Labels: 0. to triage, bug
