### ISSUE TITLE
Allow configuration (or change default) of slotDuration in v2.0.0+ to 30m

### ISSUE THREAD

**Issue by raoulbhatia** [nextcloud/calendar#1840] opened 2020-01-18 13:30 UTC
I just upgraded to Calendar v2.0.0 and the calendar is now consuming much more space on the screen.  Upon digging into the source code, I found slotDuration is set to 15m, see https://github.com/nextcloud/calendar/blob/master/src/views/Calendar.vue#L177

Any chance to make this configurable?  I think the old default was 30m that yielded in a much better overview.

Thanks,
Raoul

**Comment by georgehrke** [comment] 2020-01-18 13:52
Duplicate of https://github.com/nextcloud/calendar/issues/577

**Closed by georgehrke** 2020-01-18 13:52 UTC

**Comment by raoulbhatia** [comment] 2020-01-18 19:09
@georgehrke thanks for pointing out #1747 

How do you think about restoring the old default of slotDuration of 30m?  I'd assume that, apart from people like @AlexandreBonneau, others might find the change of defaults irritating like me?

**Comment by AlexandreBonneau** [comment] 2020-01-19 06:14
Note from people like me ; if the default `slotDuration` would be configurable, we couldn't care less about the default value on a fresh installation ;)
