### ISSUE TITLE
Feature request: Delete/Edit single event of a repeating row of entries

### ISSUE THREAD

**Issue by tomynr1** [nextcloud/calendar#830] opened 2018-05-24 13:15 UTC
Hello, I really like how the calendar works, I only miss a functionality I was really used in google calendar.
When I create a reoccurring event, which repeats every week, sometimes I need to delete or edit only one occurrence. In the nextcloud calendar I can only edit/delete the whole sequence. It would be great to have the possibility to change a single event of a row.

**Comment by georgehrke** [comment] 2018-05-24 13:26
Duplicate of #7

**Closed by georgehrke** 2018-05-24 13:26 UTC
