### ISSUE TITLE
Make links in event descriptions clickable

### ISSUE THREAD

**Issue by lectrician1** [nextcloud/calendar#5026] opened 2023-02-27 16:09 UTC
### Is your feature request related to a problem? Please describe.

I cannot click links in event descriptions:
![image](https://user-images.githubusercontent.com/22477298/221615660-a7327023-12e3-4dff-a95d-9e7b3a7d8549.png)

### Describe the solution you'd like

Links in event descriptions should be clickable. 

In order to distinguish editing vs. clicking the link, you would need to click on the Description outside of the link in order to edit the description like how it works with Task descriptions:
![image](https://user-images.githubusercontent.com/22477298/221616319-91e1ace8-a2f7-4b8e-86ce-781d39b3602d.png)

**Comment by tcitworld** [comment] 2023-02-28 14:18
Duplicate of #674. Follow #5030 for editing field/clicking updates.

**Closed by tcitworld** 2023-02-28 14:18 UTC
Labels: enhancement, 0 - to triage
