### ISSUE TITLE
Searching for groups / users to share a calendar with is broken

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3311] opened 2021-07-08 07:27 UTC
Possibly a regression from #3232

![image](https://user-images.githubusercontent.com/7427347/124880486-a0dc9600-dfce-11eb-95f9-7ecda4149e69.png)

![image](https://user-images.githubusercontent.com/7427347/124879754-d7fe7780-dfcd-11eb-96f4-f414008cc262.png)

**Comment by ChristophWurst** [comment] 2021-07-08 08:17
@st3iny we could work around the issue by checking for `!(url) return url` in the urlencode. I'm not sure if this is correct semantically.

**Comment by st3iny** [comment] 2021-07-08 08:56
We could do that but it probably won't fix the underlying bug. For some reason searching DAV returns no user or group id.

One of those two lines passes null to `urldecode()`:
```js
151: const user = urldecode(result[isGroup ? 'groupId' : 'userId'])
152: const decodedPrincipalScheme = urldecode(result.principalScheme)
```

I can reproduce the bug by inserting just one character into the search and then pressing enter. I'm investigating further. Seems like the DAV search results are malformed.

**Comment by st3iny** [comment] 2021-07-08 09:04
Found it: We also search for rooms/resources and they don't have a userId/groupId. Every time there is a room in the search results this bug is occurring.

## How to deal with this?
1. Don't include rooms/resources because sharing with them makes no sense.
2. Use results['email'] instead of results['userId'] for rooms and show them in the search results.

**Comment by ChristophWurst** [comment] 2021-07-08 09:19
> Found it: We also search for rooms/resources and they don't have a userId/groupId. Every time there is a room in the search results this bug is occurring.

@miaulalala can you confirm?

> Don't include rooms/resources because sharing with them makes no sense.

:100:%

**Comment by miaulalala** [comment] 2021-07-08 11:10
Yes I have rooms / resources on my instance, so that could be it!

**Closed** 2021-07-12 07:56 UTC
Labels: 3 - to review, bug
