### ISSUE TITLE
Feature request: Calendar app - book meeting rooms and other resources

### ISSUE THREAD

**Issue by danielbotting-mcr** [nextcloud/calendar#902] opened 2018-09-05 14:22 UTC
Hi,

I would like to be able to create a new event using the Nextcloud calendar, invite attendees as I can see you can do, but also be able to invite a meeting room and a telephone conference line (for clarification see this from Google Gsuite Calendar - https://support.getjoan.com/hc/en-us/articles/115005866245-How-do-I-set-up-room-resource-calendars-in-G-Suite-Google-Apps-). Once the room and or conference line is invited it is reserved at the time. I can see that you select an attendee and when you click on their name you can say select a Type, individual, group, resource, room or unknown, why is that present?

I also require to be able to see their availability, I understand this is possible through an external client and coming to the web interface this year (a more defined date would be useful).

Please attach the enhancement tag to this post.

Many thanks

Daniel

**Comment by georgehrke** [comment] 2018-09-05 14:47
Server support will come with Nextcloud 14.

Adding a GUI component: Duplicate of #39

**Closed by georgehrke** 2018-09-05 14:47 UTC
