### ISSUE TITLE
Import of specific calendar event completely *crashes* calendar app, makes calendar inaccessible in web interface, might crash browser

### ISSUE THREAD

**Issue by Natanji** [nextcloud/calendar#1387] opened 2019-08-06 17:05 UTC
After trying to import a large calender file from Horde, the calendar app locked up completely, and Firefox displayed an error that the webpage is slowing down the browser. (On a friend's machine where this calendar was shared, it even crashed the whole browser).

I split the calendar file into single events and was able to isolate a specific "event X" that upon import into *any* calendar will reproduce the issue. It validates as correct in both https://icalendar.org/validator.html and http://mozilla-comm.github.io/ical.js/validator.html .

It also seems that this is a front-end problem. The backend will still be accessible, accessing the calendar via CalDAV works completely fine and it will also have imported event X sucessfully, and sync it without any issue. You can even still export the calendar where event X was imported to an .ics file - which, upon importing into Nextcloud, will again lock up the calendar app.

Screenshot: 
<img width="902" alt="spinning-crash" src="https://user-images.githubusercontent.com/887286/62560276-f9ec9e00-b87c-11e9-9099-31322dfe4b92.png">

### Steps to reproduce
1. Import the following calendar event into any open calendar or a new one:
```
BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:Natanji
PRODID:-//The Horde Project//Horde iCalendar Library//EN
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20190808T180000
DTEND;TZID=Europe/Berlin:20190808T210000
DTSTAMP:20190806T154135Z
UID:be09cbc7-3d84-4e4e-b9c5-a5b19eca4e54
CREATED:20190804T115119Z
LAST-MODIFIED:20190804T115119Z
SUMMARY:CensoredEventName
CLASS:PUBLIC
STATUS:CONFIRMED
TRANSP:OPAQUE
RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=TH
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:CensoredEventName
TRIGGER;VALUE=DURATION:-PT60M
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19160430T230000
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19161001T010000
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19170416T020000
RRULE:FREQ=YEARLY;BYMONTH=4;BYMONTHDAY=15,16,17,18,19,20,21;BYDAY=1MO;UNTIL
 =19180421T000000Z
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19170917T020000
RRULE:FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=15,16,17,18,19,20,21;BYDAY=1MO;UNTIL
 =19180915T000000Z
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19400401T020000
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19421102T020000
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19430329T020000
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19431004T020000
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19440403T020000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1MO;UNTIL=19450401T010000Z
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19441002T020000
TZNAME:CE-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
DTSTART:19450916T020000
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0300
DTSTART:19450524T020000
TZNAME:CEMT
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
DTSTART:19450924T030000
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19451118T020000
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19460414T020000
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19461007T020000
TZNAME:CE-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
DTSTART:19471005T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=1SU;UNTIL=19491002T010000Z
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19470406T030000
TZNAME:CEST
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
DTSTART:19470511T020000
TZNAME:CEMT
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
DTSTART:19470629T030000
TZNAME:CEST
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0200
DTSTART:19480418T020000
TZNAME:CEST
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0200
DTSTART:19490410T020000
TZNAME:CEST
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19800406T010000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU;UNTIL=19800406T000000Z
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19800928T010000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=9;UNTIL=19950923T230000Z
TZNAME:CE-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T010000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T010000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZNAME:CE-T
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```
2. Event is shown as imported successfully, but the round icon next to the calendar keeps spinning indefinitely, and perhaps the browser even crashes.

### Expected behaviour
The calendar app should still work and show the calendar (including the imported event).

### Actual behaviour
The calendar app stops working completely, and the only way to make it working again is to unselect the calendar where this event was imported (which only works really rarely) or pressing on the 3-dot menu and deleting the whole calendar.

### Server configuration
Tested in https://demo.nextcloud.com with the default configuration.

/settings/integrity/failed:
No errors have been found.

**List of activated apps:**

Files, Activity, Gallery, Talk, Calendar, Deck

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

**CalDAV-clients:** DAVx^5

**Comment by georgehrke** [comment] 2019-08-07 14:22
Duplicate of https://github.com/nextcloud/calendar/issues/642

Sadly an upstream issue with an infinite loop.

**Closed by georgehrke** 2019-08-07 14:22 UTC

**Comment by BigMichi1** [comment] 2019-10-18 07:26
today i run into the same issue, as a dirty hack i added a check for years > 2100 to stop the yearly loop
```javascript
      if (this.rule.freq == "YEARLY") {
        for (;;) {
          this.expand_year_days(this.last.year);
          if (this.days.length > 0) {
            break;
          }

if(this.last.year > 2100) {
    break;
}
          this.increment_year(this.rule.interval);
        }

        this._nextByYearDay();
      }
```

in my case the browser was also stuck and putting breakpoints in this loop showed my after someseconds numbers for this.last.year > 44400 which is a liitle bit out of range
