### ISSUE TITLE
free/busy doesn't work with Evolution and Outlook

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#1113] opened 2019-02-12 09:32 UTC
I just tested the free/busy functionality  with some people and we get it only to work with Thunderbird. Outlook and Evolution doesn't show any free/busy information, see:

![image](https://user-images.githubusercontent.com/1589737/52625505-6f207d00-2eb1-11e9-88ac-5d3933d3c11a.png)

I couldn't see anything in the nextcloud logs. Any idea what goes wrong here?

**Comment by georgehrke** [comment] 2019-02-12 09:44
@schiessle any chance you can send me a network capture of that request (via email)?

**Comment by georgehrke** [comment] 2019-02-13 12:47
Turned out to be a duplicate of https://github.com/nextcloud/server/issues/12033

**Closed by georgehrke** 2019-02-13 12:47 UTC
