### ISSUE TITLE
Reloading switches back to current day/week/month

### ISSUE THREAD

**Issue by caugner** [nextcloud/calendar#1224] opened 2019-04-07 16:53 UTC
### Steps to reproduce
1. Switch to a day/week/month other than the current one (e.g. January 2019).
2. Reload the page.

### Expected behaviour
The same view and month should be shown.

### Actual behaviour
The same view is shown, but with the current month.

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**Server version:** 15.0.6

**Calendar version:** 1.6.4

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - bruteforcesettings
  - encryption
  - files_external
  - tasks
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***.***.***",
        "overwriteprotocol": "https",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "forcessl": "true",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***.***.***"
        ],
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***.***.***",
        "updater.release.channel": "stable",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587"
    }
}
```

**Are you using external storage, if yes which one:** no, local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 66.0.2

**Operating system:** Linux

**CalDAV-clients:** DAVx⁵

#### Web server error log
(omitted)

#### Log file (data/nextcloud.log)
(omitted)

#### Browser log
(omitted)

**Comment by georgehrke** [comment] 2019-04-07 16:57
I will close this as duplicate of https://github.com/nextcloud/calendar/issues/21
the url will contain the current visible date like `/month/2019-04-01/`, hence reloading will take you back to april.

**Closed by georgehrke** 2019-04-07 16:57 UTC
