### ISSUE TITLE
Easy copy event -- enhancement

### ISSUE THREAD

**Issue by MellowVoidUser** [nextcloud/calendar#1749] opened 2019-12-24 11:59 UTC
Many time I have to copy an event. Until now I use Thunderbird lightning because of this, but if calendar would add a easy way to copy (and repeat copy) a event that would be awesome!

**Comment by tcitworld** [comment] 2019-12-24 13:55
Copying events is duplicate from… #113 

Repeat copy is probably not really in the scope of this app, right @georgehrke ?

**Comment by georgehrke** [comment] 2020-01-05 13:20
Duplicate of #113

**Comment by georgehrke** [comment] 2020-01-05 13:20
> Repeat copy is probably not really in the scope of this app, right @georgehrke ?

I was planning to copy the RRULE, but not RDATE and EXDATE, in case that's what @MellowVoidUser refers to.

**Closed by georgehrke** 2020-01-05 13:20 UTC
Labels: Feature: Editor, enhancement-proposed, needs info
