### ISSUE TITLE
Defalut/Automatic Reminder(s) for new, subscribed, and imported events 

### ISSUE THREAD

**Issue by NukeManDan** [nextcloud/calendar#2399] opened 2020-07-16 23:16 UTC
:calendar: :arrow_right:  :alarm_clock: :email: 

**Is your feature request related to a problem? Please describe.**
I have to manually add reminders of my events :sob: ro 
each
and
every
one

This wastes times as most of the time, I want spefic ones for every event by default. 

**Describe the solution you'd like**
Automatically defaulting to a custom set or reminders for every new event (_specified for each unique calender_) that can be push notifications (desktop & mobile) as well as emails. 
Ideally this would be for subscribed (read-only) events as well :pray: 

**Describe alternatives you've considered**
I don't know of a way to add this kind of info to a `.ics` file for instance that could help. 

**Additional context**
This would be a major time saver and improve UX greatly :star:

**Comment by georgehrke** [comment] 2020-07-17 05:12
Duplicate of https://github.com/nextcloud/calendar/issues/629

**Closed** 2020-07-17 05:12 UTC
Labels: 0. to triage, enhancement-proposed
