### ISSUE TITLE
Annual View

### ISSUE THREAD

**Issue by skito** [nextcloud/calendar#2673] opened 2020-10-27 09:35 UTC
There is one thing I'm missing from all Calendar apps including Google calendar and that is "annual view" like that:

![Screenshot_49](https://user-images.githubusercontent.com/26840279/97282402-4d168c00-1847-11eb-9b6f-54144a073efa.png)

We have planned events and business trips for a year or two ahead and this gives you general overview about engagements and busy periods.  This feature will give a real kick-start of the Nexcloud Calendar.  Something that others don't offer...

The current example is created with: 
[https://year-calendar.github.io/](https://year-calendar.github.io/)

**Comment by alexanderdd** [comment] 2020-11-21 07:34
Nextcloud calendar uses fullcalendar.io for display, so we can do it only if they support it (can you check?)

**Comment by tcitworld** [comment] 2020-11-21 09:38
You can create a custom Fullcalendar view to have an annual view, but loading all of the events for the full year could be quite disastrous performance-wise, so I'm not sure about that.

**Comment by skito** [comment] 2020-11-21 11:05
@alexanderdd Thanks, I will check. If they don't. Probably will forward this idea to their GitHub.
@tcitworld  Not necessarily. In this mode we can show only the events marked as "All day". Then it shouldn't be overloading.

**Comment by tcitworld** [comment] 2020-11-21 11:18
AFAIK CalDAV doesn't allow filtering on All-day events, only `time-range`.

**Comment by skito** [comment] 2020-11-23 20:46
@tcitworld How is that related to the annual view?

**Comment by alexanderdd** [comment] 2020-11-29 11:10
> @tcitworld How is that related to the annual view?

You said you want only all-day events to show in annual view. @tcitworld said that is not (easily) possible.

**Comment by elbotho** [comment] 2020-12-04 08:10
Duplicate of #159.
But it seems not much happened since then…

**Closed** 2020-12-04 08:13 UTC
Labels: 0. to triage, enhancement-proposed

**Comment by bernd-wechner** [comment] 2022-01-04 12:00
> Nextcloud calendar uses fullcalendar.io for display, so we can do it only if they support it (can you check?)

There is a plugin to fullcalender.io:

https://github.com/p-try/fullcalendar-yearview

that does the job. To wit it is fair to conclude that NextCloud could not just fullcalendar.io but fullcalendar.io with this plugin.  It is IMHO well worth doing as it adds immense value to the NextCloud calendar.

**Comment by ChristophWurst** [comment] 2022-01-04 14:13
@bernd-wechner please put your findings in the open ticket https://github.com/nextcloud/calendar/issues/159
