### ISSUE TITLE
Scroll when dragging events

### ISSUE THREAD

**Issue by patrice-geo** [nextcloud/calendar#797] opened 2018-04-11 15:23 UTC
When moving an event from one month to another, we have to drag and drop it to the maximum we could go then switch month, then drag and drop the event again to the appropriate date. 

We have to do it several times if we want to move the event to a date that is 2-3 or more months later.

It would be nice to have automatic scrolling.

**Comment by georgehrke** [comment] 2019-09-09 11:36
Automatic scrolling within the current view was implemented in FullCalendar and will be available in Calendar 2.0.

Switching between month is yet to be resolved by #6
Closing as a duplicate of #6

**Closed by georgehrke** 2019-09-09 11:36 UTC
Labels: 1 - to develop, enhancement-approved
