### ISSUE TITLE
Please add a button to delete a date earlier

### ISSUE THREAD

**Issue by sputnick-dev** [nextcloud/calendar#2372] opened 2020-07-01 10:45 UTC
To remove a date, now it's very annoying.

You have to
 - click 'date'
 - click 'Plus'
 - click '(...)'
 - then remove the 'date'

SoGo have a better feature, when you first open the date, you can directly delete the date at this step.

Think of people with disabled finger, dividing clicking by 2 will be very helpful

Alternative way: enabling keyboard 'delete' button after clicking on a date

**Comment by georgehrke** [comment] 2020-07-01 11:27
Duplicate of #1570

**Closed by georgehrke** 2020-07-01 11:27 UTC
Labels: 0. to triage, enhancement-proposed
