### ISSUE TITLE
Detect Event Time from the Event Title (like Google Calendar)

### ISSUE THREAD

**Issue by joaofar** [nextcloud/calendar#5508] opened 2023-10-02 09:43 UTC
### Describe the solution you'd like

I've seen this feature in Google Calendar and I absolutely love it:

You type "11:00 Meeting" or "11am Meeting" when creating a new event and the time is automatically added without having to deal with that awkward time selection interface.

Such a time saver 😊

I searched the issues and couldn't find any suggestion about this so forgive me if it is a duplicate.
Thank you all you wonderful people for all your hard work.

**Comment by tcitworld** [comment] 2023-10-02 10:08
Thanks for the issue, but I think this is a duplicate of #17

**Closed by tcitworld** 2023-10-02 10:08 UTC
Labels: enhancement, 0 - to triage
