### ISSUE TITLE
Calendar view bug

### ISSUE THREAD

**Issue by d4v1d15** [nextcloud/calendar#310] opened 2017-01-20 19:46 UTC
I dont see the calendar view and the calendar entries.

### Steps to reproduce
1. Login in Nextcloud
2. Go to Calendar-app

### Expected behaviour
Tell us what should happen

### Actual behaviour
I dont see anything.
![image](https://cloud.githubusercontent.com/assets/25087698/22162927/14b22d8e-df51-11e6-9daf-56a0bbb68f10.png)

**Comment by tcitworld** [comment] 2017-01-20 19:47
What the app version ?
Duplicate of https://github.com/nextcloud/calendar/issues/225 ? Activate the Share API.

**Comment by d4v1d15** [comment] 2017-01-20 19:53
All important things are activated. I am a normal user.
![image](https://cloud.githubusercontent.com/assets/25087698/22163302/8621e38c-df52-11e6-92f1-4a3938db4cfd.png)

**Comment by georgehrke** [comment] 2017-01-20 20:58
please use the entire [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md).
There is a reason it's there ;) 

Especially the browser log is very very important in that case.

**Comment by d4v1d15** [comment] 2017-01-21 12:46
### Steps to reproduce
1. Login into Nextcloud
2. Go to Calendar

### Expected behaviour
The calendar should be shown

### Actual behaviour
I dont see the calendar, '{{dt | datepickerFilter:selectedView}}'

### Server configuration
**Operating system**
Dont know exactly - Linux

**Web server:**
Apache

**Database:**
5.5.52-MariaDB - MariaDB Server

**PHP version:**
At the moment 5.6.29, also tried PHP 7.0.14 and 7.1.0.

**Server version:** (see your admin page)
Nextcloud 11.0.1 (stable) - same behaviour on 10.0.2 (stable) and on 10.0.1 (stable)

**Calendar version:** (see the apps page)
1.5.0

**Updated from an older installed version or fresh install:**
Updated from 10.0.2 to 11.0.1 - fresh install (I didn't use the updater)

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**
- Activity 2.4.1
- Collaborative tags 1.1.3
- Comments 1.1.0
- Default encryption module 1.4.1
- Deleted files 1.1.0
- External sites
- Federation 1.1.1
- File sharing 1.1.1
- Files automated tagging 1.1.1
- First run wizard 2.0
- Gallery 16.0.0
- Log Reader 2.0.0
- Mail template editor 0.2
- Nextcloud announcements 1.0
- Notifications 1.0.1
- PDF viewer 1.0.1
- Server info 1.1.1
- Share by mail 1.0.1
- Text editor 2.2
- Theming 1.1.1
- Update notification 1.1.1
- Usage survey 0.1.5
- Versions 1.4.0
- Video player 1.0.0
- Announcement Center 3.0.0
- AppOrder 0.3.3
- Calendar 1.5.0
- Contacts 1.5.2

```
**The content of config/config.php:**


```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
<?php
$CONFIG = array (
  'passwordsalt' => '****',
  'secret' => '****',
  'trusted_domains' => 
  array (
    0 => 'cloud.****',
  ),
  'datadirectory' => '/var/www/vhosts/****/httpdocs/cloud/data/',
  'overwrite.cli.url' => 'https://cloud.****',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => '****',
  'dbhost' => 'localhost:3306',
  'dbtableprefix' => 'oc_',
  'dbuser' => '****',
  'dbpassword' => '****',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => '****',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => '****',
  'dbport' => '',
  'updater.secret' => '****',
  'integrity.check.disabled' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
55.0.2883.87 (Offizieller Build) m (32-Bit)

**CalDAV-clients:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ... ![image](https://cloud.githubusercontent.com/assets/25087698/22174485/087ae8fa-dfe0-11e6-8f43-c53b7c501e20.png)

```

**Comment by tcitworld** [comment] 2017-01-21 14:12
>  The contacts app doesn't work. Calendar and contacts are the two apps which don't work properly.

Angular is missing so I would blame a nextcloud server issue.

**Comment by georgehrke** [comment] 2017-01-21 14:14
How did you install the calendar?

**Comment by georgehrke** [comment] 2017-01-21 14:15
Do you use some reverse proxy in front of it that does some weird minifying?

**Comment by d4v1d15** [comment] 2017-01-21 14:18
> How did you install the calendar?
I installed it under Apps --> Organisation
I use Cloudflare. Rocket Loader is "Off".

**Comment by georgehrke** [comment] 2017-01-21 14:20
> I use Cloudflare. 

Can you try accessing the nextcloud instance without cloud flare?

**Comment by d4v1d15** [comment] 2017-01-21 14:22
I can try to pause cloudflare, but I cant without, because i have all DNS settings there.

**Comment by d4v1d15** [comment] 2017-01-21 14:25
Okay. It works now - finally!
In Cloudflare under "Speed" I have deactivated "Auto Minify". Great!

**Comment by georgehrke** [comment] 2017-01-21 14:28
awesome :)

**Closed by georgehrke** 2017-01-21 14:28 UTC
Labels: 1 - to develop, bug, needs info
