### ISSUE TITLE
monthly recurring event at specific week day.

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/calendar#1643] opened 2019-11-08 20:37 UTC
For monthly repetitions it would be good to have the option to choose the nth weekday, such as "first Saturday", "third Wednesday", because that's a quite a natural rhythm for recurring events.

**Comment by georgehrke** [comment] 2019-11-11 08:05
Duplicate of #10 

Implemented in Calendar 2.0

**Closed by georgehrke** 2019-11-11 08:05 UTC
Labels: 0. to triage, enhancement-proposed
