### ISSUE TITLE
[Feature Request] More options for reccuring appointment (like every last thursday of the month)

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/calendar#1825] opened 2020-01-16 12:54 UTC
I have appointments that should reccur for example ever last thursday of the month. Doesn't matter, what date this is.
I think this could be a good feature.

**Comment by georgehrke** [comment] 2020-01-16 14:14
Duplicate of #10

**Comment by georgehrke** [comment] 2020-01-16 14:14
Duplicate of #10

**Closed by georgehrke** 2020-01-16 14:14 UTC
Labels: 0. to triage, enhancement-proposed
