### ISSUE TITLE
Web-interface: Impossible to add attendees to event if whitespace (blank) in username

### ISSUE THREAD

**Issue by C-7** [nextcloud/calendar#2537] opened 2020-09-03 08:57 UTC
### Steps to reproduce
From the web-interface
- create test-user named "First Last"; assign password and e-mail. Make sure user shares at least one group with you. 
- create new calendar event, hit "More" -> Attendees. Start typing First... autocomplete [autocomplete is on in settings]; now "First Last" is shown as attendee.
- Hit "save" and watch the endless rotating circle. 

### Expected behaviour
Attendee added
### Actual behaviour
Locked
### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.4
**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
none - web interface
### Client configuration
**Browser:** (e.g. Firefox 48)
Safari / Firefox
**Operating system:** (e.g. Arch Linux)
Mac OS
### Server configuration

**Operating system**: (e.g. Debian 8)
ubuntu 18.04
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0.3)
7.4
**Nextcloud Version:** (see admin page, e.g. 17.0.2)
19.0.2
**Updated from an older installed version or fresh install:**
update
**List of activated apps:**
  - accessibility: 1.5.0
  - activity: 2.12.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - event_update_notification: 1.0.2
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_markdown: 2.3.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - group_everyone: 0.1.5
  - groupfolders: 7.0.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - registration: 0.5.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - theming_customcss: 1.6.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

**Nextcloud configuration:**
 "version": "19.0.2.2",

**Comment by georgehrke** [comment] 2020-09-03 08:59
@C-7 This is a duplicate of https://github.com/nextcloud/server/issues/21642#issuecomment-685893042, right?

**Comment by C-7** [comment] 2020-09-03 09:24
Yes, right. (sorry, I thought it would be helpful to make a separate issue).

**Comment by georgehrke** [comment] 2020-09-03 09:27
Please do not create duplicate reports. It just creates an overhead for cleaning up and organizing, but does not generally speed up fixing the actual bug.

Thanks for your reproduction steps in https://github.com/nextcloud/server/issues/21642#issuecomment-685893042 though. I will try to reproduce it again today.

**Closed by georgehrke** 2020-09-03 09:27 UTC
Labels: 0. to triage, bug

**Comment by C-7** [comment] 2020-09-03 09:31
Ok, thank you.

**Comment by ikljaic-nubilum** [comment] 2024-03-21 08:56
> Please do not create duplicate reports. It just creates an overhead for cleaning up and organizing, but does not generally speed up fixing the actual bug.
> 
> Thanks for your reproduction steps in [nextcloud/server#21642 (comment)](https://github.com/nextcloud/server/issues/21642#issuecomment-685893042) though. I will try to reproduce it again today.

4 years later, .... same problem. and it was not solved even in the original.
