### ISSUE TITLE
Make calendar notifications clickable

### ISSUE THREAD

**Issue by Almiraat** [nextcloud/calendar#1389] opened 2019-08-07 10:17 UTC
### Steps to reproduce
1. click on calendar notification
2. open calendar event

### Expected behaviour
Make calendar notifications clickable

### Actual behaviour
Calendar notifications are not clickable. I need to fin the event and open it manually.

**Comment by georgehrke** [comment] 2019-08-07 10:18
> Calendar notifications are not clickable. I need to fin the event and open it manually.

Duplicate of #21

**Closed by georgehrke** 2019-08-07 10:18 UTC
