### ISSUE TITLE
Calendar completely unusable after upgrading to 3.2.2

### ISSUE THREAD

**Issue by kolaente** [nextcloud/calendar#4081] opened 2022-03-16 22:11 UTC
### Steps to reproduce

1. Upgrade to  3.2.2
2. Open `/apps/calendar/dayGridMonth/now` in a browser (Tested in Firefox 97.0.2 and Chromium 99.0.4844.51)

### Expected behavior

Calendar works normally.

### Actual behaviour

It appears to load infinitely:

![image](https://user-images.githubusercontent.com/13721712/158699292-8f3cbbc3-af3c-4ce1-b586-b13fdcbbeea0.png)

There's an error in the browser console saying

```
Error: Could not find initial state hide_event_export of calendar
```

![image](https://user-images.githubusercontent.com/13721712/158699381-fe657797-8f17-4310-b92e-8dbb6bb0ae4c.png)

### Calendar app version

3.2.2

### Browser

Firefox 97.0.2 and Chromium 99.0.4844.51

### Client operating system

NixOS 21.11

### Server operating system

Official Docker Images

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

22.2.5

**Comment by max65482** [comment] 2022-03-20 16:01
I could not reproduce this. What version did you use before upgrading?

**Comment by kolaente** [comment] 2022-03-20 16:10
@max65482 not 100% sure but I think either 3.2.1 or 3.2.0.

**Comment by max65482** [comment] 2022-03-20 17:02
Still couldn't reproduce. Did you upgrade via web UI?

**Comment by kolaente** [comment] 2022-03-20 17:11
Yes, upgraded via the web UI.

**Comment by tcitworld** [comment] 2022-03-20 18:10
Can you check if the following line correctly exists in the corresponding file in your install (`apps/calendar/lib/Controller/ViewController.php`)?
https://github.com/nextcloud/calendar/blob/623c6a6037fca9a80475b73087f19dd9157b3973/lib/Controller/ViewController.php#L121

**Comment by kolaente** [comment] 2022-03-21 10:05
Ah, yes the folder and file in question correctly exists in `custom_apps`.

**Comment by tcitworld** [comment] 2022-03-21 10:13
Can you check the line specifically?

**Comment by kolaente** [comment] 2022-03-21 10:15
The line is identical:

![image](https://user-images.githubusercontent.com/13721712/159241675-e8bf3c62-e9ac-44e0-9547-6047fe66e6ef.png)

**Comment by miaulalala** [comment] 2022-03-21 11:39
Same issue as for the forceEventAlarmType possibly @tcitworld ? See #4051

**Comment by tcitworld** [comment] 2022-03-21 11:41
But that was fixed in 3.2.2. :thinking:

**Comment by miaulalala** [comment] 2022-03-21 11:47
yeah but only the forceEventAlarmType, right? If the initial state isn't provided, it could crash like this for the hideEventExport option, no?

**Comment by miaulalala** [comment] 2022-03-21 13:09
No shit. JS might not like it if a null value is provided.

@kolaente can you please check your database? oc_appconfig would be the table:

`select * from oc_appconfig where configkey like 'hideEventExport';`

**Comment by jfreax** [comment] 2022-03-22 08:53
I had the same problem. At least I saw the same error message in my browser console and the calendar app didn't work at all (I did not test any other thing like checking files, database or html code).

Just to inform you: I updated Nextcloud to version 23.0.3 (from 23.0.2) today and the error is gone now. Everything works fine again. I'm not sure if any other updates were done, like app updates or os packages.

**Comment by kolaente** [comment] 2022-03-22 18:41
> can you please check your database? oc_appconfig would be the table:

Nothing there:

```
MariaDB [nextcloud]> select * from oc_appconfig where configkey like 'hideEventExport';
Empty set (0.000 sec)
```

> Could you check whether you see such a hidden input field in the HTML code as in the screenshot below:

Doesn't look like there is one:

![image](https://user-images.githubusercontent.com/13721712/159552902-9f57807e-0a89-4c1f-a24c-b1346215d9cc.png)

**Comment by kolaente** [comment] 2022-03-22 18:46
FWIW after the comment from @jfreax I upgraded to 23 and the calendar works again.

**Comment by joshtrichards** [comment] 2024-02-12 00:00
> FWIW after the comment from @jfreax I upgraded to 23 and the calendar works again.

Closing on this basis. :-)

**Closed by joshtrichards** 2024-02-12 00:00 UTC
Labels: bug, 0 - to triage
