### ISSUE TITLE
Interface Problems After Upgrade to Calendar Version 2 

### ISSUE THREAD

**Issue by nathan2423** [nextcloud/calendar#2028] opened 2020-02-26 14:54 UTC
I just upgraded my nextcloud installation to nextcloud hub and I see I am now on version 2.01 of Calendar.  I have at least three issues now in 2.01 which were not present before in my earlier nextcloud calendar (version 1.8 if I recall):

(1) Unlike my previous version, on the month view I am now seeing lines like "+3 more" where I previously saw three separate entries (even if some parts of the entry description were truncated).  

(2) I can't use the week view to see what I need to see, as the view doesn't allow me to set the focus start and end times.  Is that possible?

(3) Also unlike in the prior version, the description box on the right sidebar popup is MUCH smaller than before, and there seems to me no way to view the full appointment description.  I can do without the graphic as well, but my main concern is the much smaller size of the box showing the full appointment name.

Can anything be done about these three issues?  I also use small screens (netbook size and slightly smaller) and all of these issues are even worse on any modest-size screen, especially the issue of the month view not showing all appointments.  Sometimes in my netbooks I don't even get the +3 more... indication - it just shows only one without any indication that there may be more.

Thank you!

 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0.3)

**Nextcloud Version:** (see admin page, e.g. 17.0.2)

**Updated from an older installed version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment] 2020-02-26 15:00
> (1) Unlike my previous version, on the month view I am now seeing lines like "+3 more" where I previously saw three separate entries (even if some parts of the entry description were truncated).

Duplicate of https://github.com/nextcloud/calendar/issues/1889

> (2) I can't use the week view to see what I need to see, as the view doesn't allow me to set the focus start and end times. Is that possible?

Duplicate of https://github.com/nextcloud/calendar/issues/2012
Heavily related to  #577

> (3) Also unlike in the prior version, the description box on the right sidebar popup is MUCH smaller than before, and there seems to me no way to view the full appointment description. I can do without the graphic as well, but my main concern is the much smaller size of the box showing the full appointment name.

The description automatically resizes as you type text into it.
Making the graphic smaller is a duplicate of https://github.com/nextcloud/calendar/issues/1956

**Closed by georgehrke** 2020-02-26 15:00 UTC
Labels: 0. to triage, bug
