### ISSUE TITLE
Calendar keeps load indefinitely

### ISSUE THREAD

**Issue by christiantosta** [nextcloud/calendar#4904] opened 2023-01-17 00:51 UTC
### Steps to reproduce

1. Login to Nextcloud
2. Click on calendar app
3. See the problem

### Expected behavior

Calendar app should show my calendars and events

### Actual behaviour

Calendar apps shows a busy wheel indefinitely.

![image1](https://user-images.githubusercontent.com/7252968/212786309-70e08029-1f26-4e26-a639-b6ee26f5f377.jpeg)

### Calendar app version

4.2.1

### Browser

108.0.1

### Client operating system

Fedora 37

### Server operating system

CentOS 8 Stream

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### Browser log

```Text
Error: Could not find initial state can_subscribe_link of calendar
    EF index.esm.js:13
    t Calendar.vue:221
    c Calendar.vue:65
    _invoke Calendar.vue:65
    v Calendar.vue:65
    YI Calendar.vue:65
    o Calendar.vue:65
    zI Calendar.vue:65
    zI Calendar.vue:65
    beforeMount Calendar.vue:266
    VueJS 27
    <anonymous> main.js:74
    <anonymous> main.js:81
    <anonymous> main.js:81
vue.runtime.esm.js:3049:8
```

**Comment by klauweg** [comment] 2023-01-17 10:49
I have the same Problem with 4.2.0 already (had to downgrade to 4.1.2 to get it work again).

**Comment by ChristophWurst** [comment] 2023-01-17 11:03
> can_subscribe_link

Added with https://github.com/nextcloud/calendar/pull/4573. @pboguslawski can you reproduce?

**Comment by tcitworld** [comment] 2023-01-17 11:27
I'd say that's a PHP cache issue. Is it fixed by simply force reloading the page or restarting php-fpm?
In any case the `loadstate` call should have a fallback.
https://github.com/nextcloud/calendar/blob/4030661b483b5e9632160257862174b2f03e70c9/src/views/Calendar.vue#L221

**Comment by miaulalala** [comment] 2023-01-17 18:03
duplicate of https://github.com/nextcloud/calendar/issues/4843

The user there fixed it with a server restart but we should release a fix with a fallback

**Closed by miaulalala** 2023-01-17 18:03 UTC
Labels: bug, 0 - to triage, regression
