### ISSUE TITLE
Calendar does not work and makes browser stop in month view

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/calendar#4313] opened 2022-06-22 06:11 UTC
### Steps to reproduce

1. Install Nextcloud
2. Open the Calendar App with Firefox 91

### Expected behavior

Calendar is shown

### Actual behaviour

Calendar is not shown

### Calendar app version

3.4.0

### Browser

Firefox 91

### Server operating system

Ubuntu 22.04 LTS

### Nextcloud version

23.0.5

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by tcitworld** [comment] 2022-06-22 06:53
We really can't help you with so little information. Please fill the template.

**Comment by szaimen** [comment] 2022-06-22 10:58
I fear I was able to reproduce the issue. It just keeps loading the calendars after update to 3.4.0 on NC23.0.5. This was not an issue in v3.3.2.

**Comment by szaimen** [comment] 2022-06-22 10:58
Unfotunatley nothing related is in the console logs nor the nextcloud logs...

**Comment by szaimen** [comment] 2022-06-22 11:02
It seems like some calendars simply do not get loaded correctly somehow:
![image](https://user-images.githubusercontent.com/42591237/175013750-4f200f95-591e-4268-8f0f-d37002516862.png)

**Comment by szaimen** [comment] 2022-06-22 11:02
@tcitworld any idea how to debug this?

**Comment by szaimen** [comment] 2022-06-22 11:16
It is on an instance with postgresql as database, apache as webserver, php7.4, NC23.0.5 and calendar 3.4.0

**Comment by szaimen** [comment] 2022-06-22 12:01
This seems to happen on c.nc.c as well so it should be very easy to reproduce...

**Comment by st3iny** [comment] 2022-06-22 14:15
Does it work with Chrome/Brave etc.?

**Comment by st3iny** [comment] 2022-06-22 14:57
At a first glance, this reminds me of https://github.com/nextcloud/calendar/pull/4114. I'll investigate further on Friday.

**Comment by Ramel** [comment] 2022-06-23 10:52
> okay found the problem. this seems to happen when eventlimit is set to yes in the dayGridMonth view. When it is set to no it seems to work without problem.
> 
> You can set it to no with `occ user:setting <userid> calendar eventLimit no`

That's do the trick! Thanks

**Comment by GUNT0815** [comment] 2022-06-23 14:09
setting eventlimit to no does not solve the issue here. still some calendars do not finish loading, while other do. No issue with caldav applications accessing the nextcloud instance.

**Comment by LuftschloesserUser** [comment] 2022-06-23 20:24
+1 Had to downgrade to get it working again.

**Comment by miaulalala** [comment] 2022-06-24 13:47
Reproducable by zooming the calendar window. I had the issue first on a 4k monitor, and now, zooming out on my laptop to 75% I was able to reproduce it.

**Comment by st3iny** [comment] 2022-06-24 14:30
I still can't reproduce this bug. I tried with multiple calendar containing many events. I tried shared calendars as well. Chromium and Firefox both work. Zooming makes no difference, too.

Could someone provide more information? Logs, Screencasts, etc.

Unfortunately, I can't fix a bug that I cannot reproduce.

**Comment by szaimen** [comment] 2022-06-24 14:36
> I still can't reproduce this bug. I tried with multiple calendar containing many events. I tried shared calendars as well. Chromium and Firefox both work. Zooming makes no difference, too.
> 
> Could someone provide more information? Logs, Screencasts, etc.
> 
> Unfortunately, I can't fix a bug that I cannot reproduce.

I think this only happens if you have many events in your calendar. I just disabled a few calendars and it fixed the symptoms as well...

**Comment by szaimen** [comment] 2022-06-24 14:41
Here a short video:

https://user-images.githubusercontent.com/42591237/175558674-d3795e84-46eb-4331-ae9c-7a246783477f.mp4

**Comment by szaimen** [comment] 2022-06-24 14:42
It seems like the bug is caused by a combination from many parameters unfortunatley...

**Comment by st3iny** [comment] 2022-06-24 15:39
I spammed a lot of new events (especiall recurring onces) and was finally able to reproduce the bug locally. First round of bisecting lead me to a commit that is not broken ... I'll try again later.

**Comment by bentwnghk** [comment] 2022-06-25 12:45
A similar issue is being reported at #4319

**Comment by bentwnghk** [comment] 2022-06-25 12:48
I have to switch to **weekly view** for the time being to get the Calendar app to work.

**Comment by AuspeXeu** [comment] 2022-06-27 07:24
Same issue here, switching to week view fixes it for now.

**Comment by LuftschloesserUser** [comment] 2022-06-27 07:40
How do you switch to weekview when the site is not working?

**Comment by bentwnghk** [comment] 2022-06-27 07:47
> How do you switch to weekview when the site is not working?

I do it on my phone or tablet, where the Calendar app works without any flaws.

**Comment by AuspeXeu** [comment] 2022-06-27 07:58
> How do you switch to weekview when the site is not working?

I copy the URL manually into the browser: `/apps/calendar/timeGridWeek/now`

**Comment by dinosmm** [comment] 2022-06-27 11:33
Is there something else we can do to test it or some other log we can paste here to help the devs debug this?

**Comment by the-moog** [comment] 2022-06-28 09:12
> okay found the problem. this seems to happen when eventlimit is set to yes in the dayGridMonth view. When it is set to no it seems to work without problem.
> 
> You can set it to no with `occ user:setting <userid> calendar eventLimit no`

This did not fix the issue for me.

**Comment by GUNT0815** [comment] 2022-06-28 10:23
actual status on my installation (all app/instances up-to-date): 

- occ user:setting <userid> calendar eventLimit no -> did not fix the issue
- change to weekly view -> did not fix the issue

in web-gui calendar wheel keeps spinning and view is not loaded for some calendars. no issues with caldav-access via third party apps.

**Comment by st3iny** [comment] 2022-06-28 11:49
The root of the problem is 32b05b80. The EventRender component is rendered over and over again in an endless loop.

**Comment by st3iny** [comment] 2022-06-28 13:01
I have bad news: Main is also affected.

**Comment by ChristophWurst** [comment] 2022-06-29 16:43
> I have bad news: Main is also affected.

Would a revert of https://github.com/nextcloud/calendar/pull/4305 help?

**Comment by petrikoz** [comment] 2022-06-30 07:14
> Will reverse #4305 help?

Yes, the calendar now works on the "Month" view `/apps/calendar/dayGridMonth/now`.

But all the colors in the background of the events are gone. This happened after updating to version `3.4.1`. In the other views (Day, Week and List) everything looks fine

**Comment by lapor-kris** [comment] 2022-06-30 08:08
Yes, I agree that the colors are gone. For the whole day event, they stayed. Only for hourly meeting, the colors are gone.

**Comment by miaulalala** [comment] 2022-06-30 09:19
> Yes, I agree that the colors are gone. For the whole day event, they stayed. Only for hourly meeting, the colors are gone.



> After installing v3.4.1, the calendar is fixed two of my three NC 24.0.2 instances. I also confirm that the background colour is lost in the month view.



> > Will reverse #4305 help?
> 
> Yes, the calendar now works on the "Month" view `/apps/calendar/dayGridMonth/now`.
> 
> But all the colors in the background of the events are gone. This happened after updating to version `3.4.1`. In the other views (Day, Week and List) everything looks fine

We had to accept this regression unfortunately (https://github.com/nextcloud/calendar/pull/4324) so we could get Calendar to work again.

**Comment by st3iny** [comment] 2022-06-30 09:26
> > I have bad news: Main is also affected.
> 
> Would a revert of #4305 help?

Probably. We will have to come up with another fix for the regression though.

**Comment by st3iny** [comment] 2022-07-06 12:16
Fixed by #4351, #4339 and #4324

**Closed by st3iny** 2022-07-06 12:16 UTC
Labels: 1 - to develop, bug, needs info, regression, nextcloud-gmbh

**Comment by schemar** [comment] 2022-07-08 08:28
Just updated and works like a charm :heart: Thank you!

**Comment by GUNT0815** [comment] 2022-07-08 09:33
Unfortuneately not for my installation: calendar 3.4.2 and nextcloud 24.0.2 on docke: calendar keeps spinning and is not loading on the web gui. I can even not export the calendar affected.

**Comment by ChristophWurst** [comment] 2022-07-08 09:36
@GUNT0815 please file a report and include server and browser logs.

**Comment by GUNT0815** [comment] 2022-07-23 11:44
Issue can be closed from my perspective. 

After I made a fully fresh installation based on nextcloud-aio (they use nextcloud hub 23.x) with no issues. I can see all date in the web-calendar gui and all caldav/carddav data exchanges work like a charm.

**Comment by the-moog** [comment] 2022-07-24 09:37
That is like saying I fixed the issue with my broken car by buying a new one.

> Issue can be closed from my perspective.
> 
> After I made a fully fresh installation based on nextcloud-aio (they use nextcloud hub 23.x) with no issues. I can see all date in the web-calendar gui and all caldav/carddav data exchanges work like a charm.

**Comment by GUNT0815** [comment] 2022-07-24 10:38
> That is like saying I fixed the issue with my broken car by buying a new one.
> 
> > Issue can be closed from my perspective.
> > After I made a fully fresh installation based on nextcloud-aio (they use nextcloud hub 23.x) with no issues. I can see all date in the web-calendar gui and all caldav/carddav data exchanges work like a charm.

You are absolutely right. I invested so many hours in order to fix the issue, and my famliy users where complaining already about "lost" calender entries etc. And finaly it came out with the result, that the database (mariaDB) might be broken somewhere. So based on my limited time and knowledge I decided to transfer the data to a new installation - this was the best way for me. Took me ~4h (which is less then the whole investigation for the calendar issue has consumed so far)

**Comment by the-moog** [comment] 2022-07-24 11:30
I have also spent countless hours trying to get to the bottom of this. All we need to know is what DB entry is broken then.....  I've long suspected the issues with calendar are database related.  something in the schema update is broken with long lived installs.   I don't have the luxury of a ground up install. Far too many files and users.  Losing that much history would be too painful to say the least.  Right now we just have to accept the calendar (and thus any related productivity tools like event bookings) are just not a feature.

**Comment by GUNT0815** [comment] 2022-07-24 14:30
@the-moog : maybe you should have a look into the nextcloud-aio project and look how they describe a possible migration. Sounds reasonable effort to me. But you might need some offline time to do so in a consistent manner. But maybe you try with a test user first in order to check if its working. In the long time a fresh installation might be less painfull than receiving all the complaints and the loss of trust in the nextcloud installation.

**Comment by st3iny** [comment] 2022-07-24 18:05
Please open a new ticket if you encounter a similar bug. I greatly appreciate your engagement but replying on a resolved issue causes unnecessary notifications for us developers.
