### ISSUE TITLE
Import ics-file into an existing calendar using occ

### ISSUE THREAD

**Issue by Euklios** [nextcloud/calendar#1862] opened 2020-01-19 21:39 UTC
**Is your feature request related to a problem? Please describe.**
I have a nextcloud installation including the calendar plugin running. We are sharing files and a calendar for school-related assignments using nextcloud. However, our school provides a calendar including assignments within they're own calendar, as well as an "export to ics-uri" feature that we try to use within our own calendar. We currently import this calendar using the Web-UI, but we'd prefer to have a cronjob, that periodically imports the static link into a given calendar.

**Describe the solution you'd like**
The "import calendar" button as an occ command.
Something like `occ dav/import-calendar [calendar] [uri]` should do the same as the UI is already doing.

**Describe alternatives you've considered**
It would also solve our problem if we could add an ics-uri to a given Calendar and get the same functionality as within the "Subscriptions". The Problem with a "Subscription" is, that we can't add our own events into the same calendar, or modify existing events.

**Comment by georgehrke** [comment] 2020-01-20 08:33
Duplicate of https://github.com/nextcloud/server/issues/564

**Closed by georgehrke** 2020-01-20 08:33 UTC
Labels: 0. to triage, enhancement-proposed
