### ISSUE TITLE
add to docs: share multiple calendars in one link

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#2289] opened 2020-05-28 08:46 UTC
Possibility to share multiple calendars in one link (e.g. for iframe embedding) is already implemented: https://github.com/nextcloud/calendar/issues/708 but not documented yet: https://docs.nextcloud.com/server/18/user_manual/pim/calendar.html#publishing-a-calendar

Btw this is really helpful, thanks for making it possible =)

**Comment by georgehrke** [comment] 2020-05-28 09:00
Duplicate of https://github.com/nextcloud/calendar/issues/1814#issuecomment-576657068

**Closed by georgehrke** 2020-05-28 09:00 UTC
Labels: 0. to triage, enhancement-proposed

**Comment by alexanderdd** [comment] 2020-09-04 16:45
@georgehrke the issue you linked is very unspecific, and "share multiple calendars in one link" might be overlooked. I would reopen this issue here.

**Comment by georgehrke** [comment] 2020-09-04 16:49
Documentation issues should be reported in https://github.com/nextcloud/documentation/

However, just as simple as opening a new issue, it would be to send a pull-request to fix the documentation. :) 

This is the file in question: https://github.com/nextcloud/documentation/blob/master/user_manual/pim/calendar.rst#publishing-a-calendar

You can just edit it online and send a PR. The delimiter for multiple tokens is a dot: `.`
