### ISSUE TITLE
Calendar shows US date format in UK locale

### ISSUE THREAD

**Issue by rptb1** [nextcloud/calendar#2777] opened 2021-01-07 02:33 UTC
### Steps to reproduce
1. Install Nextcloud snap (20.0.4) on Ubuntu 18.04.
2. Create account with locale set to English (UK).
3. Install Calendar addon.
4. Switch to week view.
5. Observe days are labelled with US MM/DD/YYYY format.
6. Create an event and click on it.
7. Observe events are also labelled with US MM/DD/YYYY format dates.

### Expected behaviour
The calendar should use the locale's date format.

### Actual behaviour
The calendar uses US date format.

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** macOS Calendar, DAVx5 (Android)

### Client configuration
**Browser:** Firefox 84.0.2

**Operating system:** macOS 10.14.6

### Server configuration

**Operating system**: Ubuntu 18.04.5 LTS

**Web server:** Nginx reverse proxy to snap (apache?)

**Database:** Whatever is in the snap (mysql?)

**PHP version:** Whatever is in the snap. 

**Nextcloud Version:** 20.0.4

**Updated from an older installed version or fresh install:** Fresh yesterday.

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - integration_github: 0.0.16
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
  - weather_status
```

**Nextcloud configuration:**

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1:50580"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "http:\/\/127.0.0.1:50580",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritehost": "cloud.bogus.agency",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.13.4",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "77"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.1.3",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.4.3",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1609850141.884",
            "lastcron": "1609986265",
            "lastupdatedat": "1609850141.8982",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "923ae025f0db65df3460ee76c8e9536d",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.16.2",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.10.2",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.11.1",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.17.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.12.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "integration_github": {
            "enabled": "yes",
            "installed_version": "0.0.16",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "readableLocation": "gb",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.1.0",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "5",
            "enabled": "yes",
            "imprintUrl": "***REMOVED SENSITIVE VALUE***",
            "installed_version": "1.11.0",
            "name": "Bogus Agency Cloud",
            "privacyUrl": "***REMOVED SENSITIVE VALUE***",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "5.0.0",
            "types": ""
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": "filesystem"
        }
    }
}
```

### Logs
These are tricky for me to get right now.  Please ask if you think they are relevant.

**Comment by hansdez** [comment] 2021-01-10 16:44
I can confirm that I too have the exact same issue. Please see the screenshot of my language/locale settings with today showing the correct way:

![language-locale-settings](https://user-images.githubusercontent.com/20969754/104128968-b9932880-536a-11eb-865d-c74c19e23d13.png)

And then how the calendar shows the 10th of January:

![wrong-format-1](https://user-images.githubusercontent.com/20969754/104129027-11ca2a80-536b-11eb-8710-20f57f925cf6.png)

I believe this was introduced when I upgraded from 19.x to 20.x.

It is a pretty sore bug for me, as I can easily lead to very irritating calendar mistakes, especially for the first 12 days of every month.

Below my server details:

## Server configuration detail

**Operating system:** Linux 4.15.0-130-generic #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021 x86_64

**Webserver:** nginx/1.14.0 (fpm-fcgi)

**Database:** mysql 5.7.32

**PHP version:** 

7.2.24-0ubuntu0.18.04.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 20.0.4 - 20.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.13.4
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - contactsinteraction: 1.1.0
 - dav: 1.16.2
 - deck: 1.2.3
 - federatedfilesharing: 1.10.2
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.1
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - forms: 2.1.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_totp: 5.0.0
 - twofactor_u2f: 6.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - accessibility
 - admin_audit
 - comments
 - contacts
 - dashboard
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - recommendations
 - support
 - survey_client
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "files.enhancedstrategy.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.4.0",
    "overwrite.cli.url": "https:\/\/files.enhancedstrategy.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [
        "Racist technology"
    ],
    "maintenance": false,
    "simpleSignUpLink.shown": false,
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

**Comment by mrbenjoi** [comment] 2021-03-28 18:00
I have the same issue. Language is set to English (US) and locale to German (Germany). Dates are shown in Month/Day/Year format, which is not german format.

Nextcloud version: 20.0.8
Calendar Version: 2.2.0

**Comment by mrbenjoi** [comment] 2021-04-15 07:43
I have an update on this issue. I just noticed some weird behavior on this, when switching the view modes in calendar.

**Preconditions:**
- calendar view mode is set to "week"

**Steps:**
1. set calendar view mode to "month"
1. switch to Tasks-App in Nextcloud. (I haven't tested if th
1. switch back to calendar-app, view mode should still be month
1. set view mode to "week"
1. the dates are now shown in the correct format.

Can anybody confirm this? Can anybody reproduce this in his/her set up?

**Comment by hansdez** [comment] 2021-05-20 14:44
When I change my language to 'English (British English)', the dates are shown in the correct way.

Could it be that the calendar app looks at the language rather than the locale when deciding how to format the dates?

**Comment by mrbenjoi** [comment] 2021-05-24 08:49
Is there a possibility to promote this issue? It seems like there hasn't been any reaction to it yet, or am I missing something?

**Comment by Jusgast** [comment] 2021-06-09 09:40
We are having this issue with Nextcloud 21.0.2 as well, the locale is set to Dutch and the language to English (US). Setting the language to English (English British) solves the problem. Weird thing is that some parts are being translated to Dutch with the British setting where it did not with the US setting, the online status menu for instance.
Sidenote is that the format also changes from MM/DD/YYYY to DD-MM-YYYY, with dashes instead of slashes.

**Comment by dbadura** [comment] 2021-06-19 08:06
> I have an update on this issue. I just noticed some weird behavior on this, when switching the view modes in calendar.
> 
> **Preconditions:**
> 
>     * calendar view mode is set to "week"
> 
> 
> **Steps:**
> 
>     1. set calendar view mode to "month"
> 
>     2. switch to Tasks-App in Nextcloud. (I haven't tested if th
> 
>     3. switch back to calendar-app, view mode should still be month
> 
>     4. set view mode to "week"
> 
>     5. the dates are now shown in the correct format.
> 
> 
> Can anybody confirm this? Can anybody reproduce this in his/her set up?

I was able to reproduce this behavior.

Infortunately, the calendar goes back to the unwanted state.

**Comment by mrbenjoi** [comment] 2021-07-24 08:41
Ok, so I had a look into the code and tried to find the possible source of this problem. I'm neither familiar with vue.js nor with the nextcloud code base, so I might be wrong. I think though this particular portion could be causing the issue:

File: https://github.com/nextcloud/calendar/blob/master/src/utils/moment.js

```javascript
export default async function loadMomentLocalization() {
	const locale = getLocale().replace('_', '-').toLowerCase()
	const language = getLanguage().replace('_', '-').toLowerCase()

	if (locale === language) {
		return getLocaleFor(locale)
	}

	const [realLocale, realLanguage] = await Promise.all([getLocaleFor(locale), getLocaleFor(language)])
	if (realLocale === realLanguage) {
		return realLocale
	}

	const name = `nextcloud-calendar-fake-locale-${realLocale}-${realLanguage}`
	moment.defineLocale(name, {
		parentLocale: realLanguage,
		longDateFormat: {
			LT: moment.localeData(realLocale).longDateFormat('LT'),
			LTS: moment.localeData(realLocale).longDateFormat('LTS'),
			L: moment.localeData(realLocale).longDateFormat('L'),
			LL: moment.localeData(realLocale).longDateFormat('LL'),
			LLL: moment.localeData(realLocale).longDateFormat('LLL'),
			LLLL: moment.localeData(realLocale).longDateFormat('LLLL'),
		},
		week: {
			dow: moment.localeData(realLocale).firstDayOfWeek(),
			doy: moment.localeData(realLocale).firstDayOfYear(),
		},
	})

	return name
}
```

It seems correct to differentiate between language and locale if they are not equal and to build a "custom" locale that contains parts of the language and the locale. One probably still wants week days to be translated to the correct language but the date to be formatted in the custom other locale. That's is quite tricky I guess.

**Question:** Maybe the `parentLocale` being set to `realLanguage` causes this issue somehow, even though parts of the date locales are set to `realLocale`. Could this be changed to `parentLocale = realLocale`? This would probably require `week.dow` to be set to `realLanguage` instead to provide the correct name of the week day.

These are just some thoughts. I haven't actually debugged this, since I am not experienced with debugging nextcloud apps. I might try that another time but maybe someone else feels like debugging this in the meantime and check what exactly is going on here.

**Comment by ChristophWurst** [comment] 2021-08-13 14:33
@mrbenjoi your observations seem to match https://github.com/nextcloud/server/pull/14784. I guess it's the same unsolved problem.

**Comment by mrbenjoi** [comment] 2021-08-16 06:34
@ChristophWurst thanks for your reation. Would it rather makes sense to reopen that issue or to create a new issue? It seems that this problem causes several bugs and should have an own issue. What do you think?

For all others waiting for a fix on this issue: If we repoen that other issue you might want to support the fix of the problem by leaving a comment or reaction there, as soon as it is open again.

**Comment by ChristophWurst** [comment] 2021-08-16 06:38
>  reopen that issue

The issue is at https://github.com/nextcloud/server/issues/15457 and it's still open.

**Comment by mrbenjoi** [comment] 2021-08-16 06:47
Ok, I will leave a comment there with a reference to here. @Anybody: If you're affected please show your affection using the :+1: button on the OPs or my comment.

**Comment by EricC-59** [comment] 2021-09-05 17:30
The issue is still there in:

* Nextcloud  21.0.4
* Calendar 2.3.3

When I use Language = en_US and Locale = fr_FR, I get Mon 8/30/2021 instead of Lun 30/08/2021.
With Language = en_GB, I get Mon 20/8/2021.

I suggest changing the issue title with something like "Calendar formats date according to language instead of locale", which is a more generic description of the issue.

NB: If I understand correctly, the issue at [Timestamps are not displayed in the preffered language](https://github.com/nextcloud/server/issues/15457) is different from this issue. According to issue #15457, the date should be neither "Mon 8/30/2021", nor "Lun 30/08/2021", but "Mon 30/08/2021".

**Comment by khampf** [comment] 2021-12-16 00:51
Issue is still in:

- Nextcloud 22.2.3
- Calendar 3.0.2

**Comment by ChristophWurst** [comment] 2021-12-16 12:13
It's sufficient to add your :+1: to the original report

**Comment by paultheweird** [comment] 2022-12-05 20:29
I opened #4739 for the same issue. It's still a problem on 25.0.1

**Comment by st3iny** [comment] 2024-07-10 06:48
I tried to reproduce this issue locally and it works as expected now. I couldn't find a combination of language and locale where the formatting in Calendar didn't match the preview below the locale setting. There have been multiple improvements and fixes to locale handling in the meantime.

I'll open a PR to fix the first day of the week shortly.

---

If someone is still facing the issue stated here, please let us know. Otherwise, I'm inclined to close this issue.

**Closed** 2024-07-24 09:40 UTC
Labels: bug, 0. to triage

**Comment by bemyak** [comment] 2025-03-05 16:28
I'm using Nextcloud 30.0.6 with calendar app 5.1.2, and date input fields use incorrect format:

![Image](https://github.com/user-attachments/assets/b7d1fc55-4cbe-4fac-90aa-7d12501e5fed)

(Notice how Date of birth differs from locale preview. Date and months are swapped as well, so it's a US locale)

The same goes for the calendar events:

![Image](https://github.com/user-attachments/assets/0203ff39-e424-46a7-8ba9-70dc2ff043ec)

Am I missing something?
