### ISSUE TITLE
Can't modify appointment "Additional calendars to check for conficts" if user has exactly two calendars

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#4697] opened 2022-10-28 10:37 UTC
### Steps to reproduce

1. Setup a "Appointments" in the calendar
2. Set a "Additional calendars to check for conficts"
3. save the settings and close it
4. try to edit the configured "Appointments" 
5. You can neither remove the previously added calendar "to check for conflicts" nor add a additional one

Tested on c.nc.com with the latest Firefox

### Expected behavior

I could edit the "Appointments" and remove a previously added calendar to check for conflicts or add a additional one.

### Actual behaviour

I can not edit the "Appointments" and remove a previously added calendar to check for conflicts or add a additional one.

![grafik](https://user-images.githubusercontent.com/1589737/198568289-49e3a319-09fe-402f-a751-10f5e5a32e28.png)

### Calendar app version

4.0.2

### Browser

Firefox 105.0.2

**Comment by ChristophWurst** [comment] 2022-11-02 07:23
The conflict calendar goes into disabled state if there are less than two calendars to pick from.

How many own, writeable calendars do you have? Exactly 2?

**Comment by schiessle** [comment] 2022-11-03 19:59
Indeed, I had exactly 2 (regular) calendars. Adding another one allowed me to edit again. But that's a bug, right? I should be able to remove the "private" calendar again even if there are no additional calendars.

**Comment by ChristophWurst** [comment] 2022-11-04 08:05
Duplicate of https://github.com/nextcloud/calendar/issues/4069

**Comment by ChristophWurst** [comment] 2022-11-04 08:06
Oh no, it's actually two separate bugs.

**Closed** 2024-01-10 09:53 UTC
Labels: 3 - to review, bug, Feature: Appointments
