### ISSUE TITLE
Feature Request: Next X Days view

### ISSUE THREAD

**Issue by virtualdxs** [nextcloud/calendar#672] opened 2017-12-06 03:51 UTC
I'm moving over from Google Calendar, and the main thing I miss is being able to have my view be the next 4 or the next 7 days. The reason I like this is because I want to see on Saturday what happens Saturday-Friday not last Sunday to now.

**Comment by georgehrke** [comment] 2018-02-03 02:21
Duplicate of #6 

I'm closing this as a duplicate of #6, because it's asking for exactly what we are achieving with continuous scrolling in week view. Instead of being forced to see a week as a rigid unit from Monday thru Sunday, you can just scroll to have today in the position of the first column and just see the next 7 days, no matter whether today is Monday, Tuesday or any other day of the week.

**Closed by georgehrke** 2018-02-03 02:21 UTC
