### ISSUE TITLE
Colorpicker for Calendar broken in Safari

### ISSUE THREAD

**Issue by raffisweb** [nextcloud/calendar#4508] opened 2022-09-12 19:11 UTC
### Steps to reproduce

1. opening Nextcloud Calendar on Safari for Mac, latest
2. three dots menu next to calendar name
3. calendar color editing not possibe

### Expected behavior

Color picker clickable

### Actual behaviour

Color picker appears but hides immediately after moving mouse towards colors. No chance to hit a color.

**Comment by ChristophWurst** [comment] 2022-09-13 09:12
Could you post a screenshot or short screencast please?

**Comment by ChristophWurst** [comment] 2022-09-13 09:12
This seems to be a duplicate of https://github.com/nextcloud/calendar/issues/3107

**Closed by ChristophWurst** 2022-09-13 09:12 UTC
Labels: bug, 0. to triage

**Comment by raffisweb** [comment] 2022-09-13 19:59
> Could you post a screenshot or short screencast please?

<img width="222" alt="Bildschirmfoto 2022-09-13 um 21 55 46" src="https://user-images.githubusercontent.com/22199157/189997449-e66821cb-886d-42b7-bf80-51907a253010.png">

Found this: Color Picker works if you first click something on the page. But it is unstable.
