### ISSUE TITLE
On birthdays, Calendar displays the year of birth instead of the age

### ISSUE THREAD

**Issue by Kalytis** [nextcloud/calendar#3456] opened 2021-09-07 13:26 UTC
### Steps to reproduce
1. Adding a birth date including the year in a contact card
2. Activating the birthday calendar in NC

### Expected behaviour
On the birthday, after the name, Calendar should show the age of the person.

### Actual behaviour
After the name, Calendar shows the year of birth.

### Calendar app
**Calendar app version:** v2.3.3

**CalDAV-clients used:** Thunderbird Lightning, Nextcloud web app, Etar Calendar

Thanks by advance

**Comment by raimund-schluessler** [comment] 2021-09-07 13:27
Duplicate of https://github.com/nextcloud/calendar/issues/940

**Closed by raimund-schluessler** 2021-09-07 13:27 UTC
Labels: bug, 0. to triage

**Comment by tcitworld** [comment] 2021-09-07 14:04
Also related https://github.com/nextcloud/server/issues/12462

**Comment by Kalytis** [comment] 2022-12-21 19:04
Hi, the problem still occurs, any news on this please ?
