### ISSUE TITLE
Calendar loads endlessly: Uncaught (in promise) TypeError: Cannot read property 'hasProperty' of undefined     at app.js:4069

### ISSUE THREAD

**Issue by uli-heller** [nextcloud/calendar#495] opened 2017-06-02 15:06 UTC
Unfortunately, I don't know exactly how to reproduce the bug.

I have nextcloud-12 and calendar-1.5.3 and php7.0. I'm using the web interface of the calendar.

Looking at the month of May, everything is fine.
Looking at the month of June, I see spinning wheels in the left bar forever and this javascript
error shows up:

```
Uncaught (in promise) TypeError: Cannot read property 'hasProperty' of undefined
    at app.js:4069
```

![image](https://cloud.githubusercontent.com/assets/1677414/26731762/5b2d4952-47b5-11e7-8b7f-8dd6cc86341e.png)

### June

The endless spinning wheel

![image](https://cloud.githubusercontent.com/assets/1677414/26731822/91dabb88-47b5-11e7-91a9-cd010897345e.png)

### May

Everything is fine

![image](https://cloud.githubusercontent.com/assets/1677414/26731847/adb81030-47b5-11e7-86c7-e1f45ed2e9df.png)

Shall I provide more infos?

**Comment by georgehrke** [comment] 2017-06-02 15:13
It looks like this is triggered by some broken ics data. (although an error in one event is obviously not supposed to break the entire calendar)

`vevent` is absolutely not supposed to be undefined.
- Can you check how many elements the `vevents` array has? 
- Can you evaluate `context.comp.toString()`?

**Comment by georgehrke** [comment] 2017-06-02 15:20
Apparently this catch doesn't actually catch the type error and the promise remains rejected.
https://github.com/nextcloud/calendar/blob/master/js/app/models/calendarmodel.js#L83

Therefore `Promise.all` down here fails and `then` is never executed.
https://github.com/nextcloud/calendar/blob/master/js/app/models/calendarmodel.js#L91

**Comment by uli-heller** [comment] 2017-06-02 18:53
I'll have a look at it.

I made a copy of my nextcloud instance a couple of days ago. This copy doesn't have the error.

I'll do this:

1. Provide the info you requested
2. Try to figure out what's different between the two instances. I expect just a couple of calendar events...

Best regards, Uli

**Comment by uli-heller** [comment] 2017-06-02 18:53
Am 02.06.2017 um 17:13 schrieb Georg Ehrke:
> Can you check how many elements the vevents array has?
I think it has one element: vevents:Array(1)

>     Can you evaluate context.comp.toString()?
>
How do I do this? I'm not a javascript expert, I have to admit...

Best regards, Uli

**Comment by uli-heller** [comment] 2017-06-02 18:55
I think I know now which calendar invitation caused the error. I accepted it via thunderbird and thunderbird syncs this with nextcloud. Is it of any benefit if I'd provide the ICS file?

**Comment by uli-heller** [comment] 2017-06-02 19:17
I imported the ICS file now directly into nextcloud and this works fine, no issue at all.
I guess I'll compare the records within oc_calendarobjects and oc_calendarobjects_props.
Seems like there is some issue related to thunderbird, isn't it?

**Comment by georgehrke** [comment] 2017-06-04 10:53
> Is it of any benefit if I'd provide the ICS file?

Yes, that would be great :) 
the ics format is text-based, so you can just open it in a text editor and strip everything personal

**Comment by uli-heller** [comment] 2017-06-04 13:32
I attached a zip file. It contains these:

1. The ICS file
2. The content of some nextcloud tables when accepting the ICS within 
thunderbird ("ko")
3. The content of some nextcloud tables when importing the ICS directly 
into nextcloud ("ok")

Hopefully, I stripped most of the personal information.

Thanks for your support!

-- 
Uli Heller

daemons point Gesellschaft für Datenverarbeitung mbH
Zahn-Nopper-Straße 1-3, 70435 Stuttgart
Internet: www.daemons-point.com
Tel:+49 711 806708 0, Fax: +49 711 806708 19
mailto:uli.heller@daemons-point.com

Geschäftsführer: Steffen Walter, Uli Heller
Sitz der Gesellschaft: Stuttgart
Amtsgericht Stuttgart, HRB 22333

**Comment by georgehrke** [comment] 2017-06-04 20:25
@uli-heller You can't upload attachments to GitHub by attaching them to a mail, you have to use website ;) 

If Github doesn't accept zip, just paste the raw text please

**Comment by uli-heller** [comment] 2017-06-05 04:35
![image](https://cloud.githubusercontent.com/assets/1677414/26770580/853f1d4c-49b8-11e7-9ace-cd2ea027fc6e.png)

@georgehrke: I can see a link to the zip file and clicking on it downloads the file. What do you mean by "If Github doesn't accept zip, just paste the raw text please"? Can you access the file?

I received a warning message from github (... maybe, or I just checked the ticket on the web site) and attached the zip via the web site a couple of minutes after responding via mail.  I'm hoping the content of the zip doesn't show up on google (... in case I missed some fields when doing the anonymization).

**Comment by georgehrke** [comment] 2017-06-05 07:54
Ah, I didn't see that. Thanks.

> I'm hoping the content of the zip doesn't show up on google (... in case I missed some fields when doing the anonymization).

Not sure about that, but i wasn't able to find anything private in there :)

**Comment by jcnoir** [comment] 2017-07-16 10:28
Any news on this issue ? Already a month whithout my web calendar because of this ...

**Comment by rebeccaformfx** [comment] 2017-08-19 22:56
Having this same issue in August !

**Comment by georgehrke** [comment] 2017-08-19 23:15
@rebeccaformfx Please don't comment when you can't add anything new. Use [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead. :)

If this issue was fixed, this ticket would be closed.

**Comment by rebeccaformfx** [comment] 2017-08-19 23:22
OK... then perhaps I will try and add something new.  
Having the same issue with a Google Calendar sync, and when I download the ics file from the More button on the Calendar app, the document has lots of "SUMMARY:  Busy" entries.  

Not sure if this is a Google issue of NextCloud.

**Comment by georgehrke** [comment] 2017-08-19 23:40
Summary: Busy is probably caused the fact that it's in a shared calendar, right?

**Comment by farion** [comment] 2017-10-06 11:17
Same issue here. Did work with 1.4.

**Comment by rstrietzel** [comment] 2017-10-19 21:09
I have the same problem. I had a quick look - vevent is undefined in some cases. A possible source is that I accepted changes to recurring events in Thunderbird in the month where it was not working.

To make the calendar visible again I used this quick fix:
replacing
```
				        if (!vevent.hasProperty('dtstart')) {
						resolve([]);
					}
```
with
```
					if (!vevent || !vevent.hasProperty('dtstart')) {
						resolve([]);
						return;
					}
```

**Comment by j0s** [comment] 2017-10-19 21:26
I can reproduce the problem by creating a recurring task in Evolution, copying it and pasting it on another day.

**Comment by jcnoir** [comment] 2017-10-19 22:24
Thank you so much for this fix !!!
In my case I needed an additional check  to make it work:

```javascript
 if (typeof vevent == 'undefined') {
                                                        resolve([]);
                                                        return;
                                                }
                                        if (!vevent || !vevent.hasProperty('dtstart')) {
                                                        resolve([]);
                                                        return;
                                                }

```

I like the nextcloud project very much but waiting for 5 month for a blocking issue to be fixed in a major app is very difficult to understand from my user point of view.

**Comment by georgehrke** [comment] 2017-10-20 06:19
Thx for digging into this!

@rstrietzel @j0s Can one of u please provide a broken ics file that can be used to reproduce the bug? :) THX!

**Comment by jcnoir** [comment] 2017-11-12 13:11
Just a minimal ics file (renamed to txt) that reproduces the issue (using the j0s method in evolution).
[test-2017-11-12.ics.txt](https://github.com/nextcloud/calendar/files/1464671/test-2017-11-12.ics.txt)

**Comment by jcnoir** [comment] 2017-12-09 21:51
Any news about this issue ? We have been very nice users ;-) giving all the help we can (code fix, broken ics ...)
A fix for christmas would be such a nice thing to do ;-)

**Comment by georgehrke** [comment] 2018-02-10 12:26
I will close this as duplicate of #722, because it contains more technical details what the issue actually is and how we should address it.
When I opened #722 i wasn't aware that it's the same issue as this one.

And don't worry, #722 is assigned to the same milestone as this bug ;)

**Closed by georgehrke** 2018-02-10 12:26 UTC
Labels: 1 - to develop, bug
