### ISSUE TITLE
Cannot share with user groups

### ISSUE THREAD

**Issue by Developer10Ofinube** [nextcloud/calendar#1969] opened 2020-02-08 07:41 UTC
### Steps to reproduce
1. Share a a calendar with a user group 
2. Go other site in nextcloud (ex. files)
3. Back to the calendar to check sharing user and groups
4. Group didn't save

### Expected behaviour
Save sharing with a user group
### Actual behaviour
Didn't save sharing with a group
### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0.3)

**Nextcloud Version:** (see admin page, e.g. 17.0.2)

**Updated from an older installed version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by rcdncn** [comment] 2020-02-10 02:17
Curious to know whether the user group you are sharing to is one word or multiple? I have the same issue, but only with my group 'ABCD staff', not with the group 'resources'

**Comment by IABLinz** [comment] 2020-02-13 13:26
We have the same problem if the group name contains umlauts.

**Comment by georgehrke** [comment] 2020-02-16 18:13
Duplicate of nextcloud/server#17610

**Closed by georgehrke** 2020-02-16 18:13 UTC
Labels: 0. to triage, bug
