### ISSUE TITLE
Can't import Outlook exported .ics file: File could not be parsed

### ISSUE THREAD

**Issue by PacoHolliday** [nextcloud/calendar#1176] opened 2019-03-19 16:09 UTC
### Steps to reproduce
1. Export .ics file from MS Outlook 16.0
2. Try import into NextCloud 15 Calendar
3. "File could not be parsed"
4. Try import in Google calendar, works.

### Expected behaviour
Should import fine, does so with Google calendar

### Actual behaviour
The import doesn't start, error message: File could not be parsed

### File contents
```
BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 16.0 MIMEDIR//EN
VERSION:2.0
METHOD:PUBLISH
X-CALSTART:20190320T103000Z
X-CALEND:20190410T100000Z
X-CLIPSTART:20190314T230000Z
X-CLIPEND:20190413T220000Z
X-WR-RELCALID:{0000002E-170A-F6C0-984E-DE35B7B49FEA}
X-WR-CALNAME:Tester Test
X-PRIMARY-CALENDAR:TRUE
X-OWNER;CN="Tester Test":mailto:t.test@test.com
X-MS-OLK-WKHRSTART;TZID="Mitteleuropäische Zeit":083000
X-MS-OLK-WKHREND;TZID="Mitteleuropäische Zeit":180000
X-MS-OLK-WKHRDAYS:MO,TU,WE,TH,FR
BEGIN:VTIMEZONE
TZID:Mitteleuropäische Zeit
BEGIN:STANDARD
DTSTART:16011028T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010325T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DTEND:20190320T110000Z
DTSTAMP:20190315T071431Z
DTSTART:20190320T103000Z
SEQUENCE:0
SUMMARY;LANGUAGE=de:Gebucht
TRANSP:OPAQUE
UID:Zp5GXiartkiqIgJurtj3pw==
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
BEGIN:VEVENT
DTEND:20190327T110000Z
DTSTAMP:20190315T071431Z
DTSTART:20190327T103000Z
SEQUENCE:0
SUMMARY;LANGUAGE=de:Gebucht
TRANSP:OPAQUE
UID:7X7t5g2vgEiGA5ewhXq2pA==
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
BEGIN:VEVENT
DTEND:20190403T100000Z
DTSTAMP:20190315T071431Z
DTSTART:20190403T093000Z
SEQUENCE:0
SUMMARY;LANGUAGE=de:Gebucht
TRANSP:OPAQUE
UID:omw58NrwXUiksqh+rP2aBw==
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
BEGIN:VEVENT
DTEND:20190410T100000Z
DTSTAMP:20190315T071431Z
DTSTART:20190410T093000Z
SEQUENCE:0
SUMMARY;LANGUAGE=de:Gebucht
TRANSP:OPAQUE
UID:KfQrXjKIjk+K9E4oZI/utg==
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
END:VCALENDAR
```

**Comment by tcitworld** [comment] 2019-03-19 17:05
Works on my side.

Please post your browser information (name, version) and browser console logs.

**Comment by PacoHolliday** [comment] 2019-03-19 18:54
Thanks for the hint. I copied the contents of the file to a new file (using sublime text) and then it worked. I did try re-saving the file, before. But it had to be a completely new file.

**Comment by tcitworld** [comment] 2019-03-19 19:23
Hmm, maybe it could be linked to Windows using CRLF, but we never heard of such issues.

**Comment by georgehrke** [comment] 2020-03-10 14:38
Duplicate of https://github.com/georgehrke/calendar-js/issues/78

**Closed by georgehrke** 2020-03-10 14:38 UTC
Labels: 0. to triage, bug

**Comment by FalurePoint** [comment] 2023-05-12 22:49
Am encountering this issue In the latest version current version of NextCloud on Ubuntu server connecting with Firefox.
"No valid files found, aborting import
ushcal.ics could not be parsed"

Cal content:

BEGIN:VCALENDAR
COMMENT: Author - Thomas Kelley
COMMENT:
COMMENT: The holidays added all repeat until through the year 2030
COMMENT:   * EXCEPT those noted with an asterisk, these are only added for the year 2021
COMMENT:
COMMENT:   ** Holidays with 2 asterisks have a pop-up reminder at midnight
COMMENT:
COMMENT:	New Years	            begins on 	Jan 1
COMMENT:	ML King Day 	            begins on 	3rd Monday of Jan
COMMENT:	Groundhog Day	            begins on 	Feb 2
COMMENT:	Valentine's Day	            begins on 	Feb 14	
COMMENT:	President's Day             begins on 	3rd Monday of Feb
COMMENT:   **	Daylight Savings            begins on 	2nd Sunday of March
COMMENT:	St Patrick's Day            begins on 	March 17
COMMENT:   * 	First day of spring         in 2021 is 	March 20
COMMENT:   * 	Good Friday	            in 2021 is 	Apr 2
COMMENT:   *	Easter		            in 2021 is 	Apr 4	
COMMENT:	US Tax Day	            begins on 	Apr 15	
COMMENT:	Mother's Day 	            begins on 	2nd Sunday of May
COMMENT:	Memorial Day 	            begins on 	last Monday of May
COMMENT:	Juneteenth                  begins on	June 19
COMMENT:	Father's Day                begins on 	3rd Sunday of June
COMMENT:   *	First day of summer         in 2021 is 	June 21
COMMENT:	Independence Day            begins on	July 4
COMMENT:	Labor Day 	            begins on	1st Monday of Sept
COMMENT:   *	First day of autumn         in 2021 is 	Sept 22
COMMENT:	Columbus Day 	            begins on 	2nd Monday of Oct
COMMENT:	Halloween	            begins on 	Oct 31
COMMENT:	Election Day 	            begins on 	First Tues of Nov
COMMENT:   **	Daylight Savings ends       begins on	1st Sunday of Nov
COMMENT:	Veteran's Day               begins on 	Nov 11
COMMENT:	Thanksgiving                begins on 	4th Thursday of Nov
COMMENT:	Black Friday
COMMENT:          (day after Thanksgiving)  begins on 	4th Fri of Nov
COMMENT:   *	First day of winter  	    in 2021 is 	Dec 21
COMMENT:	Christmas Eve               begins on 	Dec 24	
COMMENT:	Christmas Day               begins on 	Dec 25
COMMENT:	New Years Eve	            begins on	Dec 31
COMMENT:
PRODID:-//Astonsoft//EssentialPIM//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH

BEGIN:VEVENT
UID:243379537850136179
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20210101
DTEND:20210101T050001Z
SUMMARY:New Year's Day
DESCRIPTION:New Years Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=1;COUNT=10;BYMONTHDAY=1
END:VEVENT

BEGIN:VEVENT
UID:271696855971409183
LAST-MODIFIED:20201108T223946Z
DTSTART;VALUE=DATE:20210118
DTEND;VALUE=DATE:20210118
SUMMARY:ML King Day
DESCRIPTION:ML King Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=1;COUNT=10;BYDAY=3MO
END:VEVENT

BEGIN:VEVENT
UID:253538028088281530
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20210202
DTEND:20210202T050001Z
SUMMARY:Groundhog Day
DESCRIPTION:Groundhog Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=2;COUNT=10;BYMONTHDAY=2
END:VEVENT

BEGIN:VEVENT
UID:235015755147109088
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20210214
DTEND:20210214T050001Z
SUMMARY:Valentine's Day
DESCRIPTION:Valentine's Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=2;COUNT=10;BYMONTHDAY=14
END:VEVENT

BEGIN:VEVENT
UID:224003802519217661
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20210215
DTEND:20210215T050001Z
SUMMARY:President's Day
DESCRIPTION:President's Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=2;COUNT=10;BYDAY=3MO
END:VEVENT

BEGIN:VEVENT
UID:286227407165727939
LAST-MODIFIED:20201108T223622Z
DTSTART;VALUE=DATE:20210314
DTEND;VALUE=DATE:20210314
SUMMARY:Daylight Savings Time begins today
DESCRIPTION:Daylight Savings Time begins today - set your clocks forward 1
 hour today
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=3;COUNT=10;BYDAY=2SU
BEGIN:VALARM
TRIGGER:20210314T045500Z
ACTION:DISPLAY
DESCRIPTION:Daylight Savings Time begins today - set your clocks forward 1
 hour today
END:VALARM
END:VEVENT

BEGIN:VEVENT
UID:222782492544571366
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20210317
DTEND:20210317T040001Z
SUMMARY:St. Patrick's Day
DESCRIPTION:St. Patrick's Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=3;COUNT=10;BYMONTHDAY=17
END:VEVENT

BEGIN:VEVENT
UID:286441520307256339
LAST-MODIFIED:20201108T224304Z
DTSTART;VALUE=DATE:20210320
DTEND;VALUE=DATE:20210320
SUMMARY:First day of Spring
DESCRIPTION:First day of Spring
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
END:VEVENT

BEGIN:VEVENT
UID:266160381420208523
LAST-MODIFIED:20201110T043610Z
DTSTART;VALUE=DATE:20210402
DTEND:20210402T040001Z
SUMMARY:Good Friday
DESCRIPTION:Good Friday
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
END:VEVENT

BEGIN:VEVENT
UID:287874107485069382
LAST-MODIFIED:20201110T043654Z
DTSTART;VALUE=DATE:20210404
DTEND:20210404T040001Z
SUMMARY:Easter
DESCRIPTION:Easter
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
END:VEVENT

BEGIN:VEVENT
UID:218608764929121996
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20210415
DTEND:20210415T040001Z
SUMMARY:US Tax Day
DESCRIPTION:US Tax Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=4;COUNT=10;BYMONTHDAY=15
END:VEVENT

BEGIN:VEVENT
UID:271254752332424251
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20210509
DTEND:20210509T040001Z
SUMMARY:Mother's Day
DESCRIPTION:Mother's Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=5;COUNT=10;BYDAY=2SU
END:VEVENT

BEGIN:VEVENT
UID:287123388726072793
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20210531
DTEND:20210531T040001Z
SUMMARY:Memorial Day
DESCRIPTION:Memorial Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=5;COUNT=10;BYDAY=-1MO
END:VEVENT

BEGIN:VEVENT
UID:abe196a3-79fc-4852-bfad-a39d9efb15bc
LAST-MODIFIED:20210620T040133Z
DTSTART;VALUE=DATE:20210619
DTEND:20210619T040001Z
SUMMARY:Juneteenth
DESCRIPTION:Juneteenth
CLASS:PUBLIC
DTSTAMP:20210620T040133Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=6;COUNT=10;BYMONTHDAY=19
END:VEVENT

BEGIN:VEVENT
UID:284713224491452631
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20210620
DTEND:20210620T040001Z
SUMMARY:Father's Day
DESCRIPTION:Father's Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=6;COUNT=10;BYDAY=3SU
END:VEVENT

BEGIN:VEVENT
UID:256783220145451466
LAST-MODIFIED:20201108T224236Z
DTSTART;VALUE=DATE:20210621
DTEND:20210621T040001Z
SUMMARY:First day of Summer
DESCRIPTION:First day of Summer
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
END:VEVENT

BEGIN:VEVENT
UID:250764245802028434
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20210704
DTEND:20210704T040001Z
SUMMARY:Independence Day
DESCRIPTION:Independence Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=7;COUNT=10;BYMONTHDAY=4
END:VEVENT

BEGIN:VEVENT
UID:219633323020872501
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20210906
DTEND:20210906T040001Z
SUMMARY:Labor Day
DESCRIPTION:Labor Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=9;COUNT=10;BYDAY=1MO
END:VEVENT

BEGIN:VEVENT
UID:276779342684356697
LAST-MODIFIED:20201108T224236Z
DTSTART;VALUE=DATE:20210922
DTEND:20210922T040001Z
SUMMARY:First day of Autumn
DESCRIPTION:First day of Autumn
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
END:VEVENT

BEGIN:VEVENT
UID:226540905658092275
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20211011
DTEND:20211011T040001Z
SUMMARY:Columbus Day
DESCRIPTION:Columbus Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=10;COUNT=10;BYDAY=2MO
END:VEVENT

BEGIN:VEVENT
UID:269543526216555197
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20211031
DTEND:20211031T040001Z
SUMMARY:Halloween
DESCRIPTION:Halloween
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=10;COUNT=10;BYMONTHDAY=31
END:VEVENT

BEGIN:VEVENT
UID:261647186645341713
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20211102
DTEND:20211102T040001Z
SUMMARY:Election Day
DESCRIPTION:Election Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=11;COUNT=10;BYDAY=1TU
END:VEVENT

BEGIN:VEVENT
UID:275814952229709415
LAST-MODIFIED:20201108T223714Z
DTSTART;VALUE=DATE:20211107
DTEND;VALUE=DATE:20211107
SUMMARY:Daylight Savings Time ends today
DESCRIPTION:Daylight Savings Time ends today - set your clocks back 1 hour
 today
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=11;COUNT=10;BYDAY=1SU
BEGIN:VALARM
TRIGGER:20211107T035500Z
ACTION:DISPLAY
DESCRIPTION:Daylight Savings Time ends today - set your clocks back 1 hour
 today
END:VALARM
END:VEVENT

BEGIN:VEVENT
UID:242099225750291748
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20211111
DTEND:20211111T050001Z
SUMMARY:Veteran's Day
DESCRIPTION:Veteran's Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=11;COUNT=10;BYMONTHDAY=11
END:VEVENT

BEGIN:VEVENT
UID:270036747170405007
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20211125
DTEND:20211125T050001Z
SUMMARY:Thanksgiving Day
DESCRIPTION:Thanksgiving Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=11;COUNT=10;BYDAY=4TH
END:VEVENT

BEGIN:VEVENT
UID:269153814971909741
LAST-MODIFIED:20201108T223920Z
DTSTART;VALUE=DATE:20211126
DTEND:20211126T050001Z
SUMMARY:Black Friday - day after Thanksgiving
DESCRIPTION:Black Friday - day after Thanksgiving
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=11;COUNT=10;BYDAY=4FR
END:VEVENT

BEGIN:VEVENT
UID:226558074974626688
LAST-MODIFIED:20201108T224236Z
DTSTART;VALUE=DATE:20211221
DTEND:20211221T050001Z
SUMMARY:First day of Winter
DESCRIPTION:First day of Winter
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
END:VEVENT

BEGIN:VEVENT
UID:218447634230448016
LAST-MODIFIED:20201108T222756Z
DTSTART;VALUE=DATE:20211224
DTEND:20211224T050001Z
SUMMARY:Christmas Eve
DESCRIPTION:Christmas Eve
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=12;COUNT=10;BYMONTHDAY=24
END:VEVENT

BEGIN:VEVENT
UID:268257100556549014
LAST-MODIFIED:20201108T222756Z
DTSTART;VALUE=DATE:20211225
DTEND:20211225T050001Z
SUMMARY:Christmas Day
DESCRIPTION:Christmas Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=12;COUNT=10;BYMONTHDAY=25
END:VEVENT

BEGIN:VEVENT
UID:258666554916006268
LAST-MODIFIED:20201108T222756Z
DTSTART;VALUE=DATE:20211231
DTEND:20211231T050001Z
SUMMARY:New Year's Eve
DESCRIPTION:New Year's Eve
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=12;COUNT=10;BYMONTHDAY=31
END:VEVENT

END:VCALENDAR
