### ISSUE TITLE
Privacy: contact search 

### ISSUE THREAD

**Issue by Peterede** [nextcloud/calendar#834] opened 2018-06-01 01:18 UTC
When 'Restrict users to only share with users in their groups' is set in Sharing settings the contact search should not return results for users that are not in their group.  This is a privacy issue.

**Comment by georgehrke** [comment] 2018-06-16 10:53
Closing as a duplicate of #9058, as we are just using an API from the Nextcloud server, which is not applying it's own restrictions properly.

**Closed by georgehrke** 2018-06-16 10:53 UTC
