### ISSUE TITLE
Invites not sent in shared calendars

### ISSUE THREAD

**Issue by Perdex** [nextcloud/calendar#3434] opened 2021-08-27 13:14 UTC
### Steps to reproduce
1. Open Nextcloud Calendar in the browser
2. Create a new calendar
3. Create a new event in that calendar (using the non-minimized editor)
4. Add an email as an attendee
5. The UI says "Invitation sent." under the email (see image below)
6. Save event

![image](https://user-images.githubusercontent.com/6844274/131131362-7d85c3bf-8850-44b0-b06e-9d09b82d7504.png)

### Expected behaviour
An invitation received at the entered email address; expecting identical behaviour as when the vent is created to the calendar Personal.

(To be clear, the invite is sent when creating the event into the calendar Personal.)

### Actual behaviour
No email is received by the invited email address

### Calendar app
**calendar version:** 2.3.1

### Client configuration
**Browser:** Firefox 91.0.2

**Operating system:** Manjaro Linux

### Server configuration

**Nextcloud Version:** 21.0.3

**Updated from an older installed version or fresh install:** Autoupdated by Snap

**Comment by ChristophWurst** [comment] 2021-08-30 06:21
Duplicate of https://github.com/nextcloud/server/issues/26668

**Closed by ChristophWurst** 2021-08-30 06:21 UTC
Labels: bug, 0. to triage
