### ISSUE TITLE
Caldav sync for all nextcloud calendars incl. internet subscribed calendars

### ISSUE THREAD

**Issue by GUNT0815** [nextcloud/calendar#5379] opened 2023-07-27 11:30 UTC
### Is your feature request related to a problem? Please describe.

I want to centralize all my calendars incl. holiday calendars, school holidays, garbage collection etc. Therefore I want to configure/subscribe everything in nextcloud and then have all my clients to sync (e.g. via DAVx5) with this central stored calendars. This works fine for all "internal" calendars, but not for subscribed intranet calendars.

### Describe the solution you'd like

a) Handle subscribed intranet calendars in the same way as nextcloud internal calendars, so that they are also synced eg via DAVx5 to all clients.

b) allow subscribed intranet calendars to write appointments to an internal nextcloud calendar (one-way, read-only).

### Describe alternatives you've considered

None, as none is available from my perspective

**Comment by rokejulianlockhart** [comment] 2023-09-07 10:41
Potential duplicate of https://github.com/nextcloud/calendar/issues/5286#issue-1739261977?

**Comment by tcitworld** [comment] 2023-09-07 11:00
Closed as duplicate of #5286

**Closed** 2023-09-07 11:00 UTC
Labels: enhancement, 0 - to triage
