### ISSUE TITLE
Dashboard Calendar Widget -> Event opens new tab, starts to load, then goes unresponsive.

### ISSUE THREAD

**Issue by nztvar** [nextcloud/calendar#3785] opened 2021-12-02 16:50 UTC
### Steps to reproduce
1. Click on any event showing in the calendar widget of the Dashboard
2.
3.

### Expected behaviour
New tab with calendar app, highlighting even in detail sidebar

### Actual behaviour
New tab
Updates tab with page info
Never loads content, Chromium reports page has gone unresponsive

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
3.0.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** (e.g. Firefox 48)
Version 96.0.4664.45 (Official Build, ungoogled-chromium) (64-bit)

**Operating system:** (e.g. Arch Linux)
Ubuntu 21.04, arm64

### Server configuration

**Operating system**: (e.g. Debian 8)
RaspiOS Buster 64-bit

**Web server:** (e.g. Apache, Nginx,...)
NGINX

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
7.0.3 I think

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
23.0

**Updated from an older installed version or fresh install:**
Updated

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - calendar: 3.0.1
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.6
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.4.0
  - integration_discourse: 1.0.2
  - integration_github: 1.0.2
  - integration_gitlab: 1.0.3
  - integration_mastodon: 1.0.2
  - integration_moodle: 1.0.2
  - integration_reddit: 1.0.3
  - integration_twitter: 1.0.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.0
  - maps: 0.1.9
  - music: 1.5.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.2.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - socialsharing_diaspora: 2.4.0
  - socialsharing_email: 2.4.0
  - socialsharing_facebook: 2.4.0
  - socialsharing_twitter: 2.4.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - apporder
  - bookmarks
  - bruteforcesettings
  - encryption
  - files_external
  - groupfolders
  - riotchat
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.saewyc.ca",
            "192.168.1.100"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "overwrite.cli.url": "http:\/\/cloud.saewyc.ca",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "radio",
            "mindmap_app"
        ],
        "default_phone_region": "CA",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nztvar** [comment] 2021-12-06 16:45
Today we tested a few other browsers:

iOS Firefox Daylight 39 (6519) - works fine
Ubuntu arm64 91.3.0esr 64bit (unofficial build) - works fine
Brave and Chromium on Mac (unknown builds) - both fail
Safari on Mac (unkown build) - works fine

It looks like this may be a Chrome-specific issue.

**Comment by ChristophWurst** [comment] 2021-12-06 18:45
Duplicate of https://github.com/nextcloud/calendar/issues/2960. Our tests also show that this is a Chrome-only problem.

**Closed by ChristophWurst** 2021-12-06 18:45 UTC
Labels: bug, 0. to triage

**Comment by nztvar** [comment] 2021-12-06 18:53
Thx! subscribed.
