### ISSUE TITLE
datepicker not working properly in chinese language interface in nextCloud

### ISSUE THREAD

**Issue by funnypig29** [nextcloud/calendar#534] opened 2017-07-11 03:56 UTC
### Steps to reproduce
1.
2.
3.

### Expected behaviour
In calendar app, i want to add a new event. the "starts" and "ends" field should display like "2017年07月19日".

### Actual behaviour
In the "starts" and "ends" field, It display 2017年07711 instead of "2017年07月19日" which what I expected.

### Server configuration

**Operating system**: centos7

**Web server:** nginx

**Database:** mariadb

**PHP version:** 5.6.30

**Server version:** 12.0.0

**Calendar version:** 1.5.3

**Updated from an older installed version or fresh install:** fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**  Nextcloud 12

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.0
  - announcementcenter: 3.1.0
  - audioplayer: 2.0.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - checksum: 0.3.4
  - circles: 0.11.0
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.2.1
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_downloadactivity: 1.1.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.0.1
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_automatedtagging
  - files_external
  - notes
  - user_external
  - user_ldap


If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```

{
    "system": {
        "instanceid": "ocwopizlf58c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.hc.mmh.org.tw"
        ],
        "datadirectory": "\/usr\/share\/nginx\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/nc.hc.mmh.org.tw",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Asia\/Taipei",
        "trashbin_retention_obligation": "auto, 30",
        "log_rotate_size": 104857600,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "nextcloud",
        "mail_domain": "localhost",
        "mail_smtphost": "itmail.mmh.org.tw",
        "mail_smtpport": "25",
        "maintenance": false
    }
}


If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

https

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

firefox, chrome, internet exporer

**Operating system:**

windows 7, window 10, fedora 25

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```
no webserver log for nextcloud

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```
no error log for nextcloud

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
I have no idea how to get browser log.

**Comment by georgehrke** [comment] 2017-07-11 07:37
@funnypig29 Please actually make use of the issue template. There is a reason it's there ...

**Comment by georgehrke** [comment] 2017-07-11 07:38
Please ping me once you provided the information. I will reopen then.

**Comment by funnypig29** [comment] 2017-07-12 01:55
I have updated information about my nextcloud's issue.

**Comment by georgehrke** [comment] 2017-07-12 08:17
Can you please provide a screenshot of the accefted area :)

**Comment by funnypig29** [comment] 2017-07-12 23:58
In this blog, I can't find the way to upload screenshot. Please tell me how to upload.

**Comment by pixelipo** [comment] 2017-07-13 13:35
Just drag&drop or paste into the textarea of the comment, @funnypig29

**Comment by funnypig29** [comment] 2017-07-13 14:36
datepicker  screenshot 
![screen shot 2017-07-13 at 10 33 50 pm](https://user-images.githubusercontent.com/30065379/28171593-83b79658-681b-11e7-945c-929cdbace2c8.png)

...

**Comment by twTrueBlue** [comment] 2017-08-18 19:23
Hi @georgehrke ,
The same issue I was reported before.
I confirm that happen on no matter fresh or upgraded install.
https://github.com/nextcloud/calendar/issues/547

**Comment by georgehrke** [comment] 2018-01-04 17:56
I'd be very happy if someone could help here. 
No clue about chinese date format ...

**Comment by clumsycat** [comment] 2018-01-05 01:49
Hi @georgehrke ,
I track `moment.monthsShort()`(in file /calendar/js/public/app.js) about the initial datepicker, then I noticed that the `/nextcloud/core/vender/core.js` file in Nextcloud might be wrong.

Here is a part on line 2067(I change the code format for reading):
``` js
a.defineLocale("zh-cn", {
	months: "一月_二月_三月_四月_五月_六月_七月_八月_九月_十月_十一月_十二月".split("_"),
	monthsShort: "1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月".split("_"),
	weekdays: "星期日_星期一_星期二_星期三_星期四_星期五_星期六".split("_"),
	weekdaysShort: "周日_周一_周二_周三_周四_周五_周六".split("_"),
	weekdaysMin: "日_一_二_三_四_五_六".split("_"),
	longDateFormat: {
		LT: "HH:mm",
		LTS: "HH:mm:ss",
		L: "YYYY年MMMD日",
		LL: "YYYY年MMMD日",
		LLL: "YYYY年MMMD日Ah点mm分",
		LLLL: "YYYY年MMMD日ddddAh点mm分",
		l: "YYYY年MMMD日",
		ll: "YYYY年MMMD日",
		lll: "YYYY年MMMD日 HH:mm",
		llll: "YYYY年MMMD日dddd HH:mm"
	},
.................
```
PS: not only the **'zh-cn', 'zh-tw' and 'zh-hk'** also have the same longDateFormat.
I think the format should be **`YYYY年M月D日`**. 
However, after the following steps, nothing changed.
1. changed longDateFormat
2. re-register the calendar app
3. restart nextcloud server

Do u think the `core.js` file is wrong? Or I found a wrong place because other app using this file could show the correct date format?

**Comment by yan12125** [comment] 2018-01-14 15:21
@clumsycat: Your idea is a great hint! It turns out that there are two moment.js copies in Nextcloud, one from the server component, and another is indirectly imported via fullcalendar
https://github.com/nextcloud/calendar/blob/d34ad62083cbc70dfe9e0442f33d284581ad76f8/js/bower.json#L9

The issue is already fixed in the latest moment.js.
![correct-date](https://user-images.githubusercontent.com/1937689/34917410-ef60e318-f980-11e7-9af4-ddaa02fcc834.png)

Here are my testing steps:

1. Clone https://github.com/nextcloud/server
2. cd into apps/ and clone https://github.com/nextcloud/calendar
3. Use my forked fullcalendar repo
```Diff
diff --git a/js/bower.json b/js/bower.json
index 20fb8bef..43419abf 100644
--- a/js/bower.json
+++ b/js/bower.json
@@ -6,7 +6,7 @@
     "jquery-timepicker": "883bb2cd94",
     "jstzdetect": "https://github.com/georgehrke/jstimezonedetect.git",
     "ical.js": "1.2.2",
-    "fullcalendar": "3.4.0",
+    "fullcalendar": "https://github.com/yan12125/fullcalendar.git",
     "hsl_rgb_converter": "https://github.com/kayellpeee/hsl_rgb_converter.git"
   },
   "devDependencies": {
```
4. Have fun :)

I've opened https://github.com/fullcalendar/fullcalendar/pull/4014 for including the fix.

**Comment by yan12125** [comment] 2018-01-14 16:13
Oops, fullcalendar removes some API used in nextcloud/calendar. Needs more work here.

**Comment by georgehrke** [comment] 2018-01-14 16:14
> Oops, fullcalendar removes some API used in nextcloud/calendar. Needs more work here.

Yes, working on that :)
Will send a pull request to ensure compatibility with latest fullcalendar soon.

**Comment by yan12125** [comment] 2018-01-14 16:32
Thanks! That's a good news :)

**Comment by georgehrke** [comment] 2018-02-11 01:03
@yan12125 I updated fullcalendar and it's already part of Calendar 1.6.0.

So the bug here is actually in moment.js and not in fullcalendar? 
The calendar uses the moment.js shipped in the Nextcloud server and does not include its own copy:
https://github.com/nextcloud/calendar/blob/master/js/.bowerrc#L5

**Comment by yan12125** [comment] 2018-02-11 10:14
@georgehrke Thanks for the efforts. Unfortunately, my fix for fullcalendar is not merged yet. From https://github.com/fullcalendar/fullcalendar/pull/4014#issuecomment-361123970:

> im making a patch-release right now. since this is such a larger version jump for moment, i'll release this with the next minor version release

I guess it will be in fullcalendar 3.9

**Comment by yan12125** [comment] 2018-10-03 21:56
fullcalendar is already updated to 1.6.2, and apparently date selection works fine with nextcloud calendar 1.6.2. I guess this issue can be closed?

**Closed** 2018-11-04 09:58 UTC
Labels: 1 - to develop, bug, help wanted, needs info
