### ISSUE TITLE
Time selection not opening

### ISSUE THREAD

**Issue by rullzer** [nextcloud/calendar#2265] opened 2020-05-11 10:56 UTC
See https://cloud.nextcloud.com/s/5XZ2QDKyTz2NTXc

Basically selecting a time is no longer possible for events.

**Comment by georgehrke** [comment] 2020-05-11 10:59
Duplicate of https://github.com/nextcloud/calendar/issues/2198

**Closed by georgehrke** 2020-05-11 10:59 UTC
Labels: 0. to triage, bug
