### ISSUE TITLE
disable invitation option if not owner of calendar

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#2458] opened 2020-08-09 20:51 UTC
### Steps to reproduce
1. user1 shares calendar with user2 (write access)
2. user2 creates event in that calendar, invites user3 to event

### Expected behaviour
Invite tab shows info "You cannot invite because you are not the owner of this calendar. This calendar is owned by user1" instead of input field.
Still shows other attendees if there are some.

### Actual behaviour
user2 is shown as organizer, user3 shown as "has not replied yet"

### Comments
See also https://github.com/nextcloud/calendar/issues/2340
Imho this is a bug, not an enhancement, because user2 thinks it worked.

### Calendar app
**Calendar app version:** 2.0.3

### Server configuration
**Nextcloud Version:** 18.0.6

**Comment by georgehrke** [comment] 2020-08-10 07:07
Duplicate of #2145

**Closed by georgehrke** 2020-08-10 07:07 UTC
Labels: 0. to triage, bug
