### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'hasProperty' of undefined     at app.js:4433     at <anonymous>

### ISSUE THREAD

**Issue by piggz** [nextcloud/calendar#607] opened 2017-09-19 18:00 UTC
### Steps to reproduce
1. Export ICS from MS outlook to webdav
2. Import Webdav into 'Work' calendar using ics2owncloud.php
3. View calendar

### Expected behaviour
Calendar is displayed

### Actual behaviour
Get an infinite spinning icon

### Server configuration

**Operating system**:
Debian 7.11

**Web server:**
Apache2

**Database:**

**PHP version:**

**Server version:** (see your admin page)
12.0.2

**Calendar version:** (see the apps page)
1.5.4

**Updated from an older installed version or fresh install:**
Updated

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
core.js?v=62d5563f16ad1810cc79d8e4fd6e45b2-0:1563 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
w @ core.js?v=62d5563f16ad1810cc79d8e4fd6e45b2-0:1563
app.js:4433 Uncaught (in promise) TypeError: Cannot read property 'hasProperty' of undefined
    at app.js:4433
    at <anonymous>
app.js:4433 Uncaught (in promise) TypeError: Cannot read property 'hasProperty' of undefined
    at app.js:4433
    at <anonymous>

**Comment by piggz** [comment] 2017-09-19 18:48
Extra info from browser:

(anonymous) | @ | app.js:4433
-- | -- | --
  | Promise resolved (async) |   |  
  | (anonymous) | @ | app.js:4423
  | A.A.getFcEvent | @ | app.js:4398
  | (anonymous) | @ | app.js:3072
  | (anonymous) | @ | app.js:3071
  | Promise resolved (async) |   |  
  | E.D.fcEventSource.events | @ | app.js:3063
  | p | @ | vendor.js:33828
  | c | @ | vendor.js:33733
  | u | @ | vendor.js:33727
  | m | @ | vendor.js:33909
  | (anonymous) | @ | vendor.js:34633
  | each | @ | core.js?v=62d5563f16…c79d8e4fd6e45b2-0:2
  | each | @ | core.js?v=62d5563f16…c79d8e4fd6e45b2-0:2
  | e.fn.fullCalendar | @ | vendor.js:34633
  | c | @ | app.js:209
  | (anonymous) | @ | app.js:240
  | (anonymous) | @ | app.js:237
  | i | @ | vendor.js:9892
  | $digest | @ | vendor.js:9980
  | $apply | @ | vendor.js:10085
  | (anonymous) | @ | app.js:287
  | Promise resolved (async) |   |  
  | (anonymous) | @ | app.js:284
  | s | @ | vendor.js:2631
  | d.instance | @ | vendor.js:5761
  | p | @ | vendor.js:4902
  | s | @ | vendor.js:4229
  | (anonymous) | @ | vendor.js:4229
  | (anonymous) | @ | vendor.js:898
  | $eval | @ | vendor.js:10054
  | $apply | @ | vendor.js:10077
  | (anonymous) | @ | vendor.js:898
  | s | @ | vendor.js:2631
  | s | @ | vendor.js:898
  | ue | @ | vendor.js:898
  | le | @ | vendor.js:867
  | (anonymous) | @ | vendor.js:15301
  | j | @ | core.js?v=62d5563f16…c79d8e4fd6e45b2-0:2
  | fireWith | @ | core.js?v=62d5563f16…c79d8e4fd6e45b2-0:2
  | ready | @ | core.js?v=62d5563f16…c79d8e4fd6e45b2-0:2
  | I | @ | core.js?v=62d5563f16…c79d8e4fd6e45b2-0:2

**Comment by piggz** [comment] 2017-09-19 18:49
Seems related to just some events, as browsing forward or backward a month works ok

**Comment by tcitworld** [comment] 2017-09-24 08:53
Corresponding code block:
```js
var vevents = context.comp.getAllSubcomponents('vevent');
var exceptions = vevents.filter(function (vevent) {
    return vevent.hasProperty('recurrence-id');
});
var vevent = vevents.find(function (vevent) {
    return !vevent.hasProperty('recurrence-id');
});
var iCalEvent = new ICAL.Event(vevent, { exceptions: exceptions });

if (!vevent.hasProperty('dtstart')) {
    resolve([]);
}
```

**Comment by bperel** [comment] 2017-10-31 09:15
I have the same issue. If it can help this is the content of `vevents `in my case:
```json
[
  [
    "vevent",
    [
      [
        "dtstart",
        {},
        "date-time",
        "2014-02-23T09:30:00Z"
      ],
      [
        "dtend",
        {},
        "date-time",
        "2014-02-23T11:00:00Z"
      ],
      [
        "dtstamp",
        {},
        "date-time",
        "2017-10-31T08:43:24Z"
      ],
      [
        "uid",
        {},
        "text",
        "fbfh6tob94785g2vgn09kknmqk@google.com"
      ],
      [
        "recurrence-id",
        {},
        "date-time",
        "2014-02-22T09:00:00Z"
      ],
      [
        "created",
        {},
        "date-time",
        "2015-11-10T22:33:44Z"
      ],
      [
        "description",
        {},
        "text",
        ""
      ],
      [
        "last-modified",
        {},
        "date-time",
        "2015-11-10T23:03:32Z"
      ],
      [
        "location",
        {},
        "text",
        ""
      ],
      [
        "sequence",
        {},
        "integer",
        1
      ],
      [
        "status",
        {},
        "text",
        "CONFIRMED"
      ],
      [
        "summary",
        {},
        "text",
        "Meeting"
      ],
      [
        "transp",
        {},
        "text",
        "OPAQUE"
      ]
    ],
    []
  ],
  [
    "vevent",
    [
      [
        "dtstart",
        {},
        "date-time",
        "2014-02-09T09:30:00Z"
      ],
      [
        "dtend",
        {},
        "date-time",
        "2014-02-09T11:00:00Z"
      ],
      [
        "dtstamp",
        {},
        "date-time",
        "2017-10-31T08:43:24Z"
      ],
      [
        "uid",
        {},
        "text",
        "fbfh6tob94785g2vgn09kknmqk@google.com"
      ],
      [
        "recurrence-id",
        {},
        "date-time",
        "2014-02-08T09:00:00Z"
      ],
      [
        "created",
        {},
        "date-time",
        "2015-11-10T22:33:44Z"
      ],
      [
        "description",
        {},
        "text",
        ""
      ],
      [
        "last-modified",
        {},
        "date-time",
        "2015-11-10T23:03:32Z"
      ],
      [
        "location",
        {},
        "text",
        ""
      ],
      [
        "sequence",
        {},
        "integer",
        2
      ],
      [
        "status",
        {},
        "text",
        "CONFIRMED"
      ],
      [
        "summary",
        {},
        "text",
        "Meeting 2"
      ],
      [
        "transp",
        {},
        "text",
        "OPAQUE"
      ]
    ],
    []
  ]
]
```

**Comment by Brice187** [comment] 2018-01-25 20:56
Same problem here with one of four google calendar.

**Comment by HorlogeSkynet** [comment] 2018-01-29 06:45
Hey, looks like this related to the time zone issue. Here all events are in UTC.

(https://help.nextcloud.com/t/calendar-timezone-confusion/26079/3)

Thx

**Comment by georgehrke** [comment] 2018-02-11 01:08
duplicate of #722

**Closed by georgehrke** 2018-02-11 01:08 UTC
Labels: 1 - to develop, bug
