### ISSUE TITLE
Monthly view freezes the tab

### ISSUE THREAD

**Issue by lapor-kris** [nextcloud/calendar#4323] opened 2022-06-28 09:49 UTC
### Steps to reproduce

1. Open Calendar in Firefox
2. Change the view on Monthly view

### Expected behavior

It should not freeze.

### Actual behaviour

The tab with Calendar freezes, you cannot do/click anything.

### Calendar app version

3.4.0

### Browser

Firefox 101.0.1, Chrome 103

### Client operating system

Fedora 36, Windows 11

### Server operating system

Ubuntu

### Database engine version

MySQL

### PHP engine version

PHP 7.4

### Nextcloud version

23.0.2

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by tarradmac** [comment] 2022-06-28 09:57
Hi, the same for me, I revert back to previous version and it works again.

**Comment by miaulalala** [comment] 2022-06-28 10:36
Duplicate of #4313

**Closed by miaulalala** 2022-06-28 10:36 UTC
Labels: bug, 0. to triage
