### ISSUE TITLE
share calendar using public link but without details

### ISSUE THREAD

**Issue by dusscloud** [nextcloud/calendar#1984] opened 2020-02-11 11:22 UTC
Hello,

I would like to share my calendar to someone outside nextcloud (thus sharing publicly through a link), but I do not want to give access to the details of the event.

This is implemented by google calendar :
https://support.google.com/calendar/answer/37083
https://storage.googleapis.com/support-kms-prod/mNMj6MHrTcKSz3TQfugBBCbSsKMrfxZmzsYi

Can't we add such option when sharing a nextcloud calendar through a public link ?

Note : It also could be nice to have the same thing when sharing to specific user/group within nextcloud, but it is not my priority

**Comment by georgehrke** [comment] 2020-02-16 18:05
Duplicate of https://github.com/nextcloud/server/issues/11214.

Yes, https://github.com/nextcloud/server/issues/11214 is about sharing with users/groups, but internally publishing is the same.

**Closed by georgehrke** 2020-02-16 18:05 UTC
Labels: 0. to triage, enhancement-proposed
