### ISSUE TITLE
l10n: duration in email invitation not translated (any more)

### ISSUE THREAD

**Issue by creopard** [nextcloud/calendar#6466] opened 2024-11-06 08:02 UTC
### Steps to reproduce

1. Use a non-English nextcloud instance. (German in this case)
2. Create or change an appointment and invite someone 
3. The participant will receive the default invitation email.
4. However, instead of the correct term "Woche/Wochen", we'll see "week/weeks" instead. (See screenshot):
---

![Image](https://github.com/user-attachments/assets/0fba1568-6ded-4f3a-ad59-b77c1f4475b5)

### Expected behavior

It should say "Woche/Wochen" instead of "week/weeks", see the red framed words in the screenshot.
This happens probably in other non-English languages as well.

### Actual behaviour

See "Steps to reproduce".
This probably seems to be client independent (as the mail is created from the Nextcloud instance).

### Calendar app version

5.0.1

### CalDAV-clients used

Thunderbird Lightning

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

30.0.1

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by miaulalala** [comment] 2024-11-06 12:29
Duplicate of https://github.com/nextcloud/server/issues/47673

**Closed by miaulalala** 2024-11-06 12:29 UTC
Labels: bug, 0. to triage
