### ISSUE TITLE
Functional advice

### ISSUE THREAD

**Issue by charwavid** [nextcloud/calendar#1114] opened 2019-02-13 11:19 UTC
1、Can I load the festival?
2、Can I detect the setting of the language below and load some local calendars, such as Chinese Lunar Calendar?

**Comment by charwavid** [comment] 2019-02-13 11:27
![image](https://user-images.githubusercontent.com/7514841/52708445-17733600-2fc5-11e9-98e0-aa4db1c56f7c.png)
As shown, the local calendar is displayed on the left。

**Comment by georgehrke** [comment] 2019-02-13 12:46
@charwavid I'm sorry, but can you please elaborate what you mean? I'm not sure i can follow.

> 1、Can I load the festival?

If you want to know if you can load holiday calendars. Sure, just find a website that provides them, e.g. http://webcal.fi and add them as a subscription.

> 2、Can I detect the setting of the language below and load some local calendars, such as Chinese Lunar Calendar?

This looks like a duplicate of https://github.com/nextcloud/calendar/issues/962 to me, but i'm not completely sure what you are requesting.

**Comment by charwavid** [comment] 2019-02-13 13:29
Sorry, my English is too bad, I didn’t express it clearly. I checked the http://webcal.fi website and thought that the two feature suggestions I mentioned can be loaded in the subscription; however, this requires each user to add a subscription to see it. If you can add a default subscription in the background, That would be great; I looked at the iCal link without the Chinese lunar calendar on the http://webcal.fi website. In addition, I found a library on the Chinese lunar calendar on github, you are interested to have a look. 

Url: https://github.com/infinet/lunar-calendar

The Chinese Lunar Calendar is mostly based on the motion of the Moon. It is said due to the complicate interaction, mostly from the Sun and the Earth, the motion of Moon is very hard to predict, especially on the long run. Luckily [Hong Kong Observatory](http://data.weather.gov.hk/gts/time/conversion1_text_c.htm) has published a conversion table for the period from 1901 to 2100. It is the most trustworthy Lunar Calendar I can find on the web so far.

**Comment by georgehrke** [comment] 2019-10-20 13:20
Duplicate of #962

**Closed by georgehrke** 2019-10-20 13:20 UTC
Labels: needs info, question
