### ISSUE TITLE
[feature request] share calendar items without approval

### ISSUE THREAD

**Issue by charlessteiner** [nextcloud/calendar#1143] opened 2019-02-25 20:52 UTC
It would be helpful to me and quite possibly quite a few others to have the ability to put things on other users' calendars without the need of an approval email.  

If this is an unlikely feature to be implemented please tell me what to edit to remove the need for calendar shares to be approved.

**Comment by georgehrke** [comment] 2019-03-03 13:30
> It would be helpful to me and quite possibly quite a few others to have the ability to put things on other users' calendars without the need of an approval email.

I'm not sure I completely understand your issue. Can you please describe your current workflow? 
If you just share a calendar with write permission with another user, you don't have to approve their changes in an email.

**Comment by charlessteiner** [comment] 2019-03-04 20:10
Thanks for the response georgehrke, I had a problem sharing, shared items were not appearing on the invitee's calendar. Which caused me to misunderstand how sharing should work. 
But I did uncover a possible bug https://github.com/nextcloud/calendar/issues/1154

**Comment by georgehrke** [comment] 2019-10-19 19:37
> But I did uncover a possible bug #1154

Closing as duplicate of #1154 in that case.

**Closed by georgehrke** 2019-10-19 19:37 UTC
