### ISSUE TITLE
saving entries in shared calendar doesn't work anymore

### ISSUE THREAD

**Issue by rhonda** [nextcloud/calendar#5692] opened 2024-01-15 11:08 UTC
### Steps to reproduce

I have a shared calendar in our system, to which I gave a group user group write access. Those users can see and open the calendar fine, but when they try to edit or change entries, after hitting save it never returns and the changes don't end up in the calendar.

This used before, only last week we started to notice the issue. We are using calendar 4.6.3 on on Nextcloud 28.0.1. This used to work before updates that happened within the last week or two.

There is one interesting side effect: People with admin rights are still able to save, so I didn't notice it myself at first because it still worked for me. Even though the admin group doesn't has dedicated rights to said shared calendar, I'm only seeing it through the same shared group permission.

### Expected behavior

Saving of entries work for all people in the group the calendar is shared for read/write to.

### Actual behaviour

People that are only in the group that is shared for read/write but not in the admin group are unable to save changes to the shared calendar

### Calendar app version

4.6.3

### CalDAV-clients used

Through the website

### Browser

firefox 115, chrome 120, smart phone browsers, ...

### Client operating system

Linux, Windows, Android

### Server operating system

Debian bookworm

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

28.0.1

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.20.0
  - apporder: 0.15.0
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.3
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.0
  - event_update_notification: 2.3.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - impersonate: 1.15.0
  - keeweb: 0.6.15
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.2
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.1
  - support: 1.11.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "AT",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "defaultapp": "apporder,files,calendar",
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "calendar",
            "keeweb",
            "dashboard",
            "social",
            "sharerenamer",
            "spreed",
            "apporder",
            "bookmarks",
            "bruteforcesettings",
            "event_update_notification",
            "twofactor_totp",
            "impersonate"
        ]
    }
}
```

**Comment by miaulalala** [comment] 2024-01-15 11:25
Can you check your logs and copypaste the loglines that you find? They should be associated with the username that errors out.

Your network might also show the error on the DAV request.

**Comment by taurustiny** [comment] 2024-01-16 02:49
@miaulalala the same wrong. the difference is first installation.  browser console find 404 status code on /dav。 There is no error info in k8s pod log.
Request URL: https://xxxx/remote.php/dav/
Request Method: PROPFIND
Status Code: 404

**Comment by taurustiny** [comment] 2024-01-18 03:26
> @miaulalala the same wrong. the difference is first installation. browser console find 404 status code on /dav。 There is no error info in k8s pod log. Request URL: https://xxxx/remote.php/dav/ Request Method: PROPFIND Status Code: 404
> 
> the page is loading forever ![image](https://private-user-images.githubusercontent.com/92911421/296919475-28952e55-ab7b-440b-ae3f-e9f26e710f47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDg1MzEsIm5iZiI6MTcwNTU0ODIzMSwicGF0aCI6Ii85MjkxMTQyMS8yOTY5MTk0NzUtMjg5NTJlNTUtYWI3Yi00NDBiLWFlM2YtZTlmMjZlNzEwZjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzMjM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMGI2M2VjMDY0Mjc4Yjg5OWMyMGFiOWU1OTc5MmY2MDA5YmRhZTgxYjdhNjdmMWQ4N2JjMWEzNjJhMzViMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zd9imsorQGvHykssVcbc3regCcOZ2Leo7B3ye8UaYmY)

allow http request method PROPFIND to resolve the trouble

**Comment by miaulalala** [comment] 2024-01-18 12:16
I'm not sure what you mean - was PROPFIND blocked for http for you?

**Comment by rhonda** [comment] 2024-02-05 15:29
It looks like it runs into some strange timeout situation. The log line corresponding to it appears late after the request was made, and claims it's a TokenPasswordExpiredException. This is the log line piped through "jq .", replated USER and OTHERUSER likewise CALENDAR for user privacy:

`
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  "reqId": "sj4zE51nrtL0sg92qQY1",
  "level": 3,
  "time": "2024-02-05T15:21:31+00:00",
  "remoteAddr": "84.115.227.48",
  "user": "USER",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/calendars/USER/CALENDAR_shared_by_OTHERUSER/ED368155-E4DE-4DF5-9CE9-AD87A4B67534.ics",
  "message": "Exception thrown: OC\\Authentication\\Exceptions\\TokenPasswordExpiredException",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "version": "28.0.2.5",
  "exception": {
    "Exception": "OC\\Authentication\\Exceptions\\TokenPasswordExpiredException",
    "Message": "",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/Authentication/Token/Manager.php",
        "line": 154,
        "function": "getTokenById",
        "class": "OC\\Authentication\\Token\\PublicKeyTokenProvider",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/notifications/lib/Push.php",
        "line": 580,
        "function": "getTokenById",
        "class": "OC\\Authentication\\Token\\Manager",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/notifications/lib/Push.php",
        "line": 337,
        "function": "validateToken",
        "class": "OCA\\Notifications\\Push",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/notifications/lib/App.php",
        "line": 58,
        "function": "pushToDevice",
        "class": "OCA\\Notifications\\Push",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/Notification/Manager.php",
        "line": 329,
        "function": "notify",
        "class": "OCA\\Notifications\\App",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/event_update_notification/lib/EventListener.php",
        "line": 177,
        "function": "notify",
        "class": "OC\\Notification\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/event_update_notification/lib/EventListener.php",
        "line": 88,
        "function": "onTouchCalendarObject",
        "class": "OCA\\EventUpdateNotification\\EventListener",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php",
        "line": 86,
        "function": "handle",
        "class": "OCA\\EventUpdateNotification\\EventListener",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 230,
        "function": "__invoke",
        "class": "OC\\EventDispatcher\\ServiceEventListener",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 59,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 94,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 106,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php",
        "line": 1278,
        "function": "dispatchTyped",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/AppFramework/Db/TTransactional.php",
        "line": 63,
        "function": "OCA\\DAV\\CalDAV\\{closure}",
        "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php",
        "line": 1217,
        "function": "atomic",
        "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Calendar.php",
        "line": 199,
        "function": "createCalendarObject",
        "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1098,
        "function": "createFile",
        "class": "Sabre\\CalDAV\\Calendar",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 504,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
        "line": 370,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 172,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php",
    "Line": 216,
    "message": "",
    "exception": {},
    "CustomMessage": "Exception thrown: OC\\Authentication\\Exceptions\\TokenPasswordExpiredException"
  }
}
`

**Comment by drpetersen** [comment] 2024-02-20 16:40
I seem to have the same, or at least a very similar, problem. I cannot save entries in a calendar to which I have granted access to another user.

To me it seems that the problem is not even saving the calendar entry as such, but rather the notification about the change to the user to whom I gave access: In fact, the problem disappears when I disable the `notifications` app (which of course is only a workaround, not a real solution).

I remember having a similar problem (on another Nextcloud instance) with a link share not properly displaying a PDF file in the PDF viewer app as long as the notifications app was active (seems like the attempt to notify the sharing user about the share link download/view was the culprit). This error also disappeared when the notifications app was disabled.

Could you please give it a try, @rhonda, and report if this also works for you?

**Comment by rhonda** [comment] 2024-02-20 21:30
@drpetersen Wow. That actually did the trick.  Now I wonder how that influences the calendar app - and especially, why it was working for me but not for others.

Just to make it clear: The shared calendar wasn't mine. It was one of a dedicated created user just for the shared calendar, and not for myself. What could potentially be of influence: I never allowed nextcloud to show me notifications in the browser. I can't say anything about that for the other users though, if it might be on or off in their browser.

Also what I noticed that I couldn't dismiss the past notifications in the browser, that gave me an error too. But I would have never connected those two.

Is this actually a bug in the notification app?  Shall this bug report get reassigned?  How to support the developers to further look into it, potentially reproduce it?

**Comment by drpetersen** [comment] 2024-02-20 21:54
Ok, thanks for checking; good to know. Btw, I don't think denying or allowing browser notifications is relevant here, as the error occurs right when the notification is triggered, not when it is supposed to be actually displayed to the recipient (which could be supposed to happen on several devices, and possibly with considerable time delay).

Yes, if the root cause is actually the notifications app, this probably should get reassigned. I guess the devs of that app will be able to advise us on how to proceed. I will file a bug report [there](https://github.com/nextcloud/notifications/issues), describing my two failure scenarios (but not before tomorrow :yawning_face: :sleeping: …), and will be sure to reference this issue.

**Comment by drpetersen** [comment] 2024-02-22 13:18
@rhonda, actually the notification app's maintainer seems to have gotten to the bottom of the issue and found [an immediate fix](https://github.com/nextcloud/notifications/issues/1827#issuecomment-1959413638) that works for me. Maybe you also want to try and apply this to your `…/nextcloud/apps/notifications/lib/Push.php`. Anyway, this might be resolved in one of the next releases/candidates.

**Closed** 2024-02-22 17:25 UTC
Labels: bug, 0. to triage
