### ISSUE TITLE
Add option for flexible calendar grid

### ISSUE THREAD

**Issue by scroom** [nextcloud/calendar#2024] opened 2020-02-25 22:04 UTC
**Is your feature request related to a problem? Please describe.**
Since an update to Nextcloud 17 and a new calendar version the calendar grid seems to be fixed in size. If you are now in the month view and have several appointments on one day, you will see that there are so many more appointments hidden. In the old version, the grid was not so rigid, but rather adapted to give you a better overview of existing events.

**Describe the solution you'd like**
Would be fine to have the possibility to choose the old flexible grid.

**Describe alternatives you've considered**
Reactivating the old view

**Comment by georgehrke** [comment] 2020-02-26 03:28
Duplicate of #1889

**Closed** 2020-02-26 03:27 UTC
Labels: 0. to triage, enhancement-proposed
