### ISSUE TITLE
z-push stop syncing after update to 18.0.4

### ISSUE THREAD

**Issue by orlovnv** [nextcloud/calendar#2368] opened 2020-06-28 03:47 UTC
zpush log

BackendCalDAV->Logon(): User 'MyUser' is not authenticated on CalDAV 'https://localhost:443/nextcloud/remote.php/dav/calendars/MyUser/'

That error message makes absolutely no sense as I use the same credentials to log onto the nextcloud web front end which works perfectly fine. 
back to 18.0.3 and all work as expected.

**Comment by tcitworld** [comment] 2020-06-28 13:21
Duplicate of https://github.com/nextcloud/server/issues/20624, fixed in 18.0.6.

**Closed by tcitworld** 2020-06-28 13:21 UTC
Labels: 0. to triage, bug
