### ISSUE TITLE
Sidebar hamburger button displayed on top of text on week, day, and list view

### ISSUE THREAD

**Issue by eibex** [nextcloud/calendar#3593] opened 2021-11-02 20:39 UTC
### Steps to reproduce
1. Open calendar app
2. Use week, day, or list view

### Expected behaviour
The button should be positioned differently (maybe inside the sidebar which when collapsed is reduced to a small column?)

### Actual behaviour
The behaviour is visible both with the sidebar collapsed and open.

Week view:
![image](https://user-images.githubusercontent.com/40539455/139947721-0af67eb1-dd60-4f3b-8cfc-5665baf55e2e.png)

Day view:
![image](https://user-images.githubusercontent.com/40539455/139947766-8d174c38-5de9-4e3f-9df6-f04555a2d6f5.png)

List view:
![image](https://user-images.githubusercontent.com/40539455/139947816-46593e22-1cd2-49b9-9a2d-ea8ad7859372.png)

### Calendar app
**Calendar app version:** 2.3.4

### Client configuration
**Browser:** Latest Firefox & Chrome

**Operating system:** Windows 10

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache2.4.51

**Database:** psql

**PHP version:** 7.4

**Nextcloud Version:** 21.0.5

**Updated from an older installed version or fresh install:** Older version

**Comment by raimund-schluessler** [comment] 2021-11-02 20:58
Duplicate of https://github.com/nextcloud/calendar/issues/2515.

**Closed by raimund-schluessler** 2021-11-02 20:58 UTC
Labels: bug, 0. to triage
