### ISSUE TITLE
Update to version 3.0.0 leads to ParseError","Message":"syntax error, unexpected ')'

### ISSUE THREAD

**Issue by t2000** [nextcloud/calendar#3757] opened 2021-11-30 10:04 UTC
There is a `,` too much at the end of this line:

https://github.com/nextcloud/calendar/blob/3c09657231f2ff8a7a6cb590026414dde645c95e/lib/Controller/ViewController.php#L117

And this leads to this error after I updated my calendar app to version 3.0.0

```
{"reqId":"YaXu4Di1dgrRd6JRl@SiKgAAABI","level":3,"time":"2021-11-30T09:29:05+00:00","remoteAddr":"46.165.141.23","user":"stefan","app":"index","method":"GET","url":"/cloud/index.
php/apps/calendar/","message":{"Exception":"ParseError","Message":"syntax error, unexpected ')'","Code":0,"Trace":[{"file":"/home/stefan/www/ssl/cloud/lib/composer/composer/Class
Loader.php","line":322,"function":"Composer\\Autoload\\includeFile","args":["/home/stefan/www/ssl/cloud/apps/calendar/lib//Controller/ViewController.php"]},{"function":"loadClass
","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"function":"spl_autoload_call","args":["OCA\\Calendar\\Controller\\
ViewController"]},{"file":"/home/stefan/www/ssl/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":107,"function":"__construct","class":"ReflectionClass","type":"
->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/home/stefan/www/ssl/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve
","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/home/stefan/www/ssl/cloud/lib/private/AppFramew
ork/DependencyInjection/DIContainer.php","line":455,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewCo
ntroller"]},{"file":"/home/stefan/www/ssl/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":427,"function":"queryNoFallback","class":"OC\\AppFramework\\D
ependencyInjection\\DIContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/home/stefan/www/ssl/cloud/lib/private/AppFramework/App.php","line":13
9,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Calendar\\Controller\\ViewController"]},{"file":"/home/stefan/www/ssl/
cloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Calendar\\Controller\\ViewController","index",{"__class
__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"calendar.view.index"}]},{"file":"/home/stefan/www/ssl/cloud/lib/base.php","line":1008,"function":"match","cla
ss":"OC\\Route\\Router","type":"->","args":["/apps/calendar/"]},{"file":"/home/stefan/www/ssl/cloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args
":[]}],"File":"/home/stefan/www/ssl/cloud/apps/calendar/lib/Controller/ViewController.php","Line":118,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebK
it/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"20.0.13.1"}
```

After I remove that comma, everything is fine again.

**Comment by raimund-schluessler** [comment] 2021-11-30 10:05
Duplicate of https://github.com/nextcloud/calendar/issues/3753

**Closed by raimund-schluessler** 2021-11-30 10:05 UTC
Labels: bug, 0. to triage
