### ISSUE TITLE
Dashboard Upcoming events

### ISSUE THREAD

**Issue by stxdigitizing** [nextcloud/calendar#3963] opened 2022-02-17 06:49 UTC
### Steps To Reproduce

Login to Nextcloud, on dashboard click on create new event does not work properly after update 

### Expected Result

I expect it to open calendar app to create event from dashboard.

### Actual Result

page opens and get following response. see screen shot below. 

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/56180085/154420818-5217e3ac-4be3-4378-8145-2e5da0a80599.png)

### Build Version

Nextcloud HanssonIT VM (23.0.2)

### Environment

By downloading the VM

**Comment by ChristophWurst** [comment] 2022-02-17 07:59
Duplicate of https://github.com/nextcloud/calendar/issues/2960

**Closed by ChristophWurst** 2022-02-17 07:59 UTC
Labels: bug

**Comment by enoch85** [comment] 2022-02-17 09:22
Haha just realized my mistake.

**Comment by stxdigitizing** [comment] 2022-02-18 06:37
Thanks for the Info, Unchecked that option and it works just fine...
