### ISSUE TITLE
NC:15ResourceLocator can not find a web root

### ISSUE THREAD

**Issue by KSCNeon** [nextcloud/calendar#1348] opened 2019-07-08 14:24 UTC
I'm using Nextcloud Snap Image.
I have already reinstalled the Nextcloud server several times. I am using Ubuntu 18.
Calendar Version 1.6.5
I have only activated the Nextcloud Calendar and Contacts app.

The problem occurs during dav syncronization with Android. I have already tested several Android apps. The error is always the same.

When I syncronize I get this error message in the log but the syncronization still works.

> [lib] Error: ResourceLocator can not find a web root (root: /var/snap/nextcloud/13968/nextcloud/extra-apps/calendar, file: index.php/css/calendar/7a73-a6bf-app.min.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true)

GET /index.php/apps/calendar/
from My IP Adress by username at 2019-07-08T14:13:21+00:00

![Unbenannt](https://user-images.githubusercontent.com/26071680/60817911-ddd1e000-a19c-11e9-9ff6-90db03ab625e.PNG)

**Comment by georgehrke** [comment] 2019-07-08 14:27
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

**Comment by KSCNeon** [comment] 2019-07-08 15:43
### Steps to reproduce
Import a calendar (mine is from Google Calendar)
Use a Caldav App of your choice for Android (I use DAVx5)
Set up the calendar syncronization via Caldav in the app.
Each time it is syncronized, this error will appear in the Nextcloud log.


### Expected behaviour
No more errors in the log, easy synconization of Caldav calendars

### Actual behaviour
Each time the calendar entries are synchronized via Caldav, the following message appears in the Nextcloud Log:
[lib] Error: ResourceLocator can not find a web root (root: /var/snap/nextcloud/13968/nextcloud/extra-apps/calendar, file: index.php/css/calendar/7a73-a6bf-app.min.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true)


## Server configuration detail

**Operating system:** Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.26

**PHP version:** 

7.2.19
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 15.0.8 - 15.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Snapd

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - contacts: 3.1.3
 - dav: 1.8.2
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - mail: 0.11.1
 - nextcloud_announcements: 1.4.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - support: 1.0.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_totp: 2.1.2
 - workflowengine: 1.5.0
Disabled:
 - admin_audit
 - comments
 - encryption
 - files_external
 - passwords
 - theming
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my_domain",
        "192.168.1.15"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.8.1",
    "overwrite.cli.url": "https:\/\/my_domain",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** /Webdav/Cal/CardDav

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Operating system:** Windows 10, MacOSX, Android 9

## Logs

<details><summary>Web server error log</summary>

```
The log file is empty
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"mJHZJXzCrxJmC5k91VU9","level":3,"time":"2019-07-08T14:10:12+00:00","remoteAddr":"80.156.77.218","user":"jonathan","app":"lib","method":"GET","url":"\/index.php\/apps\/contacts\/","message":"ResourceLocator can not find a web r$
{"reqId":"4MWSCDzFguzE4f6woPAn","level":3,"time":"2019-07-08T14:10:20+00:00","remoteAddr":"80.156.77.218","user":"jonathan","app":"lib","method":"GET","url":"\/index.php\/apps\/calendar\/","message":"ResourceLocator can not find a web r$
{"reqId":"9ztU06QRoVRfGn5nUTts","level":3,"time":"2019-07-08T14:12:09+00:00","remoteAddr":"80.156.77.218","user":"jonathan","app":"lib","method":"GET","url":"\/index.php\/apps\/calendar\/","message":"ResourceLocator can not find a web r$
{"reqId":"gqV4ji3fYYWjKEhUeqby","level":3,"time":"2019-07-08T14:13:21+00:00","remoteAddr":"80.156.77.218","user":"jonathan","app":"lib","method":"GET","url":"\/index.php\/apps\/calendar\/","message":"ResourceLocator can not find a web r$
{"reqId":"PwW5qq9Jh65iaDpnH76u","level":2,"time":"2019-07-08T15:26:37+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"support","method":"POST","url":"\/index.php\/apps\/support\/generateSystemReport","message":{"Exception":"E$
{"reqId":"lkP8ACNNrs135j8fdcjs","level":2,"time":"2019-07-08T15:26:41+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"support","method":"POST","url":"\/index.php\/apps\/support\/generateSystemReport","message":{"Exception":"E$
{"reqId":"7GjZwW6WrRAVNi4L9fF7","level":3,"time":"2019-07-08T15:26:48+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"lib","method":"GET","url":"\/index.php\/settings\/admin\/issuetemplate","message":"ResourceLocator can not $
{"reqId":"DDOqUI4jiLAnJpLikBiA","level":3,"time":"2019-07-08T15:36:14+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: client-de$
{"reqId":"DDOqUI4jiLAnJpLikBiA","level":3,"time":"2019-07-08T15:36:14+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: client-de$
{"reqId":"DDOqUI4jiLAnJpLikBiA","level":3,"time":"2019-07-08T15:36:14+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detai$
{"reqId":"DDOqUI4jiLAnJpLikBiA","level":3,"time":"2019-07-08T15:36:14+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detai$
{"reqId":"DDOqUI4jiLAnJpLikBiA","level":3,"time":"2019-07-08T15:36:14+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detai$
{"reqId":"xzQK6CI4GjptQkJY5FuU","level":3,"time":"2019-07-08T15:36:55+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detai$
{"reqId":"xzQK6CI4GjptQkJY5FuU","level":3,"time":"2019-07-08T15:36:55+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detai$
{"reqId":"xzQK6CI4GjptQkJY5FuU","level":3,"time":"2019-07-08T15:36:55+00:00","remoteAddr":"192.168.1.1","user":"jonathan","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detai$

```
</details>

<details><summary>Browser log</summary>


</details>

**Comment by the-sane** [comment] 2019-08-02 04:24
It's looking like all of these "can not find a web root" issues are caused by this: https://github.com/nextcloud/server/issues/13556

It's been discussed on the snap github here: https://github.com/nextcloud/nextcloud-snap/issues/902

It appears to be a server bug not something the individual apps can fix, and affects everyone who installed via snap or who is using a nonstandard configuration.  Unfortunately, the issue doesn't seem to have gotten anyone's attention since January.

pinging @georgehrke to let you know that this isn't a bug in your app.  Also, because you were so awesome about taking care of that disabled apps bug in the server, maybe you know who we need to ping to get some eyeballs on this issue too?

**Comment by georgehrke** [comment] 2019-08-05 08:34
Duplicate of nextcloud/server#13556

**Comment by georgehrke** [comment] 2019-08-05 08:35
> pinging @georgehrke to let you know that this isn't a bug in your app. Also, because you were so awesome about taking care of that disabled apps bug in the server, maybe you know who we need to ping to get some eyeballs on this issue too?

Let me see who to ping.

**Closed by georgehrke** 2019-08-05 08:34 UTC
Labels: bug, needs info

**Comment by ph00lt0** [comment] 2020-07-20 17:50
I faced this issue when uploading a file with the name `personal` strangely after renaming the file I could import the calendar without any problem. 😕
