### ISSUE TITLE
Calendar Sorting

### ISSUE THREAD

**Issue by tomas-chrastina** [nextcloud/calendar#782] opened 2018-03-22 13:05 UTC
Hi,

it would be helpful to add option/action to sort list of Calendars e.g:
- checkbox to do it automatically by selected order (A-Z/Z-A ?, ...)
- Actions to sort all records by specified order
- Action to sort list manually - Drag and Drop?

Thank you in advance for consider it.

--
Best regards,
Tomas.

**Comment by georgehrke** [comment] 2018-03-22 13:06
Duplicate of #9

**Closed** 2018-03-22 13:06 UTC
