### ISSUE TITLE
Clicking the avatar of shared calendar owner results in an error

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#1599] opened 2019-10-26 18:47 UTC
Version: latest master f56dde65ef3369f69049f8b56a6c5e440a0204ba

Clicking the avatar of the owner of a shared calendar produces an error in the console but does nothing else:

```
TypeError: "e is null"
    menu ncvuecomponents.js:278
    menu ncvuecomponents.js:278
    VueJS 3
    hasMenu ncvuecomponents.js:278
    VueJS 3
    toggleMenu ncvuecomponents.js:278
    VueJS 3
vue.runtime.esm.js:1888:12
    VueJS 6
```

I clicked the upper avatar (with the three-dots icon due to hovering with the mouse):
<img width="281" alt="calendar" src="https://user-images.githubusercontent.com/2496460/67624523-c85af180-f831-11e9-8fd1-f2e3098a80e0.png">

**Comment by raimund-schluessler** [comment] 2019-10-27 10:39
Here the output of the development build:

```
[Vue warn]: Error in render: "TypeError: t is null"

found in

---> <Avatar>
       <AppNavigationItem>
         <CalendarListItem> at src/components/AppNavigation/CalendarList/CalendarListItem.vue
           <TransitionGroup>
             <CalendarList> at src/components/AppNavigation/CalendarList.vue
               <AppNavigation>
                 <Content>
                   <Calendar> at src/views/Calendar.vue
                     <App> at src/App.vue
                       <Root>
```

**Comment by georgehrke** [comment] 2019-10-28 12:24
@raimund-schluessler Can you confirm that this problem only occurs for you when the user associated with that avatar does not have any way to contact them? (Like an email)

**Comment by georgehrke** [comment] 2019-10-28 12:26
(Can't reproduce if contact's menu for user is not empty, seems to be an issue in Nextcloud-vue in that case.)

**Comment by raimund-schluessler** [comment] 2019-10-28 12:56
I can confirm, that the error vanishes if I set an e-mail address for the user. And it probably really is a nextcloud-vue issue, since the error is thrown in the `Avatar` component.

![Screenshot_2019-10-28 Week 44 of 2019 - Kalender - Nextcloud](https://user-images.githubusercontent.com/2496460/67679935-8b564280-f98a-11e9-9dc6-9f98edaf593e.png)

As a side note: The font-size is to large, probably also a nextcloud-vue issue.

**Comment by georgehrke** [comment] 2019-10-28 16:28
Closing as upstream issue:
https://github.com/nextcloud/nextcloud-vue/issues/699

**Closed by georgehrke** 2019-10-28 16:28 UTC
Labels: 0. to triage, bug
