### ISSUE TITLE
Send calendar invites in shared calendars from calendar owners' accounts

### ISSUE THREAD

**Issue by pi-xel** [nextcloud/calendar#2144] opened 2020-04-02 18:32 UTC
**Is your feature request related to a problem? Please describe.**
By design, no invites are sent when adding/editing an event in a shared calendar. This makes the editable calendar sharing practically useless for us. 

In addition, it is quite confusing and inconsistent that invites are sometimes sent to invitees and sometimes not.

This feature request is related to https://github.com/nextcloud/server/issues/15676 (describing the design decision), https://github.com/nextcloud/calendar/issues/2055 (describing why the current design is not really a satisfactory solution) and https://github.com/nextcloud/server/issues/20278 (a separate bug report describing an inconsistency coming from this design decision; even if the issue in the bug report would be fixed, invitees would receive cancellation notifications if the calendar owner cancelled an event not created by him/herself).

**Describe the solution you'd like**
My proposal is to simply send calendar invites in shared calendars from the owner's account.

So if A@example.com shares a calendar with B@example.com and B creates an event, then the invite is not only put in A's calendar, but is also sent from A's account.

This way it would at least be possible to create separate team accounts on NC (like team@example.com), create a shared, editable calendar there and send invites from all team members, with team@example.com as meeting owner.

In case this solution should create some concerns with changing behavior for existing accounts, maybe the introduction of a config switch to enable this new behavior may be a compromize.

**Describe alternatives you've considered**
As a workaround we need to duplicate the same calendar for every user in our team and to share them read-only with all others, which creates a big mess.

**Comment by georgehrke** [comment] 2020-04-02 19:05
@pi-xel Please do not purposefully create duplicate reports!

Duplicate of #2055 

> This feature request is related to nextcloud/server#15676 (describing the design decision), 

As a pointed out in nextcloud/server#15676, this is not a design decision on our side.
The __CalDAV standard does not have answers__ to these problems yet. This is a problem in the protocol specification, not in our implementation.

**Closed by georgehrke** 2020-04-02 19:05 UTC
Labels: 0. to triage, enhancement-proposed

**Comment by georgehrke** [comment] 2020-04-02 19:07
> In addition, it is quite confusing and inconsistent that invites are sometimes sent to invitees and sometimes not.

https://github.com/nextcloud/calendar/issues/2145

**Comment by favincen** [comment] 2020-09-15 17:44
> As I see it, this would not only solve [nextcloud/server#12501](https://github.com/nextcloud/server/issues/12501) but also answer your questions raised in [nextcloud/server#15676](https://github.com/nextcloud/server/pull/15676):
> 
> In this setup, adding and deleting events would always be on behalf of the calendar's owner, while the sharee could still add him/herself to the list of invitees to receive an explicit invitation and also cancel his/her participation using the invite without deleting the entire event.

I do support this point of view. As far as I understand it, if any change made on a shared writable calendar is made on behalf onthe calendar owner, everything else should work flawlessly, the same way as if indeed the calendar owner did the modification (or deletion) by itself. Are we missing anything there ?

Obviously, in such a case were a user invites on behalf of the calendar owner, it would be nice to have such a "on behalf" mention in the invitation mail. But that would be the icing on the cake, and I definitely would prefer a cake without icing than no cake...  ;-)
