### ISSUE TITLE
Reminders in Calendar

### ISSUE THREAD

**Issue by 995190** [nextcloud/calendar#874] opened 2018-07-27 13:17 UTC
Hey!

It would be great to have a Google Calendar-style reminders feature, i.e. tasks per given day that you can check as completed. 

https://support.google.com/calendar/answer/6285327?co=GENIE.Platform%3DDesktop&hl=en

When not completed, the automatically migrate to the next day. I know there is a Tasks app, but having a calendar with a simple to-do function in one view is time-saver. 

M.

**Comment by georgehrke** [comment] 2018-07-27 13:19
Duplicate of #28

**Closed by georgehrke** 2018-07-27 13:19 UTC
