### ISSUE TITLE
Option to duplicate event

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/calendar#3328] opened 2021-07-13 20:11 UTC
I would like to request to add option to duplicate existing event.
A lot of times, I have to create similar events and I would like to duplicate existing event, change something and save as new event.
Something like Ctrl+C -> Ctrl+V in Thunderbird calendar.

**Comment by raimund-schluessler** [comment] 2021-07-13 21:05
Duplicate of https://github.com/nextcloud/calendar/issues/113. Might come with 2.4.0.

**Closed by raimund-schluessler** 2021-07-13 21:05 UTC
Labels: 0. to triage, enhancement-proposed
