### ISSUE TITLE
Show Participant Email Address

### ISSUE THREAD

**Issue by rafny** [nextcloud/calendar#2536] opened 2020-09-02 17:14 UTC
I have contacts with multiple email addresses and sometimes I think I selected the wrong email address, but I can't confirm it since the calendar only shows the contact name, not the email .

It would be nice to at least have on the hover or is some drop down the email address that the invitation went out to.

**Comment by Dubidubiduu** [comment] 2021-10-06 21:23
Please don't do that as default since there are use cases, where users shouldn't get the email of another.

**Comment by ChristophWurst** [comment] 2021-10-12 06:26
> Please don't do that as default since there are use cases, where users shouldn't get the email of another.

Users can get the email from the calendar event anyway. You're just hiding this.



> the calendar only shows the contact name, not the email .

If I'm not mistaken this is a duplicate of https://github.com/nextcloud/calendar/issues/3189

**Closed by ChristophWurst** 2021-10-12 06:26 UTC
Labels: 1 - to develop, enhancement-approved
