### ISSUE TITLE
Go to Contact when clicking on a birthday calendar entry

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/calendar#6413] opened 2024-10-09 17:08 UTC
### Is your feature request related to a problem? Please describe.

The information about the event is not really useful in the birthday calendar scenario.

### Describe the solution you'd like

Open the contact in the Contacts app when clicking on the event.

### Describe alternatives you've considered

Alternatively the contact could be displayed directly in the sidebar instead of the event information.

**Comment by joshtrichards** [comment] 2024-11-21 15:51
Duplicate of #1226

**Closed by joshtrichards** 2024-11-21 15:51 UTC
Labels: 1. to develop, enhancement, Feature: Birthday Calendar
