### ISSUE TITLE
Request to Add Persian or Jalali Calendar

### ISSUE THREAD

**Issue by parsmmm** [nextcloud/calendar#5612] opened 2023-12-06 10:45 UTC
### Is your feature request related to a problem? Please describe.

Hello,
Please add the Persian or Jalali calendar. The Jalali calendar is highly important for us Iranians, and we need the dates to be displayed in the Persian format

**Comment by tcitworld** [comment] 2023-12-06 10:49
Duplicate of #2270 and #4200

**Closed by tcitworld** 2023-12-06 10:49 UTC
Labels: enhancement, 0 - to triage
