### ISSUE TITLE
Events with repetitions, say every third Sunday each month not possible

### ISSUE THREAD

**Issue by ulifan** [nextcloud/calendar#922] opened 2018-10-15 16:33 UTC
### Steps to reproduce
1. Try to add an event with a repetition, say every third Sunday each month

### Expected behaviour
Accepting a repetition rate like every third Sunday, every month

### Actual behaviour
Not possible to enter such condition

**Comment by georgehrke** [comment] 2018-10-15 17:06
Duplicate of #10

**Closed by georgehrke** 2018-10-15 17:06 UTC
