### ISSUE TITLE
Appointments: No updates for guests by mail (when Creator has edited fields)

### ISSUE THREAD

**Issue by SebastianBerlin** [nextcloud/calendar#4964] opened 2023-02-07 10:34 UTC
### Steps to reproduce

1. User/Guest is booking successfully an appointment with the Host/Creator.
2. Host/Creator edits something (like the place) and saves the entry.

### Expected behavior

1. The User/Guest receives immediately an automatic e-mail with the update (and a new ics-file), after the Host/Creator has changed anything.

### Actual behaviour

Nothing happens. No Mails are pushed.

**Only**, if the Host/Creator deletes the appointment-entry entirely in his calendar, the User/Guest gets an notification by mail, that the appointment is cancelled.

### Calendar app version

4.2.3 (and many versions before)

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.3 (and many version before)

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment] 2023-02-07 10:40
Are you editing the config or the calendar entry?

**Comment by miaulalala** [comment] 2023-02-07 12:45
> > Are you editing the config or the calendar entry?
> 
> The calendar entry for an individual appointment (for example the place), not the general settings.

can you expost such an ics for me? Would be interesting to see what sequence number is present. If the sequence number hasn't been updated and the other changes by themselves don't constitute a "significant change", the scheduling logic will skip this entry and there will be no email.

**Comment by miaulalala** [comment] 2023-02-07 13:04
you can export the ics from the calendar app: 

![image](https://user-images.githubusercontent.com/7427347/217252539-338f1964-ccfd-4805-b341-c7c509c4e5fb.png)

**Comment by miaulalala** [comment] 2023-02-07 19:40
Interesting, no SEQUENCE property. that might be down to the export or down to how we handle an update. I will look into it further next week when I have more time. Thanks for reporting @SebastianBerlin

**Comment by miaulalala** [comment] 2023-03-15 08:51
Hi @SebastianBerlin - I 've ran into this issue in another ticket too. There is a concept in calendaring that is called a "significant change" - i. e. there are certain properties that are defined significant enough to warrant a notification, but others are not.

In your use case, the code is not taking the change as significant.

Moving the discussion to the the linked ticket below:

Duplicate of https://github.com/nextcloud/calendar/issues/4428

**Closed by miaulalala** 2023-03-15 08:51 UTC
Labels: bug, 0 - to triage
