### ISSUE TITLE
Improve multiple "all-day" events display

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/calendar#1977] opened 2020-02-10 10:15 UTC
Please implement an option to show all "All Day" events (similar to Calendar 1.x)

**Comment by tcitworld** [comment] 2020-02-10 10:20
All-day events are shown in month view just like other events. On week and day view, they are displayed on top of the interface (in a « All day » line). Where are you missing them ?

**Comment by jpbraun** [comment] 2020-02-10 10:28
In the week view only the first all day events are shown
![2020-02-10_112705](https://user-images.githubusercontent.com/31374152/74142069-6c598480-4bf8-11ea-8c45-645f7705bbad.gif)

**Comment by tcitworld** [comment] 2020-02-10 10:47
Sorry, brain missed the double `all` in "all all day events".

@georgehrke Also had some feedback where this is limiting.

**Comment by georgehrke** [comment] 2020-02-16 18:10
Duplicate of https://github.com/nextcloud/calendar/issues/1889

**Closed by georgehrke** 2020-02-16 18:10 UTC
Labels: 1 - to develop, enhancement-approved
