### ISSUE TITLE
Sharing an appointment with the share option "When shared show as busy" not working

### ISSUE THREAD

**Issue by kaksikanaa** [nextcloud/calendar#322] opened 2017-01-26 17:15 UTC
### Steps to reproduce
1. Install newest/fresh Nexcloud 11
2. Activate newest Calendar app
3. Try to share your calendar and appointments either for other Nextcloud user or as link with the share option "When shared show as busy"

### Expected behaviour
The shared calendar and all those appointments which had a property "When shared show as busy" should appear as "Busy" period for the other user AND the original user should see these appointments as normal way.

### Actual behaviour
After setting share or Link for the calendar the original user see these appointments also only as "Busy" and the original title and other data is lost and title is changed to "Busy". The original appointment data could not be restored even by selecting the option "When shared so full event" back again.

### Server configuration
Debian Jessie
Apache 2.4
Mysql 5.7
PHP 5.6

Nextclud 11.0.2 (Fresh install)
Calendar 1.5.0 (Just activated the app from the apps page)
Admin page passes all checks ok.

**Comment by georgehrke** [comment] 2017-01-26 19:11
duplicate of https://github.com/nextcloud/server/issues/2787

**Closed** 2017-01-26 19:10 UTC
