### ISSUE TITLE
Timezone pickers look broken

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#5767] opened 2024-02-15 13:14 UTC
### Steps to reproduce

1. Open the app
2. Click Create event
3. Click the globe icon of the start time(remove all day check)
4. Focus the timezone input

### Expected behavior

Dropdown menu is shown not broken

### Actual behaviour

![Screenshot from 2024-02-15 14-12-18](https://github.com/nextcloud/calendar/assets/12728974/1ea2acce-943a-4301-94db-853e82e63fb5)

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by GretaD** [comment] 2024-02-19 09:44
We will close it after we release of the nc/vue 8.7.0

**Comment by miaulalala** [comment] 2024-02-28 09:35
Duplicate of https://github.com/nextcloud/calendar/issues/5606

Please check existing issues before opening a new one

**Closed by miaulalala** 2024-02-28 09:35 UTC
Labels: 2. developing, bug
