### ISSUE TITLE
Rich Text Formatting in Descrition

### ISSUE THREAD

**Issue by ksainc** [nextcloud/calendar#5488] opened 2023-09-22 00:41 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I would like to request support for rich text formatting in the description for calendar appointments.

There is a vcalendar property that is designated for rich text formatted descriptions, X-ALT-DESC like html.

` 
X-ALT-DESC;FMTTYPE=text/html:<html><body><a href="http://bing.com">Bing</a></body></html>
`

### Describe alternatives you've considered

None available

**Comment by tcitworld** [comment] 2023-09-22 07:25
Duplicate of #3234

**Closed by tcitworld** 2023-09-22 07:25 UTC
Labels: enhancement, 0 - to triage
