### ISSUE TITLE
Cant't move events between calendars (-> back)

### ISSUE THREAD

**Issue by albirs** [nextcloud/calendar#4166] opened 2022-04-20 14:11 UTC
### Steps to reproduce

1. created 2 calendar
2. create event on calendar 1
3. move event from calendar 1 to calendar 2
4. can't move event back from calendar 2 to calendar 1

### Expected behavior

move events between calrendars

### Actual behaviour

can't move events between calendars ...

Error response (Browser inspector): 
`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Deleted calendar object with uid already exists in this calendar collection.</s:message>
</d:error>`

### Calendar app version

3.2.2 ? (demo on https://nextcloud05.webo.cloud/apps/calendar/)

### Browser

Firefox Dev Edition (100.0b8)

### Client operating system

https://nextcloud05.webo.cloud/apps/calendar/

### Server operating system

https://nextcloud05.webo.cloud/apps/calendar/

### Nextcloud version

23.0.3

### List of activated apps

```Text
see https://nextcloud05.webo.cloud/apps/calendar/
```

### Nextcloud configuration

```Text
see https://nextcloud05.webo.cloud/apps/calendar/
```

### Web server error log

```Text
see https://nextcloud05.webo.cloud/apps/calendar/
```

### Log file

```Text
can't see log files in demo
```

### Browser log

```Text
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Deleted calendar object with uid already exists in this calendar collection.</s:message>
</d:error>
```

### Additional info

may releated to #4093

**Comment by raimund-schluessler** [comment] 2022-04-20 14:21
Duplicate of https://github.com/nextcloud/calendar/issues/3325.

**Closed by raimund-schluessler** 2022-04-20 14:21 UTC
Labels: bug, 0. to triage
