### ISSUE TITLE
UX : delete an event in less step

### ISSUE THREAD

**Issue by meaz** [nextcloud/calendar#2062] opened 2020-03-08 11:06 UTC
At the moment, to delete an event, the user has to click on the event, then click on "Plus", then click again on the three dots to finally get the "Delete" option available.

In would be a better UX to have a remove option right at the first step, so when the user click on the event.

**Comment by georgehrke** [comment] 2020-03-08 12:52
Duplicate of #1570

**Closed by georgehrke** 2020-03-08 12:52 UTC
Labels: 0. to triage, bug
