### ISSUE TITLE
NextCloud Event Email Not Being Sent Due ot DMARC Trigger on Gmail

### ISSUE THREAD

**Issue by ModestTG** [nextcloud/calendar#3680] opened 2021-11-22 21:05 UTC
### Steps to reproduce
1. Create an event in NextCloud Calendar. Add attendees with valid email addresses confgured (doesn't matter if they are NextCloud users or Contacts)
2. Ensure that the checkbox for "Send Email" is checked for each attendee
3. Save the event

### Expected behaviour
Emails should be sent to each attendee. I have confirmed that the test email works, and I can also send email from the NextCloud Mail app. This leads me to believe that my email server is configured properly, with DNS records also configured properly. MXToolbox checks out for my domain. The DMARC report is as follows:
```XML
<?xml version="1.0" encoding="UTF-8" ?>
<feedback>
  <report_metadata>
    <org_name>google.com</org_name>
    <email>noreply-dmarc-support@google.com</email>
    <extra_contact_info>https://support.google.com/a/answer/2466580</extra_contact_info>
    <report_id>11685182679346940178</report_id>
    <date_range>
      <begin>1637280000</begin>
      <end>1637366399</end>
    </date_range>
  </report_metadata>
  <policy_published>
    <domain>MY_DOMAIN_REDACTED</domain>
    <adkim>r</adkim>
    <aspf>r</aspf>
    <p>quarantine</p>
    <sp>quarantine</sp>
    <pct>100</pct>
  </policy_published>
  <record>
    <row>
      <source_ip>MAIL_SERVER_REDACTED</source_ip>
      <count>16</count>
      <policy_evaluated>
        <disposition>none</disposition>
        <dkim>pass</dkim>
        <spf>pass</spf>
      </policy_evaluated>
    </row>
    <identifiers>
      <header_from>MY_DOMAIN_REDACTED</header_from>
    </identifiers>
    <auth_results>
      <dkim>
        <domain>MY_DOMAIN_REDACTED</domain>
        <result>pass</result>
        <selector>mail</selector>
      </dkim>
      <spf>
        <domain>MY_DOMAIN_REDACTED</domain>
        <result>pass</result>
      </spf>
    </auth_results>
  </record>
</feedback>
```

### Actual behaviour
Emails are not sent, and I receive a DMARC report from Gmail.

### Calendar app
**Calendar app version:** 2.3.4

**CalDAV-clients used:** Thunderbird 91.3.1 (64-bit), NextCloud Mail 1.10.5

### Client configuration
**Browser:** Firefox 94.0.1 (64-bit)

**Operating system:** Windows 10 Version 21H1 (OS build 19043.1348)

#### Running on Docker
**Image:** linuxserver/nextcloud:latest

**Nextcloud Version:** 22.2.2

**Updated from an older installed version or fresh install:** Fresh Install

**List of activated apps:**
```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - breezedark: 22.0.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - cookbook: 0.9.6
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.3.0
  - groupfolders: 10.0.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.10.5
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - contactsinteraction
  - encryption
  - files_accesscontrol
  - files_external
  - nextcloud_announcements
  - photos
  - user_ldap
  - weather_status
```
**Nextcloud configuration:**

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.126:8084",
            "<REDACTED>"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.2.0",
        "overwrite.cli.url": "<REDACTED>",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "default_phone_region": "US",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

#### Web server error log (e.g. /var/log/apache)
```

```

#### Log file (data/nextcloud.log)
- I uploaded the applicable logs. Full log file would not fit. Let me know if you need full log file
```
[nextcloud2.log](https://github.com/nextcloud/calendar/files/7584353/nextcloud2.log)
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by tcitworld** [comment] 2021-11-23 14:55
Probably a duplicate of https://github.com/nextcloud/calendar/issues/3681

**Closed by tcitworld** 2021-11-23 14:55 UTC
Labels: bug, 0. to triage
