### ISSUE TITLE
[Feature request] add a delete shortcut icon on the event preview

### ISSUE THREAD

**Issue by CorentinS6** [nextcloud/calendar#3499] opened 2021-09-22 11:48 UTC
Hello,

### The current behavior
With the calendar, in the default config, **4 clics are needed to delete an event** :
1. Clic on the event
2. Clic on "More/Edit" button
3. Clic on "..."
4. And finnaly, Clic on "Delete"

I could be boring when you have to delete events frequently.

### An idea for an improvement
An idea could be : add a delete shortcut icon on the event preview (and/or in the event detail sidebar). Indeed, there is a blank area on the top : 
![image](https://user-images.githubusercontent.com/4438248/134336380-79b962e3-75a4-40cc-b657-f3f252b30e49.png)

So it could be look like the g$$gle  calendar :
![image](https://user-images.githubusercontent.com/4438248/134336277-855cedc3-0f07-488c-b6f9-92ac999f5405.png)

Best regards

**Comment by raimund-schluessler** [comment] 2021-09-22 11:51
Duplicate of https://github.com/nextcloud/calendar/issues/2893.

**Closed by raimund-schluessler** 2021-09-22 11:51 UTC
Labels: enhancement-proposed, 0. to triage
