### ISSUE TITLE
Cancellation or Acceptment does not do anything

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#937] opened 2018-11-02 11:48 UTC
Hi, 
I dont know if that is the desired behavior:

If I invite a user to a meeting, the user get an email and can click cancel or accept. 
But I can't see if the user is willing to attend the meeting. 
There is no change in the appointment and I'm not getting an info mail.

Thanks for the great work!
Greetings!

PS.: Is there a manual for the calendar?

**Comment by georgehrke** [comment] 2018-11-02 11:49
Duplicate of https://github.com/nextcloud/calendar/issues/879

**Closed by georgehrke** 2018-11-02 11:49 UTC
