### ISSUE TITLE
Iframe default view settings

### ISSUE THREAD

**Issue by Ryonez** [nextcloud/calendar#875] opened 2018-07-30 06:27 UTC
Hi there.

I've been trying to get the default view for an iframe to be day rather than month, as it'd work great in the sidebar for my site. How do I pass this variable on so it works?

**Comment by Ryonez** [comment] 2018-08-08 13:43
Nothing? I can see a default view flag there, there must be a way to set it.

**Comment by georgehrke** [comment] 2018-08-08 14:10
This is not possible at the moment.

I will close this as a duplicate of https://github.com/nextcloud/calendar/issues/787, because we are already planning to include the view as a url parameter there

**Closed by georgehrke** 2018-08-08 14:10 UTC
