### ISSUE TITLE
Please add a goto URL to a Calendar entry

### ISSUE THREAD

**Issue by gjpc** [nextcloud/calendar#4181] opened 2022-04-25 17:25 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The Calendar entry does not allow a URL in any of the text fields to open a new tab. For instance when I make a zoom call appointment I place the Zoom meeting URL in the entry. There is no field in the entry where I may put the URL and be able to click it and got to the zoom meeting.

**Describe the solution you'd like**
Either have the description box recognize URL syntax and allow a click. Or have the location field recognize the URL and perform the click. Or create a new field that is designed to handle a URL.

**Describe alternatives you've considered**
I mail the URL to my self

**Additional context**
<none>

**Comment by ChristophWurst** [comment] 2022-04-26 07:19
Duplicate of https://github.com/nextcloud/calendar/issues/1758

**Closed by ChristophWurst** 2022-04-26 07:19 UTC
Labels: enhancement, 0. Needs triage
