### ISSUE TITLE
Calendar invites are always pushed to default "Personal" calendar

### ISSUE THREAD

**Issue by nlincke** [nextcloud/calendar#1433] opened 2019-08-28 21:16 UTC
### Steps to reproduce
1. Create User A
2. Create User B
3. User A Creates a second calendar named "Test"
4. User A deletes default calendar "Personal"
5. User B invites User A to an appointment
6. Invitation is only present in the again newly created "Personal" calendar of User A

### Expected behaviour
- Deleted "Personal" calendar should not be recreated.
- A default calendar should be selectable
 
### Actual behaviour
Invitation is only present in the again newly created "Personal" calendar of User A

### Server configuration

**Operating system**:
Ubuntu Server 
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
Latest
**Server version:** (see your admin page)
16.0.4
**Calendar version:** (see the apps page)
Latest
**Updated from an older installed version or fresh install:**
16.0.3 -> 16.0.4

### Client configuration
**Browser:**
Chrome, IE, Andorid (Davx5)
**Operating system:**
Any
**CalDAV-clients:**
e.g. Davx5
#### Web server error log
none

**Comment by georgehrke** [comment] 2019-08-29 07:25
Duplicate of https://github.com/nextcloud/server/issues/5040

**Closed by georgehrke** 2019-08-29 07:25 UTC
