### ISSUE TITLE
Month layout messed up (browser, month view)

### ISSUE THREAD

**Issue by rookey** [nextcloud/calendar#4338] opened 2022-07-01 09:08 UTC
### Steps to reproduce

1) In month layout, there is now a line break after the set time, which results in only 1 (!) appointment being displayed, the rest is 'hidden' using the '# more' indicator. Steps to reproduce: enter several appointments for a day. Due to line breaks, valuable display space in month view is wasted and only the first appointment gets listed.
2) long event titles are breaking the layout and will write over the 'box' of the next day (also: month layout only). Steps to reproduce: create an event with event title > 30 chars

### Expected behavior

ad 1: no line break after time, just as in other display modes
ad 2: max width of even title display equals date box width

### Actual behaviour

1) In month layout, there is now a line break after the set time, which results in only 1 (!) appointment being displayed, the rest is 'hidden' using the '# more' indicator. 
2) long event titles are breaking the layout and will write over the 'box' of the next day (also: month layout only)

### Calendar app version

3.4.1

### CalDAV-clients used

DAVx5

### Browser

Firefox 101.0.1, Brave 1.25.68 / Chromium 91.0.4472.77

### Client operating system

Windows 11

### Server operating system

Debian Linux

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

24.0.2

**Comment by ChristophWurst** [comment] 2022-07-01 09:22
Duplicate of https://github.com/nextcloud/calendar/issues/4332

**Closed by ChristophWurst** 2022-07-01 09:22 UTC
Labels: bug, 0. to triage
