### ISSUE TITLE
"Enter" in attendee input should submit the attendee not the complete event

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/calendar#648] opened 2017-10-31 15:28 UTC
### Steps to reproduce
1. Create a new event
2. Go to attendee tab
3. Type an Email and press enter

### Expected behaviour
Email is added

### Actual behaviour
Event is saved (without email being added)

**Comment by georgehrke** [comment] 2017-10-31 15:41
duplicate of #502

**Closed** 2017-10-31 15:41 UTC
