### ISSUE TITLE
Automatically refresh data 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/calendar#6048] opened 2024-06-05 06:18 UTC
### Is your feature request related to a problem? Please describe.

As browser "pinned tab" user, I keep a calendar tab always open, but when I open it after a few days, the current displayed date is not shown and the events are not updated.

### Describe the solution you'd like

- Update the current date at midnight everyday without requiring a reload 
- Fetch the events every few minutes without requiring a reload

### Describe alternatives you've considered

- Listen to invite events and add them immediately to the calendar?

**Comment by tcitworld** [comment] 2024-06-05 06:34
Duplicate of #31

**Closed by tcitworld** 2024-06-05 06:34 UTC
Labels: enhancement
