### ISSUE TITLE
No connection after update

### ISSUE THREAD

**Issue by djesys** [nextcloud/calendar#1402] opened 2019-08-17 20:42 UTC
Ubuntu 18.04.2 LTS (Bionic Beaver)) ISPConfig 3.1.14p2 Nextcloud 16.0.4 Calendar 1.7.0

Everything ran fine until I  updated ISPConfig and Nextcloud.

Now, on Android, CalDav-Sync error is:
"Could not connect to Server!"
javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x45c1520: I/O error during system call, Connection reset by peer

On OSX with BusyCal 3.6.2 the error is simply:
"The request timed out"

I am aware that this is likely not Calendar related, but if someone could point my in a direction I would be very grateful !

Thanks.

**Comment by tcitworld** [comment] 2019-08-18 11:05
Try https://www.ssllabs.com/ssltest/ and see if your TLS configuration is an issue for some of your clients.

**Comment by djesys** [comment] 2019-08-18 13:41
Thank you. Did the test, did not see anything unusual.
In the meanwhile, I have reinstalled Nextcloud and deleted all certificated on OSX.
Still, my CalDAV clients cannot connect. Not to the calendar, not to contacts.
My Nextcloud app connects, I can open "https://nextcloud.xxx/remote.php/dav/principals/users/admin/" in my browser.
This is causing a big problem right now. Any help very appreciated.

**Comment by georgehrke** [comment] 2019-08-18 13:47
@djesys Did you check https://help.nextcloud.com yet?
It's our community forum and you will find plenty of setup questions there.

**Comment by djesys** [comment] 2019-08-18 13:48
my next step. It all started with the calendar, so I came here....

**Comment by georgehrke** [comment] 2019-08-22 13:58
Closing since this is a setup issue, not a bug in the calendar app.

**Closed by georgehrke** 2019-08-22 13:58 UTC
