### ISSUE TITLE
Calendar 4.2.0 on NC 25.0.2 fails to export 

### ISSUE THREAD

**Issue by javaboyuk** [nextcloud/calendar#4866] opened 2023-01-01 21:24 UTC
### Steps to reproduce

    Go to Calendar App
    Click "pencil" next to calendar you want to export - for example "Personal"
    Click export (nothing happens) and no file produced BUT exception thrown in log file.

### Expected behavior

An .ics file downloaed for the selected calendar

### Actual behaviour

more to basic backing page and exception thrown in log file

### Calendar app version

4.2.0

### CalDAV-clients used

thinderbird, DAVx5

### Browser

firefox 108.0.1 (64-bit)

### Client operating system

unbuntu 22.04 full patched todate (1/jan/23)

### Server operating system

rpi4 runing installation - docker image runing debian bullseye fully patched.

### Web server

Apache

### Database engine version

SQlite

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
# sudo -u www-data php occ app:list
Cannot load Zend OPcache - it was already loaded
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bookmarks: 12.0.0
  - calendar: 4.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 1.1.0
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud configuration

```Text
sudo -u www-data php occ config:list
Cannot load Zend OPcache - it was already loaded
{
    "system": {
        "activity_expire_days": 90,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "enable_previews": "false",
        "preview_max_x": 100,
        "preview_max_filesize_image": 1,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "loglevel": 3,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/London",
        "trashbin_retention_obligation": "auto, 7",
        "defaultapp": "calendar,files",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "knowledgebaseenabledy": false,
        "skeletondirectory": "",
        "lost_password_link": "disabled",
        "updatechecker": true,
        "trusted_domains": [
            "***BY ME REMOVED SENSITIVE VALUE***",
            "192.168.20.52:xxxxx",
            "127.0.0.1:xxxx"
        ],
        "overwrite.cli.url": "https:\/\/rt50.mooo.com:2804",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "25.0.2.3",
        "installed": true,
        "maintenance": false,
        "mail_smtpsecure": "ssl"
    },
    "apps": {
        "activity": {
            "installed_version": "2.17.0",
            "types": "filesystem",
            "enabled": "yes",
            "notify_stream_favorite": "1",
            "notify_email_favorite": "0",
            "notify_stream_file_changed": "1",
            "notify_email_file_changed": "0",
            "notify_stream_file_created": "1",
            "notify_email_file_created": "0",
            "notify_stream_file_deleted": "1",
            "notify_email_file_deleted": "0",
            "notify_stream_file_favorite": "0",
            "notify_stream_file_restored": "1",
            "notify_email_file_restored": "0",
            "notify_stream_comments": "1",
            "notify_email_comments": "0",
            "notify_stream_calendar": "1",
            "notify_email_calendar": "0",
            "notify_stream_calendar_event": "1",
            "notify_email_calendar_event": "0",
            "notify_stream_calendar_todo": "1",
            "notify_email_calendar_todo": "0",
            "notify_stream_shared": "1",
            "notify_email_shared": "0",
            "notify_stream_remote_share": "1",
            "notify_email_remote_share": "0",
            "notify_stream_public_links": "1",
            "notify_email_public_links": "0",
            "notify_stream_systemtags": "1",
            "notify_email_systemtags": "0",
            "notify_setting_batchtime": "604800",
            "notify_setting_self": "1",
            "notify_setting_selfemail": "0"
        },
        "admin_audit": {
            "installed_version": "1.15.0",
            "enabled": "yes",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "166"
        },
        "bookmarks": {
            "installed_version": "12.0.0",
            "enabled": "yes",
            "types": "",
            "previews.screenly.url": "",
            "previews.screenly.token": "",
            "previews.webshot.url": "",
            "previews.screenshotmachine.key": "",
            "previews.pageres.env": "",
            "performance.maxBookmarksperAccount": "",
            "privacy.enableScraping": "true"
        },
        "bruteforcesettings": {
            "installed_version": "1.1.0",
            "enabled": "no",
            "types": ""
        },
        "calendar": {
            "installed_version": "4.2.0",
            "enabled": "yes",
            "types": ""
        },
        "circles": {
            "installed_version": "25.0.0",
            "types": "filesystem,dav",
            "enabled": "yes",
            "loopback_tmp_scheme": "https",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1672606804,\"2\":1672606804,\"1\":1672606804,\"4\":1652925608,\"5\":1652497203}",
            "migration_run": "0",
            "migration_22": "1",
            "migration_22_1": "1"
        },
        "cloud_federation_api": {
            "installed_version": "1.8.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "comments": {
            "installed_version": "1.15.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "5.0.2",
            "enabled": "yes",
            "types": "dav"
        },
        "contactsinteraction": {
            "installed_version": "1.6.0",
            "types": "dav",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1502119527.0509",
            "lastupdatedat": "1672606817",
            "vendor": "nextcloud",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "installed.bundles": "[\"CoreBundle\"]",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "lastcron": "1672606804",
            "backgroundjobs_mode": "cron",
            "lastupdateResult": "[]",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "updater.secret.created": "1637260981",
            "shareapi_enforce_links_password": "yes",
            "theming.variables": "1485fe817d0d85489684b87a2c22ba1a",
            "enterpriseLogoChecked": "yes",
            "oc.integritycheck.checker": "[]"
        },
        "dashboard": {
            "installed_version": "7.5.0",
            "types": "",
            "enabled": "yes"
        },
        "dav": {
            "installed_version": "1.24.0",
            "types": "filesystem",
            "enabled": "yes",
            "buildCalendarSearchIndex": "yes",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "chunks_migrated": "1",
            "buildCalendarReminderIndex": "yes",
            "sendEventRemindersToSharedGroupMembers": "no"
        },
        "federatedfilesharing": {
            "installed_version": "1.15.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.15.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.20.1",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_pdfviewer": {
            "installed_version": "2.6.0",
            "types": "",
            "enabled": "yes"
        },
        "files_rightclick": {
            "installed_version": "1.4.0",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.17.0",
            "types": "filesystem",
            "enabled": "yes",
            "outgoing_server2server_share_enabled": "no",
            "incoming_server2server_share_enabled": "no",
            "lookupServerUploadEnabled": "no"
        },
        "files_texteditor": {
            "installed_version": "2.8.0",
            "types": "",
            "enabled": "no"
        },
        "files_trashbin": {
            "installed_version": "1.15.0",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.18.0",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "2.14.0",
            "types": "logging",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "18.4.0",
            "types": "",
            "enabled": "no"
        },
        "logreader": {
            "installed_version": "2.10.0",
            "types": "",
            "enabled": "yes",
            "levels": "11111",
            "relativedates": "",
            "live": "1"
        },
        "lookup_server_connector": {
            "installed_version": "1.13.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "installed_version": "1.14.0",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notes": {
            "installed_version": "4.6.0",
            "enabled": "yes",
            "types": ""
        },
        "notifications": {
            "installed_version": "2.13.1",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.13.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.15.0",
            "types": "authentication",
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "maximumLoginAttempts": "10"
        },
        "photos": {
            "installed_version": "2.0.1",
            "types": "dav,authentication",
            "enabled": "yes"
        },
        "preview": {
            "jpeg_quality": "30",
            "?": "",
            "enable_previews": "",
            "preview_max_x": ""
        },
        "previewx": {
            "preview_max_x": ""
        },
        "privacy": {
            "installed_version": "1.9.0",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "1.15.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "recommendations": {
            "installed_version": "1.4.0",
            "types": "",
            "enabled": "yes"
        },
        "related_resources": {
            "installed_version": "1.0.3",
            "types": "",
            "enabled": "yes"
        },
        "serverinfo": {
            "installed_version": "1.15.0",
            "types": "",
            "enabled": "yes",
            "cached_count_filecache": "36185",
            "cached_count_storages": "4"
        },
        "settings": {
            "installed_version": "1.7.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.15.0",
            "types": "filesystem",
            "enabled": "yes",
            "sendpasswordmail": "no"
        },
        "support": {
            "installed_version": "1.8.0",
            "types": "session",
            "enabled": "yes",
            "SwitchUpdaterServerHasRun": "yes"
        },
        "survey_client": {
            "installed_version": "1.13.0",
            "types": "",
            "enabled": "yes",
            "last_sent": "1617282904",
            "last_report": "{\"id\":\"ocbrgc20a0y4\",\"items\":[[\"server\",\"version\",\"20.0.8.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.3.27\"],[\"php\",\"memory_limit\",-1],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"sqlite3\"],[\"database\",\"version\",\"3.27.2\"],[\"database\",\"size\",4898816],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"bruteforcesettings\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"2.9.0\"],[\"apps\",\"federatedfilesharing\",\"1.10.2\"],[\"apps\",\"lookup_server_connector\",\"1.8.0\"],[\"apps\",\"provisioning_api\",\"1.10.0\"],[\"apps\",\"files_sharing\",\"1.12.2\"],[\"apps\",\"comments\",\"1.10.0\"],[\"apps\",\"updatenotification\",\"1.10.0\"],[\"apps\",\"federation\",\"1.10.1\"],[\"apps\",\"survey_client\",\"1.8.0\"],[\"apps\",\"dav\",\"1.16.2\"],[\"apps\",\"systemtags\",\"1.10.0\"],[\"apps\",\"password_policy\",\"1.10.1\"],[\"apps\",\"files_videoplayer\",\"1.9.0\"],[\"apps\",\"notifications\",\"2.8.0\"],[\"apps\",\"files_versions\",\"1.13.0\"],[\"apps\",\"workflowengine\",\"2.2.0\"],[\"apps\",\"files_pdfviewer\",\"2.0.1\"],[\"apps\",\"sharebymail\",\"1.10.0\"],[\"apps\",\"serverinfo\",\"1.10.0\"],[\"apps\",\"files_trashbin\",\"1.10.1\"],[\"apps\",\"logreader\",\"2.5.0\"],[\"apps\",\"files\",\"1.15.0\"],[\"apps\",\"oauth2\",\"1.8.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.9.0\"],[\"apps\",\"theming\",\"1.11.0\"],[\"apps\",\"nextcloud_announcements\",\"1.9.0\"],[\"apps\",\"activity\",\"2.13.4\"],[\"apps\",\"calendar\",\"2.2.0\"],[\"apps\",\"contacts\",\"3.5.1\"],[\"apps\",\"bookmarks\",\"4.1.0\"],[\"apps\",\"notes\",\"4.0.4\"],[\"apps\",\"tasks\",\"0.13.6\"],[\"apps\",\"accessibility\",\"1.6.0\"],[\"apps\",\"cloud_federation_api\",\"1.3.0\"],[\"apps\",\"support\",\"1.3.0\"],[\"apps\",\"recommendations\",\"0.8.0\"],[\"apps\",\"viewer\",\"1.4.0\"],[\"apps\",\"files_rightclick\",\"0.17.0\"],[\"apps\",\"privacy\",\"1.4.0\"],[\"apps\",\"text\",\"3.1.0\"],[\"apps\",\"photos\",\"1.2.3\"],[\"apps\",\"settings\",\"1.2.0\"],[\"apps\",\"contactsinteraction\",\"1.1.0\"],[\"apps\",\"admin_audit\",\"1.10.0\"],[\"apps\",\"user_status\",\"1.0.1\"],[\"apps\",\"weather_status\",\"1.0.0\"],[\"apps\",\"dashboard\",\"7.0.0\"],[\"stats\",\"num_files\",1178],[\"stats\",\"num_users\",2],[\"stats\",\"num_storages\",4],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",2],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",0],[\"files_sharing\",\"num_shares_user\",0],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",0],[\"files_sharing\",\"num_shares_link_no_password\",0],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}"
        },
        "systemtags": {
            "installed_version": "1.15.0",
            "types": "logging",
            "enabled": "yes"
        },
        "tasks": {
            "installed_version": "0.14.5",
            "enabled": "yes",
            "types": ""
        },
        "text": {
            "installed_version": "3.6.0",
            "types": "dav",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "2.0.1",
            "types": "logging",
            "enabled": "yes",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "cachebuster": "3",
            "color": "#C978A3",
            "name": "xpress2"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.14.0",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.15.0",
            "types": "",
            "enabled": "yes",
            "update_check_errors": "0",
            "core": "25.0.2.3",
            "calendar": "4.2.0",
            "contacts": "5.0.2",
            "bookmarks": "12.0.0",
            "bruteforcesettings": "1.1.0",
            "notes": "4.5.1",
            "tasks": "0.14.5",
            "files_pdfviewer": "1.2.1",
            "theming": "1.4.5",
            "files_rightclick": "0.15.1"
        },
        "user_status": {
            "installed_version": "1.5.0",
            "types": "",
            "enabled": "yes"
        },
        "viewer": {
            "installed_version": "1.9.0",
            "types": "",
            "enabled": "yes"
        },
        "weather_status": {
            "installed_version": "1.5.0",
            "types": "",
            "enabled": "yes"
        },
        "workflowengine": {
            "installed_version": "2.7.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}
```

### Web server error log

```Text
Error	index	Exception: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/calendar/lib/Controller/SettingsController.php' line 71	
January 01, 2023 20:04:34
Error	index	Exception: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/calendar/lib/Controller/SettingsController.php' line 71	
January 01, 2023 20:01:59
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140
```

### Log file

```Text
Error	index	Exception: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/calendar/lib/Controller/SettingsController.php' line 71	
January 01, 2023 20:04:34
Error	index	Exception: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/calendar/lib/Controller/SettingsController.php' line 71	
January 01, 2023 20:01:59
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140



====================more detail================
Exception: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/calendar/lib/Controller/SettingsController.php' line 71

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()

Caused by TypeError: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OCA\Calendar\Controller\SettingsController->setConfig()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()
```

### Browser log

```Text
~~~~I removed my server name

TypeError: e is null
    getMarkerYear https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    startOfMonth https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    startOf https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    c https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    buildRangeFromDuration https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    buildCurrentRangeInfo https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    build https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    u https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    _handleAction https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    runTask https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    drain https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    drained https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    tryDrain https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    request https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    request https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    dispatch https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    dispatch https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    gotoDate https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    t https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    A https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    A https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    <anonymous> https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    A https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    ke https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    confirmTransition https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    transitionTo https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    push https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    push https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    y https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    Ot https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    n https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    _wrapper https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
calendar-main.js:2:4789981
    l https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    A https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    A https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    <anonymous> https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    A https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    r https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    ke https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    confirmTransition https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    transitionTo https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    push https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    push https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    y https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    Ot https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    n https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
    _wrapper https://myserver.subdom.dom:MyPORT/apps/calendar/js/calendar-main.js?v=9fb6f2ca-3:2
No new notification data received notifications-main.js:2:1310993
Polling interval updated to 30000 notifications-main.js:2:1311757
No new notification data received notifications-main.js:2:1310993
Polling interval updated to 30000 notifications-main.js:2:1311757
```

### Additional info

might be related to the same as the other instances reported.

**Comment by miaulalala** [comment] 2023-01-02 06:36
Please make sure to look for existing issues frst!

Duplicate of https://github.com/nextcloud/calendar/issues/4844

**Closed by miaulalala** 2023-01-02 06:36 UTC
Labels: bug, 0 - to triage
