### ISSUE TITLE
Many appointments are not distinguishable due to identical title

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#4263] opened 2022-06-09 15:05 UTC
### Steps to reproduce

1. Create an appointment "1:1 meeting"
2. Send the link to people and ask them to book a meeting freely

### Expected behavior

As the organizer of the meetings, I'm able to look at my daily/weekly schedule and see who I will have meeting with.

### Actual behaviour

It's all the same. There are many "1:1 meetings" in my calendar. I have to open the individually and check the attendee list to eventually find out which even belongs to which booking party.

### Calendar app version

3.x

### Additional info

@jancborchardt @nimishavijay any ideas? I thought about including the booking person name in the even title by default, but it's hard to place it correctly.

E.g. the format could be *{meeting title} with {name}*. In my example that would translate to *1:1 meeting with Jan*.

For the organizer that is a huge improvement, but then the booking person has a "meeting with themselves" in their calendar. Like for them it should probably say *1:1 meeting with Christoph*.

Getting the title right this way is not trivial.

A more technical solution would be to allow the user to place the name. Then I could say the appointment title is *1:1 meeting Christoph/{name}" and it turns into *1:1 meeting Christoph/Jan*. That title make sense for the organizer and the booking person.

The other idea would be to show attendee avatars on the events. We discussed that in https://github.com/nextcloud/calendar/issues/3162.

Do you have any other ideas?

**Comment by JuliaKirschenheuter** [comment] 2022-06-09 15:25
I agree with your suggestion about title like "1:1 meeting Christoph/Jan". It is a bit easier and also understandable for  both participants =)

**Comment by leArthurDent** [comment] 2022-06-17 09:32
Please consider that appointments are also used for external people booking slots. Focusing on usernames or avatars might not suffice to cover all applications.
Since you can provide a name when booking a slot, using that custom name might be more reasonable to use.

**Comment by nimishavijay** [comment] 2022-06-20 10:08
It's definitely a good idea to show the name of the booking person. 

I'm thinking about the cases when the appointment name itself is something like "Coffee with Nimisha" where it includes the organizer's name, then the calendar event would show "Coffee with Nimisha Christoph/Nimisha" which seems odd. Perhaps we could use a separator symbol, for eg. a middle dot (·)
Then the events would look like
 "1:1 meeting · Christoph and Jan" or "Coffee with Nimisha · Christoph and Nimisha"
The format would be `{title} · {booking person} and {organizer}`.

What do you think? cc @jancborchardt for any other suggestions

**Comment by schiessle** [comment] 2022-11-29 19:20
Some input from the other ticket I just closed because it is a duplicate of this one.

When booking a appointment people can define at the moment their name, email address and the description. There should be another input field "topic" this topic should be set as event title. Or maybe even something like "[title] - booked by [name]". If no title is set we could fall back to "[generic title] - booked by [name]". But I expect most people will fill in a meaningful title if they book a event.

**Comment by michel-thomas** [comment] 2023-02-08 16:43
Hello, any news about this request? I hope this request resolved to move from Appointments app to this. Thanks !

**Comment by pjrobertson** [comment] 2023-05-27 02:38
Small modification to name the event "ATTENDEE NAME - APPOINTMENT NAME" in May 2023, which should provide a reasonable fix for this.

**Comment by tcitworld** [comment] 2023-05-28 07:50
Closed by #5229

**Closed by tcitworld** 2023-05-28 07:50 UTC
Labels: bug, 0 - to triage, Feature: Appointments
