### ISSUE TITLE
Get public birthday calendar as ICS

### ISSUE THREAD

**Issue by mkriegl** [nextcloud/calendar#1184] opened 2019-03-22 11:10 UTC
I am using a few calendars with a smart home dashboard. Therefore I made those calendars public and used the ICS download link at each published calendar `https://<URL>/remote.php/dav/public-calendars/<some_cryptic_information>?export`.
As the birthday calandar is listed at the subscribed calendars it is not possible to get or generate a public link. The only link I get is that one where I have to log in `https://<URL>/remote.php/dav/calendars/<user>/contact_birthdays/`
Could you please provide this functionality? I am also fine with a workaround to get a downloadable ics birthday calendar link without the need of the login data.

Thanks in advance .. Max

**Comment by mkriegl** [comment] 2019-03-22 17:48
I did a hack and solved it by myself:

lists the shared calendars: `SELECT * FROM oc_dav_shares;`  
add a new entry: `INSERT INTO `oc_dav_shares` (`id`,`principaluri`,`type`,`access`,`resourceid`,`publicuri`) VALUES (<new_entry_numer>,'<principaluri_from_oc_calendars>','calendar',4,<id_from_oc_calendars>,'new_but_different_publicuri');`
calendar can then be downloaded via: `https://<URL>/remote.php/dav/calendars/<USER>/<publicuri>?export`
it is more easy, when there is already a shared calendar in the table

**Comment by georgehrke** [comment] 2019-05-08 08:17
Duplicate of nextcloud/server#14717

**Closed by georgehrke** 2019-05-08 08:17 UTC

**Comment by jangop** [comment] 2019-08-20 10:15
> Duplicate of nextcloud/server#14717

I do not think that this is a duplicate of #1307 (which nextcloud/server#14717 links to)  because in that issue there is no mention of the birthday calendar being required to be public.

**Comment by georgehrke** [comment] 2019-08-20 10:18
Sharing includes publishing here :)
But let me add that to the description of #1307.

**Comment by jangop** [comment] 2019-08-20 10:19
Alright, thanks for the clarification. In that case, I'll add a question over there. 😉
