### ISSUE TITLE
Calendar settings menu has wrong title

### ISSUE THREAD

**Issue by sciurius** [nextcloud/calendar#1735] opened 2019-12-19 13:54 UTC
### Steps to reproduce
1. Open the Calendar
2. Look at the settings menu bottom-left

### Expected behaviour
The title should be "Settings & import"

### Actual behaviour
The title is "Settings &amp;amp; import"

![scrot20191219145413](https://user-images.githubusercontent.com/1118804/71178962-7b166180-226f-11ea-96bb-e91b5b2b5407.png)

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1) 2.0.0 beta 3

### Client configuration
**Browser:** (e.g. Firefox 48) Firefox 70.0

**Operating system:** (e.g. Arch Linux) Fedora 29

### Server configuration

**Operating system**: (e.g. Debian 8) DSM 6.2

**Web server:** (e.g. Apache, Nginx,...) Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL) MariaDB

**PHP version:** (e.g. 7.0.3) 7.3

**Nextcloud Version:** (see admin page, e.g. 17.0.2) 18.0.0 Beta 3

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:** N/A

**Comment by georgehrke** [comment] 2020-01-05 13:38
@ChristophWurst @skjnldsv This seems to be an issue with nextcloud-vue, because I don't see how else i should do it: https://github.com/nextcloud/calendar/blob/master/src/components/AppNavigation/Settings.vue#L23

How should we handle this? Should we add an additional properly `:title-vhtml="true"`?

**Comment by skjnldsv** [comment] 2020-01-06 08:32
Isn't it coming from the `t()` function?

**Comment by georgehrke** [comment] 2020-01-06 08:34
Yes, `t()` is automatically escaping it: `"Settings &amp; Import"`.
That's why my suggestion was to allow to use vhtml for the Settings title, but I'm open for other solutions.

**Comment by skjnldsv** [comment] 2020-01-06 09:22
@georgehrke or automatically urldecode the text?

**Comment by georgehrke** [comment] 2020-01-06 09:27
> @georgehrke or automatically urldecode the text?

Doesn't do anything, because it's not URI encoded:
![9F4780CC-8E70-4516-8B52-0527BFC5DAB5](https://user-images.githubusercontent.com/1250540/71808896-2d6f6680-306f-11ea-98f4-8d797187a869.png)

**Comment by skjnldsv** [comment] 2020-01-06 09:29
I meant htmldecode :p

**Comment by georgehrke** [comment] 2020-01-06 09:45
Not sure if we don't have our own implementation that I'm not aware of, but there is no method to decode HTML in the standard javascript libs.

You can write your own using `document.createElement()`, `innerHTML` and `innerText`.
I guess simply using `.replace(/&amp;/g, '&');` is the cleaner approach here.

**Comment by ChristophWurst** [comment] 2020-01-07 08:56
Looks like this is the same issue with the app tokens header in your personal settings. The `&` is escaped there as well. Couldn't figure out why, though.

**Comment by georgehrke** [comment] 2020-01-07 09:18
Fix is in https://github.com/nextcloud/calendar/pull/1760

**Comment by ChristophWurst** [comment] 2020-01-07 09:26
Fix or workaround? :see_no_evil:

**Comment by ChristophWurst** [comment] 2020-01-07 09:26
What happens to umlauts and other HTML-escaped characters?

**Comment by georgehrke** [comment] 2020-01-07 09:29
> What happens to umlauts and other HTML-escaped characters?

Only the ampersand is causing problems:
![06B1BCC3-B8A7-4FAE-BF3A-96013E7315EB](https://user-images.githubusercontent.com/1250540/71884397-8f47d300-3138-11ea-96ed-d2ec9d423746.png)

ref https://github.com/nextcloud/server/blob/master/core/src/OC/l10n.js#L125

**Comment by georgehrke** [comment] 2020-01-07 09:31
I'm not exactly sure why we call `DOMPurify.sanitize` there anyway.
We already escape all the variables above: https://github.com/nextcloud/server/blob/master/core/src/OC/l10n.js#L100L113

**Comment by ChristophWurst** [comment] 2020-01-07 09:56
> I'm not exactly sure why we call `DOMPurify.sanitize` there anyway.
> We already escape all the variables above: https://github.com/nextcloud/server/blob/master/core/src/OC/l10n.js#L100L113

Me neither. And this is a regression. Any clue where this is coming from? Did we add the escaping recently? The `&` in the app password settings used to work.

**Comment by georgehrke** [comment] 2020-01-07 10:01
The `DOMPurify` itself has been there for years now: https://github.com/nextcloud/server/commit/6c8d48b0f6faac5d5b832a70d0245941a912f78b#diff-45c3b58acdf48f696d3ffe092e58e33cR176

**Comment by georgehrke** [comment] 2020-01-07 10:08
> The & in the app password settings used to work.

But that's related to your vue-refactoring? Isn't it?

`translate` returns `Devices &amp; session`, and since you are using it inside curly breakets, vue is escaping the `&amp;` to `&amp;amp;`
https://github.com/nextcloud/server/commit/4b72475#diff-f57c51aacf630692a4a5d90e51cf3f11R24

Before it was just PHP:
https://github.com/nextcloud/server/commit/4b72475#diff-060894acdc1f2f2a9f681015e65b9f51L97

**Comment by ChristophWurst** [comment] 2020-01-07 10:10
I don't have a 16 instance at hand but I don't think it was broken when I switched to Vue.

**Comment by georgehrke** [comment] 2020-01-07 10:13
My only other guess would be that we most likely had a heavily outdated `DOMPurify` and it broke, when we added it to our `package.json` and updated it to a new version.

**Comment by rullzer** [comment] 2020-01-07 10:58
Yes it was some weird dompurify stuff I remember.

**Comment by raimund-schluessler** [comment] 2020-01-07 16:14
There is an issue in server for this as well https://github.com/nextcloud/server/issues/18662

**Comment by ChristophWurst** [comment] 2020-01-07 17:50
So basically @rullzer fixed this with https://github.com/nextcloud/server/pull/17254 but it broke again. Thanks for the ref, @raimund-schluessler.

**Comment by ChristophWurst** [comment] 2020-01-07 18:14
Can't find where or why that behavior changed in dompurify. Temporarily reverted to v1 and that solves the issue in settings, hence it must be a change in the lib.

**Comment by ChristophWurst** [comment] 2020-01-07 18:48
Submitted upstream because it could also be a regression https://github.com/cure53/DOMPurify/issues/379

**Closed** 2020-01-09 14:37 UTC
Labels: 3 - to review, bug
