### ISSUE TITLE
Calendar sync Error 507 (Insufficient Storage)

### ISSUE THREAD

**Issue by Aircan** [nextcloud/calendar#2074] opened 2020-03-13 20:14 UTC
Using NC 18.0.1 I tried to sync Calender with Android app OneCalendar.
I got the error:

Response status code does not indicate success: 507 (Insufficient Storage) : <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d=“DAV:” xmlns:s=“http://sabredav.org/ns 2”>
<s:exception>OCA\DAV\Exception\UnsupportedLimitOnInitialSyncException</s:exception>
<s:message/>
<d:number-of-matches-within-limits/>
</d:error>

**Comment by georgehrke** [comment] 2020-03-13 20:29
Duplicate of nextcloud/server#18490

**Closed by georgehrke** 2020-03-13 20:29 UTC

**Comment by DesertCookie** [comment] 2024-12-04 19:26
While still an issue with NC 30 in 2024, there seems to be at least a small chance a fix might land in a January '25 release.

**Comment by NoModuleNamedNumpy** [comment] 2024-12-18 09:29
> While still an issue with NC 30 in 2024, there seems to be at least a small chance a fix might land in a January '25 release.

Do you know when this will be fixed in Jan 25, bc. I can't access the calendar, but I need it.

**Comment by for4ver** [comment] 2025-03-20 18:15
## Issue Description

I'm experiencing a 507 (Insufficient Storage) error when trying to sync my Nextcloud calendar with the OneCalendar application. The synchronization specifically fails during the initial loading of calendar events.

## Technical Details

* **Nextcloud Version**: 30
* **Affected Client**: OneCalendar (latest version)
* **Exact Error Message**: Response status code does not indicate success: 507 (). : <d:error xmlns:d="DAV:" xmlns:s="[http://sabredav.org/ns">](http://sabredav.org/ns%22%3E) <s:exception>Internal Server Error</s:exception> <s:message> The server was unable to complete your request. If this happens again, please send the technical details below to the server administrator. More details can be found in the server log. </s:message>
<s:technical-details> <s:remote-address>108.162.245.199</s:remote-address> <s:request-id>4qpIvrg2wRlZ9BGWgkjR</s:request-id>
</s:technical-details> </d:error>

## Additional Information

I have sufficient storage space in my Nextcloud account, so the "Insufficient Storage" error seems to be an incorrect response from the server.

Is there any adjustment or configuration that can be implemented at the server level to fix this issue while a definitive solution is being developed?

Thank you for any guidance on this matter.
