### ISSUE TITLE
External no events from external ICS calendars are shown any longer

### ISSUE THREAD

**Issue by markusd112** [nextcloud/calendar#5710] opened 2024-01-23 16:43 UTC
### Steps to reproduce

1. create a new calendar (external ICS calendar) in NC calendar web GUI connected to public URL to an ICS download (e.g. some Google test calendar with a public read only URL)

### Expected behavior

The events in the external calendar should be displayed in the Nextcloud calendar.

### Actual behaviour

No event is displayed. It worked well until a short time, I am not sure if it is in relation of an update to NC 28.0.1 or Calendar App V. 4.6.4?

### Calendar app version

4.6.4

### CalDAV-clients used

DAVx5, ipadOS Calendar

### Browser

Firefox 121.0.1

### Client operating system

Windows 11 Pro

### Server operating system

Linux 5.4.0-167-generic x86_64

### Web server

None

### Database engine version

MySQL

### PHP engine version

PHP 8.2

### Nextcloud version

28.0.1

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by LuCu11** [comment] 2024-01-26 08:52
I have also synchronized the external calendar on my cell phone, where it is displayed

**Comment by markusd112** [comment] 2024-01-26 09:53
For me too: on my Android device the external calander events are displayed, too. But there I am using ICSx5, where I have stored the calender URL. So I think it is independent from the Next Cloud Calendar App which displays the calendar on the calender web page of the NC instance, where the problem occurs.

**Comment by grisumedia** [comment] 2024-01-28 05:49
The requests of the web client look normal, but the replies from the server do not contain any entries for calendar subscriptions.
The problem persists with Nextcloud 28.0.2RC4

**Comment by tcitworld** [comment] 2024-01-29 08:00
Duplicate of https://github.com/nextcloud/server/issues/42143

**Closed by tcitworld** 2024-01-29 08:00 UTC
Labels: bug, 0 - to triage
