### ISSUE TITLE
Tasks defined in calendars list are not displayed in calendar view

### ISSUE THREAD

**Issue by vincowl** [nextcloud/calendar#1516] opened 2019-10-08 18:15 UTC
I am facing this trouble :
- Create a calendar. It appears in Tasks
- In Tasks, create a new task in the calendar's tasks list that is displayed
- Add begining and due date to this task
- Task is displayed in the task list
- Task doesn't appear in the calendar view

What's wrong with it ? Is it normal or is it a bug or am I doing it wrong ?

Nextcloud : 16.0.5
Calendar : 1.7.1
Tasks : 0.11.3

**Comment by georgehrke** [comment] 2019-10-08 18:16
Duplicate of #28

**Closed by georgehrke** 2019-10-08 18:16 UTC
