### ISSUE TITLE
Event ignoring timezone in modal and details, but correct on calendar overview

### ISSUE THREAD

**Issue by philiprenich** [nextcloud/calendar#6206] opened 2024-07-30 04:12 UTC
### Steps to reproduce

1. Create an event with a non-local timezone (ie, you live in PST -0800, create an event for +0100 in Europe)
2. Save the event and it will appear in your primary calendar view at your local (adjusted) time.
3. Click to view the modal or More Detail and it will show the Create time in Europe.

### Expected behavior

The times displayed in the main view, modal view of the event, and more detail pane should all have the same (local) time displayed.

### Actual behaviour

The overview shows local time, but the modal and detail view show the Created (Europe, in this example) time.

<img width="519" alt="Screen Shot 2024-07-30 at 4 04 19 PM" src="https://github.com/user-attachments/assets/2531dff9-5d9c-4ee3-87bd-57ceda841d58">

The event is maintaining the timezone it was created with, but is inconsistent with translating that to your local time. This is confusing. Additionally, for something like an appointment event, the notification that is generated uses the Create time (Europe, in this example) with no indication about timezones whatsoever.

The Modal view also gives no indication of what timezone it is. Only when you go into More Detail/Edit and click on the globe icon 🌐 do you see the timezone.

It's useful to know the time/timezone the event was created in, but I think the primary display should A) be local and B) be consistent.

### Calendar app version

4.7.13

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

29.0.4

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by miaulalala** [comment] 2024-08-05 15:00
Duplicate of https://github.com/nextcloud/calendar/issues/5031

**Closed by miaulalala** 2024-08-05 15:00 UTC
Labels: bug, 0. to triage
