### ISSUE TITLE
Locale is ignored - Week always starts on Sunday

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/calendar#1954] opened 2020-02-02 05:39 UTC
### Steps to reproduce
CHange locale to "English World" 

### Expected behaviour
Calendar displays week starting with Monday

### Actual behaviour
Calendar always starts on Sunday

## Server configuration detail

**Operating system:** Linux 5.4.0-12-generic #15-Ubuntu SMP Tue Jan 21 15:12:29 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.3.11-0ubuntu2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 18.0.0 - 18.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Git

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - audioplayer: 2.9.0
 - bookmarks: 2.3.4
 - breezedark: 18.0.2
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - drawio: 0.9.4
 - event_update_notification: 1.0.1
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_markdown: 2.2.0
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - gpxpod: 4.1.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextbackup: 19.12.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.6
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - phonetrack: 0.6.1
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - rainloop: 6.0.6
 - ransomware_protection: 1.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.1
 - survey_client: 1.6.0
 - suspicious_login: 3.0.1
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - extract
 - files_external
 - firstrunwizard
 - news
 - recommendations
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
SNIP
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.0.10",
>SNIP
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "app_install_overwrite": [
        "occweb",
        "drawio"
    ],
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls"
}
```
</details>

**Are you using external storage, if yes which one:** NA

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** NA

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

**Operating system:** Ubuntu

## Logs
There's no log info as far as I can see.... 
<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

![Screenshot_2020-02-02 Settings - FOSFOR](https://user-images.githubusercontent.com/6204273/73603732-07ae8200-4587-11ea-9c6c-0cc718552da4.png)

**Comment by georgehrke** [comment] 2020-02-02 12:18
Duplicate of #1844

**Closed by georgehrke** 2020-02-02 12:18 UTC
Labels: 0. to triage, bug
