### ISSUE TITLE
Smart recurring events via webinterface

### ISSUE THREAD

**Issue by dacoex** [nextcloud/calendar#1764] opened 2020-01-08 23:43 UTC
**Is your feature request related to a problem? Please describe.**
Recurring event series are based on the number of the day of the month.
E.g. every day 5 of each month.

**Describe the solution you'd like**
User should be able to specify:
Each second Wednesday of a month...

**Describe alternatives you've considered**
Entering such series via client apps, e.g. Thunderbird, works.

**Additional context**

**Comment by georgehrke** [comment] 2020-01-09 08:56
Duplicate of #10

**Closed by georgehrke** 2020-01-09 08:56 UTC
Labels: 0. to triage, enhancement-proposed
