### ISSUE TITLE
Business hours

### ISSUE THREAD

**Issue by GLLM** [nextcloud/calendar#824] opened 2018-05-11 10:41 UTC
Hi all !

It would be great if we could define the start and the end time/hours of what should be displayed in the week or day view.
As of today (NC 13.0.2), you must see all hours of a day, from 00:00 to 23:59.

![image](https://user-images.githubusercontent.com/3989573/39920774-8d8c3c16-5518-11e8-8675-c07c766282ee.png)
The part in red is useless for me :-/

I'd like to see only 07:00 - 23:00. 
As a consequence, I'd be able to see the whole day without the need for scrolling !
And the upper pane for the "all day" events would have more space.

thanks
GLLM

**Comment by GoetheG** [comment] 2018-05-19 03:14
Yes, this is definitely a function that is needed in the future Nextcloud versions.

**Comment by georgehrke** [comment] 2018-05-19 06:55
@GoetheG Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)

**Comment by arunikayadav42** [comment] 2018-05-31 18:55
@georgehrke can I please work on this issue :)

**Comment by georgehrke** [comment] 2018-08-08 14:09
Duplicate of https://github.com/nextcloud/calendar/issues/577

**Closed by georgehrke** 2018-08-08 14:09 UTC
Labels: enhancement-proposed
