### ISSUE TITLE
Import of calendar via URL fails - but same link works @Google

### ISSUE THREAD

**Issue by NextBlaubeere** [nextcloud/calendar#5771] opened 2024-02-16 16:32 UTC
### Steps to reproduce

Hi. I am trying to import a calender via URL to nextcloud:
1. Goto Calendar App
2. (+) New Calendar
3. New subscription from link (read-only)
4. Past URL there
5. press the arrow
6. See the calendar gets added on the sidebar but wait for nothing to appear

Unfortunatelly it does not work, as no appointments appear. Even after a long time of waiting.
The same link however does work when I do import it in Google Calendar, so it seems to be an issue with nextcloud calender or nextcloud itself.

I found this in the logs:
```
{
  "reqId": "vdeVtczWeGqmhJ4H34jD",
  "level": 4,
  "time": "2024-02-16T16:05:19+00:00",
  "remoteAddr": "92.248.17.105",
  "user": "blaubeere",
  "app": "no app in context",
  "method": "REPORT",
  "url": "/remote.php/dav/calendars/blaubeere/restkonzertmeisterapp-1/",
  "message": "Could not boot files_trackdownloads: Call to undefined method OC\\Server::getEventDispatcher()",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0",
  "version": "28.0.2.5",
  "exception": {
    "Exception": "Error",
    "Message": "Call to undefined method OC\\Server::getEventDispatcher()",
    "Code": 0,
    "Trace": [
      {
        "file": "/app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 200,
        "function": "boot",
        "class": "OCA\\FilesTrackDownloads\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/app/www/public/lib/private/App/AppManager.php",
        "line": 434,
        "function": "bootApp",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->"
      },
      {
        "file": "/app/www/public/lib/private/App/AppManager.php",
        "line": 213,
        "function": "loadApp",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/app/www/public/lib/private/legacy/OC_App.php",
        "line": 125,
        "function": "loadApps",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/app/www/public/remote.php",
        "line": 157,
        "function": "loadApps",
        "class": "OC_App",
        "type": "::"
      }
    ],
    "File": "/config/www/nextcloud/apps/files_trackdownloads/lib/AppInfo/Application.php",
    "Line": 49,
    "message": "Could not boot files_trackdownloads: Call to undefined method OC\\Server::getEventDispatcher()",
    "exception": {},
    "CustomMessage": "Could not boot files_trackdownloads: Call to undefined method OC\\Server::getEventDispatcher()"
  }
}
```

Because of privacy reasons I do not want to share the link, however I can send it via DM if neccessary.
Let me know if you need anything else.

### Expected behavior

appointments appear

### Actual behaviour

appointments do not appear

### Calendar app version

4.6.5 (should be current)

### Browser

Firefox

### Server operating system

UnRaid

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

None

### Nextcloud version

28.0.2

### Updated from an older installed version or fresh install

None

**Comment by CreatsheR** [comment] 2024-02-17 10:09
I didn't look into the logs, but i have the same problem here. Additional I can say, that the entries of the subscribed calendar appears in the calendar-app on iOS, where I've added the Nextcloud-account. So the subscription is working in some ways, but don't show up in the web-ui.

**Comment by miaulalala** [comment] 2024-02-20 11:24
Duplicate of https://github.com/nextcloud/server/issues/42143

**Closed by miaulalala** 2024-02-20 11:24 UTC
Labels: bug
