### ISSUE TITLE
Calendar created talks in webinar mode

### ISSUE THREAD

**Issue by mokkin** [nextcloud/calendar#1890] opened 2020-01-23 17:08 UTC
For better scheduling of webinars, meeting rooms in talk should be always in "webinar mode".
![DeepinBildschirmfoto_Bereich auswählen_20200123180640](https://user-images.githubusercontent.com/2938748/73006705-56cc1880-3e0b-11ea-90c9-95be2e256566.png)
![DeepinBildschirmfoto_Bereich auswählen_20200123180737](https://user-images.githubusercontent.com/2938748/73006709-592e7280-3e0b-11ea-9b92-b3407a8be8cf.png)

**Comment by georgehrke** [comment] 2020-01-23 17:42
Duplicate of #1839

**Closed by georgehrke** 2020-01-23 17:42 UTC
Labels: 0. to triage, enhancement-proposed
