### ISSUE TITLE
[Feature Request] More choices for repeating calendar events.

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/calendar#1153] opened 2019-03-04 14:57 UTC
I want the advanced but widely used choices for repeating events like first Tuesday of the month every 12 months, etc. available in the NextCloud calendar.

I find most repeating events to be intolerably set, however _because of logistics in real life_, a monthly "last Friday of the month Fish-Fry dinner meeting" makes sense for some people and groups.

This extends to business applications where a calendar for a shared resource (_meeting room_), have strange set patterns that are set way in advance and better repeating schedules would avoid collisions in shared resource use. Board uses room for a full workday on the first wednesday of the month every 3 months to discuss their quarterly financial reports that need to be submitted on the 15th. Secretary pool needs the room for continuing education of their technologies used, and they prefer wednesdays at lunchtime for 1 hour. The conflict needs to be mitigated by deleting or moving the lower priority event, or ideally having it split into multiple repeating events.

**Comment by georgehrke** [comment] 2019-03-04 14:59
Duplicate of #10

**Closed by georgehrke** 2019-03-04 14:59 UTC
