### ISSUE TITLE
Event not visible in attendees calendar after it was confirmed

### ISSUE THREAD

**Issue by Mito173** [nextcloud/calendar#1505] opened 2019-10-01 21:02 UTC
**Setup:**
* Server NextCloud 16.0.3
* Calendar App 1.7.1
* Sender: Apple Calendar App on IOS 12.4.1
* Recipient: Apple Calendar App on IOS 13.0
* Sender and recipient have a NextCloud account 
* Mail addresses of sender and recipient are configured in NextCloud
* Sender and recipient do not share their calendars in NextCloud

**Steps to reproduce:**
* User A (sender) creates an appointment and invites user B by entering is mail address
* User B (recipient) gets the invitation as mail from the Nextcloud server

Current behavior:
* if I **use the 'Accept' link/button** in the invitation mail, the participant status in the appointment of the sender is updated but it does not show up in the recipients calendar
* if I **open the attached file 'event.ics'** and click 'add', the appointment is added to the recipients calendar but the participant status in the appointment on sender side is not updated.
* The 'Input' window (button on the right side at the bottom of the IOS calendar) stays empty even after refresh

Expected behavior:
* **Option A**: User B (the recipient) clicks in the 'Accept' button/link in the invitation mail and the event is added to his calendar as well as the status of the recipient on senders side is set to 'accepted'
* **Option B**: User B (the recipient) opens the input window in his calendar app and sees the invitation on tab page 'New' - he then clicks accept and the event is added to his calendar as well as the status of the recipient on senders side is set to 'accepted'

**Comment by BegreenOz** [comment] 2019-10-01 23:19
Isn't this related to the expected behaviour of issue #879 ?

**Comment by Mito173** [comment] 2019-10-02 12:26
If I use the 'accept' button in the mail invitation this does update the status in the corresponding senders calendar appointment (shows little green checkbox next to participiant in details view) in my case. Though, when testing with a different user, this seems not to work for all users. 

My problem is that the appointment is not added to the recipients calendar when he accepts in the invitation mail.

I did some more tests after posting this issue and it seems to be more complex also:
The problem which I have described seems to exists only for older users (created with the initial Nextcloud 15 version. For them I deleted the Contacts Birthday calendar as it produced issues at that time. User which were recently created don't show this issue: for them. the invitation is shown in the IOS calendar 'inbox' of the recipient and can be accepted to the own calendar. Though, the invitation status does not change in the senders calendar and the 'accept' link in the invitation mail returns also an error.

All in all there seem to be several issues coming together. If I find some time within the next days I will create two new test users and try testing again step by step.

**Comment by georgehrke** [comment] 2019-10-02 12:46
Two quick questions:
1. The email addresses configured in Nextcloud are the same as used for invitations.
2. Are the email addresses unique or is the same address assigned to multiple accounts?

**Comment by Mito173** [comment] 2019-10-02 12:54
Yes, mail addresses in Nextcloud are the same as used for the invitations
The mail addresses are all unique, I was testing with 'real' user accounts

Will upgrade to the latest NextCloud version and test Calendar invitations again with two test users which will get own Mailadressen in our domain. I would really like to get this working since NextCloud is working great for us except the Calendar.

**Comment by Mito173** [comment] 2019-10-02 20:40
Tested again with corrected configuration (each mail address must only exist once in the user list)
Invitation does now show up in the recipients **IOS calendar inbox**. If the invitation is accepted there,
* the attendees status in the senders calendar is updated
* the appointment is added to the attendees calendar

Though, if the **'accept' link in the invitation mail** is used,
* the attendees status in the senders calendar is updated
* but the appointment is *not* added to the attendees calendar (it is shown as _proposed_ in the attendees calendar after his/her IOS calendar inbox is updated.

Is this an intended behavior? Wouldn't it be better to immediately show the appointment in the attendees calendar as accepted after it was accepted over the invitation mail link? 
Of course it will be shown as proposed after the inbox update, but the invitation has to be accepted there again which could cause misunderstandings.

**Comment by georgehrke** [comment] 2020-01-09 09:39
Duplicate of https://github.com/nextcloud/server/issues/18750

**Closed by georgehrke** 2020-01-09 09:39 UTC
