### ISSUE TITLE
first day of week, date and hour independent of locale

### ISSUE THREAD

**Issue by nbbn** [nextcloud/calendar#283] opened 2017-01-09 14:27 UTC
Hello,
I see that first day of week, date and hours depends on language selected in profile, but I believe that there should be option to select mix of those settings like 24h clock, ISO dates and Sunday as first day of week. Ability to change those settings is in almost every calendar software.
I use 11.0 version.
Best
Jakub

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Server version:** (see your admin page)

**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:**

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment] 2017-01-09 14:29
won't fix. / won't implement dedicated first day of week choice 

The nextcloud server will introduce a region option instead.
https://github.com/nextcloud/server/issues/1781

**Closed by georgehrke** 2017-01-09 14:29 UTC

**Comment by pmyadlowsky** [comment] 2017-10-09 17:04
Time/date format is a personal choice and should be independent of any language or region setting. Please reconsider the "won't fix" decision.

**Comment by Progdrasil** [comment] 2017-10-13 16:32
I agree with @pmyadlowsky , this is a personal choice. Please reconsider

**Comment by bboissy** [comment] 2019-05-13 15:14
hi, i also agree with @pmyadlowsky and @Progdrasil , Please reconsider

**Comment by jhpratt** [comment] 2019-06-14 03:36
@georgehrke Just because my locale is the United States doesn't mean I want my calendar to show Sunday as the first day of the week. I also prefer ISO (YYYY-MM-DD) formats, yet there's no option to change this.

**Comment by IanJSaul** [comment] 2022-04-04 18:19
This is why the USA is still on the "Imperial" measurement system - because we get stuck with what we have, and we came to Nextcloud for change.

I'd love 24-Hour functional ability + starting the week on a selected day.

Cheers, -Ian

**Comment by baermb** [comment] 2022-09-03 00:23
I would also like this to be reconsidered. I'm going to hate myself a little bit for using this term, bu the following is a 'user story' as to why I think adding three separate preferences (at least a 12/24 hour one) would be better.

I want to set is 12/24 time, 1st day of week, short/long date format. The idea of using locales sounds simple, but I think ends up being pretty user unfriendly.

It appears what I have to do in order to find the right combination, is go down the list of locales one by one until I get lucky. Doing this feels either extremely foolish or purposefully masochistic. I would prefer to think I'm purposefully masochistic. But either way, I tried to do this. TLDR: I can't.

English (World), 12 hour clock, really? okay.
English (Europe), 12 hour clock, (I guess this is for Paris, TX)
English for each of the following is also 12 hour clocks:
United Arab Emirates, Antigua and Barbados, Anguilla, American Somoa, Austria, Australia, Barbados, Belgium, Burundi, Bermuda, Bahamas, Botswana, Belize, Canada, Cocos, Switzerland, Cook Islands, Cameroon, Christmas Island, Cyprus, Germany, Diego Garcia, Denmark, Dominica, Eritrea, Finland, Fiji, Falkland Islands, Micronesia, Granada, Guernsey, Ghana, Gibralter, Gambia, Guam, Guyana, Hong Kong, Isle of Man (really?), India, Jersey, Jamaica, Kenya, Kiribati, Caymans, St. Lucia, Liberia, Lesotho, Madagascar, Marshall Islands, Macao, Montserrat, Malta, Mauritius, a whole bunch I don't feel like typing, Netherlands (because Really?), Another whole bunch I'm too lazy to type.

English for the following are 24 hour clocks, but of course these all start on Monday (not how I want to do it), and these all do day/month/year, again not how I do it (like a commenter above, I like the ISO year-month-day):
United Kingdom, Ireland, Israel, Singapore.

Also, weirdly, this long list isn't in alphabetical order which makes finding a particular locale even harder.

In order to set three options, I have to go through ~50 choices. None of these matches what I'm  actually looking for. And this is just for English. I can imagine there is a good programmatic reason for doing this (e.g. date object in a library that uses locales), but from a user perspective, it seems difficult, and in my case impossible, to set three seemingly simple preferences.

**Comment by ctag** [comment] 2023-01-12 16:53
Sifting through locales randomly to find one that just happens to display the calendar and clock correctly feels like visiting one of those [prank javascript pages](https://blog.rysolv.com/worst-time-date-selectors-in-the-world) that demos the worst ways to interact with a UI element. I do not understand how this is the intended behavior.

**Comment by kn0wmad** [comment] 2024-01-09 15:23
Bump.  Any chance to get a 24hr clock?  This is a very popular standard and an option across all kinds of software.

**Comment by pmyadlowsky** [comment] 2024-01-09 17:17
Bump++

**Comment by Nitrowolf** [comment] 2025-01-15 14:06
Bump++ 

I can't fathom why anyone in their right mind would think setting your time/date formats based on your locale makes any kind of sense.  

Please give the option to select your time and date format independent of your locale.  Absolutely ridiculous that you can't.
