### ISSUE TITLE
Email sent when appointment is used

### ISSUE THREAD

**Issue by Ecphrasis** [nextcloud/calendar#4456] opened 2022-09-01 15:22 UTC
### Is your feature request related to a problem? Please describe.

When someone makes an appointment with the link, the owner doesn't know anything, he have to check the calendar. So he can miss the appointment.

### Describe the solution you'd like

When someone creates a appointment, a mail is sent to the owner of the calendar when the appointment is confirmed for example.

**Comment by nickian** [comment] 2022-09-04 23:29
I agree. I am not sure how this was overlooked. It's 100% necessary to send an email confirmation to both the person who owns the calendar and to the person requesting a meeting.

**Comment by ChristophWurst** [comment] 2022-09-05 07:20
Duplicate of https://github.com/nextcloud/calendar/issues/3630. This was not overlooked.

**Closed by ChristophWurst** 2022-09-05 07:20 UTC
Labels: enhancement, 0. to triage
