### ISSUE TITLE
No e-mail invitations send, but cancellation mails

### ISSUE THREAD

**Issue by pserrer** [nextcloud/calendar#644] opened 2017-10-26 15:41 UTC
I have a special problem with invitations. I have two nextcloud installtions on  the same server.

Instance no-1: newly created, which is in the public directory example.com/nextcloud 
Instance no-2: old one, which is in the public directory example.com/owncloud (old name because we don't want to change all links..)

In the newly created nextcloud has no problems to send invitations to the given mails, the old one doesn't send invitations. The interesting thing is, the cancelled notification is sent from both.

### Steps to reproduce
1. Create a new invitation
2. Choose participants
3. Participants receive no e-mails

---
1. Delete the invitation
2. Participants receive an "Cancelled: ..." e-mail

### Expected behaviour
Participants should receive an invitation

### Actual behaviour
Participants don't receive an invitation

### Server configuration

**Operating system**:
Linux (Shared Hoster)

**Web server:**
Apache

**Database:**
MySQL 5.7

**PHP version:**
5.6.31 - fpm

**Server version:** (see your admin page)
Nextcloud 12.0.3

**Calendar version:** (see the apps page)
1.5.6

**Updated from an older installed version or fresh install:**
Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Default + calendar, contacts
```

**Nextcloud configuration:**

```
$CONFIG = array (
  'instanceid' => '....',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' =>
  array (
    0 => '...',
  ),
  'datadirectory' => '/files/data',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => '...',
  'dbhost' => '...',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'installed' => true,
  'maintenance' => false,
  'overwrite.cli.url' => '...',
  'loglevel' => 0,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by georgehrke** [comment] 2017-10-26 16:09
please provide logs, both config.php and provide much more detailed reproduction steps.
Please describe the email addresses use (use placeholders), when did the event in question start, ...

**Comment by georgehrke** [comment] 2017-10-26 16:11
did you create the event in the web browser or some local client like thunderbird?

**Comment by pserrer** [comment] 2017-10-27 08:41
The config of the working nextcloud looks the same as the config from the non working installation

```
$CONFIG = array (
  'instanceid' => 'oc0xbkcis333',
  'passwordsalt' => 'QOPZG+bcdurad5+e1ahwvhyCz2+fDu',
  'secret' => 'yIlzEsgbaItNkBS12jC4Op/RFSflh5rk6Vws7NVHIfWmSTts',
  'trusted_domains' =>
  array (
    0 => 'cloud.galileo-webagentur.de',
  ),
  'datadirectory' => '/html/htdocs/nextcloud/data',
  'overwrite.cli.url' => 'http://cloud.galileo-webagentur.de/nextcloud',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'usr_p243593_2',
  'dbhost' => 'db1314.mydbserver.com',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'p243593',
  'dbpassword' => '2014gwmnTbxBhnsnWJY2',
  'installed' => true,
);
```

I tried it with different mail addresses (gmail and company mail - no special chars) no difference. One installation sends invitations and cancellations - the other only cancellations.

It tried it with Thunderbird and with the web interface - also same result.

The log is completly empty and doesn't contain anything related.

**Comment by rcmcronny** [comment] 2018-02-02 14:52
I have this also,for me this happens if "user a" shares a calendar with "user b". If "user b" now creates a calendar entry, there is NO mail send to the attenties. If you delete the the entry , the invited attendies get a cancelled mail, so mail works. 
If you create the entry as "user a" , the invite mails are correctly sent, cancellation mails also work. 

May that makes it easier to locate, where the issue is  ?

**Comment by georgehrke** [comment] 2018-02-02 16:00
@rcmcronny Yours is a duplicate of https://github.com/nextcloud/server/issues/3830

@pserrer Are you talking about shared calendars too?

**Comment by georgehrke** [comment] 2019-08-29 16:20
No response to question for over a year, closing since i was never able to reproduce

**Closed by georgehrke** 2019-08-29 16:20 UTC
Labels: 1 - to develop, bug, needs info
