### ISSUE TITLE
Appointments "Additional calendars to check for conflict" bug when a calendar is deleted

### ISSUE THREAD

**Issue by nonfreegithub** [nextcloud/calendar#5131] opened 2023-04-05 22:06 UTC
### Steps to reproduce

1. Create a new calendar "example"
2. Create a new appointment config and set example calendar in "Additional calendars to check for conflict"
3. Delete example calendar
4. edit the appointment and check "Additional calendars to check for conflict", it's bug

### Expected behavior

I can edit the "Additional calendars to check for conflict" in the appointment config

### Actual behaviour

I can not edit it :(

### Calendar app version

4.3.1

### CalDAV-clients used

DAVx5

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment] 2023-04-06 06:49
Good observation.

Duplicate of https://github.com/nextcloud/calendar/issues/4092

**Closed by ChristophWurst** 2023-04-06 06:49 UTC
Labels: bug, 0 - to triage
