### ISSUE TITLE
Calender entries not sorted by date

### ISSUE THREAD

**Issue by cnoelker** [nextcloud/calendar#4588] opened 2022-10-10 07:24 UTC
### Steps to reproduce

1.Create two or more appointments on the same date
2.Check on the Month view: They are not sorted
3.

### Expected behavior

Appointments should be display in chronologic order

### Actual behaviour

The last date seems to be at first position

### Calendar app version

3.5.0

### Browser

Firefox

### Server operating system

Ubuntu

### Web server

Apache

### Nextcloud version

23.0.10

**Comment by ChristophWurst** [comment] 2022-10-10 07:25
Duplicate of https://github.com/nextcloud/calendar/issues/4443

**Closed by ChristophWurst** 2022-10-10 07:25 UTC
Labels: bug, 0 - to triage
