### ISSUE TITLE
Embedded code not working on chrome/brave

### ISSUE THREAD

**Issue by lalejand** [nextcloud/calendar#2944] opened 2021-03-10 17:42 UTC
### Steps to reproduce
1. Open https://scenari.org/co/page_test_calendrier.html with Brave or Chrome
2. Click on next month button until there is some event in the month
3. Click on any other button --> calendar stays freezed.

### Calendar app
Calendar    2.1.3

### Client configuration
Brave Version 1.16.68 Chromium: 86.0.4240.111 (Build officiel) (64 bits) on Ubuntu 20.10
Also tested on Chrome 89.0.4389.82 (Build officiel) (64 bits) on Windows 10

### Server configuration
OS Ubuntu 18.04
Web server Nginx
BDD MariaDb
PHP 7.2.24
Nextcloud 20.0.8
Updated from an older installed version

Accessibility    1.6.0
Activity    2.13.4
Brute-force settings    2.0.1
Calendar    2.1.3
Collaborative tags    1.10.0
Comments    1.10.0
Contacts    3.4.3
Contacts Interaction    1.1.0
Dashboard    7.0.0
Deck    1.2.5
Deleted files    1.10.1
Federation    1.10.1
File sharing    1.12.2
First run wizard    2.9.0
Log Reader    2.5.0
Mind Map    0.0.24
Monitoring    1.10.0
Nextcloud announcements    1.9.0
Notifications    2.8.0
Password policy    1.10.1
PDF viewer    2.0.1
Photos    1.2.3
Privacy    1.4.0
Recommendations    0.8.0
Right click    0.17.0
Share by mail    1.10.0
Support    1.3.0
Text    3.1.0
Theming    1.11.0
Update notification    1.10.0
Usage survey    1.8.0
User status    1.0.1
Versions    1.13.0
Video player    1.9.0
Weather status    1.0.0
Auditing / Logging    1.10.0
Default encryption module    2.8.1
External storage support    1.11.1
LDAP user and group backend    1.10.2 

https://user-images.githubusercontent.com/30934848/110672847-5db11880-81d0-11eb-892a-dffe7204f4a5.mp4

**Comment by MisterErwin** [comment] 2021-03-11 21:43
Appears to be a duplicate (albeit with a hosted example) of #2929

If I reduce the height of the iframe in your example (or most likely if you add more weeks with events per month) it also does not work in firefox.

**Comment by lalejand** [comment] 2021-03-12 00:20
You are totally right !!! I tested with a 20px increased height and it works on brave !

**Comment by fschrempf** [comment] 2021-03-19 10:52
I'm closing this as a duplicate of #2929. Let's continue over there!

**Closed by fschrempf** 2021-03-19 10:52 UTC
Labels: 0. to triage, bug
