### ISSUE TITLE
Add groups to appointment instead of members individual

### ISSUE THREAD

**Issue by Papewaio** [nextcloud/calendar#4840] opened 2022-12-28 13:21 UTC
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I have to add several persons to an appointment, even when they are all members of one group in NC.

(I know that there has been a similar issue #4742, but the discussion is - at least in my perception - about something else)

### Describe the solution you'd like

I can add a group to an appointment and automatically, all members of the group will be listed as an attendee.
"Adding a group" is just a "shortcut" of adding each member of the group ( at this moment) step by step to the appoinment.
And everyone get's an invitation to this appointment per mail.

### Describe alternatives you've considered

I know that I can add a new calender and then add a group to this calendar.
Now every member of the group has access to this calender. 
My problem is, when you have a lot of groups its getting pretty messy:
Either you have a lot of calendars, which can be really confusing or you have less calendars with a lot of appointments, which are of no concern for you.

### Additional context

I'm a teacher at a school in Germany and we have a lot of different groups (members > 10) 
We need one "general calendar" with all possible appointments. Every teacher has access to this calendar (write and read) and can check what is planned on a particular day in the school and add new appointment.
For example, the class 05a is making a trip to the museum. A teacher is adding the appointment to the generall calendar. But maybe only 1/5 of the colleagues are interested in this appointment.
I tried to establish calendars for each group but due to the amount of our groups that is not workable for me. So I thought it would be good, if I can add the teachers, who are affected and they'll get an email. The recipient of the email can decide, if he/she wants this appointment in his personal calendar.

The idea of adding groups as a shortcut to add every member step by step is inspired by the possiblity in moodle to add members to a course as an "global group" in manual enrolement.

**Comment by miaulalala** [comment] 2022-12-29 10:18
Hi, thanks for your ticket and the added context. Development of this feature is on its way in https://github.com/nextcloud/calendar/pull/4742 as you already found.

Duplicate of #167

**Closed by miaulalala** 2022-12-29 10:18 UTC
Labels: enhancement, 0 - to triage

**Comment by Papewaio** [comment] 2022-12-29 11:35
Hi miaulalala,
thanks for the feedback 😊
Still trying to discover github ...
