### ISSUE TITLE
Allow accept/decline button for secondary email address

### ISSUE THREAD

**Issue by gcolpart** [nextcloud/calendar#6304] opened 2024-08-30 19:29 UTC
### Is your feature request related to a problem? Please describe.

If I add a secondary email address in my profile, please allow accept/decline button for calendar event where this email is attendee. Please allow also for IMIP email for a new event in "Mail".

**Comment by miaulalala** [comment] 2024-09-02 07:49
Duplicate of https://github.com/nextcloud/server/issues/40891

**Closed by miaulalala** 2024-09-02 07:49 UTC
Labels: enhancement, 0. to triage

**Comment by kesselb** [comment] 2025-09-05 12:20
> Please allow also for IMIP email for a new event in "Mail".

https://github.com/nextcloud/mail/issues/11349
