### ISSUE TITLE
List view with events of more than only one month

### ISSUE THREAD

**Issue by martingwb** [nextcloud/calendar#4999] opened 2023-02-21 16:54 UTC
### Is your feature request related to a problem? Please describe.

Would be great to have a list view available with all events from a (or selected) calendars. Currently it is only possible to view all events in a month.

### Describe the solution you'd like

While the current solution only provides a list view for a specific month it would be great to have a list of all events of a calendar.

**Comment by tcitworld** [comment] 2023-02-21 16:57
Duplicate of #2943

**Closed by tcitworld** 2023-02-21 16:57 UTC
Labels: enhancement, 0 - to triage
