### ISSUE TITLE
Personal calendar not visible when importing ICS (for some users)

### ISSUE THREAD

**Issue by matclab** [nextcloud/calendar#5300] opened 2023-06-09 08:23 UTC
### Steps to reproduce

1. Try to import ICS
2. Default personnal calendar not visible in the dropdown list (for some user. An admin can see its own calendar)
3. Newly created calendar not visible in the drop down list (only admin shared calendar visible)

### Expected behavior

The personal calendar and any newly created calendar should be visible as a target for ICS import.

### Actual behaviour

The personal calendar and any newly created calendar is not visible in the targer dropdown menu.

### Calendar app version

4.3.4

### Browser

Brave 1.52.122 Chromium: 114.0.5735.110 

### Client operating system

Windows

### Server operating system

Hosted by Hetzner

### Web server

Nginx

### Database engine version

MySQL

### PHP engine version

PHP 8.2

### Nextcloud version

26.0.2.1

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.18.0
  - apporder: 0.15.0
  - auto_groups: 1.5.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.4
  - calendar_resource_management: 0.5.0
  - cloud_federation_api: 1.9.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - event_update_notification: 2.2.0
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_markdown: 2.4.0
  - files_readmemd: 2.0.0
  - files_rightclick: 1.5.0
  - files_texteditor: 2.15.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - forms: 3.3.0
  - holiday_calendars: 0.3.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - notify_push: 0.6.3
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - piwik: 0.11.1
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - related_resources: 1.1.0-alpha1
  - serverinfo_hetzner: 1.18.0
   - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - user_migration: 3.0.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - welcome: 1.0.9
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - backup: 1.2.0 (installed 1.2.0)
  - circles: 26.0.0 (installed 22.1.1)
  - comments: 1.16.0 (installed 1.12.0)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.12.0)
  - files_pdfviewer: 2.7.0 (installed 2.3.1)
  - files_sharing: 1.18.0 (installed 1.14.0)
  - files_trashbin: 1.16.0 (installed 1.12.0)
  - photos: 2.2.0 (installed 1.4.0)
  - recommendations: 1.5.0 (installed 1.1.0)
  - systemtags: 1.16.0 (installed 1.12.0)
  - user_ldap: 1.16.0
  - weather_status: 1.6.0 (installed 1.2.0)
```

### Nextcloud configuration

```Text
Information not available wth Hetzner share storage
```

### Web server error log

```Text
Information not available wth Hetzner share storage
```

### Log file

```Text
Information not available wth Hetzner share storage
```

### Additional info

Tested on client side with firefox, chrome, edge and brave browsers.
Calendar app not updated to v4.4.0 according to Hetzner request.

**Comment by joshtrichards** [comment] 2024-05-15 21:13
> for some user. An admin can see its own calendar

Can *some* users see it (other than admin)? Or are you saying only the admin can see their personal calendar?

Sounds like #3231

**Comment by joshtrichards** [comment] 2024-09-05 19:08
Closing due to inability to reproduce/ no follow-up info received after >4 months. We can reopen if further actionable info is submitted.

**Closed by joshtrichards** 2024-09-05 19:08 UTC
Labels: bug, needs info, 0. to triage

**Comment by matclab** [comment] 2024-09-09 09:30
Sorry for the delay. 
I just get the feedback from the person experiencing the problem and it now works as expected.
