### ISSUE TITLE
Keep sidebar open when clicking another event

### ISSUE THREAD

**Issue by PVince81** [nextcloud/calendar#4027] opened 2022-03-08 08:20 UTC
### Steps to reproduce

1. Have a bunch of meetings during the week (in my case, one on ones) which don't have attendee names in the title
2. Look at the weekly view and be curious about whose 1-1 you're having with for some of the event blocks
3. To find out, click the first meeting block => popup appears
4. Click "More"
5. Click "Attendees" and see who's the attendee
6. Click another meeting block
7. Click "More"
8. Click "Attendees" and see who's the attendee
9. Repeat with each meeting block

### Expected behavior

When I click another meeting block, I'd like the sidebar to stay open on the last tab instead of disappearing.
This way I can more easily iterate over multiple events and see the attendees.

### Actual behaviour

The sidebar closes after every click on an event, it's very tedious and frustrating to have to click so many times to go back to sidebar mode

### Calendar app version

the one from c.nc.com

### Browser

Firefox 97.0.1

### Server operating system

the one from c.nc.com

### Nextcloud configuration

```Text
see c.nc.com
```

**Comment by PVince81** [comment] 2022-03-08 08:20
@nextcloud/designers not sure if this has been discussed before

**Comment by raimund-schluessler** [comment] 2022-03-08 08:23
Duplicate of https://github.com/nextcloud/calendar/issues/2384. 😉

**Closed** 2022-03-08 09:06 UTC
Labels: bug, design, 0. to triage
