### ISSUE TITLE
Custom categories broke event editor

### ISSUE THREAD

**Issue by CATER-COM** [nextcloud/calendar#3802] opened 2021-12-10 12:54 UTC
### Steps to reproduce
1. create or open an event 
2. fill what is needed
3. type a custom category
4. click on this custom category to add it

### Expected behaviour
The custom category is added (Worked great until some days ago)

### Actual behaviour
Cannot click on the custom category, the category remain display waiting to be validate and cannot do anything in the editor. When trying to close the event curently edited the panel remain open but the content disappear and a wheel turn until closing the tab ou windows 

### Calendar app
**version 3.0.1**

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, iOS Calendar)

### Client configuration
**Browser: Firefox 94**

**Operating system:** Windows 10, Ubuntu

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** (e.g. 7.4)

**Nextcloud Version:** 22.2.3

**Updated from an older installed version or fresh install:** updated

**List of activated apps:**
- accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.13.0
  - calendar: 3.0.1
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - collectives: 0.16.22
  - comments: 1.12.0
  - contacts: 4.0.6
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.4.0
  - groupfolders: 10.0.0
  - guests: 2.1.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.1
  - metadata: 0.15.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - rainloop: 7.1.2
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - sharingpath: 0.4.3
  - spreed: 12.2.2
  - support: 1.5.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0

**Nextcloud configuration:**
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": REMOVED,
        "Overwriteprotocol": "http",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "35242",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maxZipInputSize": 209715200,
        "allowZipDownload": true,
        "loglevel": 0,
        "maintenance": false,
        "defaultapp": "files",
        "enable_avatars": true,
        "appcodechecker": false,
        "updatechecker": true,
        "updater.release.channel": "stable",
        "integrity.check.disabled": true,
        "check_for_working_htaccess": true,
        "check_for_working_wellknown_setup": true,
        "gs.federation": "global",
        "filesystem_check_changes": 1,
        "theme": "",
        "remember_login_cookie_lifetime": 604800,
        "session_lifetime": 21600,
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "trusted_domains": [
            REMOVED
        ],
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "allow_user_to_change_display_name": true,
        "knowledgebaseenabled": true,
        "filelocking.enabled": true,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "occweb",
            "groupfolders",
            "twofactor_nextcloud_notification",
            "spreed",
            "files_downloadactivity",
            "sharingpath"
        ],
        "mysql.utf8mb4": true

Thanks for your replies

**Comment by tcitworld** [comment] 2021-12-10 12:56
Please post your browser logs as asked in the issue template, it's hard to guess what went wrong without those.

**Comment by CATER-COM** [comment] 2021-12-10 14:06
here is the extracted from FF Console :

```
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 22 util.js:135:11
XHRGEThttp://owncloud.toto.biz/ocs/v2.php/apps/notifications/api/v2/notifications
TypeError: e is undefined
    valueKeys vue-multiselect.min.js:1
    valueKeys vue-multiselect.min.js:1
    VueJS 3
    isSelected vue-multiselect.min.js:1
    optionHighlight vue-multiselect.min.js:1
    render vue-multiselect.min.js:1
    Se VueJS
    render vue-multiselect.min.js:1
    VueJS 14
    deactivate vue-multiselect.min.js:1
    blur vue-multiselect.min.js:1
    VueJS 33
vue.runtime.esm.js:1897:4
TypeError: t is undefined
    toICAL ical.js:411
    value ical.js:1680
    multiValue ical.js:1657
    property ical.js:1594
    component ical.js:1480
    component ical.js:1489
    toString ical.js:2754
    toICS index.esm.js:984
    n calendarObjects.js:215
vue.runtime.esm.js:1897:4
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 22 util.js:135:11
XHRGEThttp://owncloud.toto.biz/ocs/v2.php/apps/notifications/api/v2/notifications
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 22 util.js:135:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 22 util.js:135:11
XHRPUThttp://owncloud.toto.biz/index.php/apps/user_status/heartbeat
Uncaught (in promise) TypeError: t.t0.response is undefined
    t notificationsService.js:72
    u runtime.js:63
    _invoke runtime.js:294
    v runtime.js:119
    l notifications-main.js:2
    s notifications-main.js:2
    promise callback*l notifications-main.js:2
    i notifications-main.js:2
    u notifications-main.js:2
    u notifications-main.js:2
    p notificationsService.js:53
    t notificationsService.js:39
    u runtime.js:63
    _invoke runtime.js:294
    v runtime.js:119
    l notifications-main.js:2
    i notifications-main.js:2
    u notifications-main.js:2
    u notifications-main.js:2
    c notificationsService.js:26
    t App.vue:277
    u runtime.js:63
    _invoke runtime.js:294
    v runtime.js:119
    m notifications-main.js:2
    i notifications-main.js:2
    h notifications-main.js:2
    h notifications-main.js:2
    _fetch App.vue:190
    _backgroundFetch App.vue:311
notificationsService.js:72:2
XHRPUThttp://owncloud.toto.biz/index.php/apps/user_status/heartbeat
XHRGEThttp://owncloud.toto.biz/ocs/v2.php/apps/notifications/api/v2/notifications
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 22 util.js:135:11
XHRPUThttp://owncloud.toto.biz/index.php/apps/user_status/heartbeat
XHRGEThttp://owncloud.toto.biz/ocs/v2.php/apps/notifications/api/v2/notifications
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 22 util.js:135:11
```

**Comment by CATER-COM** [comment] 2021-12-10 14:09
Strange to see "OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21" as the instance running is NC22+

**Comment by raimund-schluessler** [comment] 2021-12-10 14:15
I can confirm the issue. As soon as you click the custom category, the error is triggered. Should be easy to reproduce. I will check later with a debug build what goes wrong.

**Comment by CATER-COM** [comment] 2021-12-10 14:40
Thanks a lot. We are using category with Thunderbird. As long we cannot redefine default list in the web UI we need the custom category to insert it manually each time. So actually we need to wait going back to the office to manage categories in our events  :-/

**Comment by mklemme1** [comment] 2021-12-31 17:24
I have the same issue.
Tested with NC 21.0.7  22.2.3
Calendar App version 3.0.4 and the one before.

**Comment by ManuelWardeh** [comment] 2022-01-17 06:31
Same issue with NC 23.0.0

Cannot add custom categories. Likewise, default categories that have already been added cannot be edited or deleted.

The following error occurs in the console when adding a custom category via the plus icon

`vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at PropertySelectMultiple.vue:129:1
    at Array.sort (<anonymous>)
    at options (PropertySelectMultiple.vue:128:1)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
    at o.options (vue.runtime.esm.js:4851:17)
    at o.<anonymous> (PropertySelectMultiple.vue?vue&type=template&id=7c83eba2&:1:544)
    at o.t._render (vue.runtime.esm.js:3569:22)
    at o.r (vue.runtime.esm.js:4081:21)
    at bn.get (vue.runtime.esm.js:4495:25)
qt @ vue.runtime.esm.js:1897
Wt @ vue.runtime.esm.js:1888
$t @ vue.runtime.esm.js:1848
t._render @ vue.runtime.esm.js:3571
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn.run @ vue.runtime.esm.js:4570
vn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
te @ vue.runtime.esm.js:1915
Promise.then (async)
Qt @ vue.runtime.esm.js:1942
ie @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
mt.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
addCategory @ calendarObjectInstance.js:529
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
Ne._withCommit @ vuex.esm.js:624
Ne.commit @ vuex.esm.js:464
Ne.commit @ vuex.esm.js:409
addCategory @ EditSidebar.vue:378
Vt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Vt @ vue.runtime.esm.js:1863
t.$emit @ vue.runtime.esm.js:3903
selectValue @ PropertySelectMultiple.vue:143
Vt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Vt @ vue.runtime.esm.js:1863
t.$emit @ vue.runtime.esm.js:3903
select @ vue-multiselect.min.js:1
click @ vue-multiselect.min.js:1
Vt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
i._wrapper @ vue.runtime.esm.js:6961
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'value')
    at vue-multiselect.min.js:1:10087
    at Array.map (<anonymous>)
    at o.valueKeys (vue-multiselect.min.js:1:10064)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
    at o.valueKeys (vue.runtime.esm.js:4851:17)
    at o.isSelected (vue-multiselect.min.js:1:11234)
    at optionHighlight (vue-multiselect.min.js:1:15243)
    at vue-multiselect.min.js:1:43378
    at o.Se [as _l] (vue.runtime.esm.js:2646:16)
qt @ vue.runtime.esm.js:1897
Wt @ vue.runtime.esm.js:1888
$t @ vue.runtime.esm.js:1848
t._render @ vue.runtime.esm.js:3571
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn.run @ vue.runtime.esm.js:4570
vn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
te @ vue.runtime.esm.js:1915
Promise.then (async)
Qt @ vue.runtime.esm.js:1942
ie @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
mt.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
addCategory @ calendarObjectInstance.js:529
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
Ne._withCommit @ vuex.esm.js:624
Ne.commit @ vuex.esm.js:464
Ne.commit @ vuex.esm.js:409
addCategory @ EditSidebar.vue:378
Vt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Vt @ vue.runtime.esm.js:1863
t.$emit @ vue.runtime.esm.js:3903
selectValue @ PropertySelectMultiple.vue:143
Vt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Vt @ vue.runtime.esm.js:1863
t.$emit @ vue.runtime.esm.js:3903
select @ vue-multiselect.min.js:1
click @ vue-multiselect.min.js:1
Vt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
i._wrapper @ vue.runtime.esm.js:6961
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'value')
    at vue-multiselect.min.js:1:10087
    at Array.map (<anonymous>)
    at o.valueKeys (vue-multiselect.min.js:1:10064)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
    at o.valueKeys (vue.runtime.esm.js:4851:17)
    at o.isSelected (vue-multiselect.min.js:1:11234)
    at optionHighlight (vue-multiselect.min.js:1:15243)
    at vue-multiselect.min.js:1:43378
    at o.Se [as _l] (vue.runtime.esm.js:2646:16)`

**Comment by TenchuA** [comment] 2022-05-11 23:40
Same issue on Nextcloud Hub II 24.0.0 and Calendar 3.3.0
Impossible to add new custom categories, this issues isn't new I have this problem since NC21.
Any fix ?

**Comment by max65482** [comment] 2022-05-22 08:07
> Any fix ?

 #3944 still to be reviewed.

**Comment by xeruf** [comment] 2022-06-04 20:38
Also unable to add custom categories at all, seeing this in the console:
```sh
TypeError: e is undefined
    valueKeys vue-multiselect.min.js:1
    valueKeys vue-multiselect.min.js:1
    VueJS 3
    isSelected vue-multiselect.min.js:1
    optionHighlight vue-multiselect.min.js:1
    render vue-multiselect.min.js:1
    Se VueJS
    render vue-multiselect.min.js:1
    VueJS 14
    deactivate vue-multiselect.min.js:1
    blur vue-multiselect.min.js:1
    VueJS 33
```

**Comment by nderambure** [comment] 2022-07-25 14:31
Same error here, using Nextcloud 24.0.3 and Calendar 3.4.2.
Trying to create a custom category for any event throw a JS error `TypeError: e is undefined`.
I'm surprised that this bug has been around for so long, it's a common feature but maybe not really used ?
Anyway, I hope this will be fixed soon !

Thx.

**Comment by RalfAlbers** [comment] 2022-08-24 04:51
Still in NC24.0.4 and Calendar 3.4.3

**Comment by nderambure** [comment] 2022-08-24 13:58
May anyone be assigned to this blocking bug ?
The Calendar is really a mess wihtout the categories, even in small teams.
Hope someone will crush this bug soon :)

**Comment by max65482** [comment] 2022-08-24 15:09
Maybe someone can merge #3944 which fixes the issue.

**Comment by Kayoku** [comment] 2022-10-05 07:51
Still bugged.... And really a pain for a lot of team. Can't even add new category in calendar..
NC 24.0.5 / Calendar 3.5.0

**Closed** 2022-10-07 07:40 UTC
Labels: 3 - to review, bug
