### ISSUE TITLE
[Feature request] add categories

### ISSUE THREAD

**Issue by Sherl0ck007** [nextcloud/calendar#909] opened 2018-09-18 07:30 UTC
### Expected behaviour
It would be nice to be able to categorize events.

### Actual behaviour
Currently, to differentiate events from each other optically, you have to create different calendars. I dont't know about you, but I don't think that's what different calendars are meant for. For example, in a private calendar there would be sports events and general appointments and no way to differentiate those.

**Comment by gjgd** [comment] 2018-09-29 19:17
Hey @Sherl0ck007 
Actually you can assign categories in the right column (see screenshots)
![screen shot 2018-09-29 at 14 13 35](https://user-images.githubusercontent.com/7913565/46249645-3d22e880-c3f2-11e8-9aeb-c488c4b1bb28.png)
<img width="1352" alt="screen shot 2018-09-29 at 14 16 57" src="https://user-images.githubusercontent.com/7913565/46249648-5b88e400-c3f2-11e8-9d05-8b421c84b983.png">

**Comment by georgehrke** [comment] 2018-10-01 18:46
Duplicate of #107

**Closed by georgehrke** 2018-10-01 18:46 UTC
