### ISSUE TITLE
Copy Calendar Entrys

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/calendar#932] opened 2018-10-25 05:50 UTC
Hello,

I use the calendar to enter my roster.
I have different services and these are repeated every few days and I would like to copy these entries easier and not create each day individually. For this Job i use ACalendar+ for Android but i would use it at the Browser.

Would be a great Feature.

**Comment by georgehrke** [comment] 2018-10-25 08:37
Duplicate of #906

**Closed by georgehrke** 2018-10-25 08:37 UTC
