### ISSUE TITLE
Calendar event editing not working in mont view

### ISSUE THREAD

**Issue by aledef** [nextcloud/calendar#4322] opened 2022-06-27 16:54 UTC
Nextcloud version: 24.0.2

The issue I am facing:
Calendar event editing not working when calendar is in mont view

Steps to replicate it:

1. Open calendar app in mont view
2. Try to edit an event

The issue started after last NC & calendar app update

### Expected behavior

Events editing should be working in month view

### Actual behaviour

The Ui stops working

### Calendar app version

3.4.0

**Comment by miaulalala** [comment] 2022-06-28 07:31
Duplicate of #4313

**Closed by miaulalala** 2022-06-28 07:31 UTC
Labels: bug, 0. to triage
