### ISSUE TITLE
Since Upgrade to Nextcloud 24 the "show busy times" view is broken

### ISSUE THREAD

**Issue by brotkastn** [nextcloud/calendar#4222] opened 2022-05-16 19:36 UTC
### Steps to reproduce

1. Create new Event
2. Add someone else to the Calendar
3. Press "show buys times"

### Expected behavior

As it was the case with nextcloud 23, the busy-view should show the times the attendee is available

### Actual behaviour

The view opens, but is stuck in "loading" - see screenshot
![Screenshot_20220516_212416](https://user-images.githubusercontent.com/604466/168667868-3610b61a-2df2-4737-9b2f-654f03c9c10d.png)

### Calendar app version

3.3.0

### Browser

Firefox 100, Chromium 101, Edge on Windows

### Client operating system

Arch Linux / Windows

### Server operating system

Ubuntu 22.04

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

24.0.0

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
www-data@nextcloud:~/nextcloud$ php occ app:list
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - admin_notifications: 1.0.2
  - apporder: 0.15.0
  - approval: 1.0.10
  - calendar: 3.3.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_automatedtagging: 1.14.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.0
  - groupfolders: 12.0.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.7.0-beta2
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - rainloop: 7.2.5
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.1
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_email: 2.4.0
  - twofactor_totp: 6.3.0
  - twofactor_webauthn: 0.3.1
  - updatenotification: 1.14.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "debug": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.deutsches-theater.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.deutsches-theater.de",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "proxy": "dtm-proxy:3128",
        "proxyexclude": [
            ".deutsches-theater.de",
            ".dtmuc.de"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "theme": "",
        "app_install_overwrite": [
            "calendar",
            "admin_notifications",
            "twofactor_rcdevsopenotp",
            "twofactor_yubikey",
            "twofactor_email",
            "rainloop",
            "twofactor_admin",
            "shifts"
        ],
        "mysql.utf8mb4": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "Mitarbeiter DT",
            "lokale_NC_user"
        ],
        "twofactor_enforced_excluded_groups": [],
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "DE"
    }
}
```

### Browser log

```Text
InstallTrigger is deprecated and will be removed in the future. constants.js:50:14
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:40:65
Failed to get subsystem status for purpose Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://b8f35181-48e2-4bae-91b4-2b02dcf1444f/content-utils.js:28
content-script.js:95:21
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. node.js:393
Unrecognized at-rule or error parsing at-rule ‘@-ms-viewport’. 29a3-55b6-server.css:1101:14
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. 29a3-55b6-server.css:1932:17
Ruleset ignored due to bad selector. 32d7-55b6-styles.css:247:58
Ruleset ignored due to bad selector. 32d7-55b6-styles.css:251:58
Ruleset ignored due to bad selector. 32d7-55b6-styles.css:254:58
Ruleset ignored due to bad selector. 593e-55b6-icons.css:302:1
No OC found index.js:46:4
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
JQMIGRATE: Migrate is installed, version 3.4.0 jquery-migrate.min.js:2:698
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. now:132:11
Unknown property ‘-moz-border-radius’.  Declaration dropped. now:136:22
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. now:146:11
Unknown property ‘-moz-border-radius’.  Declaration dropped. now:150:22
Unknown property ‘zoom’.  Declaration dropped. now:9:10
Expected declaration but found ‘*’.  Skipped to next declaration. now:10:5
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. now:55:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. now:71:13
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. now:137:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. now:204:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. now:309:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. now:321:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. now:585:13
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. now:15:10
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Loading theming data for notification bell styling App.vue:150
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Registering notifications container as a menu App.vue:160
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Notifications permissions granted App.vue:395
Polling interval updated to 30000 App.vue:355
Started background fetcher as session_keepalive is enabled App.vue:217
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Unknown property ‘speak’.  Declaration dropped. now:91:9
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. now:100:27
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘left’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. FreeBusy.vue:310:1
Error in parsing value for ‘top’.  Declaration dropped. EditSidebar.vue:398:1
Error in parsing value for ‘height’.  Declaration dropped. EditSidebar.vue:398:1
[INFO] calendar: 
Initial settings:
	- AppVersion: 3.3.0
	- EventLimit: true
	- FirstRun: false
	- ShowWeekNumbers: true
	- ShowTasks: false
	- ShowWeekends: true
	- SkipPopover: true
	- SlotDuration: 00:30:00
	- DefaultReminder: none
	- TalkEnabled: true
	- TasksEnabled: true
	- Timezone: automatic
	- HideEventExport: false
	- ForceEventAlarmType: false
 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6" }
ConsoleLogger.js:33:8
[DEBUG] @nextcloud/vue: Using version 2.2019c of the timezone database 
Object { uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", app: "@nextcloud/vue" }
ConsoleLogger.js:29:8
@nextcloud/calendar-js app is using version 2.2019c of the timezone database index.esm.js:14166:4
Fallback to locale en moment.js:85:3
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 16 globals.js:62:15
session heartbeat polling started session-heartbeat.js:103:9
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 172 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
[INFO] calendar: Updated moment locale: nextcloud-calendar-fake-locale-de-en 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6" }
ConsoleLogger.js:33:8
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 188 globals.js:62:15
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:29:8
Got notification data App.vue:318
Polling interval updated to 30000 App.vue:355
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 5 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 61 globals.js:62:15
[DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/0D09054F-D2CA-4F35-8EF4-74B155B69AA6/ 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6" }
ConsoleLogger.js:29:8
calendar home scanned 
Array(9) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…} ]
 
Array [ {…} ]
calendars.js:573:2
[DEBUG] calendar: calendars and trash bin loaded 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", calendars: (9) […], trashBin: {…} }
ConsoleLogger.js:29:8
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[DEBUG] calendar: Option render 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", option: {…} }
ConsoleLogger.js:29:8
[INFO] calendar: fetching suggestions for 0 attendees 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6" }
ConsoleLogger.js:33:8
[DEBUG] calendar: availability of room suggestions fetched 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", results: [] }
ConsoleLogger.js:29:8
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 520 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 globals.js:62:15
[INFO] calendar: fetching suggestions for 1 attendees 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6" }
ConsoleLogger.js:33:8
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
GEThttps://nextcloud.deutsches-theater.de/avatar/Michael Groh/64
[HTTP/2 404 Not Found 77ms]

GEThttps://nextcloud.deutsches-theater.de/avatar/Lucia Maxein/64
[HTTP/2 404 Not Found 112ms]

[DEBUG] calendar: availability of room suggestions fetched 
Object { app: "calendar", uid: "0D09054F-D2CA-4F35-8EF4-74B155B69AA6", results: [] }
ConsoleLogger.js:29:8
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
TypeError: i is undefined
    a main.js:5213
    a main.js:5216
    t main.js:5222
    fT main.js:5226
    processRawCalendarOptions main.js:7162
    _computeOptionsData main.js:7135
    Bh main.js:1009
    t main.js:6968
    e main.js:53
    mounted FullCalendar.js:21
    VueJS 19
    openFreeBusy InviteesList.vue:167
    VueJS 33
vue.runtime.esm.js:1897:4
TypeError: this.$el.querySelector(...) is null
    mounted FreeBusy.vue:269
    VueJS 19
    openFreeBusy InviteesList.vue:167
    VueJS 33
vue.runtime.esm.js:1897:4
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 172 globals.js:62:15
```

### Additional info

As always: Thank you for your work, and i will be happy to provide more information

**Comment by ChristophWurst** [comment] 2022-05-17 06:11
Duplicate of https://github.com/nextcloud/calendar/issues/4209

**Closed by ChristophWurst** 2022-05-17 06:11 UTC
Labels: bug, 0. to triage
