### ISSUE TITLE
Can't set start or end date on some specific language.

### ISSUE THREAD

**Issue by twTrueBlue** [nextcloud/calendar#547] opened 2017-07-25 08:30 UTC
### Steps to reproduce
1. Change Language to Chinese('zh_TW', 'zh_CN' or 'zh_HK')
2. Add event on calendar
3. Select start date or end date

### Expected behaviour
I can set date that before or after today.

### Actual behaviour
No matter what date I set, It will show and set today's date.

PHP version: PHP 7.0
Calendar version: 1.5.3
Updated from an older installed version or fresh install: fresh install
Signing status (ownCloud/Nextcloud 9.0 and above): Nextcloud 12.0.0
Browser: Chrome

### Browser log
a) The javascript console log:
```
core.js?v=9c0971a414feae6884dc8d82857e82a9-30:1563
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
```

**Comment by georgehrke** [comment] 2018-02-11 01:03
Duplicate of #534

**Closed by georgehrke** 2018-02-11 01:03 UTC
Labels: 1 - to develop, bug, unconfirmed
