### ISSUE TITLE
NC28 events of newly subscribed public calendars are not shown

### ISSUE THREAD

**Issue by escoand** [nextcloud/calendar#5629] opened 2023-12-14 09:02 UTC
### Steps to reproduce

1. add new external calendar (in my case https://www.feiertage-deutschland.de/kalender-download/ics/schulferien-sachsen.ics)
2. the calendar is added but no events appear, without any error

Import of the same ICS file is working without problems.

### Expected behavior

events appear as with NC27

### Actual behaviour

no events appear

### Calendar app version

4.6.0

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

28.0.0.11

### Updated from an older installed version or fresh install

None

**Comment by escoand** [comment] 2023-12-14 09:11
Maybe a duplicate of #5628

**Comment by c86-moe** [comment] 2023-12-14 10:55
I think it is not a duplicate.

#5628 is about events in subscribed calendars not showing in the *dashboard widget*, and this is about events not showing up in the *main calendar app*.

**Comment by miaulalala** [comment] 2023-12-14 11:32
Duplicate of https://github.com/nextcloud/server/issues/42143

We tracked it down to a change in the upstream lib.

**Closed by miaulalala** 2023-12-14 11:32 UTC
Labels: bug, 0 - to triage
