### ISSUE TITLE
Week and day view strechted too much

### ISSUE THREAD

**Issue by itmuecke** [nextcloud/calendar#1983] opened 2020-02-11 08:11 UTC
**Is your feature request related to a problem? Please describe.**
After upgradibg to nextcloud 18.0.0 the calendar view day and week are too strechted. You always have to scroll, to the the whole day. Before upgrade the day was visible at once and without scrolling.

**Describe the solution you'd like**
Compress the day and week view to hours instead of half hours.

**Describe alternatives you've considered**
Offer the possibility to change the view in "big" and "compact" mode or smth like this

**Comment by tcitworld** [comment] 2020-02-11 08:46
Duplicate of #1747. 

I think we better revert to the old behavior since there's so many negative feedback. See https://github.com/nextcloud/calendar/issues/577#issuecomment-578089725 if you want to do it manually until then.

**Closed by tcitworld** 2020-02-11 08:46 UTC
Labels: 0. to triage, enhancement-proposed
