### ISSUE TITLE
[feature request] : auto detect hour in event title

### ISSUE THREAD

**Issue by tykayn** [nextcloud/calendar#974] opened 2018-11-29 09:43 UTC
currently not featured in calendar: 
the ability to detect an hour to auto fill the event data.

scenario: if i type these
10:15 do the meeting
or
15h get the packages

the event would be auto filled on the blur of the title input.
the regex to capture the hour and minute data would check only the begining of the string, and would be something like this:
^\d\d?[\:|h]\d?\d?
then the found matches would be maxed to 24for hours and 59 for minutes and filled to the form.

this is one nice feature from google calendar i would love to find again in nextcloud calendar, what do you think ?

**Comment by georgehrke** [comment] 2018-11-29 09:44
Duplicate of https://github.com/nextcloud/calendar/issues/17

**Closed by georgehrke** 2018-11-29 09:44 UTC
