### ISSUE TITLE
[Question / Feature Request] Invite all members of a contact group / user group

### ISSUE THREAD

**Issue by pwFoo** [nextcloud/calendar#1361] opened 2019-07-20 08:43 UTC
Installed contacts and calendar apps. Created NC users / groups and added contact with groups.
Now I tried to invite a group of NC users or contact group. 

Groups not autocompleted / recognized and should be add all members of the group to the list of participants.

Is it a configuration problem or not implemented (yet)?

**Comment by georgehrke** [comment] 2019-07-20 08:53
Duplicate of https://github.com/nextcloud/calendar/issues/167

**Comment by georgehrke** [comment] 2019-07-20 08:54
Please search for existing issues before creating new ones!

**Closed by georgehrke** 2019-07-20 08:53 UTC
