### ISSUE TITLE
Timezone picker behind event modal

### ISSUE THREAD

**Issue by Nitrowolf** [nextcloud/calendar#5800] opened 2024-02-27 18:33 UTC
### Steps to reproduce

1. Create New Event
2. Select a Timezone

### Expected behavior

See all available time zones in the picker

### Actual behaviour

![image](https://github.com/nextcloud/calendar/assets/237610/54d59ac4-9c06-45eb-b31c-0a93536ab1e4)

### Calendar app version

4.6.5

### Browser

Firefox 122.0.1

### Client operating system

Windows 11

### Server operating system

Nextcloud Docker under Unraid

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text
Enabled:
  - activity: 2.20.0
  - calendar: 4.6.5
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.2
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - fulltextsearch: 28.0.0
  - integration_google: 2.1.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.16.0)
  - files_external: 1.20.0
  - recommendations: 2.0.0 (installed 0.4.0)
  - suspicious_login: 6.0.0
  - updatenotification: 1.18.0 (installed 1.17.0)
  - user_ldap: 1.19.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.123.15:9443",
            "nextcloud.pixelrover.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.pixelrover.com",
        "overwritehost": "nextcloud.pixelrover.com",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "twofactor_yubikey",
            "fbsync"
        ],
        "has_rebuilt_cache": true,
        "mysql.utf8mb4": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "default_phone_region": "us",
        "session_lifetime": 86400,
        "upgrade.disable-web": true
    }
}
```

### Additional info

This was supposedly fixed by https://github.com/nextcloud-libraries/nextcloud-vue/pull/4014 ... but it's clearly not been fixed or it's regressed.

**Comment by miaulalala** [comment] 2024-02-28 09:35
Duplicate of https://github.com/nextcloud/calendar/issues/5606

Please check existing issues before opening a new one

**Closed by miaulalala** 2024-02-28 09:35 UTC
Labels: bug
