### ISSUE TITLE
Truncated appointment titles in the extended editor

### ISSUE THREAD

**Issue by nrgeen** [nextcloud/calendar#5608] opened 2023-12-05 13:30 UTC
### Is your feature request related to a problem? Please describe.

In the extended appointment editor, long appointment titles are cut off. In the simple appointment editor, the entire appointment title is displayed by supporting multiple lines.

### Describe the solution you'd like

Functionally, it would be good if you could also see the full appointment title in the extended editor.

**Comment by Findus23** [comment] 2024-04-19 12:55
I think this is the same issue as #4210

**Comment by miaulalala** [comment] 2024-04-19 15:07
Duplicate of https://github.com/nextcloud/calendar/issues/4210

**Closed by miaulalala** 2024-04-19 15:07 UTC
Labels: enhancement, 0. to triage
