### ISSUE TITLE
End-To-End Encryption

### ISSUE THREAD

**Issue by trymeouteh** [nextcloud/calendar#2045] opened 2020-02-29 02:25 UTC
Please add the ability to have client side encryption with Nextcloud calendars. This will require Nextcloud making a Nextcloud calendar app for Android, iOS, Windows, Mac and Linux or having the Nextcloud clients add a calendar syncing integration into the app.

EteSync is the king of privacy and security for calendars since they have E2EE. I would like to see Nextcloud add this security and even allow the ability to edit the calendar in the browser using JavaScript to encrypt/decrypt the client side encryption. And I would like calendar sharing to still be possible within the same domain and to be federated.

**Comment by georgehrke** [comment] 2020-02-29 09:00
Duplicate of https://github.com/nextcloud/server/issues/5927

**Closed by georgehrke** 2020-02-29 09:00 UTC
Labels: 0. to triage, enhancement-proposed
