### ISSUE TITLE
Calendar update (to 3.0.4) resulted in endless loading of calendars

### ISSUE THREAD

**Issue by McGee23** [nextcloud/calendar#3858] opened 2021-12-30 16:13 UTC
Since I was involved at a later time when the problem already existed, I can't give the steps to reproduce for sure. It was told to me, that before the update to 3.0.4 of the calendar app, everything worked fine, but after the update, the calendar of one user didn't load anymore.
I verified, that with some users the calendar app just worked fine, but using one particular user resulted in endless loading of the calendar app. There was no freezing and one could change to any other app, but the calendar was not loaded and no calendar specific options (add event, ...) could be performed.

After duplicating the cloud to have a playground I managed to track down the issue:
In the mySQL DB in table 'oc_properties' there were the following entries (shortened and anonymized):

`MariaDB [nextcloud]> SELECT * FROM oc_properties;`

> +----+---------+-------------------------------------------------------+------------------------------------------+---------------+
> | id | userid  | propertypath                                          | propertyname                             | propertyvalue |
> +----+---------+-------------------------------------------------------+------------------------------------------+---------------+
> |  7 | user01  | calendars/user01/user02                               | {http://owncloud.org/ns}calendar-enabled | 1             |
> | 10 | user02  | calendars/user02/personal                             | {http://owncloud.org/ns}calendar-enabled | 1             |
> | 11 | user01  | calendars/user01/personal_shared_by_user02            | {http://owncloud.org/ns}calendar-enabled | 1             |
> | 12 | user01  | calendars/user01/personal_shared_by_user02            | {DAV:}resourcetype                       | Object        |

The last line was the problem. Deleting the line with
`MariaDB [nextcloud]> DELETE FROM oc_properties where id=12;`
solved the problem.

### Calendar app
3.0.4

### Client configuration
not relevant

### Server configuration
**Operating system**: Ubuntu 20.04.3 LTS
**Web server:** Apache/2.4.41
**Database:** mariadb  Ver 15.1
**PHP version:** 8.0.14
**Nextcloud Version:** 23.0.0
**Updated from an older installed version or fresh install:** Updated

HTH, if anyone encounters the same issue.

**Comment by ChristophWurst** [comment] 2021-12-30 16:38
What version were you on before?

**Comment by McGee23** [comment] 2021-12-31 10:19
As far as I could find out (I was involved on 29th of December, 8 days after bespoken user01 noticed the misbehaviour):
* The person, who usually takes care of that nextcloud, performed updates on November 16 (NC 22.2.2.0 to 22.2.3.0) and November 30 (NC 22.2.3.0 to 23.0.0.10) as well as various reinstalls of the calendar app from December 27 to December 29. Sadly, I didn't find the calendar app versions in the logs.
* Checking the logs again and now knowing, that the error was first reported on 21th of December, I found an interesting log entry (see below).

> {"reqId":"rnC1LUEofuD0KW3M9dVC","level":3,"time":"2021-12-21T10:25:43+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"user01","app":"PHP","method":"PROPPATCH","url":"/remote.php/dav/calendars/user01/personal_shared_by_user02/","message":"Object of class Sabre\\DAV\\Xml\\Property\\ResourceType could not be converted to string at /var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php#92","userAgent":"iOS/15.1.1 (19B81) dataaccessd/1.0","version":"23.0.0.10","exception":{"Exception":"Error","Message":"Object of class Sabre\\DAV\\Xml\\Property\\ResourceType could not be converted to string at /var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php#92","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[4096,"Object of class Sabre\\DAV\\Xml\\Property\\ResourceType could not be converted to string","/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",92,{"params":["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}]}]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":92,"function":"execute","class":"PDOStatement","type":"->","args":[["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}]]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1165,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}]]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":267,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->","args":["INSERT INTO `oc_properties` (`userid`,`propertypath`,`propertyname`,`propertyvalue`) VALUES(?,?,?,?)",["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}],[]]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1799,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->","args":["INSERT INTO `oc_properties` (`userid`,`propertypath`,`propertyname`,`propertyvalue`) VALUES(?,?,?,?)",["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}],[]]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":246,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["INSERT INTO `oc_properties` (`userid`,`propertypath`,`propertyname`,`propertyvalue`) VALUES(?,?,?,?)",["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}],[]]},{"file":"/var/www/html/nextcloud/lib/private/DB/ConnectionAdapter.php","line":75,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["INSERT INTO `oc_properties` (`userid`,`propertypath`,`propertyname`,`propertyvalue`) VALUES(?,?,?,?)",["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}],[]]},{"file":"/var/www/html/nextcloud/apps/dav/lib/DAV/CustomPropertiesBackend.php","line":312,"function":"executeUpdate","class":"OC\\DB\\ConnectionAdapter","type":"->","args":["INSERT INTO `*PREFIX*properties` (`userid`,`propertypath`,`propertyname`,`propertyvalue`) VALUES(?,?,?,?)",["dbuser","*** sensitive parameter replaced ***","{DAV:}resourcetype",{"__class__":"Sabre\\DAV\\Xml\\Property\\ResourceType"}]]},{"file":"/var/www/html/nextcloud/apps/dav/lib/DAV/CustomPropertiesBackend.php","line":164,"function":"updateProperties","class":"OCA\\DAV\\DAV\\CustomPropertiesBackend","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/PropPatch.php","line":288,"function":"OCA\\DAV\\DAV\\{closure}","class":"OCA\\DAV\\DAV\\CustomPropertiesBackend","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/PropPatch.php","line":227,"function":"doCallBackMultiProp","class":"Sabre\\DAV\\PropPatch","type":"->","args":[["{DAV:}resourcetype"],{"__class__":"Closure"}]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1263,"function":"commit","class":"Sabre\\DAV\\PropPatch","type":"->","args":[]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":373,"function":"updateProperties","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropPatch","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PROPPATCH",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/nextcloud/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/nextcloud/remote.php","line":166,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61cec44f02f30"}

**Comment by ChristophWurst** [comment] 2021-12-31 13:11
You can get the app version from a db snapshot. It's in oc_appconfig

**Comment by McGee23** [comment] 2022-01-01 21:23
Hi Christoph, I'm currently not able to access that server, but I will try to give that information, as soon as possible (probably around the 7th of January).
Before learning when exactly the issue was observed for the first time and consequently finding the log entry, I was almost sure, that it was an issue resulting from an update (like "the older version had entries, that are not compatible with the new version anymore"). Now I'm not too sure anymore, but I'll come back to you with the information as soon as I have checked the entries in oc_appconfig.

**Comment by JB1985** [comment] 2022-01-05 08:45
Seems to be the same bug as here.

https://github.com/nextcloud/calendar/issues/3551

**Comment by McGee23** [comment] 2022-01-05 17:31
Hi Christoph, as far as I see in the backups, the calendar app version was 3.0.0 on 30th of November, when the update from NC 22.2.3 to 23.0.0 was performed.

**Comment by McGee23** [comment] 2022-01-05 17:35
@JB1985, yes, I think, that's correct. Sorry, I didn't find that issue. Maybe the threads can be merged?

**Comment by miaulalala** [comment] 2022-01-19 10:57
Duplicate of #3551

**Closed** 2022-01-19 10:58 UTC
Labels: bug, 0. to triage
