### ISSUE TITLE
Invitations of Microsoft Outlook won't display

### ISSUE THREAD

**Issue by unnamed15** [nextcloud/calendar#1419] opened 2019-08-26 15:39 UTC
### Steps to reproduce
1. Create an event in your MS Exchange calendar
2. Add an attendee 
3. Open nextcloud 
4. Open nextcloud calendar
5. The e-mail is shown, but without an attachment of the Event. 

### Expected behaviour
- Get an overview of the event where you can slect 
-> Confirm the Event
-> Dismiss the Event

==> Automatical entry in my nextcloud calendar

### Actual behaviour
There is only an empty E-Mail without the Event details . 

## Server configuration detail

**Operating system:** Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 10.1.38

**PHP version:** 

7.3.8
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - deck: 0.6.6
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.2
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.mg-sky.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpauthtype": "LOGIN",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** -> NO

**Are you using encryption:** -> NO

**Are you using an external user-backend, if yes which one: -> NO

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Operating system:** Windows 10

**Comment by georgehrke** [comment] 2019-08-29 15:22
> 4. Open nextcloud calendar
> 5. The e-mail is shown, but without an attachment of the Event.

I'm not really able to follow your reproduction steps. What email are you talking about and how do you view it?

**Comment by georgehrke** [comment] 2019-09-13 14:51
Closing because original reporter never answered to questions.

**Closed by georgehrke** 2019-09-13 14:51 UTC
Labels: needs info

**Comment by stylefieber** [comment] 2020-11-05 10:16
Hey, I have the same issue and I think I know what he meant.

He was talking about the invitation email from the Outlook calendar. He opens it in the nextcloud mail app an this mail is empty. You cannot click any button or any file which should be attached to the mail. Just an empty mail.

**Comment by tcitworld** [comment] 2020-11-21 11:30
@stylefieber In that case please open an issue in the mail app repository
