### ISSUE TITLE
Participants group's

### ISSUE THREAD

**Issue by flozi00** [nextcloud/calendar#2004] opened 2020-02-18 13:01 UTC
Is it possible to add participants by group as same as sharing calendars ?
By sharing calendars without write permission, the others don't get the reminders.
If I add them as participants, they get the reminders but I have to invite everyone single

**Comment by georgehrke** [comment] 2020-02-18 13:02
Duplicate of https://github.com/nextcloud/calendar/issues/167

**Closed by georgehrke** 2020-02-18 13:02 UTC
Labels: 0. to triage, enhancement-proposed
