### ISSUE TITLE
Cannot Rename and share subscrptions

### ISSUE THREAD

**Issue by chris4795** [nextcloud/calendar#582] opened 2017-09-01 16:03 UTC
I am unable to rename and share added subscriptions Viz CalDav

### Steps to reproduce
1. Add This Link "https://www.opm.gov/about-us/open-government/Data/Apps/Holidays/holidays.ical"
2.  (For renaming) Try to Rename it
3. (For Sharing) Share the calendar via CalDav and an app password

### Expected behaviour
I would like to rename "https://www.opm.gov/about-us/open-government/Data/Apps/Holidays/holidays.ical" to "US Public Holidays" (or something similar, since it is a holiday list). I would also like this show show up in my CalDav, so I do not have to manually add it to every device that I share my CalDav with (Such as Android devices)

### Actual behaviour
There is no way to rename the subscription. The subscription does not share when it is shared via CalDav

**Operating system**:
Debian Jessie
**Web server:**
Apache
**Server version:** (see your admin page)
12.0.1
**Calendar version:** (see the apps page)
1.5.3

**Comment by georgehrke** [comment] 2017-09-01 16:14
Renaming works like expected and survives reload:

![kapture 2017-09-01 at 18 09 25](https://user-images.githubusercontent.com/1250540/29978364-335b00e4-8f41-11e7-8940-feee0c4c5d28.gif)

Not being available via CalDAV is a duplicate of https://github.com/nextcloud/server/issues/1497

**Closed by georgehrke** 2017-09-01 16:14 UTC

**Comment by chris4795** [comment] 2017-09-01 16:18
I feel silly for not trying that. Thank you!

If I may make a suggestion, would it make sense to make it more obvious, like another textbox saying "Rename" or some sort?

**Comment by georgehrke** [comment] 2017-09-01 16:38
Maybe we can make it more intuitive by not using the URL as a fallback.

(The webcal feed you posted didn't contain a name in its ics data. If it did, the calendar would have used this name. As a fallback, it uses the URL).

Possible options for naming would be:
1. opm.gov calendar
2. holidays.ical

What do you think?

**Comment by chris4795** [comment] 2017-09-01 16:48
I think that's a great Idea! You could also put "Unnamed Calendar" as a fallback as well, I think that would make it obvious as well.

**Comment by georgehrke** [comment] 2017-09-05 11:09
I created a dedicated issue about the fallback: https://github.com/nextcloud/calendar/issues/585
