### ISSUE TITLE
Subscribe external calendar into nc-exististing one

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/calendar#1955] opened 2020-02-02 23:39 UTC
**Is your feature request related to a problem? Please describe.**
I regulary get new external events and I want to share these with specific teams. I don't want to import .ics files to the existing - and shared - calendar cause this is a manual thing to do and I'm gonna have a lot of different person groups/calendars.

**Describe the solution you'd like**
Instead I just want to subscribe that external calendar and get every event subscribed into existing nc calendar which is shared with a team.

So what is this all about: Creating events in wordpress/civicrm, syncing these automatically to the existing nextcloud calendars which are shared with specific groups/users. So if my ppl got that nextcloud app installed on their smartphones they get the information about our meetings without additional configuration on their side.

**Describe alternatives you've considered**
Possibility to just share a subscrubed calendar, but this isn't as good as my preferred alternate, cuz it is creating a lot of overhead of calendars, as we still need calendars for groups with write access within nextcloud.

**Comment by georgehrke** [comment] 2020-02-16 18:21
Duplicate of https://github.com/nextcloud/server/issues/1600

**Closed by georgehrke** 2020-02-16 18:21 UTC
Labels: 0. to triage, enhancement-proposed
