### ISSUE TITLE
search result should be ordered

### ISSUE THREAD

**Issue by MacsKavana** [nextcloud/calendar#5494] opened 2023-09-27 08:35 UTC
### Is your feature request related to a problem? Please describe.

There is no related problem.

### Describe the solution you'd like

The search results in the calendar should start with the current day and should show the future events in an ascending ordered mode.

Currently it shows random events from the past and the future in an unordered list.

**Comment by tcitworld** [comment] 2023-09-28 08:04
Duplicate of https://github.com/nextcloud/server/issues/27353

**Closed by tcitworld** 2023-09-28 08:04 UTC
Labels: enhancement, 0 - to triage
