### ISSUE TITLE
Use Other color for weekend and "not working hours" in weekly and daily calendar view

### ISSUE THREAD

**Issue by MarkusKepert** [nextcloud/calendar#4303] opened 2022-06-20 15:31 UTC
### Is your feature request related to a problem? Please describe.

In weekly calendar  view it is sometimes not easy to handly appointments around the start of working day or the end of business hours/stores closing time.

What can help: Use a slightly other base color for times outside the "normal" business times to have a visual separation of those slots. Currently everything is white.

### Describe the solution you'd like

Timeslots in daily and weekly calender view are colored with a very light grey, when:

- time is between 0:00 and 08:00am and 6:00pm - 0:00 for monday - friday
- Day is saturday or sunday (whole day)

**Comment by Zoldiru** [comment] 2022-07-11 13:43
If I can add something about this feature request, it would also be nice to have the possibility to show only working hours (defined in some sort of settings like the availability is). It would optimize the view space in the week view.

**Comment by ChristophWurst** [comment] 2022-07-11 14:06
Duplicate of https://github.com/nextcloud/calendar/issues/3570

**Closed by ChristophWurst** 2022-07-11 14:06 UTC
Labels: enhancement, 0. to triage
