### ISSUE TITLE
Layout problem in chrome

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/calendar#2863] opened 2021-02-04 13:24 UTC
Hi! Noticed, that in Google Chrome 87.0.4280.88
When you're creating new event, the pop-up appears under the button and hover list of calendars. 
But in firefox, this pop-up appears in the center-top of screen. 

Example Chrome: 
![gscreenshot_2021-02-04-135525](https://user-images.githubusercontent.com/26598203/106895566-acaaf000-66f0-11eb-9d5b-7272e34dead4.png)

And Firefox:
![изображение](https://user-images.githubusercontent.com/26598203/106895801-f8f63000-66f0-11eb-80be-0b3571fb1410.png)

### Steps to reproduce
1. Nextcloud from docker 19.0.4
2. Calendar ver. 2.0.4
3. Enable calendar and go to create new event

### Expected behaviour
Popup window in center-top

### Actual behaviour
Pop-up window directly under "New event button"

### Calendar app
2.0.4

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
Google Chrome 87.0.4280.88

**Operating system:** Arch Linux :)

### Server configuration

**Operating system:**
Debian 10 Buster

**Web server:**
nginx/1.19.1

**Database:**
Percona xtradb-cluster 5.7.19

**PHP version:**
PHP 7.3.20

**Nextcloud version:** (see Nextcloud admin page)
19.0.1-fpm

**Updated from an older Nextcloud/ownCloud or fresh install:**
Rolling updates from 16 

**Where did you install Nextcloud from:**
 Docker image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No messages
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - analytics: 2.5.0
  - apporder: 0.11.0
  - bookmarks: 3.4.3
  - calendar: 2.0.4
  - camerarawpreviews: 0.7.8
  - checksum: 0.4.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - cookbook: 0.7.6
  - dashboardcharts: 0.1.3
  - dav: 1.15.0
  - deck: 1.1.2
  - dicomviewer: 1.2.2
  - encryption: 2.7.0
  - external: 3.6.0
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.1
  - files_automatedtagging: 1.9.0
  - files_downloadactivity: 1.8.0
  - files_external: 1.10.0
  - files_markdown: 2.3.1
  - files_mindmap: 0.0.23
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.0.4
  - gpxedit: 0.0.13
  - gpxmotion: 0.0.11
  - gpxpod: 4.2.2
  - groupfolders: 7.1.0
  - groupquota: 0.1.4
  - keeweb: 0.6.3
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - music: 0.16.0
  - news: 14.2.2
  - notes: 3.6.4
  - oauth2: 1.7.0
  - ocr: 6.0.56
  - onlyoffice: 6.0.2
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quicknotes: 0.6.1
  - quota_warning: 1.8.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sociallogin: 3.4.1
  - socialsharing_email: 2.1.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.4
  - text: 3.0.1
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - appointments
  - nextcloud_announcements
  - notifications
  - phonetrack
  - theming
  - theming_customcss
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "theme": "mytheme",
        "blacklisted_files": [],
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 25,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/dev\/stdout",
        "enable_previews": true,
        "preview_max_filesize_image": 4096,
        "preview_max_y": 4096,
        "preview_max_x": 4096,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Photoshop"
        ],
        "logtimezone": "Europe\/Prague",
        "social_login_auto_redirect": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "objectstore_multibucket": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "num_buckets": 15000,
                "bucket": "nextcloud-",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "use_ssl": true,
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": 443,
                "use_path_style": true
            }
        },
        "onlyoffice": {
            "jwt_header": "Authorization",
            "verify_peer_off": true
        },
        "loglevel": 3,
        "trusted_domains": [
            "nc.domain.org",
            "localhost",
            "10.*.*.*",
            "onlyoffice.domain.org",
            "nc-api.domain.org",
            "*cluster.local"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "https:\/\/nc.domain.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Minio S3 as default backend

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Keyclak and Social login app in NC

#### Web server error log (e.g. /var/log/apache)
```
Nothing related to calendar
```

#### Log file (data/nextcloud.log)
```
Nothing related to calendar
```

#### Browser log
![gscreenshot_2021-02-04-142317](https://user-images.githubusercontent.com/26598203/106898483-8a1ad600-66f4-11eb-84cd-804bd8cc6550.png)

**Comment by szaimen** [comment] 2021-09-30 01:04
Doea rhis still happen?

**Comment by krakazyabra** [comment] 2021-09-30 11:29
@szaimen I don't know, because I stopped using calendar since 4th Feb, because there was no answer to this issue. 
It's better to close the issue, than fix it, isn't it? ;-)

**Comment by szaimen** [comment] 2021-09-30 11:31
I was asking because I think this was fixed in the meantime and I wanted you to confirm it.

**Comment by krakazyabra** [comment] 2021-09-30 11:32
![image](https://user-images.githubusercontent.com/26598203/135447369-e75d8e9d-248e-4306-8fae-f61ab335e8d2.png)
I've just checked on Chrome 93.0.4577.82
Still actual. Let's abandon it for the next half-year?

**Comment by szaimen** [comment] 2021-09-30 11:58
Please don't be so negative!

I tried to reproduce this but I cannot on Win10, Chrome 94.0.4606.61, NC21.0.4 with Calendar 2.3.4.
Do you have this Calendar version installed on your Nextcloud? If not, could you try to update to Calendar 2.3.4?
And do you have some extensions installed  in Chrome? If yes, could you try to disable them to see if this fixes the problem?

Thanks!

**Comment by krakazyabra** [comment] 2021-09-30 12:06
I'm not negative, such reaction, because 90% of my issues were closed by you without any try to reproduce or take a look from team side. 
My screenshot is from private mode, no extensions, calendar ver. 2.3.4

**Comment by ChristophWurst** [comment] 2021-09-30 12:44
> I'm not negative, such reaction, because 90% of my issues were closed by you without any try to reproduce

https://github.com/nextcloud/calendar/issues/created_by/krakazyabra 0%

In any case, even if it was not meant in a negative way sarcasm doesn't work well in online comments.

We try our best to fix problems. Since we get a lot of reports we prioritize by the impact of reports. And even if we don't comment it doesn't mean we don't read or try to reproduce. Our time just doesn't allow us to spend 15m on each and every report. I hope this is somewhat understandable :v:

**Comment by krakazyabra** [comment] 2021-09-30 13:19
https://github.com/nextcloud/server/issues/created_by/krakazyabra @ChristophWurst 

I try to provide as max info as possible, also we are trying to fix it, and when we are not success with fixing, I'm openning issue. This is only my cases, I understand, that you have millions of them each day. 

@szaimen I will try to restart redis and make repair at night, because this problem is only on production server. On staging and with ghcr.io/szaimen/nextcloud-easy-test it looks fine.

**Comment by szaimen** [comment] 2021-09-30 13:21
> @szaimen I will try to restart redis and make repair at night, because this problem is only on production server. On staging and with ghcr.io/szaimen/nextcloud-easy-test it looks fine.

👍

**Comment by szaimen** [comment] 2021-12-13 20:54
Any update here?

**Closed** 2022-01-03 21:48 UTC
Labels: bug, needs info, 0. to triage
