### ISSUE TITLE
[New Feature Request]

### ISSUE THREAD

**Issue by fernandoc2021** [nextcloud/calendar#952] opened 2018-11-23 21:29 UTC
Will be possible to set the start and ending hours of the working days? I understand that this may cause some problems when working on different time zones but in those cases it will trigger a warning about it so it will be more import for the local calendar user!
Hope it can be done, because having to see the whole window from 0 to 23 makes it hard to see.
Thanks!

**Comment by georgehrke** [comment] 2018-11-23 21:30
Duplicate of https://github.com/nextcloud/calendar/issues/577

**Closed by georgehrke** 2018-11-23 21:30 UTC
