### ISSUE TITLE
[feature request] detect time in calendar event creation

### ISSUE THREAD

**Issue by tykayn** [nextcloud/calendar#853] opened 2018-06-25 18:00 UTC
if the event creation could detect hours and minutes in the text, that would be great.
when creating an event with for example "13h30 do something" or "13h stuff happens" or "13:30 stuf stuff", auto detect the time.

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Server version:** (see your admin page)

**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:**

**Signing status (ownCloud/Nextcloud 9.0 and above):**

**Comment by georgehrke** [comment] 2018-06-27 06:42
Duplicate of https://github.com/nextcloud/calendar/issues/17

**Closed by georgehrke** 2018-06-27 06:42 UTC
