### ISSUE TITLE
When event creator email contains a +, e-mail are not being sent

### ISSUE THREAD

**Issue by NewRedsquare** [nextcloud/calendar#2149] opened 2020-04-04 19:50 UTC
### Steps to reproduce
1. Create an event on a calendar ( for my case not shared, it's "mine")
2. Add an email adress to the persons list
3. Click on save or update

### Expected behaviour
Tell us what should happen
I expected the other person to receive the mail
### Actual behaviour
Tell us what happens instead
Even after checking the spam list or waiting an hour, nothing is being received

The test e-mail has been successfully received and when i create an e-mail for a file sharing (sharebymail: 1.8.0) , i received it in a very short time. The e-mail sending itself is working excepting for calendar. 
### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.2
**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
Thunderbird Lightning, DAVx5, Calendar app

### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 74.0.1
**Operating system:** (e.g. Arch Linux)
Windows 10 pro
### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.04
**Web server:** (e.g. Apache, Nginx,...)
Nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0.3)
7.4.4
**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.3
**Updated from an older installed version or fresh install:**
18.0.1
**List of activated apps:**

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.9.0
  - browser_warning: 0.2.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.2
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - event_update_notification: 1.0.1
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.2
  - files_downloadactivity: 1.7.0
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trackdownloads: 1.7.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - guests: 1.4.3
  - issuetemplate: 0.6.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - music: 0.13.2
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 6.0.28
  - ocsms: 2.1.7
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - phonetrack: 0.6.2
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - sharelisting: 0.3.0
  - sharingpath: 0.2.0
  - socialsharing_email: 2.0.0
  - socialsharing_twitter: 2.0.0
  - spreed: 8.0.7
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - talk_simple_poll: 1.1.0
  - tasks: 0.12.1
  - telephoneprovider: 1.0.3
  - theming: 1.9.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_email: 1.0.1
  - twofactor_gateway: 0.15.1
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - video_converter: 0.1.3
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - analytics
  - announcementcenter
  - breezedark
  - camerarawpreviews
  - cms_pico
  - data_request
  - drawio
  - encryption
  - external
  - files_antivirus
  - files_fulltextsearch
  - files_linkeditor
  - flowupload
  - forms
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - jsloader
  - keeweb
  - mail
  - maps
  - occweb
  - ocdownloader
  - ransomware_protection
  - recommendations
  - registration
  - scanner
  - shorten
  - text
  - theming_customcss
  - uploaddetails
  - user_ldap
  - workflow_scripter
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": true,
        "trusted_domains": [
            "****",
            "****"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "0": {
            "verify_peer_off": false
        },
        "version": "18.0.3.0",
        "overwrite.cli.url": "https:\/\/****",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "onlyoffice": "",
        "installed": true,
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "app_install_overwrite": [
            "limit_login_to_ip",
            "onlyoffice",
            "shorten",
            "keeweb",
            "forms",
            "ocsms",
            "twofactor_email",
            "checksum",
            "contacts",
            "sharerenamer",
            "socialsharing_email",
            "uploaddetails",
            "socialsharing_twitter",
            "sharingpath",
            "jsloader"
        ],
        "maintenance": false,
        "twofactor_enforced": "true",
        "has_internet_connection": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}
```

#### Web server error log (e.g. /var/log/apache)
```
Nothing which concerns this issue
```

#### Log file (data/nextcloud.log)
```
Nothing which concerns this issue
```

**Comment by tcitworld** [comment] 2020-04-04 20:58
Inside the Groupware settings (`/settings/admin/groupware`), is the "Send invitations to attendees" setting activated ?

**Comment by NewRedsquare** [comment] 2020-04-04 21:00
Everything is activated ( the 4 boxes )

**Comment by NewRedsquare** [comment] 2020-04-04 21:12
mmmh that's very strange, i had to enable/disable those options like 3 times to get emails working ( for some emails not all ), i'll check this the next days, don't close this please, this could be still an issue

**Comment by NewRedsquare** [comment] 2020-04-05 08:55
First update : it seems like i had to remove the events prior enabling/disabling 3 times, then recreating events to get emails working.

**Comment by georgehrke** [comment] 2020-04-05 09:46
Were those events in the past or the future?
We don’t send out invitations for events in the past

**Comment by NewRedsquare** [comment] 2020-04-05 09:55
Those events are in the future ( the 9th april)

**Comment by georgehrke** [comment] 2020-04-05 16:04
Can you please double check the Sent folder of the email account you configured to send emails for your Nextcloud, to check that there are really no invitation emails in there.

**Comment by NewRedsquare** [comment] 2020-04-05 16:43
Sadly, I can't tell you as the mail sent via SMTP are not shown in the sent folder ( my mail UI is Zimbra )

**Comment by tcitworld** [comment] 2020-04-05 17:22
> Can you please double check the Sent folder of the email account you configured to send emails for your Nextcloud, to check that there are really no invitation emails in there.

I don't think SMTP saves a copy of sent emails in the `Sent` folder anyway, that's only some clients doing it with IMAP. SMTP logs would be quite handy though.

**Comment by NewRedsquare** [comment] 2020-04-05 18:18
> 
> 
> > Can you please double check the Sent folder of the email account you configured to send emails for your Nextcloud, to check that there are really no invitation emails in there.
> 
> I don't think SMTP saves a copy of sent emails in the `Sent` folder anyway, that's only some clients doing it through IMAP. SMTP logs would be quite handy though.

If i don't self-host the mail server, how can i achieve it ?

**Comment by dirigit** [comment] 2020-04-16 07:44
(B)CC + filter at inbound to move the mail

**Comment by ASTIN-UA** [comment] 2020-05-08 11:08
HI all. Have same problem. No E-mail form Calendar only. Same use ZIMBRA. 
I'm use NC 18.0.4 and Calendar 2.0.3 on Ubuntu Server 20.04.
E-mail from any other apps work stable. Have any idea?

**Comment by einalex** [comment] 2020-05-08 11:40
go to `apps/mail/vendor/christophwurst/kitinerary-bin/bin/` and make sure the `kitinerary-extractor` file is executable. that fixed it for me.

**Comment by georgehrke** [comment] 2020-05-08 11:42
@einalex Are you absolutely sure about that? I don't see how the itinerary Feature of the mail app would interfere with the mailing system of Nextcloud. The mailing system of Nextcloud has nothing to do with the mail app.

**Comment by einalex** [comment] 2020-05-08 11:50
oh no you're right. I was fixing two issues at the same time and got the solutions confused. I'll adjust my initial comment.

**Comment by Supergamerx3000** [comment] 2020-06-23 09:12
I also have a problem sending the invitation email. If I create an appointment and add a participant and then click on save / update, it loads in a continuous loop and the appointment is not saved. The email server is configured correctly and the test mail goes out. My Nextcloud version is 19.0.0 and the error was already in 18. In the 17 version, the email is sent. My PHP version is 7.4 the calendar APP is up to date. Unfortunately, the logs do not show anything when I perform this action.

**Comment by iprok** [comment] 2020-07-21 08:40
I also have the same problem. I'm admin of the nextcloud server and of the email server used. I've tried to set\unset options in /settings/admin/groupware without any success. When creating attendees I just see no action in servers logs (both nextcloud and mail server). So seems that nextcloud doesn't try to send the mail at all.

**Comment by ClemPera** [comment] 2020-08-02 15:59
I've the same issue, I don't receive mail remainder too...
Before the last update it worked fine

**Comment by dumblob** [comment] 2020-09-08 16:05
>Before the last update it worked fine

You mean NC update? What was that last working NC version?

**Comment by ClemPera** [comment] 2020-09-08 16:19
> 
> 
> > Before the last update it worked fine
> 
> You mean NC update? What was that last working NC version?

Sorry, I don't remember the update, I just know that at the beginning of the year it worked...

**Comment by Supergamerx3000** [comment] 2020-09-08 17:54
Since the last update the error in 19.0.2 & 18.08 has been fixed. E-mails are sent when I create an appointment.

**Comment by ClemPera** [comment] 2020-09-08 20:01
> 
> 
> Since the last update the error in 19.0.2 & 18.0.8 has been fixed. E-mails are sent when I create an appointment.

I just update the last nextcloud & calendar update.

So I tried to : 
- Create a new event with a reminder by email at the beginning of the event : I don't receive any email at the beginning

- Add a new participant to that event (I enter an email not a registered user on my nextcloud) : The participent did receive the email to accept/refuse the participation to the event BUT he also didn't receive the email when the event starts.

So I think it's not fixed.

**Comment by ImaCrea** [comment] 2021-02-23 15:24
same here on NC 18.0.12
emails are not sent when inviting someone *but* strangely if I invite someone when I create an event on the native Agenda app from my mac, guest receives nextcloud invitation(!)

**Comment by paulRbr** [comment] 2021-05-06 18:10
hi @ImaCrea, thanks so much for these details. I had the exact same problem and couldn't get my calendar events to send email invitations to attendees.

My nextcloud user account has a “+” (plus sign) in its email address. And my invitations are not sent.

I tried with another user account on the same NC instance and the invitations were sent out correctly! 🎉 

_Note: the invitation emails are sent to attendees with the language preference of the **event creator** - which I think should be the language of the user to whom the email is sent - but that's part of another issue I guess_

**Comment by ImaCrea** [comment] 2021-05-07 07:35
One might consider renaming the issue title to make it clear this is related to the "+" contained in account's email maybe.

**Comment by einalex** [comment] 2021-05-10 07:49
This happend without any special characters in email addresses on my instance.

**Comment by stertingen** [comment] 2022-01-07 07:25
I had the same issue on my instance. Looking at the event in the calendar screen, the `+` sign had been replaced by `%2b`. So it seems that the sender's mail address is URL-encoded, making it invalid.

**Comment by miaulalala** [comment] 2024-09-16 15:07
Duplicate of (and tracked in) https://github.com/nextcloud/server/issues/15814

**Closed by miaulalala** 2024-09-16 15:07 UTC
Labels: 1. to develop, bug
