### ISSUE TITLE
handling of recurring events - editing or deleting single events in a series of events

### ISSUE THREAD

**Issue by DrMartinus** [nextcloud/calendar#826] opened 2018-05-16 06:53 UTC
### Steps to reproduce
1. Create any repeating event
2. edit a single event in the series or
3. delete a single event in the series

### Expected behaviour
A popup should ask if only the selected one, or all starting from this one, or all events in the series should be changed or deleted, and then changes should be applied accordingly.

### Actual behaviour
The changes affect all events in the series without warning. So if you want to delete one entry in the series, you delete all.

### Server configuration

**Operating system**: Synology DSM

**Web server:** Apache 2.4

**Database:** SQLite

**PHP version:** 7.0.28

**Server version:** 13.02

**Calendar version:** 1.6.1

**Updated from an older installed version or fresh install:** fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):** Nextcloud 13.02

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
No errors have been found.

**List of activated apps:**

I get an "unsupported declare "strict-type" in app.ph on line 2" error
the same for application.php
And a parse error: unexpected "{" , expecting identifier (T_STRING) in application.php on line 27

**Nextcloud configuration:**

$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' => 
  array (
    0 => '...',
    1 => '...',
  ),
  'datadirectory' => '/pathto/nextcloud/data',
  'overwrite.cli.url' => 'http://pathto/nextcloud',
  'dbtype' => 'sqlite3',
  'version' => '13.0.2.1',
  'installed' => true,
  'mail_from_address' => '...',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => '...',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '...',
  'mail_smtpport' => '465',
  'mail_smtpname' => '...',
  'mail_smtppassword' => '',
  'maintenance' => false,
);

**Are you using encryption:** not yet

### Client configuration
**Browser:** Firefox 60.0

**Operating system:** Linux Manjaro

**CalDAV-clients:** 

### Logs
#### Web server error log
I'll post logs if need be...

**Comment by mhow2** [comment] 2018-05-16 07:08
And once you did that, there is no option to undo the changes. So basically you loose all the events : it's very annoying. All my gratitude to the one who fix this !

**Comment by georgehrke** [comment] 2018-05-16 07:50
@DrMartinus I just linked the work in progress yesterday in the issue you commented on: https://github.com/nextcloud/calendar/issues/801#issuecomment-389320362

Why are you creating yet another issue?

Duplicate of #7

**Closed by georgehrke** 2018-05-16 07:50 UTC
