### ISSUE TITLE
Allow read-only calendars as appointment conflict calendar

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#4714] opened 2022-11-03 20:06 UTC
### Is your feature request related to a problem? Please describe.

Additionally to my regular calendar I subscribed to a calendar with public holidays. On public holidays I don't work, so people shouldn't be able to schedule a appointment on these days.

At the moment I'm not allowed to chose this calendar as a calendar to check for additional conflicts.

### Describe the solution you'd like

Allow the user to add every calendar they have access to as additional conflict calendar. This way I could add the calendar with the public holidays.

I don't see a reason why we should limit the kind of calendars a user can add as conflict calendar

### Describe alternatives you've considered

Importing the public holidays every year into a regular calendar and use this calendar than as a conflict calendar. But this would be extra work I have to do regularly and there is a high chance that I will miss it or that people book already appointments for the next year before I imported the new public holidays. 

It is way easier to just subscribe to a calendar which updates itself.

**Comment by ChristophWurst** [comment] 2022-11-04 08:04
Duplicate of https://github.com/nextcloud/calendar/issues/3786

**Closed by ChristophWurst** 2022-11-04 08:04 UTC
Labels: enhancement, 0 - to triage, Feature: Appointments
