### ISSUE TITLE
Appointment timezone issues

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/calendar#546] opened 2017-07-24 15:14 UTC
### Steps to reproduce
1. Install z-push
2. Attach iphone or outlook 2016 to zpush with nextcloud calendar as calendar backend
3. Create appointments on iphone / office 2016 with 9:00 start time.
4. Appointments are synced with UTC timezone and show properly in calendar overview
5. Edit the appointment in web interface and it shows you a UTC timezone with 7:00 start. 7:00? - no 9:00 and timezone is Berlin/Germany, not UTC.
5. Create appointment in web interface and you get a default timezone Berlin/Germany. Schedule for 11:00. Save
6. Go into iphone and the appointment synced as 10:00 ???

### Expected behaviour
Always the correct timezone and no sync issues and no moved schedules. I expect every schedule show in Berlin timezone and not UTC or any other random. Summer/winter time seems to be additional trouble here.

### Actual behaviour
Schedules are not starting as expected. On the end of the day I have no longer any idea when it really starts.

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**Server version:** 12.0.0

**Calendar version:** 1.5.3

**Updated from an older installed version or fresh install:** No, new install.

**Signing status (ownCloud/Nextcloud 9.0 and above):**

Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome

**Operating system:** Win

**CalDAV-clients:** z-push 2.3.6 on server side and iOS / Outlook 2016 via ActiveSync

**Comment by georgehrke** [comment] 2017-07-24 15:19
Can you please export example calendar data and post them here?

**Comment by yamlfd** [comment] 2017-07-24 15:24
Scheduled via web interface for 2-3pm. In Outlook 2016 it appears as 3-4pm.

```
BEGIN:VCALENDAR
PRODID:-//Nextcloud calendar v1.5.3
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20170724T172055
DTSTAMP:20170724T172055
LAST-MODIFIED:20170724T172055
UID:XU2VJ6UDFACS0GE9CPM1TM
SUMMARY:Test
CLASS:PUBLIC
STATUS:CONFIRMED
DTSTART;TZID=Europe/Berlin:20170725T140000
DTEND;TZID=Europe/Berlin:20170725T150000
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

**Comment by georgehrke** [comment] 2017-07-24 15:26
DTSTART;TZID=Europe/Berlin:20170725T140000
DTEND;TZID=Europe/Berlin:20170725T150000

As you can see here, it's properly scheduled for 14:00 - 15:00 in the Berlin timezone.
If Outlook displays that wrong, it's either a bug in Outlook or (which is more probable) one in z-push.

**Comment by yamlfd** [comment] 2017-07-24 15:27
This is the example created with Outlook and it looks good everywhere as long as I do not edit it (than it is UTC), what is bad for usability.
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//z-push-contrib//NONSGML Z-Push-contrib Calendar//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20170724T152514Z
LAST-MODIFIED:20170724T152514Z
DTSTART:20170726T070000Z
SUMMARY:Test2
DTEND:20170726T073000Z
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
CLASS:PUBLIC
TRANSP:OPAQUE
DESCRIPTION:\n
UID:20170724T152525Z-2a458a3c6b9b4c3819f3d48b65bede79
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR

```

**Comment by georgehrke** [comment] 2017-07-24 15:29
> (than it is UTC)

Not only then, it's always.
`DTSTART:20170726T070000Z`
Z indicates UTC.

**Comment by yamlfd** [comment] 2017-07-24 15:35
Maybe it is z-push. I was confused that one way it works and the other not and that the web GUI shows UTC if zpush is used. Not sure how Outlooks/iOS sends it to z-push... maybe they also use UTC. Do you know?

But why does the entry show as entered in Outlook in the overview and once I edit it, it switches to UTC and tells me 2 hours earlier? Ok I know this is the UTC time, but we should not expect that normal users understand why their appointment moved from 9:00 to 7:00. I more likely expect that all timestamps stay in the current users timezone, and maybe under the hood get's saved as UTC.

Aside there is no setting for the users prefered timezone... now sure how you detect the users timezone... Budapest looks a bit random to me if I'm in Germany.

**Comment by georgehrke** [comment] 2017-07-24 17:58
> Not sure how Outlooks/iOS sends it to z-push... maybe they also use UTC. Do you know?

iOS definitely sends it with the `TZID=Europe/Berlin` format. Outlook is not easy to tell.

> But why does the entry show as entered in Outlook in the Calendar overview and once I edit it, it switches to UTC and tells me 2 hours earlier?

The calendar app recognizes that you are in Europe/Berlin, so it automatically displays the event in the equivalent time in your timezone. But if you edit it, it shows the data from the calendar data.

> Ok I know this is the UTC time, but we should not expect that normal users understand why their appointment moved from 9:00 to 7:00.

If the timezones of the event does not equal your timezone it will always display the timezone as an additional information. So you know why the time is different.

>  I more likely expect that all timestamps stay in the current users timezone, and maybe under the hood get's saved as UTC.

I'm sorry, but this a really a feature, not a bug ;)
When someone from New York sends me an event, let's say even a recurring one, I expect it to show in the correct time in the grid and the new York time in the editor. 
And changing timezones is a really bad idea especially for recurring events, because New York timezone and Berlin timezone change from daylight saving time to standard time and vice versa on different days.
This is also very useful when e.g. booking a flight between different timezones.
Let's say the flight starts in Berlin at 6pm, then I want to enter the arrival time in new York local time.
I want to know that I arrive at 9pm. I don't care that it's 3am in german time.

> Aside there is no setting for the users prefered timezone... now sure how you detect the users timezone... Budapest looks a bit random to me if I'm in Germany.

We are using some magic javascript library for that, but lately we get more and more bugreports because there seem to be issues with newer browsers. We will likely introduce a timezone list where a user can select their preferred timezone at some point.

**Comment by georgehrke** [comment] 2017-07-24 17:59
I see no issue in our software here and think this is a bug in z-push or whatever software creates events with UTC instead of timezone data.

You should reach out to the z-push developers.
I hope you are not mad if i close this issue here.

**Closed by georgehrke** 2017-07-24 17:59 UTC
Labels: needs info
