### ISSUE TITLE
Event details are NOT displayed when ORGANIZER prop is set and when the calendar is publicly shared

### ISSUE THREAD

**Issue by SergeyMosin** [nextcloud/calendar#4706] opened 2022-10-29 20:00 UTC
### Steps to reproduce

1. Create an event with an attendee (this will set the ORGANIZER as well)
2. Share the calendar via a public link
3. Visit the link as a GUEST (NOT LOGED-IN USER)
4. Click on the event 

### Expected behavior

![image](https://user-images.githubusercontent.com/10747559/198849903-6f90ab8f-10bb-47ad-83aa-0d85efe396af.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/10747559/198849879-78d58bee-ff80-47f0-ab86-a596d025c1ac.png)

### Calendar app version

4.0.2 and earlier

### Browser

all

### Client operating system

ubuntu

### Server operating system

unbuntu

### Database engine version

MySQL

### PHP engine version

PHP 8.0

### Nextcloud version

25

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
see screen shot
```

### Browser log

```Text
vue.runtime.esm.js:3045 TypeError: Cannot read properties of undefined (reading 'emailAddress')
    at getCurrentUserPrincipalEmail (principals.js:103:92)
    at Be.r.forEachGetter.t._wrappedGetters.<computed> (vuex.esm.js:881:12)
    at tr.<anonymous> (vuex.esm.js:140:12)
    at t.get (vue.runtime.esm.js:3441:33)
    at t.evaluate (vue.runtime.esm.js:3542:27)
    at tr.getCurrentUserPrincipalEmail (vue.runtime.esm.js:5517:25)
    at Object.get [as getCurrentUserPrincipalEmail] (vuex.esm.js:671:39)
    at o.userAsAttendee (EditorMixin.js:234:61)
    at t.get (vue.runtime.esm.js:3441:33)
    at t.evaluate (vue.runtime.esm.js:3542:27)
```

### Additional info

ICS file for the event:
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//IDN nextcloud.com//Calendar app 4.0.1//EN
BEGIN:VEVENT
CREATED:20221029T192636Z
DTSTAMP:20221029T195639Z
LAST-MODIFIED:20221029T195639Z
SEQUENCE:3
UID:23adc7a4-c39c-4f47-b07b-8750b4bd4df8
DTSTART;VALUE=DATE:20221105
DTEND;VALUE=DATE:20221106
STATUS:CONFIRMED
SUMMARY:Organizer Test
ORGANIZER;CN=Admin25:mailto:sergey@reducted.com
ATTENDEE;CN=Cool Name;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PART
 ICIPANT;RSVP=TRUE;SCHEDULE-STATUS=1.1:mailto:someemail@example.com
END:VEVENT
END:VCALENDAR
```

**Comment by tcitworld** [comment] 2022-10-31 07:40
Seems introduced by https://github.com/nextcloud/calendar/pull/3864 which doesn't check that we indeed have a `currentUserPrincipal` (in the case of public links) before calling it.
https://github.com/nextcloud/calendar/blob/51518a3204f42a5a01baa72b5f5a3102a60272df/src/mixins/EditorMixin.js#L234

**Comment by ChristophWurst** [comment] 2022-10-31 11:24
Duplicate of https://github.com/nextcloud/calendar/issues/4011?

**Comment by finkandreas** [comment] 2022-11-08 05:31
Also duplicate of #4169

**Closed** 2023-05-10 11:59 UTC
Labels: 1 - to develop, bug, Feature: Public sharing, regression
