### ISSUE TITLE
Different timezones are not preserved when selected for start and end of event

### ISSUE THREAD

**Issue by RuralYak** [nextcloud/calendar#1989] opened 2020-02-14 05:54 UTC
When event created with start time in one timezone but ends in another selection is not saved

### Steps to reproduce
1. Create event in one timezone
2. Set the end in another timezone
3. Save event

### Expected behaviour
Event has to have a proper lenght and end of the event should preserve selected timezone

### Actual behaviour
End of the event gets reset to the timezone of the start time

### Calendar app
**Calendar app version:** (2.0.1)

**CalDAV-clients used:** (Web page)

### Client configuration
**Browser:**  Firefox 72.0.2 (64-bit)

**Operating system:** Ubuntu 19.10

### Server configuration

**Operating system**: Ubuntu 18.04.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.0.3
**Nextcloud Version:** 17.0.3

**Updated from an older installed version or fresh install:**

**List of activated apps:**

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - cookbook: 0.5.7
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_downloadactivity: 1.6.0
  - files_external: 1.8.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trackdownloads: 1.6.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.5
  - impersonate: 1.4.0
  - ldap_write_support: 1.0.2
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.5
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - occweb: 0.0.7
  - onlyoffice: 4.1.4
  - password_policy: 1.7.0
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_clipboard
  - files_readmemd
  - files_trashbin
  - survey_client
  - theming_customcss
```

**Nextcloud configuration:**

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           ***removed***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***remved***",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "tasks",
            "occweb"
        ],
        "theme": "",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3"
        ]
    }
}
```

**Comment by tcitworld** [comment] 2020-02-14 07:40
Looks like the same thing as issue #1914.

**Comment by georgehrke** [comment] 2020-02-16 18:01
Definitely a duplicate like @tcitworld said.

**Comment by georgehrke** [comment] 2020-02-16 18:01
Duplicate of #1914

**Closed by georgehrke** 2020-02-16 18:01 UTC
Labels: 0. to triage, bug
