### ISSUE TITLE
Timezone offset for events in the detailed calendar view.

### ISSUE THREAD

**Issue by bureau2crea** [nextcloud/calendar#5447] opened 2023-09-05 08:50 UTC
### Steps to reproduce

1. Select a local timezone (UTC+2 - Europe/Paris)
2. Import a calendar (ices file)

### Expected behavior

In detailed view, it must shown the event with local timezone (UTC+2)

### Actual behaviour

In the normal view, it displays the correct time, but in the detailed view, it shows the time according to the general timezone (UTC).

### Calendar app version

4.4.4

### Browser

Chrome 116

### Client operating system

Mac Os

### Server operating system

Linux 3.10.108 armv7l

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

27.0.2

### Updated from an older installed version or fresh install

Fresh install

**Comment by miaulalala** [comment] 2023-09-05 11:40
Duplicate of https://github.com/nextcloud/calendar/issues/4802

**Closed by miaulalala** 2023-09-05 11:40 UTC
Labels: bug, 0 - to triage
