### ISSUE TITLE
[Feature request] Show same events as "merged" entry

### ISSUE THREAD

**Issue by zerix2889** [nextcloud/calendar#858] opened 2018-07-02 08:35 UTC
Would be a nice feature to see same events (from shared calendars etc) merged into one simple event with some kind of indicator that it has been merged. (E.g. taken the colors from the corresponding calendars and make some outline circles (with border-color of the calendar itself))

I know we can hide different types of calendar, but especially in bigger environments it's common to have displayed all calendars to see what's happening indoor and when someone have to leave.

This feature could be optional and can be toggled on the left side panel of the nextcloud window above/below the "Show/Hide calendars"

The comparsion could be to compare title/description/date/time or generate some kind of md5 checksum to set as attribute and with that it should be easy to merge them easily. If then some event from one user are different (e.g. in time) it won't be merged anymore and show up on it's own.

Hopefully it's clear what I wanted to request, I didn't find any duplicate of this problem in github.

Here is some draft what I mean:
![mergedentry](https://user-images.githubusercontent.com/39445371/42153365-3440fe3c-7de3-11e8-9fdb-30d9b9694207.PNG)

**Comment by slings21** [comment] 2018-07-02 08:55
I think this is a good idea. I need also this feature.

**Comment by georgehrke** [comment] 2018-07-02 08:55
@slings21 Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)

**Comment by georgehrke** [comment] 2019-09-02 09:19
Duplicate of #1329

**Closed by georgehrke** 2019-09-02 09:19 UTC
Labels: 1 - to develop, enhancement-approved
