### ISSUE TITLE
Can't share caledars to groups with a blank in the group name

### ISSUE THREAD

**Issue by Tom61** [nextcloud/calendar#479] opened 2017-05-28 14:47 UTC
### Steps to reproduce
1. Login as admin
2. Share a calendar to a group with a blank ' ' in the group name ('test group')
3. Login as member of this group

### Expected behaviour
You should see the shared calendar

### Actual behaviour
The shared calendar is not shown

### Server configuration
**Operating system**: Linux ssv-cloud 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.0.29

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud 11.0.2

**Where did you install Nextcloud from: Auto Update

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - announcementcenter: 3.1.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - circles: 0.10.0
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - passman: 2.1.2
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_facebook: 1.0.1
 - socialsharing_googleplus: 1.0.1
 - socialsharing_twitter: 1.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - admin_audit
 - encryption
 - federation
 - files_external
 - twofactor_u2f
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "",
    "logfile": "\/var\/log\/nextcloud.log",
    "loglevel": 2,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        ""
    ],
    "datadirectory": "\/home\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/ssv-cloud.de",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_from_address": "ssv-cloud",
    "mail_domain": "xxx.xxx",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "maintenance": false,
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

**Server version:** (see your admin page)
12.0.0

**Calendar version:** (see the apps page)
1.5.3

**Comment by georgehrke** [comment] 2017-05-28 14:48
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
https://github.com/nextcloud/server/issues

I'm very sure this is the duplicate of another bug report in the server. Will post the link in a second

**Closed** 2017-05-28 14:47 UTC

**Comment by georgehrke** [comment] 2017-05-28 14:49
Here you go: https://github.com/nextcloud/server/issues/4885
