### ISSUE TITLE
Calendar 1.7 incompatible with NC16

### ISSUE THREAD

**Issue by duub** [nextcloud/calendar#1281] opened 2019-05-18 01:59 UTC
### Steps to reproduce
1. Web Update to NC16.0.1 (from NC15.0.7)
2. complete the process
3. Get the calendar app disabled

### Expected behaviour
Should be compatible with NC16, so don't get the incompatiblity message neither the app disabled.

### Actual behaviour
After the update the app is disabled and when i go to the apps page I get the warning that it's not compatible.

### Server configuration

**Operating system**: Debian 9.6

**Web server:** Apache

**Database:** MySQL 14.14

**PHP version:** 7.3

**Server version:** 16.0.1.1

**Calendar version:** 1.7.0

**Updated from an older installed version or fresh install:** NC15.0.7

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - deck: 0.6.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - unsplash: 1.1.3
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - calendar
  - circles
  - encryption
  - files_external
  - impersonate
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by georgehrke** [comment] 2019-05-18 06:22
> After the update the app is disabled and when i go to the apps page I get the warning that it's not compatible.

Can you please provide a screenshot?

As you can see on https://apps.nextcloud.com/apps/calendar, 1.7.0 is definitely compatible with Nextcloud 16.

**Comment by tcitworld** [comment] 2019-05-18 06:26
You need to reload the page.

**Comment by duub** [comment] 2019-05-18 11:01
Updating the page makes the message dissapear, the behaviour during the process is still failing.

I don't see the message anymore so I can't attach the message, I could enable the app without any issue.

**Comment by ericcotelnu** [comment] 2019-05-18 15:42
Because there's an issue with indices, and other issues that prevent upgrading.

```
Doctrine\DBAL\Schema\SchemaException: The column 'calendartype' on table 'oc_calendarchanges' already exists.
Update failed
```

```
Doctrine\DBAL\Schema\SchemaException: An index with name 'calid_type_synctoken' was already defined on table 'oc_calendarchanges'.
Update failed
```

`
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE INDEX calendarobject_value_index ON oc_calendarobjects_props (value, calendartype)':`

```
Doctrine\DBAL\Schema\SchemaException: The column 'calendartype' on table 'oc_calendarobjects' already exists.
Update failed
```
```

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
Update failed
```

Which has been going on for several major versions. I'm surprised no one else reported this.

The end result is the calendar app gets disabled, and takes everything else down with it, due to the upgrade command stalling on one app. There should be some checks in place to see : 

a) if an index exists, if so, skip it 
b) see if creating that index will be too big, and propose an alternate solution (or some other Good Thing To Do ™)
c) (not so popular solution, I'll admit) stop using mysql with "key length" issues.

(Apologies if I come off as snarky, not my intent).

**Comment by georgehrke** [comment] 2019-05-18 15:44
@ericcotelnu Please report a bug in https://github.com/nextcloud/server

The calendar app is just a web app. Everything that's caldav related in inside the main Nextcloud server.

**Comment by georgehrke** [comment] 2019-05-18 15:44
I will close this since @duub's issue seems to be resolved.

**Closed by georgehrke** 2019-05-18 15:44 UTC

**Comment by ericcotelnu** [comment] 2019-05-19 01:18
> @ericcotelnu Please report a bug in https://github.com/nextcloud/server
> 
> The calendar app is just a web app. Everything that's caldav related in inside the main Nextcloud server.

OK, thanks. Been looking all over just where the DB stuff comes in.

**Comment by brianWreaves** [comment] 2019-08-14 21:13
I'm also seeing the incompatible message for both _Calendar_ and _AppOrder_.  I just updated from NC15 to NC16.03.
 
![nc16_calendar_apporder_disabled_01](https://user-images.githubusercontent.com/2764169/63056618-c4eee400-bf2b-11e9-8c65-7a31189c23ec.png)
 
I haven't been able to find a solution outside of 'just try it anyway.'

**Comment by georgehrke** [comment] 2019-08-15 08:08
@brad2014 It's incompatible, because you have version 1.6.5 installed. Click the Update to 1.7.0 button and then you can enable the app.

  
![63056618-c4eee400-bf2b-11e9-8c65-7a31189c23ec-2](https://user-images.githubusercontent.com/1250540/63081714-9b8e8200-bf44-11e9-9f79-e430cdffb6d5.png)

**Comment by tobip** [comment] 2019-08-15 15:25
Even after updating the calendar app to 1.7.0 it still doesn't work:

![Screenshot from 2019-08-15 17-22-45](https://user-images.githubusercontent.com/3918330/63105658-8ab03180-bf81-11e9-98f5-b75b7900730e.png)

It says: "Server version 15 or lower is required".

**Comment by georgehrke** [comment] 2019-08-15 15:25
@tobip As @tcitworld said further up in this thread, you have to reload the page after updating.

**Comment by tobip** [comment] 2019-08-15 15:39
Ah sorry I missed that post. Yes after the reload it works. Thanks!

**Comment by brianWreaves** [comment] 2019-08-15 21:05
Great,  one of my calendars was lost...

**Comment by georgehrke** [comment] 2019-08-16 09:02
@brianWreaves Can you please report a bug about that in https://github.com/nextcloud/server? 

I know that it can be difficult, but please try to describe reproduction steps as detailed as possible.
(Also provide an anonymised access.log)

I doubt that it's related to the calendar app update problem, because the calendar app itself does not store any calendar-data.
