### ISSUE TITLE
Calendar links from dashboard(upcoming events) or notifications are not opening

### ISSUE THREAD

**Issue by mohammadsiddiqui** [nextcloud/calendar#3439] opened 2021-08-30 18:02 UTC
Calendar event links from dashboard(upcoming events) or notifications are not opening.
It's happening at the Nextcloud Demo Instance
https://demo1.nextcloud.com/apps/dashboard/

### Steps to reproduce
1. From the calenders app, create an event
2. Head to Dashboard
3. Click on the calendar event from dashboard(upcoming events) or notifications. Its opening in a new tab and the page never loads.

### Expected behaviour
Expected to open calender with the event details

### Actual behaviour
 Its not loading anything, the page is stuck.

### Calendar app
2.3.2

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:**  
Chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Operating system:** (e.g. Arch Linux)
Windows

### Server configuration
It's happening on the nextcloud demo server.
https://demo1.nextcloud.com/apps/dashboard/

**Comment by ChristophWurst** [comment] 2021-08-31 07:19
I believe this is a duplicate of https://github.com/nextcloud/calendar/issues/3302

**Closed by ChristophWurst** 2021-08-31 07:19 UTC
Labels: bug, 0. to triage
