### ISSUE TITLE
New week view to show the full days (mornings until evenings)

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/calendar#1872] opened 2020-01-20 21:07 UTC
**The problem I am encountering**
Since the last update, the week overview has a per-quarter of an hour view.

This is causing the days not to be shown in full anymore, which is why you have to scroll up and down to see what is planned in the morning and in the evenings. Earlier, it was possible to see everything planned in the week in one view.

**Describe the solution you'd like**
Have the ability to set the calendar back to a half-hour view for the week, or have the ability to define the from / to of the day that the week view should show in one overview on-screen.

**Comment by tcitworld** [comment] 2020-01-20 22:34
Duplicate of https://github.com/nextcloud/calendar/issues/1840

**Comment by tcitworld** [comment] 2020-01-20 22:35
And #577

**Closed by tcitworld** 2020-01-20 22:34 UTC
Labels: 0. to triage, enhancement-proposed
