### ISSUE TITLE
Change single event out of a series

### ISSUE THREAD

**Issue by dacoex** [nextcloud/calendar#1763] opened 2020-01-08 23:41 UTC
**Is your feature request related to a problem? Please describe.**
Make it possible to change a single / individual event of a series of recurring events.

**Describe the solution you'd like**
Example:
a meeting happens every 1rst Monday of a month.
one first Monday falls on a holiday and thus should be shifted to a the following Tuesday for 1 meeting.

**Describe alternatives you've considered**
Changing from client apps, e.g. thunderbird is possible.

**Additional context**

**Comment by georgehrke** [comment] 2020-01-09 08:55
Duplicate of #7

**Closed by georgehrke** 2020-01-09 08:55 UTC
Labels: 0. to triage, enhancement-proposed
