### ISSUE TITLE
Sharing calendar is impossible when username contains space

### ISSUE THREAD

**Issue by olivierb2** [nextcloud/calendar#1943] opened 2020-01-31 15:08 UTC
Dear community,

I'm Nextcloud user since many years, and I recently discovered that it's possible to create users with spaces in their username.

We discovered today that sharing a calendar with people who has a space in their username simply doesn't work.

### Steps to reproduce
1. Go to Settings > Users, and create a new user with a space in Username (e.g. "test test")
2. Go to Calendar app, click on Share button of any calendar.
3. Add the new user to sharing list (Modify right doesn't matter).
4. The user seems to be added, move to another tab.
5. Go back to Calendar, click again on Share button and username has now disappeared.

### Expected behaviour
Either disable ability to have space in username of a user account (probably mostly best practice), or fix Calendar app Sharing feature.

### Actual behaviour
It's just impossible to share a calendar with users that are containing space in their username.

### Calendar app
**Calendar app version:** 2.0.1 (no update available yet)

### Client configuration
**Browser:** Firefox 68.4.1esr
**Operating system:** Debian Buster 10

### Server configuration

**Operating system**: no idea : (Hosting Infomaniak)
**Web server:** Probably Apache
**Database:** MariaDB 5.7.26
**PHP version:** 7.3.13
**Nextcloud Version:** 17.0.2

**Updated from an older installed version or fresh install:** Fresh install

**List of activated apps:** Calendar

**Nextcloud configuration:**

**Comment by georgehrke** [comment] 2020-01-31 15:35
Duplicate of https://github.com/nextcloud/server/issues/17610

**Closed by georgehrke** 2020-01-31 15:35 UTC
Labels: 0. to triage, bug
