### ISSUE TITLE
[Feature request] Allow to overwrite event visibility when sharing a calendar

### ISSUE THREAD

**Issue by ypid-geberit** [nextcloud/calendar#944] opened 2018-11-14 10:19 UTC
### Steps to reproduce
1. Create calendar "work" under "work_account".
2. Create event in "work_account" with visibility/privacy set to "When shared hide this event".
3. Share calendar "work with "private_account" and allow edits.
4. [Feature request]: Configure this share to overwrite all event-based visibility settings to "Full event for all events regardless of event visibility".
5. Open the shared calendar under "private_account".

### Expected behaviour

Event which is set to "When shared hide this event" should be visible.

### Actual behaviour

Currently, because the event visibility can not be overwritten, the event is missing.

### User story

My use case is that I have a work calendar which is synced to Nextcloud using a restricted account ("work_account") because I don’t want to give my work systems access to any (private) information that is not required (Principle of least privilege). I then have my regular Nextcloud user ("private_account") to which I have shared the work calendar with edit permissions. The "private_account" bundles all my calendars and I use DavDroid to sync the calendars of this one account with my smartphone. This works nicely because all calendars which are shared with "private_account" automatically appear and I don’t have to setup much when adding a new calendar to get them synced. The only issue is now that events that are set to private in my work calendar don’t end up in my "private_account". I can obviously not change the viability of the event itself because they should be private in my work calendar (shared with coworkers).

The only workaround for this is for me to setup syncing using the "work_account" on my private devices (DavDroid). This obviously also conflicts with Principle of least privilege because then my private devices would have access to work resources that are not required.

### Related issues

* https://github.com/nextcloud/calendar/issues/531
  Posted there first, then I opened it as a new issue here.
* https://github.com/nextcloud/calendar/issues/898

**Comment by georgehrke** [comment] 2019-09-13 11:21
Duplicate of https://github.com/nextcloud/server/issues/11214

**Closed by georgehrke** 2019-09-13 11:21 UTC
Labels: enhancement-proposed
