### ISSUE TITLE
Sequence of calendar entries

### ISSUE THREAD

**Issue by afgeissler** [nextcloud/calendar#4595] opened 2022-10-11 19:56 UTC
### Steps to reproduce

1. add multiple entries to the same day with different start times
2. rename entries and see how they appear in another order. all-day entries are shown on the bottom.

### Expected behavior

entries should appear in order of start time, starting with the earliest one. all-day entries should be always on top.

### Actual behaviour

entries are sorted alphabetical

### Calendar app version

3.5.0

### CalDAV-clients used

nextcloud

### Browser

any

### Client operating system

any

### Server operating system

debian

### Web server

Apache

### Nextcloud version

24.0.6

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by tcitworld** [comment] 2022-10-12 06:52
Duplicate of https://github.com/nextcloud/calendar/issues/4443

**Closed by tcitworld** 2022-10-12 06:52 UTC
Labels: bug, 0 - to triage
