### ISSUE TITLE
Event creation modal goes over the line of vision

### ISSUE THREAD

**Issue by trollepierre** [nextcloud/calendar#2073] opened 2020-03-13 19:09 UTC
a big issue I am facing using the Framagenda is when creating event on the first week, sometimes modal goes to a hidden place, see the picture
<img width="1440" alt="Capture d’écran 2020-03-13 à 19 59 05" src="https://user-images.githubusercontent.com/8363334/76652267-86bfae80-6566-11ea-9aed-c6822a3f54a7.png">

**Comment by georgehrke** [comment] 2020-03-13 20:29
@trollepierre When opening a new issue, please always use the issue template.
Bug reports like this one are not really helpful, as you didn't even mention what version you are using, etc. 😉

**Comment by georgehrke** [comment] 2020-03-13 20:29
Duplicate of https://github.com/nextcloud/calendar/issues/1934

**Closed by georgehrke** 2020-03-13 20:29 UTC
