### ISSUE TITLE
Support for HTML formatted descriptions

### ISSUE THREAD

**Issue by ksainc** [nextcloud/calendar#5636] opened 2023-12-21 13:12 UTC
### Is your feature request related to a problem? Please describe.

No, missing functionality.

### Describe the solution you'd like

Please add support for HTML descriptions

RFC:
X-ALT-DESC:",%3Ch1%3ERich%20%3Cb%3EText%3C%2Fb%3E%C2%
 A0%3C%2Fh1%3E%3Ch4%3E%3Cu%3EDescription%3C%2Fu%3E%20%F0%9F%99%82%3C%2Fh4%3E"

Or 

DESCRIPTION;ALTREP="data:text/html,%3Ch1%3ERich%20%3Cb%3EText%3C%2Fb%3E%C2%
 A0%3C%2Fh1%3E%3Ch4%3E%3Cu%3EDescription%3C%2Fu%3E%20%F0%9F%99%82%3C%2Fh4%3E
 ":Rich Text \nDescription 🙂

The second option is the way thunder bird implements this.

### Describe alternatives you've considered

None

### Additional context

Rich text in calendar description

**Comment by tcitworld** [comment] 2023-12-21 13:52
Duplicate of #3234

**Closed by tcitworld** 2023-12-21 13:52 UTC
Labels: enhancement, 0 - to triage
