### ISSUE TITLE
Copy & Search

### ISSUE THREAD

**Issue by Beta0815** [nextcloud/calendar#2355] opened 2020-06-21 23:55 UTC
Hi,

first, the App great, really.
But I miss the function to copy entries and "Search"

Is this planned in the near future?

Greetz

**Comment by georgehrke** [comment] 2020-06-22 06:11
@Beta0815 When opening feature requests, please
(1) use the issue template
(2) create one issue per enhancement
(3) and search for existing issues!

**Comment by georgehrke** [comment] 2020-06-22 06:11
Duplicate of #113 
Duplicate of #8

**Closed by georgehrke** 2020-06-22 06:11 UTC
Labels: 0. to triage, enhancement-proposed
