### ISSUE TITLE
Change default calendar used when New Event is created

### ISSUE THREAD

**Issue by arthurlutz** [nextcloud/calendar#1173] opened 2019-03-18 09:28 UTC
### Steps to reproduce
1. Create 2nd calendar called "Family" (for example)
2. Create an Event, "Personal" is selected as default calendar to add event
3.

### Expected behaviour
Tell us what should happen

1. Create 2nd calendar, change settings to tell Nextcloud Calendar that this is the main calendar that should show up as default when creating events
2. Create new event, 2nd calendar is selected by default

### Actual behaviour

Can't set "default calendar", unless it has been created first. For example, I have : 1. Personal (default when initialising) 2. "really unimportant rarely used" 3. Family "use it all the time" 4. Personal (imported from other application). Then I deleted "1." in favor of using "4.". 

When I create events I have "2." as a default which I have to change every time I use it. 

### Versions

Nextcloud 13.0.6
Calendar 1.6.1

**Comment by georgehrke** [comment] 2019-03-18 09:37
Duplicate of #9 

The first in the list will always be the default one.

**Closed by georgehrke** 2019-03-18 09:37 UTC
