### ISSUE TITLE
30 minutes events are depicted as lasting 1hour

### ISSUE THREAD

**Issue by florian-prd** [nextcloud/calendar#3396] opened 2021-08-04 08:53 UTC
When creating an event that lasts 30min, it is depicted as lasting 1h. Please see examples below. The bug is present on Daily and weekly view.
Nextcloud version: 21.0.3
Calendar version: 2.3.1

![image](https://user-images.githubusercontent.com/23257616/128151855-805969d7-b175-44f2-9daf-bb66ff492f9c.png)

**Comment by miku86** [comment] 2021-08-05 13:22
I actually thought that this is a "feature".

Seems like the boxes try to "glue" to each other, although there is a gap of 15min between the meetings:

![2021-08-05_15-18](https://user-images.githubusercontent.com/7271016/128356683-9f55febc-dd71-4185-bc63-5a6098740ebc.png)

```
Nextcloud version: 21.0.3
Calendar version: 2.3.1
```

**Comment by ChristophWurst** [comment] 2021-08-09 13:49
I'd say this is a duplicate of https://github.com/nextcloud/calendar/issues/3275

**Closed by ChristophWurst** 2021-08-09 13:49 UTC
