### ISSUE TITLE
Can't change the assigned calendar in an event back and forth

### ISSUE THREAD

**Issue by kirlue** [nextcloud/calendar#3927] opened 2022-02-01 16:28 UTC
Hello,
I can reproduce the following bug at several Nextcloud installations on different systems and servers. It first occurred (or at least we first remarked it) about 5 months ago – I can't specifically date it or name the version. It occurs with shared and with "normal" calendars. First thought it was a problem of Thunderbird (where I use the calendars) but it appears also at the nextcloud calendar interface.

### Steps to reproduce
1. Create 3 seperate calendars in your nextcloud calendar.
2. Create a random event in calendar 1.
3. Change the event to calendar 2 in the "details"-section (without creating or copying the event, just change the calendar!)
4. Refresh the page, because often the color of the event has changed correctly, but the name of the calendar shown in the details is still the old one. (-> another bug?)
5. Take the same event and try to change it back to the original calendar 1.
6. (Try to change it to a new calendar, f.e. calendar 3.)

### Expected behaviour
It should be possible to change the assigned calendar multiple times forth and back again. In the same or other calendars (f.e. an appointment in the calendars of different colleagues has been assigned to Marcel, he gets ill and the boss would like to change it to Julia – no problem. Then Marcel decides that he can do the appointment from home office, so the event should be changed back to his calendar without any problems.) 

### Actual behaviour
When changing the calendar back to the original one the famous "spinning circle" appears. The event cannot be changed back. One can freely change the calendar to a new one (f.e. the third calendar created in step 1) but never change the calendar back to one where the event has already been before. Tried on Thunderbird an error message appears as well. Any other changes are still possible in the calendar and the event.
It is possible by the way to **copy** the event in Thunderbird and **paste** it back to calendar 1, delete it afterwards in calendar 2. But the actual changing of the calendars is not possible anymore.

### Calendar app
**Calendar app version:** 3.0.5

**CalDAV-clients used:** Thunderbird Lightning, DavX⁵

### Client configuration
**Browser:** any browser

**Operating system:**  any operating system

### Server configuration

**Nextcloud Version:** 22.2.0

**Updated from an older installed version or fresh install:** updated

**Comment by st3iny** [comment] 2022-02-01 16:49
Duplicate of https://github.com/nextcloud/calendar/issues/3325.

**Closed by st3iny** 2022-02-01 16:49 UTC
Labels: bug, 0. to triage
