### ISSUE TITLE
Download shared calendar error: "This is the WebDAV interface."

### ISSUE THREAD

**Issue by Kaeltis** [nextcloud/calendar#841] opened 2018-06-09 11:55 UTC
### Steps to reproduce
1. Upgrade Nextcloud to 13.0.3
2. Create a calendar
3. Generate and visit public URL
4. Click "Download"

### Expected behaviour
An ICS file should be downloaded, this was working in 13.0.2

### Actual behaviour
The following message is shown: 
`This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.`

### Server configuration

**Operating system**: CentOS 7

**Web server:** nginx/1.13.12 (fpm-fcgi)

**Database:** mysql 10.2.15

**PHP version:** 7.2.5

**Server version:** 13.0.3 - 13.0.3.2

**Calendar version:** 	1.6.1

**Updated from an older installed version or fresh install:** Updated from 13.0.2

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - checksum: 0.4.0
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - issuetemplate: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_u2f: 1.5.5
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - federation
  - files_external
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.myhost.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.myhost.com",
        "dbtype": "mysql",
        "version": "13.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome/68.0.3440.17

**Operating system:** Windows 10 - Version 1803

**CalDAV-clients:** None

#### Log file (data/nextcloud.log)
```
{"reqId":"XsMkD6hIZM3o66V5wXOA","level":4,"time":"2018-06-09T13:50:40+02:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"Kaeltis","app":"webdav","method":"REPORT","url":"\/remote.php\/dav\/public-calendars\/fSD4kwzqQj9FCkH8\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ReportNotSupported\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/nginx\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/share\\\/nginx\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#3 \\\/usr\\\/share\\\/nginx\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/nginx\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(287): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/share\\\/nginx\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/share\\\/nginx\\\/html\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/ngin...')\\n#7 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php\",\"Line\":725}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.17 Safari\/537.36","version":"13.0.3.2"}
```

#### Browser log
```
core.js?v=64d462e1-41:5729 REPORT https://cloud.myhost.com/remote.php/dav/public-calendars/fSD4kwzqQj9FCkH8/ 415 ()
request @ core.js?v=64d462e1-41:5729
getAll @ app.min.js?v=64d462e1-41:4
D.fcEventSource.events @ app.min.js?v=64d462e1-41:2
(anonymous) @ vendor.min.js?v=64d462e1-41:14
construct @ vendor.min.js?v=64d462e1-41:11
t.fetch @ vendor.min.js?v=64d462e1-41:14
e.requestSource @ vendor.min.js?v=64d462e1-41:16
e.addSource @ vendor.min.js?v=64d462e1-41:16
e.addEventSource @ vendor.min.js?v=64d462e1-41:14
(anonymous) @ vendor.min.js?v=64d462e1-41:16
each @ core.js?v=64d462e1-41:2
each @ core.js?v=64d462e1-41:2
r.fn.fullCalendar @ vendor.min.js?v=64d462e1-41:15
O @ app.min.js?v=64d462e1-41:1
(anonymous) @ app.min.js?v=64d462e1-41:1
(anonymous) @ app.min.js?v=64d462e1-41:1
r @ vendor.min.js?v=64d462e1-41:3
$digest @ vendor.min.js?v=64d462e1-41:3
$apply @ vendor.min.js?v=64d462e1-41:3
(anonymous) @ app.min.js?v=64d462e1-41:1
Promise.then (async)
(anonymous) @ app.min.js?v=64d462e1-41:1
o @ vendor.min.js?v=64d462e1-41:1
c.instance @ vendor.min.js?v=64d462e1-41:2
h @ vendor.min.js?v=64d462e1-41:2
o @ vendor.min.js?v=64d462e1-41:2
(anonymous) @ vendor.min.js?v=64d462e1-41:2
(anonymous) @ vendor.min.js?v=64d462e1-41:1
$eval @ vendor.min.js?v=64d462e1-41:3
$apply @ vendor.min.js?v=64d462e1-41:3
(anonymous) @ vendor.min.js?v=64d462e1-41:1
o @ vendor.min.js?v=64d462e1-41:1
o @ vendor.min.js?v=64d462e1-41:1
de @ vendor.min.js?v=64d462e1-41:1
le @ vendor.min.js?v=64d462e1-41:1
(anonymous) @ vendor.min.js?v=64d462e1-41:6
j @ core.js?v=64d462e1-41:2
fireWith @ core.js?v=64d462e1-41:2
ready @ core.js?v=64d462e1-41:2
I @ core.js?v=64d462e1-41:2
(anonymous) @ VM2295:2
e.string.g.function.c.(anonymous function) @ VM2332:52
(anonymous) @ VM2295:2
b @ VM2295:1
(anonymous) @ VM2295:2
ja @ VM2332:53
l @ VM2332:50
```

**Comment by tcitworld** [comment] 2018-06-09 11:59
Duplicate of #839

**Closed** 2018-06-09 12:00 UTC
