### ISSUE TITLE
Calendar view in List mode overlays date

### ISSUE THREAD

**Issue by aleadco** [nextcloud/calendar#3652] opened 2021-11-15 21:08 UTC
Calendar view in List mode overlays date with side button
### Steps to reproduce
1. Show in list mode

### Actual behaviour
![image](https://user-images.githubusercontent.com/35962168/141853981-d9309bd6-30f6-4d56-b78e-643e0a6c4b8e.png)

### Calendar app
**Calendar app version:** 2.3.4

**Comment by raimund-schluessler** [comment] 2021-11-15 22:05
Duplicate of https://github.com/nextcloud/calendar/issues/2515.

**Closed by raimund-schluessler** 2021-11-15 22:05 UTC
Labels: bug, 0. to triage
