### ISSUE TITLE
Notification mail when someone books an appointment

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#3547] opened 2021-10-13 13:45 UTC
People need to be made aware of when someone books an appointment. This could for example just be the same mechanism that is used by the Calendar when someone confirms or rejects an invitation.

As example, this is how Calendly’s notification mail looks like:
![Calendly notification mail](https://user-images.githubusercontent.com/925062/137145105-de44f6e8-2a74-4bb7-afe3-bd10ee5337e5.png)

**Comment by ChristophWurst** [comment] 2022-03-22 15:51
Duplicate of https://github.com/nextcloud/calendar/issues/3630

**Closed** 2022-03-22 15:55 UTC
Labels: 0. to triage, Feature: Appointments
