### ISSUE TITLE
Participation status is not updated if the invitation comes from a shared calendar organizer

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/calendar#6560] opened 2024-12-10 14:25 UTC
### Steps to reproduce

1. Alice shares her personal calendar to Bob
2. Bob organizes an event on the Alice calendar, inviting Jane
3. Jane receives the invitation and she accepts it (through the link in the invitation mail, or through the NC web interface on her calendar)
4. Participation status of Jane is not updated in the Alice calendar (waiting for a response), it is only updated on the event of the Jane's calendar.

### Expected behavior

Participation status of attendees should be updated even if the organizer is not the owner of the inviting calendar

### Actual behavior

Participation status of attendees is only updated if Alice invites herself from her own calendar.
When the organizer isn't the owner of the calendar, participation status of attendee is not updated.

### Calendar app version

5.0.6

### CalDAV-clients used

None

### Browser

Firefox 133

### Client operating system

Ubuntu

### Server operating system

Debian

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

Other

### Nextcloud version

30.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.0.1
  - app_api: 4.0.0
  - assistant: 2.1.1
  - calendar: 5.0.6
  - cfg_share_links: 6.1.1
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.1
  - contactsinteraction: 1.11.0
  - context_chat: 3.1.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.2
  - drawio: 3.0.3
  - external: 5.5.2
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_emailviewer: 0.1.3
  - files_external: 1.22.0
  - files_linkeditor: 1.1.21
  - files_mindmap: 0.0.30
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - files_zip: 2.1.0
  - forms: 4.3.4
  - groupfolders: 18.0.6
  - guests: 4.0.1
  - impersonate: 1.17.0
  - integration_giphy: 2.0.1
  - integration_openai: 3.2.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.7
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - notify_push: 0.7.0
  - oauth2: 1.18.1
  - onlyoffice: 9.5.0
  - password_policy: 2.0.0
  - photos: 3.0.2
  - polls: 7.2.5
  - provisioning_api: 1.20.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - spreed: 20.1.0
  - systemtags: 1.20.0
  - tables: 0.8.1
  - tasks: 0.16.1
  - text: 4.1.0
  - text_templates: 1.1.0
  - theming: 2.5.0
  - theming_customcss: 1.17.0
  - thesearchpage: 1.2.8
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "ratelimit.protection.enabled": false,
        "auth.bruteforce.protection.enabled": false,
        "simpleSignUpLink.shown": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.agglo-montbeliard.fr",
            "192.168.50.106"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.agglo-montbeliard.fr\/",
        "dbtype": "mysql",
        "version": "30.0.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "theme": "",
        "loglevel": 3,
        "debug": false,
        "maintenance": false,
        "maintenance_window_start": 1,
        "app.mail.background-sync-interval": 86400,
        "app.mail.verify-tls-peer": false,
        "activity_expire_days": 365,
        "trashbin_retention_obligation": "auto, 15",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "app.mail.imap.timeout": 620,
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "default_phone_region": "FR",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "spreed",
            "files_mindmap",
            "pdfdraw",
            "issuetemplate",
            "files_linkeditor",
            "files_texteditor",
            "files_trackdownloads",
            "emlviewer",
            "files_archive",
            "impersonate",
            "extract",
            "tables",
            "cfg_share_links",
            "workflow_script",
            "files_emlviewer"
        ],
        "allow_local_remote_servers": true,
        "default_language": "fr",
        "default_locale": "fr_FR",
        "force_locale": "fr_FR",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_memory": 512,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "sharing.enable_share_mail": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "bulkupload.enabled": "false"
    }
}
```

### Web server error log

```Text
no relevant log
```

### Log file

```Text
no relevant log
```

### Browser log

```Text
no relevant log
```

### Additional info

Invitations from shared calendars is only possible since https://github.com/nextcloud/server/pull/45054
Maybe the accept/decline process for these specific invitations has been forgotten ?

**Comment by SebastianKrupinski** [comment] 2024-12-10 18:23
Hi @Mer0me 

Log time no talk 😄 

This is a know issue.

Duplicate of https://github.com/nextcloud/server/issues/48511

I will close this ticket, you can track status on the link above.

**Closed** 2024-12-10 18:24 UTC
Labels: bug, 0. to triage
