### ISSUE TITLE
Highlight the event title in the simple editor, just like in the full editor

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/calendar#1965] opened 2020-02-05 12:11 UTC
**Is your feature request related to a problem? Please describe.**
In the full calendar event box, the event title is highlighted automatically when creating a new item. In the simple event editor, this is not the case. You have to click the event title first.

**Describe the solution you'd like**
Highlighting the event title in the simple editor, so that you can immediately start typing when after having defined a time window in the week view.

**Comment by georgehrke** [comment] 2020-02-16 18:25
Duplicate of https://github.com/nextcloud/calendar/issues/1930

**Closed by georgehrke** 2020-02-16 18:25 UTC
Labels: 0. to triage, enhancement-proposed
