### ISSUE TITLE
UX improvement for the popup newevent form 

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/calendar#1386] opened 2019-08-05 08:14 UTC
### Steps to reproduce
1. Click on any day to create a new event;
2. Click outside the popover window

### Expected behaviour
The popup event form closes.

### Actual behaviour
The popup event form closes and a new one is opened on a different day.

**Comment by georgehrke** [comment] 2019-08-05 08:16
Duplicate of https://github.com/nextcloud/calendar/issues/899

**Closed by georgehrke** 2019-08-05 08:16 UTC
