### ISSUE TITLE
Calendar irresponsive / stuck - can not access settings (or any other action in the calendar)

### ISSUE THREAD

**Issue by naelfe** [nextcloud/calendar#4319] opened 2022-06-24 16:34 UTC
### Steps to reproduce

1. login to nextcloud
2. access the calendar app (either via icon, or https://nextcloud.your.domain/apps/calendar
![image](https://user-images.githubusercontent.com/108142825/175574873-43b1b37e-e10d-4132-bf95-6b0107d43186.png)

### Expected behavior

I would like to add events, hide, add or remove calenders, access the settings, etc.

### Actual behaviour

The page does open, but I can not click on anything. It is totally unresponsive. Chrome + FireFox both say the page is slow and wan't me to wait or leave.
![image](https://user-images.githubusercontent.com/108142825/175575451-f390dfb3-46dd-49b8-8ac9-66ea5cfbf4a0.png)
The circle border for my work-calendar is permanently spinning.
RAM consumption (chrome + ff) both increase periodically (~4seconds) for 200MB, than drop back to the startingvalue and increase again.

### Calendar app version

3.4.0

### CalDAV-clients used

iOS Calendar

### Browser

Chrome 102.0.5005.115, Edge (same Version), Firefox 101.0.1

### Client operating system

Windows 11 21H2

### Server operating system

Docker

### Nextcloud version

24.0.2

### List of activated apps

```Text
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - news: 18.1.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.3.0
  - richdocuments: 6.1.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_email: 2.4.0
  - unsplash: 1.2.5
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - announcementcenter: 6.3.1
  - circles: 0.21.4
  - encryption
  - files_antivirus: 3.3.0
  - keeweb: 0.6.9
  - maps: 0.1.10
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "nextcloud.my.domain"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.2.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***:2443",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "trashbin_retention_obligation": "30, 60",
        "default_phone_region": "DE"
    }
}
```

### Browser log

```Text
Network Log does not have any other status than 200 + 207
```

### Additional info

Wow... when trying to export the browser logs I found a workaround, but first my initially suspected cause:

I do have my personal and contactbirthday default calendars included. Additionally I shared my office365 work calender as read-only subscription.
Today we have a MS tenant migration which might have broken all existing sharings for offce (teams, sharepoint) and outlook calendars.
-> That is why I suspect the calendar-app to be hung up trying to read the no longer accessible calendar-subscription.

Problem **was**: due to the unresponsive ui, I could not remove it, which is why I wanted to add this issue in the first place.

**Workaround:**

- When I tried chrome to get the browserlogs, nothing happened on the /apps/calendar page. So I opened the dev-tools on the nextcloud dashboard and clicked on the calendar icon after they were open.
- then, then (due to the smaller windowsize I guess?) the calendar-page opend with the minimized navigation, BUT I could open it again and everything was clickable -> the office 365 subscription calendar could be removed.

I guess there should be a timeout / read-/access error exception that simply stops the subscription from permanently trying to load. But I have no idea how to do it.

**Comment by kadrim** [comment] 2022-06-25 10:58
same here

**Comment by bentwnghk** [comment] 2022-06-25 12:32
Only when loading the Calendar app **in monthly view** does it get unresponsive; it loads normally in weekly and other modes.

And it seems to affect desktop or laptop browsers only; there is no such issue in my iPhone, iPad or Samsung Galaxy Tablet.

**Comment by st3iny** [comment] 2022-06-25 15:38
Duplicate of #4313.

**Closed** 2022-06-25 15:38 UTC
Labels: bug, 0. to triage

**Comment by pwnoobz** [comment] 2022-11-12 14:12
Same here. Hanging on the calendar in any browser.
