### ISSUE TITLE
New calendar subscriptions via .ICS import not showing up

### ISSUE THREAD

**Issue by Goose-Tech** [nextcloud/calendar#1884] opened 2020-01-22 04:16 UTC
### Steps to reproduce
1. Click + to add new calendar and click "New subscription from link"
2. Paste link
3. No entries show up on the calendar

### Expected behaviour
Tell us what should happen

### Actual behaviour
Calendar is added to the list, but no entries appear

### Calendar app
2.0.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
Web UI
Thunderbird Lightening
DAVx5

### Client configuration
Firefox 72.0.1

**Operating system:** (e.g. Arch Linux)
Windows10
Manjaro (Arch) Linux

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu Server 18.04

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
7.2

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
17.0.2

**Updated from an older installed version or fresh install:**
Fresh install, native, not snap

**List of activated apps:**
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.1
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtptimeout": "30"
    }
}

#### Web server error log (e.g. /var/log/apache)
```
[Tue Jan 21 06:25:01.968245 2020] [mpm_prefork:notice] [pid 1190] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jan 21 06:25:01.968268 2020] [core:notice] [pid 1190] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 22 02:57:43.615917 2020] [autoindex:error] [pid 24999] [client 192.168.10.125:64459] AH01276: Cannot serve directory /var/www/html/apps/calendar/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Wed Jan 22 02:57:58.914876 2020] [autoindex:error] [pid 31416] [client 192.168.10.125:64471] AH01276: Cannot serve directory /var/www/html/apps/calendar/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Wed Jan 22 02:58:13.665671 2020] [autoindex:error] [pid 31826] [client 192.168.10.125:64477] AH01276: Cannot serve directory /var/www/html/apps/calendar/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Wed Jan 22 02:59:10.261933 2020] [mpm_prefork:notice] [pid 1190] AH00169: caught SIGTERM, shutting down
[Wed Jan 22 02:59:24.328806 2020] [mpm_prefork:notice] [pid 1275] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Jan 22 02:59:24.329269 2020] [core:notice] [pid 1275] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 22 03:00:11.672301 2020] [autoindex:error] [pid 1300] [client 192.168.10.125:64519] AH01276: Cannot serve directory /var/www/html/apps/calendar/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Wed Jan 22 03:29:25.907532 2020] [php7:error] [pid 2455] [client 220.191.249.136:51090] script '/var/www/html/elrekt.php' not found or unable to stat
[Wed Jan 22 03:38:09.484456 2020] [mpm_prefork:notice] [pid 1275] AH00169: caught SIGTERM, shutting down
[Wed Jan 22 03:38:09.602736 2020] [mpm_prefork:notice] [pid 4095] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Jan 22 03:38:09.602810 2020] [core:notice] [pid 4095] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 22 03:42:38.645622 2020] [mpm_prefork:notice] [pid 4095] AH00169: caught SIGTERM, shutting down
[Wed Jan 22 03:42:51.897126 2020] [mpm_prefork:notice] [pid 1295] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Jan 22 03:42:51.897606 2020] [core:notice] [pid 1295] AH00094: Command line: '/usr/sbin/apache2'
```

**Comment by tcitworld** [comment] 2020-01-22 07:20
Duplicate of #1843

**Closed** 2020-01-22 07:20 UTC
Labels: 0. to triage, bug
