### ISSUE TITLE
browser hangs after changing timezone of an entry

### ISSUE THREAD

**Issue by BigMichi1** [nextcloud/calendar#1493] opened 2019-09-22 16:04 UTC
### Steps to reproduce
1. add an appointment series
2. edit appointment in the series and change timezone
3. browser hangs

### Expected behaviour
browser should not freeze

### Actual behaviour
i edited an entry of a series in the calendar (changed the timezone) and after that the browser wascompletly unresponsive. now i can no longer open the calendar anymore, if completly freezes when accessing the calendar

### Server configuration

**Operating system:** Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.9 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bcmath, bz2, calendar, ctype, curl, dom, mbstring, facedetect, fileinfo, ftp, gd, geoip, gettext, gmp, horde_lz4, iconv, igbinary, imagick, imap, intl, json, ldap, libpuzzle, exif, mongodb, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, propro, raphf, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, ssh2, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, http, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Calendar version:** 1.7.1

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - bookmarks: 2.0.3
 - calendar: 1.7.1
 - circles: 0.17.7
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_external: 1.7.0
 - files_pdfviewer: 1.5.0
 - files_retention: 1.5.1
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.1.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.17.0
 - maps: 0.1.2
 - metadata: 0.9.0
 - news: 13.1.6
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.2
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.9.0
 - phonetrack: 0.5.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - socialsharing_diaspora: 1.0.4
 - socialsharing_email: 1.0.5
 - socialsharing_facebook: 1.0.4
 - socialsharing_googleplus: 1.0.4
 - socialsharing_twitter: 1.0.4
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - updatenotification: 1.6.0
 - user_external: 0.7.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - user_ldap

**Nextcloud configuration:**

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 1
    },
    "trusted_domains": [
        "mydomain.de"
    ],
    "dbtype": "pgsql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "https:\/\/mydomain.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "stable",
    "defaultapp": "apporder",
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "mydomain.de",
                143,
                "tls",
                "mydomain.de"
            ]
        }
    ],
    "app_install_overwrite": [
        "calendar"
    ]
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36

**Operating system:** Fedora 30

**CalDAV-clients:** no

#### Browser log
not able lo open

**Comment by tcitworld** [comment] 2019-09-22 16:54
Are you able to open the browser logs before opening the calendar app and seeing if there's something interesting ?

**Comment by BigMichi1** [comment] 2019-09-23 13:20
console doesn't show anything except these deprecation warnings for NC 19

the only thing i can see is that one calendar has a loading icon and cpu usage is shown in the chrome task manager with 102% and memory usage is very fast increasing up to 2 gb

**Comment by georgehrke** [comment] 2019-10-01 07:54
Do you recall what timezone you changed it to?

I tried setting to plenty of timezones but i was not able to reproduce this issue.

**Comment by BigMichi1** [comment] 2019-10-01 08:52
i was changing it from UTC to Europe/Berlin

**Comment by BigMichi1** [comment] 2019-10-01 15:26
actually i was now able to get the response of the url that hangs when it is requested via the calendar app, maybe it helps

https://pastebin.com/EfaYm8bE

**Comment by georgehrke** [comment] 2019-10-18 21:20
Ah, it's those bloody Horde timezone definitions.

Closing as duplicate of https://github.com/nextcloud/calendar/issues/642

**Closed by georgehrke** 2019-10-18 21:20 UTC

**Comment by georgehrke** [comment] 2019-10-18 21:26
(technically, those timezone definitions are perfectly valid as of RFC5545. It's just that it's causing issues with ical.js. And imho it's completely unnecessary to ship historic timezone information from 1916)
