### ISSUE TITLE
Error on calendar subscription

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/calendar#896] opened 2018-08-25 18:11 UTC
I'd like to subscribe at NC 13.0.5 with calendar app from app store 1.6.1 an external calendar and an error occours.

Example external ical link: http://fux.zuhage.de/ics/Schulferien_2018-2019_BB.ics

```
Error: Call to a member function getUID() on null

    /var/www/clients/client39/web136/web/apps/calendar/appinfo/application.php - line 70: OCA\Calendar\Controller\SettingsController->__construct('calendar', Object(OC\AppFramework\Http\Request), Object(OC\User\Session), Object(OC\AllConfig))
    /var/www/clients/client39/web136/web/3rdparty/pimple/pimple/src/Pimple/Container.php - line 113: OCA\Calendar\AppInfo\Application->OCA\Calendar\AppInfo\{closure}(*** sensitive parameters replaced ***)
    /var/www/clients/client39/web136/web/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: Pimple\Container->offsetGet('SettingsControl...')
    /var/www/clients/client39/web136/web/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 460: OC\AppFramework\Utility\SimpleContainer->query('SettingsControl...')
    /var/www/clients/client39/web136/web/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 438: OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('SettingsControl...')
    /var/www/clients/client39/web136/web/lib/private/AppFramework/App.php - line 92: OC\AppFramework\DependencyInjection\DIContainer->query('SettingsControl...')
    /var/www/clients/client39/web136/web/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('SettingsControl...', 'setConfig', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/clients/client39/web136/web/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/clients/client39/web136/web/lib/base.php - line 999: OC\Route\Router->match('/apps/calendar/...')
    /var/www/clients/client39/web136/web/index.php - line 42: OC handleRequest()
    {main}
```

**Comment by georgehrke** [comment] 2019-08-30 19:25
Duplicate of #1215

**Closed by georgehrke** 2019-08-30 19:25 UTC
