### ISSUE TITLE
Some icons missing when webroot is not /

### ISSUE THREAD

**Issue by streichgeorg** [nextcloud/calendar#903] opened 2018-09-06 22:36 UTC
### Steps to reproduce
1. Set up nextcloud behind a nginx proxy.

**Nginx location block**
```
location /nextcloud {
    rewrite ^/nextcloud(.*) $1 break;
    proxy_pass          http://127.0.0.1:8000;
}
```

**Changes to config.php**
```
'overwritehost' => 'mydomain.com',
'overwriteprotocol' => 'https',
'overwritewebroot' => '/nextcloud',
```

2. Open the calendar tab in the nextcloud web app.

### Expected behaviour
The browser can display the arrow icons next to day, week, month label, it should load them from https://mydomain.com/nextcloud/extra-apps/calendar/img.
<img width="299" alt="view_week_expected" src="https://user-images.githubusercontent.com/16862886/45188502-e1bb6b80-b234-11e8-9abd-6280d5fe7e5b.png">

### Actual behaviour
The browser can't display the icons because it tries to load them from https://mydomain.com/extra-apps/calendar/img (/ instread of /nextcloud).
<img width="299" alt="view_week_expected" src="https://user-images.githubusercontent.com/16862886/45188564-21825300-b235-11e8-8abb-67c2e10399ae.png">

This only happens in the calendar tab to my knowledge, the icons in the other tabs/views seem to work fine.

## Server configuration detail

**Operating system:** Linux 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64

**Webserver:** Apache/2.4.34 (Unix) (fpm-fcgi)

**Database:** mysql 5.7.22

**PHP version:** 

7.1.20
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, mcrypt, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 13.0.5 - 13.0.5.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Installed as a snap

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - calendar: 1.6.1
 - comments: 1.3.0
 - dav: 1.4.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.7
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - files_pdfviewer
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "mydomain.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/mydomain.com",
    "dbtype": "mysql",
    "version": "13.0.5.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "overwritehost": "mydomain.com",
    "overwriteprotocol": "https",
    "overwritewebroot": "\/nextcloud"
}
```
</details>

**Are you using external storage, if yes which one:** No
**Are you using encryption:**  No
**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Operating system:** Ubuntu 16.04.5 LTS (Xenial Xerus)

## Logs

<details><summary>Browser log</summary>

```
```
</details>

<details><summary>Nextcloud log</summary>

```
```
</details>

<details><summary>Browser log</summary>
</details>

**Comment by georgehrke** [comment] 2018-09-08 08:58
> The browser can display the arrow icons next to day, week, month label, it should load them from

There are no icons next to the views.
Can you please provide proper logs so we can see what's missing? Thx!

**Comment by georgehrke** [comment] 2018-09-08 09:07
Oh, next to the date picker, not next to the icons. Nevermind then, sorry.

**Comment by didierm** [comment] 2018-09-26 15:01
We are experiencing exactly the same issue.

We use webroot to run multiple NC instances. Instead of retrieving the two arrow images (leftarrow.svg and rightarrow.svg) from their proper location (e.g. GET **/sandbox**/apps-appstore/calendar/img/leftarrow.svg) , downloading fails : 
`"GET /apps-appstore/calendar/img/leftarrow.svg HTTP/1.1" 404 238`

The error is due to the webroot being removed from the path when the css file is constructed from the sccs template, apparently being invoked in _**./lib/private/Template/SCSSCacher.php**_ : 
https://github.com/nextcloud/server/blob/ff55bcdad5c2c36375c41eb641b87bc70967e384/lib/private/Template/SCSSCacher.php#L447 (originally authored by @skjnldsv), which is called in https://github.com/nextcloud/server/blob/ff55bcdad5c2c36375c41eb641b87bc70967e384/lib/private/Template/SCSSCacher.php#L308 .



The exact same erroneous behaviour also occurs with e.g. the _group.svg_ file from the Contacts app 
 (as defined in file _./contacts/css/style.css:_  background-image: url("../img/group.svg"); })

**Comment by skjnldsv** [comment] 2018-09-26 17:34
@didierm this is an issue which have been fixed iirc.
What version are you using?

**Comment by didierm** [comment] 2018-09-26 17:44
@skjnldsv John, thanks for your swift reply.
This is happening with both versions **13.0.0** and **14.0.0**.

**Comment by didierm** [comment] 2018-09-27 13:17
Stopgap fix (to be re-run when any app is installed or upgraded) : 

* variables : 
```
NCPATH=/srv/nextcloud/
WEBROOT=cloud00
```

* css fix :
```
STROLD="url('\/apps-appstore\/"
STRNEW="url('\/${WEBROOT}\/apps-appstore\/"
for CSS in $(grep -rl "${STROLD}" $NCPATH/$WEBROOT/data/appdata_*/css/*/*.css); do
  echo "Processing : ${CSS}"
  sed -i "s/${STROLD}/${STRNEW}/g" "${CSS}"
  gzip -c "${CSS}" > "${CSS}.gzip"
done
```
* update/clean cache(s) : 
```
occ files:scan-app-data -v
redis-cli -s /var/run/redis/redis.sock flushall
```

**Comment by didierm** [comment] 2018-09-28 08:07
@georgehrke remove label "unconfirmed" ?

**Comment by skjnldsv** [comment] 2018-09-28 08:15
Actually it's a server bug. So it's not related to the calendar :)
have you tried doing a maintenance:repair with occ to clear the cache?

It will regenerate the css & gzip files

**Comment by didierm** [comment] 2018-09-28 09:27
Yes, I did run the maintenance:repair.
As I could reproduce the bug with the Contacts app, I figured this to be a NC/server bug/regression.

I leave it at your discretion to link this to the appropriate server commit/issue ?

**Comment by georgehrke** [comment] 2019-08-25 13:19
As @skjnldsv said above, this is a server issue and not caused by the calendar app.
Closing

**Closed by georgehrke** 2019-08-25 13:19 UTC
Labels: 1 - to develop, bug
