### ISSUE TITLE
Sharing a calendar with groups doesn't get saved (v2.0.1)

### ISSUE THREAD

**Issue by DBJRdev** [nextcloud/calendar#1893] opened 2020-01-24 11:04 UTC
### Steps to reproduce
1. Share a calendar with a group -> it looks as if it's accepted
2. Reload: the share was not saved
3. side note: sharing with a single user still works correctly
Problem appears since calendar upgrade this morning via web interface

### Expected behaviour
Sharing with a group should be possible as before

### Actual behaviour
Shared with group is not saved

### Calendar app
**Calendar app version:** 2.0.1

### Client configuration
**Browser:** (e.g. Firefox 48)
Tested on 
* Firefox 72.0.1 on Ubuntu 19.10
* Firefox 68.4.2 ESR on Windows 10 1803
* Safari on iPad (latest versions)
* Microsoft Edge (not the new Chromium engine) on Windows 10 1803

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySQL

**PHP version:** 
7.3

**Nextcloud Version:**
17.0.2

**Updated from an older installed version or fresh install:**
Updated since 17.0

**List of activated apps:**

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.9.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - deck: 0.8.0
  - encryption: 2.5.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_antivirus: 2.2.1
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.5
  - groupquota: 0.1.2
  - guests: 1.3.1
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.0.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.1
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocr: 5.0.4
  - ojsxc: 4.0.0-rc.1
  - password_policy: 1.7.0
  - polls: 1.0.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - ransomware_protection: 1.5.1
  - recommendations: 0.5.0
  - richdocuments: 3.5.1
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_nextcloud_notification: 2.2.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

**Comment by georgehrke** [comment] 2020-01-24 11:06
@DBJRdev Are you talking about system groups defined by admins or user-defined groups (circles)?

**Comment by DBJRdev** [comment] 2020-01-24 11:07
@georgehrke : the system-wide user groups

**Comment by DBJRdev** [comment] 2020-01-24 11:10
One additional info: we upgraded from calendar 1.7.2 to 2.0.1, that's when the break happened

**Comment by georgehrke** [comment] 2020-01-24 11:51
I can't reproduce this. Does the group-name contain anything special like special characters, emojis or umlauts?

**Comment by georgehrke** [comment] 2020-01-24 12:09
And can you please provide the Nextcloud and browser log? Are there any failed requests in the network tab of the browser?

**Comment by DBJRdev** [comment] 2020-01-24 12:15
You're right: the group was called "DBJR-Geschäftsstelle"... and after your hint I tried a group called "test", then the sharing works. So it's about either the dash or the ä...
Does that help or you still need logs?

**Comment by georgehrke** [comment] 2020-01-24 12:16
Thanks!

I don't think I will need logs for now. Let me try to reproduce it again.

**Comment by georgehrke** [comment] 2020-01-24 12:20
I was able to reproduce it with Umlauts. Dash does not cause any errors.

**Comment by DBJRdev** [comment] 2020-01-24 12:25
Thanks for the superfast response! 

I'll stand by if any patch should be tried out :)

**Comment by major-mayer** [comment] 2020-01-25 17:20
I would like to add that whitespaces " " also prevent the added group from being saved.
BTW is it normal that, if you invite someone who also has access to the shared calendar, the event appears twice in his/ her calendar?

**Comment by georgehrke** [comment] 2020-01-25 18:16
> BTW is it normal that, if you invite someone who also has access to the shared calendar, the event appears twice in his/ her calendar?

Yes, because the event is automatically saved into all attendees calendars.
So this is the expected behaviour.

Please see #1329. We are planning to hide duplicate events.

**Comment by major-mayer** [comment] 2020-01-25 18:36
Thanks, seems to be a lot of background story related to this issue.
So in future i cannot invite any participants to a event that is in a shared calendar anymore?

**Comment by georgehrke** [comment] 2020-01-25 18:39
> So in future i cannot invite any participants to a event that is in a shared calendar anymore?

You will be able to invite attendees even if you share the calendar with them. Not sure where i said something different?

**Comment by major-mayer** [comment] 2020-01-25 18:45
Okay I'm sorry, seems like I misread something.
I thought this will be disabled because it's not in the webcal standard.

**Comment by georgehrke** [comment] 2020-01-26 16:05
Duplicate of https://github.com/nextcloud/server/issues/17610

**Closed by georgehrke** 2020-01-26 16:05 UTC
Labels: 0. to triage, bug

**Comment by DBJRdev** [comment] 2020-01-26 19:43
@Georg: I think nextcloud/server#17610 must have a different reason, because the sharing to "DBJR-Geschäftsstelle" worked fine just until the day before. The proof is that we can still see the calendar shares from the days before, but not add new ones. (If that difference is clear to you, then consider this comment irrelevant)
