### ISSUE TITLE
Appointments Talk integration

### ISSUE THREAD

**Issue by ChildLearningClub** [nextcloud/calendar#4680] opened 2022-10-25 05:01 UTC
### Is your feature request related to a problem? Please describe.

Many appointments are online now, I'm sure this is already being worked on, but if not, having the option to auto generate a talk link and add it to the appointment email similar to how the appointments app does it.

### Describe the solution you'd like

Admin can chose if they want to enable the option to generate online meeting links.

**Comment by ChristophWurst** [comment] 2022-10-25 12:43
Duplicate of https://github.com/nextcloud/calendar/issues/3480

**Closed by ChristophWurst** 2022-10-25 12:43 UTC
Labels: enhancement, 0 - to triage

**Comment by ChildLearningClub** [comment] 2022-10-26 07:20
Sorry @ChristophWurst, searched and didn’t see the other.

**Comment by ChristophWurst** [comment] 2022-10-26 09:18
No problem
