### ISSUE TITLE
shared users e-mail hiding behind main calendar section

### ISSUE THREAD

**Issue by markuswochnik** [nextcloud/calendar#1717] opened 2019-12-11 20:22 UTC
Hello, 
i don't really know how can i better explain it, so here a picture of the problem.
When hovering over the shared person, the email ist cropped and it looks like its "behind" the main section.

![nxc-calendar-beta3bug](https://user-images.githubusercontent.com/7039362/70657386-02eee100-1c5c-11ea-90b0-5abdc2ccccd0.png)

Nextcloud Version: 17.0.1
Calendar Version: 2.0.0 beta3
Firefox Version: 71.0

**Comment by georgehrke** [comment] 2019-12-12 15:02
I would consider this a bug in nextcloud/vue

@tcitworld Agree?

**Comment by tcitworld** [comment] 2019-12-12 15:39
Absolutely.

**Comment by georgehrke** [comment] 2020-01-10 11:23
Closing as Duplicate of https://github.com/nextcloud/nextcloud-vue/issues/801

**Closed by georgehrke** 2020-01-10 11:23 UTC
Labels: 1 - to develop, bug
