### ISSUE TITLE
Problem Importing (and then syncing) Only Certain Google ICS Secret Feeds

### ISSUE THREAD

**Issue by ChuckStrusz** [nextcloud/calendar#3617] opened 2021-11-08 11:20 UTC
### Steps to reproduce
1. Add new Calendar to NC Calendar - "New Subscription From Link (read-only)"
2. Paste in "Secret Address in iCal format" for PRIMARY/MAIN Google Calendar.
3. Get popup "_An error occurred, unable to create the calendar_." - Browser Console shows error 500 ("failed to load resource" at https://SOME.LOCAL.IP/nextcloud/remote.php/dav/calendars/admin/calendargooglecom-1
4. Calendar **does not appear**.  Refresh page and it appears, but _future events are NOT synced. (**I have CRON running every 5 minutes, and have verified it is running - I also set the webdav/cal sync setting to "PT5M"**).

- I created a NEW Calendar, with one event - when I paste in that secret Google ICS URL, all works as expected! No errors on load, and new events are synced properly.
- My NextCloud log references an error ""_SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'lastoccurence' at row 1_" - assuming this had to do with recurring events, I removed ALL my recurring events and tried again - still the same result.
- My MariaDB log show **no errors**.  HTTP log, PHP log, and system messages show **no errors**.  The only error is in the nextcloud.log file, and it appears to have redacted the stuff that might help me track down the problem event(s).  

### Expected behaviour
Calendar should be added without an error AND future events **synced**.

### Actual behaviour
Error happens, calendar only appears with page refresh, future sync **does not work** - new events never appear.

### Calendar app
**Calendar app version: **  2.3.4

**CalDAV-clients used:**  NONE - adding Google ICS link

### Client configuration
**Browser:** Chrome 95.0.4638.69

**Operating system:** Windows 10 Pro 20H2

### Server configuration

**Operating system**:  CentOS 8

**Web server:** Apache 2.4.37

**Database:** MariaDB 10.3.28

**PHP version:** PHP 7 .4.25

**Nextcloud Version:** 22.2.0

**Updated from an older installed version or fresh install:**  FRESH INSTALL

**List of activated apps:**
  - accessibility: 1.8.0
  - activity: 2.15.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - collectives: 0.15.22
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.3
  - external: 3.9.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.10.5
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - onlyoffice
  - user_ldap

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'instanceid' => 'REMOVED',
  'passwordsalt' => 'SECURED',
  'secret' => 'SECURED',
  'trusted_domains' =>
  array (
    0 => 'x.x.x.x',
  ),
  'datadirectory' => '/REDACTED/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
  'overwrite.cli.url' => 'http://x.x.x.x.x',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'USER',
  'dbpassword' => 'PASSWORD',
  'installed' => true,
  'allow_local_remote_servers' => true,
);

```

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "x.x.x.x"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "overwrite.cli.url": "http:\/\/x.x.x.x",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "allow_local_remote_servers": true
    }
}

```
#### Web server error log (e.g. /var/log/apache)
```
There really isn't anything useful in the web server logs. errors or not.  I'll happily provide them, but suspect it won't help.
```

#### Log file (data/nextcloud.log)
The nextcloud log messages are fairly verbose - I have attached the full log from the attempt in question, and pasted in what I suspect may be the most relevant portion(s) here.

```
"user":"admin","app":"webdav","method":"MKCOL","url":"/nextcloud/remote.php/dav/calendars/admin/calendargooglecom","message":"An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'lastoccurence' at row 1"

{"file":"/var/www/html/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":335,"function":"wrap","class":"OC\\DB\\Exceptions\\DbalException","type":"::"},{"file":"/var/www/html/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php","line":1305,"function":"executeStatement","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php","line":144,"function":"createCalendarObject","class":"OCA\\DAV\\CalDAV\\CalDavBackend","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/AppInfo/Application.php","line":283,"function":"refreshSubscription","class":"OCA\\DAV\\CalDAV\\WebcalCaching\\RefreshWebcalService","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\DAV\\AppInfo\\{closure}","class":"OCA\\DAV\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]}

```

**You can see above that "sensitive parameters replaced"** - I suspect that's what I need to help me track down the troublesome events, right?  How can I expose that info?

#### Browser log
```
Insert your browser log here, this could for example include:

index.js:46 No OC found
Fr @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
ProxyBus.js:72 Proxying an event bus of version 1.3.0 with 2.0.0
e.ProxyBus @ ProxyBus.js:72
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
ProxyBus.ts:17 Proxying an event bus of version 1.3.0 with 2.0.0
t @ ProxyBus.ts:17
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
ProxyBus.js:72 Proxying an event bus of version 1.3.0 with 2.0.0
e.ProxyBus @ ProxyBus.js:72
ConsoleLogger.js:33 [INFO] calendar: 
Initial settings:
	- AppVersion: 2.3.4
	- EventLimit: true
	- FirstRun: true
	- ShowWeekNumbers: false
	- ShowTasks: true
	- ShowWeekends: true
	- SkipPopover: false
	- SlotDuration: 00:30:00
	- DefaultReminder: none
	- TalkEnabled: true
	- TasksEnabled: true
	- Timezone: automatic
 Object
ConsoleLogger.js:33 [INFO] calendar: Updated moment locale: en Object
session-heartbeat.js:101 session heartbeat polling started
calendars.js:543 calendar home scanned Array(7) Array(1)
/nextcloud/remote.php/dav/calendars/admin/calendargooglecom:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**NextCloud Log Attached**
[nextcloud.log](https://github.com/nextcloud/calendar/files/7496529/nextcloud.log)

This seems to contain some useful info, but the stuff that might be most useful seems to have been redacted.

**Comment by ChuckStrusz** [comment] 2021-11-08 11:22
I am more than happy to assist in tracking down this problem any way I can!  I'd love to know what I can do to try and figure out which specific event(s) are causing the issue.  If you don't trust that my HTTP, SQL, and PHP logs contain no errors or anything useful, I'll happily upload them in toto.  It really is nothing except in the HTTP access_log, and it's just a bunch of successful sutff.

**Comment by ChuckStrusz** [comment] 2021-11-08 12:00
In case it was missed in the text above, new events added to my minimal "TESTING" calendar are being synced and added as expected.  That feed also does not present an error upon initial addition, nor does it require a page refresh to show the added events and new calendar.

**Comment by ChuckStrusz** [comment] 2021-11-08 12:13
I obviously don't want to post the "secret" ICS link publicly, but if it would help some dev track down the issue, I'd probably be happy to provide that link to someone - there's really nothing terribly sensitive in there.

**Comment by laribA** [comment] 2023-05-17 02:52
Can confirm this is still an issue. Will provide more details as requested.

**Comment by tcitworld** [comment] 2023-05-17 06:31
This is a duplicate of https://github.com/nextcloud/server/issues/20804.

One of the events has a datetime outside of 1970-01-01 and 2038-01-19.

**Closed by tcitworld** 2023-05-17 06:31 UTC
Labels: bug, 0 - to triage
