### ISSUE TITLE
Undefined index: defaultColor at /var/www/html/apps/calendar/templates/part.fullcalendar.php#28	

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/calendar#451] opened 2017-05-15 12:35 UTC
Undefined index: defaultColor at /var/www/html/apps/calendar/templates/part.fullcalendar.php#28	 

on c.nc.c, it seems to be triggered when opening a public calendar.

cc @georgehrke

**Comment by georgehrke** [comment] 2017-05-17 07:42
Can't reproduce with latest master anymore, hence will be fixed with the upcoming 1.5.3

**Closed by georgehrke** 2017-05-17 07:42 UTC
Labels: 1 - to develop, bug

**Comment by georgehrke** [comment] 2017-05-17 07:45
defaultColor is included in all templates since https://github.com/nextcloud/calendar/pull/372/files#diff-b143e1db4ce6ee8d3c38bca02fbb4d5dR201
