### ISSUE TITLE
open week view when cell header is clicked in month view

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/calendar#836] opened 2018-06-04 22:32 UTC
In month view clicking anywhere in the Day cell always creates an (all-day) event. 

Clicking a cell's header could instead open the Day in Week view, similarly to what Google Calendar does.

**Comment by georgehrke** [comment] 2018-06-05 12:44
@cptMikky How is this issue different from https://github.com/nextcloud/calendar/issues/796?

**Comment by cptMikky** [comment] 2018-06-05 13:10
I don't understand, #796 is completely differnet.

**Comment by georgehrke** [comment] 2018-06-05 14:17
@cptMikky It's both about what should happen when clicking a day in month view.
I don't like the idea of adding a special action to the cell header, because it's not (or barely) discoverable. cc @jancborchardt

**Comment by cptMikky** [comment] 2018-06-05 14:31
I disagree, @georgehrke. This issue is about what happens when **clicking on a specific part** of a day cell in month view while the other is about default settings when **creating an event** in month view. The only thing they (currently) share is the entry point but after that these are separate issues.

Also I strongly disagree it's "barely discoverable".  Quite the opposite, it was actually one of the first things I tried when I was testing both Nextcloud and Google calendar apps. For others there's always the documentation.

It's intuitive and makes absolute sense. One should to be able to simply "zoom in" on a more detailed view of a specific period from a month overview. From week view, in turn, one should be able to "zoom in" to the day view in the same fashion.

**Comment by ggeorgg** [comment] 2018-06-05 17:52
@cptMikky At the very end of the discussion [#796](https://github.com/nextcloud/calendar/issues/796#issuecomment-384270183) you said something about changing to the day view when clicking a day in month view. 
I don't like this proposal at all. I would leave the current behavior as it is right now. 
I even would suggest to not open the "create new event" dialog when clicking on a day, because I like to just click a day to highlight it. (So this would be the behavior like in Thunderbird Lightning). Problem is, one can not create an event that spans multiple days with one click anymore... But this suggestion is off topic here...

**Comment by cptMikky** [comment] 2018-06-05 21:13
@ggeorgg in said discussion I merely suggested that if such behavior existed in month view, the issue itself would be irrelevant (to me).

I can't help myself but to feel that all discussions here are rather heated for no apparent reason, in some cases almost hostile. Can't tell if the raeason is me or just my ideas but the way you (both) convey your thoughts makes me feel unwelcome. If that's your point just say it up straight, I have no problem with that.

So far you've pretty much said "I categorically refuse this idea because I personally dislike it" without actually giving any arguments why the idea is bad. Again, if this is the way this project is developed, I have no problem with that but say it up straight. I can take it, I'm a big boy.

**Comment by jancborchardt** [comment] 2018-06-05 22:17
> This issue is about what happens when clicking on a specific part of a day cell in month view

Two parts of the same cell having completely different effects when clicked will be confusing. I think that's what @georgehrke meant? :)


Sorry if the tone sometimes is a bit off – unfortunately that comes with non-personal text communication. I do think though in this issue it has been friendly and not heated. Please also remember that project developers get a lot of requests and it's mostly done in free time, and if you want something to be developed essentially for you, then there should be solid arguments. "It's intuitive" does not cut it unfortunately. ;)

What would help is if you do some more detailed research of how Google Calendar does it, and also others like iCloud calendar, or other calendaring solutions – with screemshots. Also remember that people more and more use touch interfaces, and small tap targets are both not usable and not discoverable or confusing.

**Comment by cptMikky** [comment] 2018-06-05 22:51
This functionality doesn't actually has to be developed - it's already there, just disabled. See fullcalendar.io demo (which NC calendar is based on), it does exactly that in the exact way I described.

The only thing needed is to set navLinks opt to true somewhere in the DayGrid instance (mind you I have exactly zero experience with javascript and have no idea what I'm talking about right now so take it with a huge grain of salt). If I knew how to do that I'd have a pull request done already.

My arguments are:

- I like it and want it (a valid argument according to what I can see in this discussion)
- Google calendar does that (I'd say Google has high quality UX designers)
- Fullcalendar.io does that - defaults to Day view but can be configured to week view
- Simplecalendar App on Android does that (to Day view)
- at least one other calenadar app on Android does that (can't remeber the name)
- the functionality is already there, it just needs to be enabled
- the link only takes about 5% of the surface of the cell making UX 95% the same, 100% if people only click inside the cell and not the header
- touch interface will be 95% unaffected

I spent last two hours digging through code I've never seen before in a language and framework I've only heard about. I'd like to help in any way I can - I've identified some lines in the code which are part of the solution and I have general idea of what needs to be done from, say, "analyst perspective".

**Comment by jancborchardt** [comment] 2018-06-06 07:44
@georgehrke maybe we can just do a pull request where we can let people beta-test?

(Regarding apps – Business Calendar 2 on Android, which is really by far the best calendar app, doesn't split functionality (cause it's too small a space - of course cause it's on mobile). When you tap a cell in month view, regardless where, there's a small popover which lists the events of the day. If no event exists there yet, the cell is marked with a + and tapping again creates a new event.)

**Comment by ggeorgg** [comment] 2018-06-06 14:15
@cptMikky Sorry, I didn't want to offend you. I am not a native speeker, so sorry if my tone is a bit rough.
I think I wouldn't mind if it is just the header that leads to the day view but I also agree with georgehrke, that it could be a problem on mobile devices.

**Comment by cptMikky** [comment] 2018-06-06 19:54
@ggeorgg no need to apologise, I don't get offended that easily.

As for touch - it doesn't even have to be the entire header, just the numer, which is in fact how it is currently implemented (and disabled). That would affect touch only marginally.

Also, is there some kind of statistics on how many people actually use NC Calendar on touch-enabled devices? As from what I see around me, everybody who uses a touch device, uses a dedicated calendar app anyway.

**Comment by georgehrke** [comment] 2019-09-13 10:59
Duplicate of https://github.com/nextcloud/calendar/issues/796#issuecomment-531193232

**Closed by georgehrke** 2019-09-13 10:59 UTC
Labels: enhancement-proposed
