### ISSUE TITLE
CALDAV support with login

### ISSUE THREAD

**Issue by rightsaidfred99** [nextcloud/calendar#3318] opened 2021-07-11 03:55 UTC
Currently Calendar is not very useful with 3rd party providers like Google. 
One can subscribe to ICS, but sometimes it takes a week to update rendering it useless. 

Google Supports CALDAV, however Calendar cannot use this because there is no mechanism to login. 

Just proposing a way to securely login to CALDAV making it compatible with other calendars.

**Comment by ChristophWurst** [comment] 2021-07-12 06:38
sounds like a duplicate of https://github.com/nextcloud/server/issues/1440 to me

**Comment by florom** [comment] 2021-07-14 11:00
Hi @rightsaidfred99 ,

I have the same problem and would appreciate such a feature.
In the meantime probably this works for you too:

https://github.com/nextcloud/server/issues/1440#issuecomment-879795954

**Comment by tcitworld** [comment] 2021-07-15 07:02
Yeah, I think the Nextcloud calendar app itself should only be used to render Nextcloud server's own calendars and webcal subscriptions. Handling more CalDAV accounts should be the job of a fully-featured calendar client (DAVx5, Thunderbird, iCal, …).

As Christoph said, the federated sharing feature would also probably match such an use case.

>  One can subscribe to ICS, but sometimes it takes a week to update rendering it useless.

You can change the refresh rate. https://docs.nextcloud.com/server/latest/admin_manual/groupware/calendar.html#refresh-rate

**Closed by tcitworld** 2021-07-15 07:02 UTC
Labels: 0. to triage, enhancement-proposed

**Comment by rightsaidfred99** [comment] 2021-07-15 10:23
Well that's a shame, most of us have private lives and work lives that are separate, but at the same time it's good to be able to see work and private calendars in the same location to avoid clashes. 

I guess it's best to just use a phone for this and not a desktop which I don't agree is ideal, thanks anyway.
