### ISSUE TITLE
l10n: One word is not localisable because it is not available at Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/calendar#3523] opened 2021-10-01 10:43 UTC
Reported by attentive translator at Transifex.

### Steps to reproduce
1. Open calendar
2. Enter new event
3. Make the event as a repeating event

See my german NC instance for example:
![grafik](https://user-images.githubusercontent.com/2069590/135606564-cc337e34-aeff-484b-8877-b535ee138da2.png)

The second item in this enumeration is not translated. The fun is the name here: "second" 😄 .

The string is not available at Transifex.

I searched GitHub and found this two occurences.

https://github.com/nextcloud/calendar/blob/d0fd1215cf8684d9f2080e771e4630d5c18dcdf0/src/filters/recurrenceRuleFormat.js#L211

https://github.com/nextcloud/calendar/blob/d0fd1215cf8684d9f2080e771e4630d5c18dcdf0/src/components/Editor/Repeat/RepeatFirstLastSelect.vue#L65

The code looks pretty good to me. All other strings are extracted and synced to Transifex.

### Expected behaviour
"Second" should be translated to "zweiter"

### Actual behaviour
String is still in english

### Calendar app
**Calendar app version:** 2.3.4

**CalDAV-clients used:** NC web calendar

### Client configuration
**Browser:** ff v92

**Operating system:** Win10

**Nextcloud Version:** v22.1.1

**Comment by rakekniven** [comment] 2021-12-01 10:44
Still the same for v3.0.1 on NC v22.2.3

**Comment by ChristophWurst** [comment] 2021-12-01 10:44
@st3iny could you maybe have a look?

**Comment by st3iny** [comment] 2021-12-01 20:06
Duplicate of https://github.com/nextcloud/calendar/issues/3441.

**Closed** 2021-12-01 20:08 UTC
Labels: 1 - to develop, bug, feature: 👅 language l10n and translations

**Comment by rakekniven** [comment] 2021-12-01 20:10
Good catch.
