### ISSUE TITLE
Updated text / layout of event boxes has some issues

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#4332] opened 2022-06-29 11:38 UTC
### Steps to reproduce

1. Open any of the views except list view
2. See that there’s weird line breaking between time and title which wasn’t there before

Not sure if this has to do either with the introduction of the icons for events being shared and having reminders, or changing from ellipsizing to showing the full event name, or both.

### Expected behavior

**Month view** should only have 1 line per event. Only show start time of the event, and ellipsize the title. Icons for reminder and shared state are not necessary here as there is simply no space. Ref Google Calendar and Outlook (note Outlook has these "event icons" in front of the title which can be customized, let’s ignore those):
![image](https://user-images.githubusercontent.com/925062/176426635-2a103414-bada-4c19-9e5a-4be1370a6e76.png)
![image](https://user-images.githubusercontent.com/925062/176427393-8d730b8f-a015-4aed-85b6-049b0befdc5b.png)

-----

**Week view and day view** should have the text of the event first. The time (both beginning and end) in the last possible line, and the icons if at all can go on the same line as the time, on the right. That way it doesn’t cut anything from the title.
![image](https://user-images.githubusercontent.com/925062/176426369-1c8d3602-3381-445d-865c-7ad47480dc1a.png)

Outlook doesn’t even show the time in the event bubble itself (which I find a bit too little info tbh and especially for Friday/Sat/Sun events you have to jump to the left:
![image](https://user-images.githubusercontent.com/925062/176427600-74fec827-a819-4e51-bebd-43dd539aa699.png)

### Actual behaviour

There is always 1 line with the time and then it breaks for the text:
![image](https://user-images.githubusercontent.com/925062/176418951-61126788-57e4-4a69-95a4-7952cbacd967.png)

In the day and week view there was even this curiosity – first even breaks without needing to, and the second event for some reason has a small title?
![image](https://user-images.githubusercontent.com/925062/176419095-2dfc1f83-da09-4b39-a356-7d4063af47bc.png)

### Calendar app version

3.4.0

### Browser

Firefox 102.0b7

### Client operating system

Ubuntu 20.04

### Server operating system

cloud.nextcloud.com

### Nextcloud version

24

**Comment by Zaxooy** [comment] 2022-06-29 23:45
Just to add another point of this issue: After the latest update (3.4.1) in the monthly view the colors of events having a time are missing (tried 2 different browsers):
![grafik](https://user-images.githubusercontent.com/16104343/176563871-0856a3ce-8731-48bc-a3cf-37fc0f437231.png)

**Comment by ChristophWurst** [comment] 2022-06-30 07:52
That is because of https://github.com/nextcloud/calendar/pull/4324. We had to accept the design regression so the calendar renders at least. 

> Same issue or we create an other one ?

https://github.com/nextcloud/calendar/issues/4290.

**Comment by dinosmm** [comment] 2022-06-30 08:46
This is a much better report for [#4316](https://github.com/nextcloud/calendar/issues/4316), am I understanding correctly that these layout problems have now been acknowledged as a bug and will be worked on for a future version?

**Comment by daumas-git** [comment] 2022-06-30 10:27
For me the events overflow on the others, with last version :  
![image](https://user-images.githubusercontent.com/108462855/176655440-fe637195-056a-4f6c-913a-c7e726556477.png)

**Comment by genofire** [comment] 2022-07-02 07:57
Same problem like @daumas-git -> we downgrade from 3.4.1 to 3.3.2 - (no idea when this happens on 3.4.0 or 3.4.1)

**Comment by manicmarvin** [comment] 2022-07-04 09:45
Same problem as well. Cannot afford to downgrade right now, hoping this will be fixed with a patch soon soon soon. 🙏🏽

**Comment by ygoe** [comment] 2022-07-04 20:07
I upgraded to the latest version now and found out that the calendar UI is again broken. It's broken after so many upgrades. I'm wondering if anybody takes a look at this before releasing?

Now in the week view, the text of most appointments flows out of the box at the bottom. Can't show a screenshot because I couldn't find a good example without confidential information.

**Comment by ygoe** [comment] 2022-07-05 10:24
No, didn't see that, and I don't understand the reasons behind it. Hm, you had to accept partially unreadable rendering to have some rendering at all. Neither of these options sound like a good reason for a public release. I could have postponed that update, now I'll have to live with it for another month or so. Please exclude such updates with major known issues from the auto-upgrade in the settings UI or at least put a warning on them about what will break.

**Comment by pm-pm** [comment] 2022-07-05 13:55
> > I'm wondering if anybody takes a look at this before releasing?
> 
> Did you read [#4332 (comment)](https://github.com/nextcloud/calendar/issues/4332#issuecomment-1170887955)? We were aware.

Hi,
i read #4332, but I didn't understand why this had to happen and why no one had recognised it. 

**Maybe someone can explain to us why such big design errors (have to) be actively taken over?**

Thanks.
pm-pm

**Comment by ChristophWurst** [comment] 2022-07-05 14:00
Then feel free to read up and get some context for this ticket. The bug wasn't always reproducible. We do QA before each release but can't test all possible views. This is highly unfortunate and we are doing our best to resolve this. Two people are working on this.

I'm going to collapse the unrelated comments. It's merely wrong assumptions and false claims like we intentionally broke something.

**Comment by ChristophWurst** [comment] 2022-07-06 11:53
Fixed with https://github.com/nextcloud/calendar/pull/4351

**Closed by ChristophWurst** 2022-07-06 11:53 UTC
Labels: 2 - developing, bug, design, Feature: Fullcalendar, regression, blocked

**Comment by JuliaKirschenheuter** [comment] 2022-07-06 11:57
I've started to fix several visual bugs. But then saw very weird behavior with reactivity https://github.com/nextcloud/calendar/issues/4336 and https://github.com/nextcloud/calendar/issues/4334. Right now it is not possible to continue with this ticket, because the way of using EventRender.vue is unfortunately wrong, and as an easy/quick fix was to revert this changes: https://github.com/nextcloud/calendar/pull/4351. 

- First the right way of using EventRender.vue should be found
- Then the design / css could be adapted to the new structure

**Comment by miaulalala** [comment] 2022-07-06 14:48
I just released a pre- release for Calendar (v3.4.2-RC.1). Can people test and give us feedback if possible?

Thanks!!! :pray:

**Comment by dinosmm** [comment] 2022-07-06 16:44
>       * events with too-long-to-fit titles are truncated so they fit (with ellipsis…) exactly in a column

I am away and not able to test this at the moment - are events now back on a single line in month view, regardless of whether they have a notification icon or not?

**Comment by rigrig** [comment] 2022-07-06 16:55
They are back on a single line, but without any icons:   
![image](https://user-images.githubusercontent.com/2941436/177602652-e18f46ca-0bc5-4cca-8001-7299cae5d3c7.png)

Didn't think to test that before, but setting a reminder does *not* show up as icon (in any view mode)

**Comment by miaulalala** [comment] 2022-07-06 17:22
> They are back on a single line, but without any icons: ![image](https://user-images.githubusercontent.com/2941436/177602652-e18f46ca-0bc5-4cca-8001-7299cae5d3c7.png)
> 
> Didn't think to test that before, but setting a reminder does _not_ show up as icon (in any view mode)

Yeah this has been reverted (https://github.com/nextcloud/calendar/issues/3162) for now. We're working on getting the events back!

Thanks for testing!

**Comment by dinosmm** [comment] 2022-07-06 17:25
> Yeah this has been reverted (#3162) for now. We're working on getting the events back!

Once the icons are back, will the events stay as one-liners please, rather than revert to the difficult-to-read two-liner format?
