### ISSUE TITLE
[Feature Request] Meeting Scheduling Functionality

### ISSUE THREAD

**Issue by jsc144** [nextcloud/calendar#805] opened 2018-04-23 04:19 UTC
This isn't exactly a feature request as I am already implementing the feature along with a group of peers, but I couldnt think of a better tag (pull request warning?).  We would love to see the capabilities of nextcloud calendar expanded to allow for secure meeting scheduling. 

Our current idea is to maintain a table separate from those maintained by CalDav/Sabre so that sensitive data used for the caldav protocol is obscured. We would begin by implementing one to one meeting scheduling. This would be useful in a variety of settings. In a school setting, teachers could use this to schedule meetings with students and parents. In a business setting, it could be used to book appointments with clients. We could expand the functionality to offer one to many meeting scheduling as well, i.e. something somewhat analogous to  https://doodle.com/

The calendar app is already a huge reason why nextcloud is so popular, and expanding that functionality to tap into other markets could potentially bring an explosive surge of clients and developers to nextcloud in general. I believe that this could truly differentiate nextcloud calendar from the rest, but I'd also love to hear the community's opinion and input on the issue.

**Comment by georgehrke** [comment] 2018-04-23 15:58
> We would love to see the capabilities of nextcloud calendar expanded to allow for secure meeting scheduling.

We are already offering Free/Busy support for scheduling events via CalDAV. What's missing is the GUI inside the Nextcloud calendar: #39 

> Our current idea is to maintain a table separate from those maintained by CalDav/Sabre so that sensitive data used for the caldav protocol is obscured.

Why do you want to obscure it and how is the calendar app supposed to use it. The calendar app is just a CalDAV client as well. Generally i consider having Free/Busy access via CalDAV is a feature not a bug.

**Comment by jsc144** [comment] 2018-04-23 16:07
We considered performing this through the caldav scheduling protocol, however our client(i.e. the professor) wished for these scheduling requests to be accessible by public users and for the chosen meeting to be autopopulated into the sender's (who sent the invite) calendar. We opted to obscure our info so that we could ensure security for the autopopulation step. I.E. we wanted to protect against attackers creating forged appointments in the sender's calendar. To my knowledge, there would be no way of working with CalDav to ensure this without changing Nextcloud Server.

**Comment by jsc144** [comment] 2018-04-28 00:45
So I just want to be sure, the only goal for the nextcloud calendar app is to be a caldav client right? No other functionality is desired?

**Comment by georgehrke** [comment] 2018-04-28 10:42
Whatever possible should be done via CalDAV so it's not only available in the browser but also via all other clients. For stuff that's not available in vanilla CalDAV, we should define our own extensions. (Looking at the files app, comments and trashbin are also managed via WebDAV)

> wished for these scheduling requests to be accessible by public users

Public users can also access CalDAV. The entire public calendar sharing is using CalDAV as well.
That's why i was talking about allowing multiple public calendar shares in the other ticket.
You would want to have support for multiple tokens, so you can have tokens that allow read-only access while also having tokens that allow read-write access to the same calendar. similarly for calendars that display all information vs. calendars that display only busy values.

> We opted to obscure our info so that we could ensure security for the autopopulation step. I.E. we wanted to protect against attackers creating forged appointments in the sender's calendar.

I still don't get this. What exact info do you want to obscure and how exactly is that helping to protect spamming?

**Comment by jsc144** [comment] 2018-04-28 14:55
> We opted to obscure our info so that we could ensure security for the autopopulation step. I.E. we wanted to protect against attackers creating forged appointments in the sender's calendar.

What I mean by this is that we dont allow access to the tables used by CalDav without going through CalDav. Essentially the only tables users (public or NC) can access directly are the tables that we defined. And even to access our tables, it requires either a UID fetched serverside (for nextcloud users) or the public share token along with our scheduling token. When the appointment is "auto-populated" we access our tables and find all of the confirmations for a user. These confirmations are checked for validity  and, in the case where theyre valid, we perform a caldav request to add the event into the right calendar layer.


> You would want to have support for multiple tokens, so you can have tokens that allow read-only access while also having tokens that allow read-write access to the same calendar.

We do this. The route uses the public sharing route plus an id and plus the token we generate. The public share token prevents unwanted users from reading the data and our password token prevents writing data. On the flipside, Sender actions that affect the DB fetch the User's UID server-side and use that to prevent forgery.

I'll push our changes to my fork of calendar (should take like 15 minutes max) so that you can check it out for yourself.

**Comment by georgehrke** [comment] 2018-05-02 15:32
@jsc144 hey, sorry for the late reply. Can you please sent a pull-request for your changes?
That would make discussing the changes much easier! Thx :)

**Comment by jsc144** [comment] 2018-05-02 20:40
sure thing!

**Comment by tbabej** [comment] 2019-08-08 19:39
@jsc144 How did this effort end up? What can be done to get this eventually merged?

**Comment by jsc144** [comment] 2019-08-15 18:53
It's pull-request #822. The code compiled fine on my computer, but the Travis-ci check failed as well as coveralls. There are also some change conflicts in app.info and l10n. 

Unfortunately the PC that I installed it on had a hard drive failure and broke. I think the main thing that could help, is debugging the error in the pull request.

**Comment by georgehrke** [comment] 2019-09-13 12:31
See https://github.com/nextcloud/calendar/pull/822#issuecomment-531218682

**Closed by georgehrke** 2019-09-13 12:31 UTC
