### ISSUE TITLE
Public calendar iframe has issues on some browsers

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#169] opened 2016-11-07 17:40 UTC
OS | Linux | Windows
----|----|----
Firefox | Works | Works
Chrome 54 | Displays the grid, not the events. When refreshed, redirect issue. | Displays the grid, not the events. When refreshed, redirect issue.
Chromium 53 | Works | Not tested
Chromium 54 | Not tested | Displays the grid, not the events. When refreshed, redirect issue.
Edge | Not available | Works
IE 12 | Not available | Displays the grid, not the events

**Comment by tcitworld** [comment] 2016-11-07 17:43
@georgehrke Can you test on Safari ?

**Comment by tcitworld** [comment] 2016-11-07 17:46
The Chrome error is `ERR_TOO_MANY_REDIRECTS`

**Comment by georgehrke** [comment] 2016-12-06 21:37
@tcitworld Do you have some example code for me?
Did you just include the iframe into an otherwise blank html file?

**Comment by georgehrke** [comment] 2016-12-17 10:51
ping @tcitworld ^ :)

**Comment by tcitworld** [comment] 2016-12-17 11:05
For instance this one works with Firefox and Chromium but not Chrome on Linux : http://www.berrylab36.org/Ouverture

**Comment by georgehrke** [comment] 2016-12-21 07:42
Safari 10 on macOS works just fine for me.

**Comment by georgehrke** [comment] 2016-12-21 08:03
<img width="916" alt="planning d ouverture - berrylab36 chromium today at 8 45 44 am" src="https://cloud.githubusercontent.com/assets/1250540/21381201/367c8a5e-c75a-11e6-96a5-1662fbde2bae.png">
<img width="1309" alt="planning d ouverture - berrylab36 chromium today at 8 56 09 am" src="https://cloud.githubusercontent.com/assets/1250540/21381402/5d707354-c75b-11e6-93d0-9cb714d07155.png">
<img width="1124" alt="planning d ouverture - berrylab36 chromium today at 8 47 24 am" src="https://cloud.githubusercontent.com/assets/1250540/21381202/376df0b0-c75a-11e6-82b0-ef1f4bd781cb.png">

I see a few issues here.
To my knowledge there is no `X-FRAME-OPTIONS: ALLOW`. There is only `DENY`, `SAMEORIGIN` and `ALLOW-FROM https://...`

Further Chrom(e|ium) doesn't support X-Frame-Options.
It expects something like `Content-Security-Policy: frame-ancestors my-trusty-site.com `
Source: https://www.owasp.org/index.php/Content_Security_Policy_Cheat_Sheet#Preventing_Clickjacking

Also Chrom(e|ium) got more strict about https lately.
Maybe it's related to the fact, the berrylab36.org is http, but framagenda.org is https. (at least when sending requests like PROPFIND or so)

Maybe @LukasReschke has more insights here

**Comment by georgehrke** [comment] 2016-12-24 14:53
IE doesn't work for the same reason the calendar app itself doesn't work in Internet explorer. 

Should we display some overlay asking the user to use a different webbrowser?

**Comment by tcitworld** [comment] 2016-12-27 10:50
I guess [this](https://github.com/nextcloud/calendar/blob/master/controller/viewcontroller.php#L186-L189) needs some tweaking.

**Comment by tcitworld** [comment] 2016-12-27 10:52
Will see how https://github.com/nextcloud/server/issues/1472 handles things.

**Comment by enoch85** [comment] 2017-03-12 11:31
I can confirm this. `Got redirected to many times` Chrome version 56.0.2924.87 (64-bit)

**Comment by enoch85** [comment] 2017-03-12 11:34
Maybe my Ǹextcloud is to secure? 

```
Load denied by X-Frame-Options: https://cloud.techandme.se/apps/calendar/public/G1ZXEIKC3AGL8X4S does not permit cross-origin framing.
```

**Comment by georgehrke** [comment] 2017-03-19 14:07
> Maybe @LukasReschke has more insights here

@LukasReschke ping :)

**Comment by georgehrke** [comment] 2017-03-19 14:07
> IE doesn't work for the same reason the calendar app itself doesn't work in Internet explorer.
Should we display some overlay asking the user to use a different webbrowser?

At least IE 11 should be fixed by now

**Comment by flips** [comment] 2017-03-21 17:50
Seeing the same "<mydomain> redirected you too many times" in both Opera 43.0.2442.1165 and Chrome 57.0.2987.110. In Firefox 52.0.1 only seeing blank iframe. (macOS 10.12, all 64 bit browsers)

**Comment by georgehrke** [comment] 2017-03-21 17:51
We don't support Opera. Will definitely look into the Chrome and Firefox issue

**Comment by flips** [comment] 2017-03-21 18:09
When I used http://www.tinywebgallery.com/blog/advanced-iframe/free-iframe-checker
it also complained about the X-FRAME-OPTIONS ... (As mentioned previously here)
Placing my test.html file on the same domain as my NextCloud installation, the iFrame started working in Firefox, but not in Safari (10.0.3) or Chrome.

**Comment by georgehrke** [comment] 2017-04-02 09:44
This requires changes to the Nextcloud server, to be released with Nextcloud 12.
Rescheduling this ticket to Calendar 1.7.0

**Comment by law** [comment] 2017-08-01 08:18
Still seeing this issue on Nextcloud 12 and Chrome.  tl; dr - firefox and safari work, Chrome throws a redirect error.

**Comment by Ich5003** [comment] 2018-01-28 23:09
Error still exists.
I'd really love to add the iframe to my webpage, but sadly id still doesn't work.
Any fixes or workarounds?

**Comment by georgehrke** [comment] 2018-01-29 09:30
@Ich5003 What Browser, Nextcloud version, calendar app version?

**Comment by Ich5003** [comment] 2018-01-29 10:44
@georgehrke 
Calendar app version is 1.5.7
Nextcloud Version is 12.0.5

Google Chrome (newest version) shows "too many redirects" error in iframe
Microsoft Edge (newest version) shows the correct IFrame
Opening the embedded link in chrome directly works aswell.

Do you need some more information?

**Comment by PeteKirkham** [comment] 2018-01-30 15:22
I'm having the problem too.
framagenda embedded in yeswiki displays correctly on Firefox 58.0 but not on Chrome 63.0
Nextcloud version 12. (where do I find the subversion?)

**Comment by Ich5003** [comment] 2018-01-30 16:47
This is my network log (excluding fonts) in Firefox
Can't see why chrome throws the redirect error.
![log](https://user-images.githubusercontent.com/1706621/35578868-888b69a8-05e5-11e8-9a31-608184a2806a.PNG)

**Comment by PeteKirkham** [comment] 2018-01-30 17:38
I can’t see your network log.

This redirect error seems to have been around for a while on Chrome but I don’t understand why Firefox is unaffected if it is a real problem. Unfortunately I do know that some browsers are more strict on following the “rules” than others.

 

De : Lucas [mailto:notifications@github.com] 
Envoyé : mardi 30 janvier 2018 17:47
À : nextcloud/calendar <calendar@noreply.github.com>
Cc : PeteKirkham <pete.kirkham@orange.fr>; Comment <comment@noreply.github.com>
Objet : Re: [nextcloud/calendar] Public calendar iframe has issues on some browsers (#169)

 

This is my network log (excluding fonts) in Firefox
Can't see why chrome throws the redirect error.
 <https://user-images.githubusercontent.com/1706621/35578868-888b69a8-05e5-11e8-9a31-608184a2806a.PNG>

**Comment by Ich5003** [comment] 2018-01-30 19:12
I just tested again with Edge.
It's interesting that in the networking log of Edge the login page is called multiple times in a row.
This may be the reason for "too many redirects".

I guess the problem is something like this:
Any part of the page (maybe not even visible in foreground of the iframe) is responsible for an endless redirect loop.
While Chrome shows an error message on this, Edge and Firefox simply stop redirecting those background tasks and show the visible part.
I'll try to investigate this even further.

**Comment by Ich5003** [comment] 2018-01-30 19:42
And I found something even more interesting.
Let's say my nextcloud instance runs on aaa.example.com

Embedding the iframe on bbb.example.com (same server as aaa.example.com): Works a expected in all browsers
Embedding the iframe on example.com (different server): Works as expected
Embedding the iframe on someotherdomain.com: Does not work in Chrome.

So it mus be something domain specific.

**Comment by georgehrke** [comment] 2018-01-30 19:43
It seems to be related to `X-Frame-Options` in that case 🙈

**Comment by georgehrke** [comment] 2018-01-30 19:47
@tcitworld Does https://github.com/nextcloud/server/pull/5462 help here?

It only does if the admin whitelists all the sites that may include the iframe, right?

**Comment by Ich5003** [comment] 2018-01-30 20:14
Hey @georgehrke 
You're right, this may be possible.
I tried using jsloader and allow the other domain, but it still does not work.
Maybe I'll find another way to edit those X-Frame-Options.

**Comment by Ich5003** [comment] 2018-01-30 21:10
Filtered x-frame-options from header in my apache conf.
Still doesn't work. Really confusing.

**Comment by rullzer** [comment] 2018-08-07 20:29
Do you have some steps for me to run to trigger the error? Else it is hard to see what is going on.

**Comment by tcitworld** [comment] 2018-08-08 07:42
Sure, this should be it:
 * Share a public link from a calendar
 * open the public link
 * Take the embed html iframe code on the left
 * include it in any basic html page
 * access the html page

**Comment by tplusm** [comment] 2018-08-14 21:57
@tcitworld same issue here

**Comment by rullzer** [comment] 2018-08-17 20:13
So I had some time to look into this.

The issue indeed our samesite cookie check. In an IFRAME the lax cookies are not send. Resulting in the check to fail because we do send the other cookies.

Now we could do a lot of nasty hacks and exceptions. But I think the cleaner approach here would be to migrate to lax samesite cookies for all our cookies. This only makes the cookies more secure. Plus it makes sure that if you embed some public page somewhere everbody will see the exact same thing. (as the IFRAME won't send any cookies then resulting in a true 'publicpage' rendering).

I'll track this in the server.

**Comment by tcitworld** [comment] 2018-10-02 20:14
Thanks to https://github.com/nextcloud/server/pull/11433 we should be good with NC15.

**Comment by rullzer** [comment] 2018-10-02 20:27
Yes you should.
Would be good of course if somebody coould setup a test server and test it :wink:

**Comment by tcitworld** [comment] 2018-10-07 14:56
@rullzer I tested and we're still blocked by https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Middleware/Security/SameSiteCookieMiddleware.php#L60-L61 which triggers 302s for every request.

**Comment by rullzer** [comment] 2018-10-16 12:35
Ah ok. So the check I had in mind doesn't fully work. As that would with the current logic log you out of your nextcloud if you embed a page.

Thinking more this would need a few adjustments

1. calendar endpoint must of course be marked with ```@NoSameSiteCookieRequired```
2. The css and js endpoint should be marked as such I don't think this hurts as this is public info anyway
3. The theming endpoints should be marked as such. Also should not be that much of an issue as they just serve generic theming info

**Comment by pReya** [comment] 2020-01-19 21:47
Got the same problem as described in #1861

**Comment by LewisDodgson** [comment] 2020-02-15 23:09
I have this same issue as described in  #1861

**Comment by FredMa01** [comment] 2020-02-19 16:14
Same issue. Embed code generate this error :```

The page is not redirected correctly
An error occurred while connecting to framagenda.org.
The cause of this problem can be the deactivation or refusal of cookies.
```

**Comment by fpoulain** [comment] 2020-04-02 15:51
Using the embed link on a recent NC 18, I am receiving
```
Content-Security-Policy: ... 'self';frame-ancestors 'self'; ...
```
Consequently Firefox block the content loading. Afaik there is no option in NC to define a « trusted embeder ». Moreover, may be the embed link should allow anyone to embed.

I overcame the situation by munging Content-Security-Policy by this kludge on my reverse proxy:
```
       location / {
               proxy_pass http://xxx.xxx.xxx.xxx;
               location /nextcloud/apps/calendar/embed/ {
                       proxy_pass http://xx.xx.xx.xx;
                       proxy_hide_header Content-Security-Policy;
                       add_header Content-Security-Policy "frame-ancestors 'self' https://ourwebsite.com https://www.ourwebsite.com";
               }
       }

```

**Comment by rullzer** [comment] 2020-04-02 17:28
A fixis already in master. and will be in the next release.
CC: @georgehrke

**Closed** 2020-04-02 17:35 UTC
Labels: 1 - to develop, bug

**Comment by nd-** [comment] 2020-06-09 18:45
Hello, NC 18.0.6 and I still have this problem.
Is it supposed to be fixed with the latest releases ?

I even added the headers mentionned by @fpoulain (`Content-Security-Policy "frame-ancestors 'self' https://ourwebsite.com"`) but nada...

**Comment by nderambure** [comment] 2020-06-09 20:41
Same here.

**Comment by georgehrke** [comment] 2020-06-09 21:23
It should work on Nextcloud 19. There are known issues with Nextcloud 18 and below.

**Comment by nd-** [comment] 2020-06-09 23:23
I updated to NC 19 (on the beta channel), it still doesn't work.

**Comment by gelmio** [comment] 2020-09-21 09:42
> It should work on Nextcloud 19. There are known issues with Nextcloud 18 and below.

We updated to NC19 and still have the same issue; firefox requests still returning a 503; chrome is fine.

**Comment by ashnansen** [comment] 2021-01-20 15:31
There are also a problem with embeding it in wordpress
