### ISSUE TITLE
changed events should send email

### ISSUE THREAD

**Issue by Zweihorn** [nextcloud/calendar#6024] opened 2024-05-28 15:22 UTC
### Is your feature request related to a problem? Please describe.

Apparently, changing an event does not send emails to participants about the change and this becomes lost to external clients which accepted the event after the first invitation (e.g., Thunderbird).

### Describe the solution you'd like

Changing the date and/or time of an event shall send emails to participants about the change as applicable.

### Describe alternatives you've considered

none

### Additional context

May be a duplicate but this [plethora](https://en.wiktionary.org/wiki/plethora) of issues found with searching "change" made it difficult to find one in due time if this would exist already. 😇 

However, keep on the good work and prosper.

🌻

**Comment by SebastianKrupinski** [comment] 2024-05-29 13:34
@Zweihorn This is a know bug, we are already working on fixing this.

**Comment by Zweihorn** [comment] 2024-05-29 14:37
> This is a know bug, we are already working on fixing this.

👍 

Just curios which one and which issue number, if I may?

🤔

**Comment by SebastianKrupinski** [comment] 2024-05-30 22:31
Confirmed.

### Cause
This is being caused by the significant changes test.

https://github.com/nextcloud/server/blob/48e62405021627914c7fc6dd58168e011cb0f574/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L109-L114

The sabre/vobject/lib/ITip/Broker class considers only changes to  'DTSTART', 'DTEND', 'DURATION', 'DUE', 'RRULE', 'RDATE', 'EXDATE', 'STATUS' as significant.

### Solution
- Create custom comparison algorithm
- update sabre dav repo to include other parameters

**Comment by Zweihorn** [comment] 2024-05-31 13:38
> Confirmed.
> ### Cause
> 
> This is being caused by the significant changes test.

@SebastianKrupinski - THX alot.

Keep on the good work and prosper.

🌻

**Comment by SebastianKrupinski** [comment] 2024-10-21 22:28
This issue should now be resolved with https://github.com/nextcloud/server/pull/48583

**Closed by SebastianKrupinski** 2024-10-21 22:28 UTC
Labels: 2. developing, enhancement, feature: iMip
