### ISSUE TITLE
White page after editing an calendar entry.

### ISSUE THREAD

**Issue by JB1985** [nextcloud/calendar#2142] opened 2020-04-01 15:11 UTC
### Steps to reproduce
1. Create a event
2. Edit this event and click somewhere next to the event
3. The calendar entries disappear. Whitescreen

### Expected behaviour
No whitescreen

### Actual behaviour
A whitescreen.

### Calendar app
**Calendar app version:** 	2.0.2

**CalDAV-clients used:** No

### Client configuration
**Browser:** Firefox 74.0 & Chome 80.0.3987.149

**Operating system:** Windows 10

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 18.0.3

**Updated from an older installed version or fresh install:** Updates from Nextcloud 17.0.4

#### Browser log
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'calendar' of undefined
    at t.e._sliceDateSpan (main.esm.js:8519)
    at t.sliceDateSelection (main.esm.js:1552)
    at t.e.sliceProps (main.esm.js:8446)
    at t.render (main.esm.js:1542)
    at t.e.receiveProps (main.esm.js:3951)
    at t.render (main.esm.js:1597)
    at t.e.receiveProps (main.esm.js:3951)
    at t.renderView (main.esm.js:6298)
    at t.render (main.esm.js:6162)
    at t.e.receiveProps (main.esm.js:3951)
ze @ vue.runtime.esm.js:1888
Ze @ vue.runtime.esm.js:1879
Ue @ vue.runtime.esm.js:1839
Qe @ vue.runtime.esm.js:1862
Kt @ vue.runtime.esm.js:4219
before @ vue.runtime.esm.js:4076
un @ vue.runtime.esm.js:4306
(anonymous) @ vue.runtime.esm.js:1980
Je @ vue.runtime.esm.js:1906
Promise.then (async)
He @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
e.$nextTick @ vue.runtime.esm.js:3521
mounted @ vue-resize.esm.js:67
Qe @ vue.runtime.esm.js:1854
Kt @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
D @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn.run @ vue.runtime.esm.js:4554
un @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Je @ vue.runtime.esm.js:1906
Promise.then (async)
He @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
dn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
(anonymous) @ EditorMixin.js:453
c @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
vf @ calendar.js?v=c958a53a-14:2
a @ calendar.js?v=c958a53a-14:2
Promise.then (async)
vf @ calendar.js?v=c958a53a-14:2
a @ calendar.js?v=c958a53a-14:2
(anonymous) @ calendar.js?v=c958a53a-14:2
(anonymous) @ calendar.js?v=c958a53a-14:2
save @ EditorMixin.js:436
(anonymous) @ EditorMixin.js:751
c @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
vf @ calendar.js?v=c958a53a-14:2
a @ calendar.js?v=c958a53a-14:2
(anonymous) @ calendar.js?v=c958a53a-14:2
(anonymous) @ calendar.js?v=c958a53a-14:2
beforeRouteLeave @ EditorMixin.js:742
(anonymous) @ vue-router.esm.js:2295
f @ vue-router.esm.js:2158
r @ vue-router.esm.js:1884
Ee @ vue-router.esm.js:1892
Ie.confirmTransition @ vue-router.esm.js:2185
Ie.transitionTo @ vue-router.esm.js:2072
t.push @ vue-router.esm.js:2403
(anonymous) @ vue-router.esm.js:2815
Ge.push @ vue-router.esm.js:2814
(anonymous) @ select.js:61
select @ Calendar.vue:384
Qe @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Qe @ vue.runtime.esm.js:1854
e.$emit @ vue.runtime.esm.js:3888
t.<computed> @ main.esm.js:295
e.publiclyTrigger @ main.esm.js:6975
e.triggerDateSelect @ main.esm.js:7222
n.handlePointerUp @ main.esm.js:1205
Ge @ main.esm.js:982
t.triggerWith @ main.esm.js:3576
t.trigger @ main.esm.js:3571
handlePointerUp @ main.esm.js:1000
Ge @ main.esm.js:982
t.triggerWith @ main.esm.js:3576
t.trigger @ main.esm.js:3571
n.onPointerUp @ main.esm.js:814
Ge @ main.esm.js:982
t.triggerWith @ main.esm.js:3576
t.trigger @ main.esm.js:3571
handleMouseUp @ main.esm.js:103
Show 45 more frames

**Comment by georgehrke** [comment] 2020-04-01 15:20
Please look for existing issues before creating duplicates!

**Comment by georgehrke** [comment] 2020-04-01 15:21
Duplicate of #2051

**Closed by georgehrke** 2020-04-01 15:21 UTC
Labels: 0. to triage, bug
