### ISSUE TITLE
Provide calendar info from remote calendars via WebDAV

### ISSUE THREAD

**Issue by janvlug** [nextcloud/calendar#5171] opened 2023-04-28 17:50 UTC
### Is your feature request related to a problem? Please describe.

Calendars that are subscriptions from link seem not to be available via WebDAV.

Example:
In Nextcloud Calendar subscribe to a calendar via a link:

1. Choose: New Calendar
2. Choose: New subscription from link (read only)
3. Enter for example: https://www.calendarlabs.com/ical-calendar/ics/101/Netherlands_Holidays.ics

Now open a client (like Thunderbird or Evolution) that is subscribed to the Nextcloud WebDAV.

Note that the newly added calendar from a link is not visible.

### Describe the solution you'd like

I would like to see the calendars that are subscriptions from a link also in WebDAV clients, so that I do not have to add them manually on each client on each device.

**Comment by tcitworld** [comment] 2023-05-01 18:19
Duplicate of https://github.com/nextcloud/server/issues/17754 (and see https://github.com/nextcloud/server/issues/17754#issuecomment-828451393 for details).

Clients *should* be able to discover subscriptions collection themselves and allow to subscribe to them straight away, just like DAVx⁵ does. Otherwise it's really a hack.

**Closed by tcitworld** 2023-05-01 18:19 UTC
Labels: enhancement, 0 - to triage
