### ISSUE TITLE
Let unsubscribed users edit a public calendar

### ISSUE THREAD

**Issue by Cwpute** [nextcloud/calendar#5126] opened 2023-04-04 11:41 UTC
### Is your feature request related to a problem? Please describe.

I wanted to create a calendar on which anyone with the link to it could add, edit or remove events. It turns out unsubscribed users (without an account on the Nextcloud instance i'm using) cannot edit this shared calendar in any way.

### Describe the solution you'd like

I'd like an option that when you share a calendar, you have the option to allow anyone with the link to add, edit or delete events within the calendar, even if they arent registered users. Additionally, access to said calendar could be protected by a password.

### Describe alternatives you've considered

* Having everyone become a registered user isn't an option, as the instance provider is a paid one.
* Freely available instances of Nextcloud Calendar isn't an option either as that would require everywne of us to register, which isn't necessary nor desired for people who already struggle with remembering a single password (which is the target audience i'm working with).
* Popular schedulers like Doodle or Framadate don't fit my use-case as they require you enter specific dates to be voted on, but the time-frame i'll be using this calendar for is way too big for this tool (two vhole months, with an option for an extended period afterwards that could last many other months or years even). It would somewhat work, but would first be a pain for me to manually enter each individual date, then the UI would not even be practical as it isn't designed to support such a number of date choices. Therefore this type of tool is out of the question.
* I've found no other calendar providers out there that allow registered users to share editable calendars with unregistered users. Usually, unregistered users can only see the events, and sometimes subscribe to said events.

### Additional context

This feature already exists for shared folders in Nextcloud Files.
Other Nextcloud tools being limited in that regard doesn't provide a coherent experience throughout the Nextcloud suite, and can come off as an unpolished oversight.

**Comment by ChristophWurst** [comment] 2023-04-04 11:59
Duplicate of https://github.com/nextcloud/server/issues/3509

**Closed by ChristophWurst** 2023-04-04 11:59 UTC
Labels: enhancement, 0 - to triage
