### ISSUE TITLE
Calendar weekly view

### ISSUE THREAD

**Issue by TechTommy** [nextcloud/calendar#1945] opened 2020-02-01 10:25 UTC
Hello. I think the zoom is too high in the week view. Therefore I don't get to see the whole day and I always have to scroll. Please add a possibility to set the time grid to 30 minutes in the settings. (Instead of 15 minutes)

**Comment by ltGuillaume** [comment] 2020-02-01 13:53
Indeed, this makes the week view pretty useless.

**Comment by tcitworld** [comment] 2020-02-01 14:03
Duplicate of https://github.com/nextcloud/calendar/issues/577

**Closed by tcitworld** 2020-02-01 14:03 UTC
Labels: 0. to triage, enhancement-proposed

**Comment by ltGuillaume** [comment] 2020-02-01 14:17
@tcitworld Imho, this is not exactly a duplicate, as this could rather be seen as a regression in v2 compared to v1.

**Comment by meaz** [comment] 2020-02-10 08:49
indeed, I don't understand why having 15 minutes by default... 30 minutes was much better.

**Comment by Piyou29** [comment] 2020-02-23 13:56
I agree with @ltGuillaume, it's a regression. Before I sent every monday, a view of the week to the members of my organisation. To day it's not possible because of this new view.
