### ISSUE TITLE
Feature Request - Display who added an event in shared calendars

### ISSUE THREAD

**Issue by Luticus** [nextcloud/calendar#721] opened 2018-02-07 17:22 UTC
It would be really nice if in events on shared calendars, there were a way to know who added the event.  Perhaps in the event details when you click on it.  Right now the only way to tell is to look through the activity feed which is tedious if I want to ask someone to update an event title, description, or ask them to move their event to a different calendar.

**Comment by georgehrke** [comment] 2018-02-07 17:23
Duplicate of https://github.com/nextcloud/calendar/issues/668

**Closed by georgehrke** 2018-02-07 17:23 UTC
