### ISSUE TITLE
Calendar Month view, scroll-by-week request

### ISSUE THREAD

**Issue by ianp5a** [nextcloud/calendar#862] opened 2018-07-06 11:28 UTC
BACKGROUND. When viewing entries, it is often important to have an overview of several weeks, to help  find the best time to fit new entries in. 
PROBLEM:  In Month view, the Forward/Backward command jumps a complete month.  If the area of interest lays across 2 different months, the user has to jump forward and back between the 2 months.  A single view cannot show the required area. 
REQUIREMENT:  To add an additional possibility to scroll forwards and backwards by 1 week at a time. E.G add a new arrow  buttons alongside the existing arrow buttons. The use can then choose the period required. The Display shows the same number of weeks. But it does not always start on the 1st of the month. This is already the way used by many calendars, including smartphone app calendars.
SUGGESTION:
In addition to the new buttons, it will be necessary to differentiate between the months on the grid. Some calendars shade the squares by calendar month, alternating between white and then a light colour shade. Other calendars use a fat line between the grid squares at the end of each month.
Some Calendars call it "Multi-Week View", and separate it from the "Month View". 

### Steps to reproduce
1. Start the Calendar 
2. Set to view by Month
3. Click the Forward button
4. See the calendar period jumps forward by 1 complete month. Not OK.

### Expected behaviour
4. The calendar period should move forward 1 week only.

### Actual behaviour
The calendar period jumps forward by 1 complete month. Not OK.

### ATTACHED Image showing multi weeks with month grid shading, in grey/white. And a Month delimiting line in black. 
![multiweek view](https://user-images.githubusercontent.com/21156757/42376683-598b7a74-8120-11e8-8bf2-2da0efe81f26.jpg)

**Comment by georgehrke** [comment] 2018-07-06 11:29
> REQUIREMENT: To add an additional possibility to scroll forwards and backwards by 1 week at a time. E.G add a new arrow buttons alongside the existing arrow buttons. The use can then choose the period required. The Display shows the same number of weeks. But it does not always start on the 1st of the month. This is already the way used by many calendars, including smartphone app calendars.

Duplicate of #6 

> SUGGESTION:
In addition to the new buttons, it will be necessary to differentiate between the months on the grid. Some calendars shade the squares by calendar month, alternating between white and then a light colour shade. Other calendars use a fat line between the grid squares at the end of each month.
Some Calendars call it "Multi-Week View", and separate it from the "Month View".

Duplicate of #26

**Closed by georgehrke** 2018-07-06 11:29 UTC
