### ISSUE TITLE
[feature request] : missing options to modify repeated events

### ISSUE THREAD

**Issue by tykayn** [nextcloud/calendar#975] opened 2018-11-29 09:50 UTC
when we modify a repeated event we have no option to change only a part of the repeat.
a common use case would be when a regular meeting changes its frequency or time, but we dont want to change ALL the history of events in the past.
( i checked, this is not a duplicate of the issue #10 )

a common solution would be to prompt the user at the moment of changing the repeating event some options:
do you want to modify - only future events: in which case we end the repeatition to the last one and create a new repeated event with new scheduling.
-only this event: then we split the repeated event in two repeated events: past and future, + we prompt the user to create a one time event pre filled with the selected event.
- only past events: we split repeated event, creating the future events in a repeatition starting with the selected event, and we prompt the user with the modification of the selected event, making it end at the selection by default.

**Comment by georgehrke** [comment] 2018-11-29 09:51
Duplicate of #7

**Closed by georgehrke** 2018-11-29 09:51 UTC
