### ISSUE TITLE
Memory consumption since upgrade to 25.0.11

### ISSUE THREAD

**Issue by albatros69** [nextcloud/calendar#5479] opened 2023-09-18 22:35 UTC
### Steps to reproduce

After upgrading to 25.0.11, some users are unable to use the Calendar webUI. Event previews on the homepage or CalDAV is still working fine for them. Only the WebUI is unavailable (Error 500).

### Expected behavior

The WebUI should show for every user.

### Actual behaviour

For those users, going to their calendar only triggers an error 500 with a blank page.

### Calendar app version

4.5.0

### Browser

Firefox/117.0 or /102

### Client operating system

debian, ubuntu

### Server operating system

Debian 

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 7.4

### Nextcloud version

25.0.11

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.17.0
  - calendar: 4.5.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.4.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.5
  - keeweb: 0.6.13
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - news: 22.0.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.8.1
  - notifications: 2.13.1
  - oauth2: 1.13.1
  - password_policy: 1.15.0
  - photos: 2.0.1
  - previewgenerator: 5.3.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.2.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.4.0
  - encryption
  - files_external
  - files_photospheres: 1.25.3
  - maps: 1.0.2
  - survey_client: 1.3.0
  - suspicious_login
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<domain>"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "dbtype": "pgsql",
        "version": "25.0.11.1",
        "overwrite.cli.url": "https:\/\/<domain>",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie"
        ],
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.release.channel": "stable",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "logtimezone": "Europe\/Paris",
        "log_rotate_size": 10485760,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "keeweb",
            "calendar"
        ],
        "default_phone_region": "FR"
    }
}
```

### Web server error log

```Text
<remoteAddr> - - [19/Sep/2023:00:04:58 +0200] "GET /apps/calendar/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
<remoteAddr> - - [19/Sep/2023:00:11:15 +0200] "GET /apps/calendar/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
<remoteAddr> - - [19/Sep/2023:00:14:16 +0200] "GET /apps/calendar/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
<remoteAddr> - - [19/Sep/2023:00:18:40 +0200] "GET /apps/calendar/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
```

### Log file

```Text
{"reqId":"Ec661Yl5bBMHbnxJHFvE","level":3,"time":"2023-09-19T00:11:15+02:00","remoteAddr":"<remoteAddr>","user":"<username>","app":"PHP","method":"GET","url":"/apps/calendar/","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /var/www/ipv5.fr/nextcloud/3rdparty/sabre/vobject/lib/Property/ICalendar/DateTime.php#81","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.11.1","data":{"app":"PHP"}}
{"reqId":"AtVsTJzs8kVraM0ZaNNj","level":3,"time":"2023-09-19T00:14:16+02:00","remoteAddr":"<remoteAddr>","user":"<username>","app":"PHP","method":"GET","url":"/apps/calendar/","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /var/www/ipv5.fr/nextcloud/3rdparty/sabre/vobject/lib/Property/ICalendar/DateTime.php#81","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.11.1","data":{"app":"PHP"}}
{"reqId":"s4uto7nCgRuNfpNh5AlC","level":3,"time":"2023-09-19T00:18:40+02:00","remoteAddr":"<remoteAddr>","user":"<username>","app":"PHP","method":"GET","url":"/apps/calendar/","message":"Allowed memory size of 671088640 bytes exhausted (tried to allocate 20480 bytes) at /var/www/ipv5.fr/nextcloud/3rdparty/sabre/vobject/lib/Property/ICalendar/DateTime.php#81","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.11.1","data":{"app":"PHP"}}
{"reqId":"65gy0PP2A4UMgV92fLMM","level":0,"time":"2023-09-16T11:40:41+02:00","remoteAddr":"<remoteAddr>","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"calendar\" in appstore","userAgent":"--","version":"25.0.10.1","data":{"app":"updater"}}
{"reqId":"65gy0PP2A4UMgV92fLMM","level":0,"time":"2023-09-16T11:40:41+02:00","remoteAddr":"<remoteAddr>","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"calendar\" in appstore","userAgent":"--","version":"25.0.10.1","data":{"app":"updater"}}
{"reqId":"xEk9DGXOfigMeh3sXRD7","level":3,"time":"2023-09-18T13:53:02+02:00","remoteAddr":"<remoteAddr>","user":"<username>","app":"PHP","method":"GET","url":"/apps/calendar/","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /var/www/ipv5.fr/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php#568","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"25.0.11.1","data":{"app":"PHP"}}
{"reqId":"kwRXMGohYf1cAX7UUGQw","level":3,"time":"2023-09-18T13:53:46+02:00","remoteAddr":"<remoteAddr>","user":"<username>","app":"PHP","method":"GET","url":"/apps/calendar/","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /var/www/ipv5.fr/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php#568","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"25.0.11.1","data":{"app":"PHP"}}
{"reqId":"VcM4oqk7nwOH0nQdSNuK","level":3,"time":"2023-09-18T13:55:18+02:00","remoteAddr":"<remoteAddr>","user":"<username>","app":"PHP","method":"GET","url":"/apps/calendar/","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /var/www/ipv5.fr/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php#568","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"25.0.11.1","data":{"app":"PHP"}}
{"reqId":"RAOT3ssknVazLrJscvwr","level":3,"time":"2023-09-18T14:13:54+02:00","remoteAddr":"<remoteAddr>","user":"<username>","app":"PHP","method":"GET","url":"/apps/calendar/","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /var/www/ipv5.fr/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php#568","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"25.0.11.1","data":{"app":"PHP"}}
```

### Additional info

I tried to increase the php memory_limit from the recommended 512M value. Only increasing the limit to 1G was able to circumvent the issue (but this can't be a sensible solution, can it?).

**Comment by albatros69** [comment] 2023-09-19 06:06
I forgot to add that the users facing the errors 500 are the heavy users of Calendar. Those with just a few events doesn't suffer from the issue.

**Comment by ChristophWurst** [comment] 2023-09-19 12:17
Possible duplicate of https://github.com/nextcloud/calendar/issues/5476

**Comment by albatros69** [comment] 2023-09-24 17:49
Just for the sake of exhaustivity, I'm experiencing the same issue (error 500 for some users) on a fresh install of NC 27.1.1 (on the same data).

**Comment by albatros69** [comment] 2023-09-27 22:24
Can I help in any way to pinpoint the culprit?
Is the patch mentioned in #5476 worth a try for this issue too?

**Comment by miaulalala** [comment] 2023-10-04 09:48
> Can I help in any way pinpoint the culprit? Is the patch mentioned in #5476 worth a try for this issue too?

If you update to Calendar 4.5.2 the feature that caused the heavy load has been reverted so it should work fine again.

**Comment by albatros69** [comment] 2023-10-04 15:03
I can confirm that version 4.5.2 is not affected by this issue anymore.

**Comment by miaulalala** [comment] 2023-10-04 19:19
Closing this then :)

**Closed by miaulalala** 2023-10-04 19:19 UTC
Labels: bug, 0 - to triage
