### ISSUE TITLE
Respect Nextcloud language setting

### ISSUE THREAD

**Issue by jgonsior** [nextcloud/calendar#2175] opened 2020-04-10 17:02 UTC
### Steps to reproduce
1. Install Nextcloud, keep language set to English
2. Be in Germany

### Expected behaviour
The weekdays as well as "KW" and Ganztägig in the Calendar is in German

### Actual behaviour
I expected the language to be in English like the rest of Nextcloud. I tried to change the timezone to something like "Europe/London", that didn't changed it either.

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** Firefox 75

**Operating system:** Arch Linux

### Server configuration

**Operating system**: Arch Linux

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** (e.g. 7.0.3)

**Nextcloud Version:** 18.0.3

**Comment by georgehrke** [comment] 2020-04-10 17:04
> Be in Germany

Are you referring to setting your Locale to German?

**Comment by georgehrke** [comment] 2020-04-10 17:07
If that's the case, this is a Duplicate of #1844

**Comment by jgonsior** [comment] 2020-04-10 17:11
`LC_TIME` is set to `de_DE.UTF-8`, but `LANG` to `en_US.UTF-8`. Shouldn't the language setting in Nextcloud be respected here instead of the locale setting?

**Comment by georgehrke** [comment] 2020-04-10 17:13
Can you please check the locale configured in your personal settings.

**Comment by georgehrke** [comment] 2020-04-10 17:16
The default fullcalendar localisation backend relies on the [Internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), so your browser returns German Day Names because of your OS locale settings. Replacing the default backend with a moment backend as discussed in #1844 will solve the problem.

Closing as Dup.

**Closed by georgehrke** 2020-04-10 17:16 UTC
Labels: 0. to triage, bug, needs info

**Comment by georgehrke** [comment] 2020-04-10 17:18
I updated the title of #1844 to properly reflect this side of the issue as well.
