### ISSUE TITLE
Improve invitation update notification email

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#3919] opened 2022-01-28 10:44 UTC
**Is your feature request related to a problem? Please describe.**
When responding to an invitation via an external client or my new feature, our CalDAV backend will send a notification to the organizer. However, this notification is very crude and could be improved.

**Describe the solution you'd like**
Show more information about what actually changed about the event. We could start by adding information about the invitee that reacted.

**Describe alternatives you've considered**
*None*

**Additional context**
How the notification email currently looks:
![Screenshot_20220128_111203](https://user-images.githubusercontent.com/1479486/151533271-0aa15508-f8f1-4423-860b-b1fb190a4ad8.png)

The term "Einladung aktualisiert" means "invitation was updated" in English.

**Comment by ChristophWurst** [comment] 2022-01-28 11:01
https://github.com/orgs/nextcloud/projects/45#card-74890297 guess this materializes that card into a ticket. Thanks :)

**Comment by tobiasKaminsky** [comment] 2022-02-02 10:15
Same happens when:
- there is a monthly appointment
- one appointment is moved from e.g. Wednesday to Friday
- email is: ![image](https://user-images.githubusercontent.com/5836855/152134674-f9300b99-3823-42a0-85ef-899e52b5ce48.png)
- which shows start of appointment rule, but not what appointment (today's) was changed to what (moved to Friday, different time)

**Comment by miaulalala** [comment] 2022-12-12 18:40
Investigated a bit. Seems the issue is with not taking the SEQUENCE into account for recurrences.

From the iTip rfc:

   1.  The primary key for referencing a particular iCalendar component
       is the "UID" property value.  To reference an instance of a
       recurring component, the primary key is composed of the "UID" and
       the "RECURRENCE-ID" properties.

   2.  The secondary key for referencing a component is the "SEQUENCE"
       property value.  For components where the "UID" and
       "RECURRENCE-ID" property values are the same, the component with
       the highest numeric value for the "SEQUENCE" property obsoletes
       all other revisions of the component with lower values.

So when changing a single recurrence like in @tobiasKaminsky 's example, the highest SEQUENCE should win.

**Comment by ChristophWurst** [comment] 2022-12-14 14:01
Could we collect a list of use cases where we want to improve the email contents? So far we discussed

1) Recurring events
2) One-time event where the location (or anything similar) changed -> highlight that?
3) ???

**Comment by avinash-0007** [comment] 2023-01-26 05:56
@ChristophWurst Is there any update on this to highligh updates in invitation?

**Comment by avinash-0007** [comment] 2023-01-26 08:59
@ChristophWurst As right now ,Mail about "Invitation updated" doesn’t say what actually happened
In case of One time and Recurring event:
We need to highlight 
1)title
2)description
3)Location
4) Date

We can highlight the change using color change as well.For e.g
![screenshot-mail google com-2023 01 26-14_28_19](https://user-images.githubusercontent.com/21700809/214795837-5c5f24eb-b112-4cf4-8148-8acbd81e1440.png)

**Comment by miaulalala** [comment] 2023-01-26 13:15
> @ChristophWurst As right now ,Mail about "Invitation updated" doesn’t say what actually happened In case of One time and Recurring event: It would be useful to highlight 1)title 2)description 3)Location 4) Date
> 
> We can highlight the change using color change as well.For e.g ![screenshot-mail google com-2023 01 26-14_28_19](https://user-images.githubusercontent.com/21700809/214795837-5c5f24eb-b112-4cf4-8148-8acbd81e1440.png)

Please see https://github.com/nextcloud/server/pull/35743 for the current state.

We're going to provide a diff of the changed values you mentioned above.

**Comment by miaulalala** [comment] 2023-02-13 15:14
Closed in https://github.com/nextcloud/server/pull/35743

**Closed by miaulalala** 2023-02-13 15:14 UTC
Labels: 2 - developing, enhancement, Feature: Scheduling, skill:backend
