### ISSUE TITLE
[Feature request] Display the invitation status in the UI

### ISSUE THREAD

**Issue by MisterY** [nextcloud/calendar#918] opened 2018-10-05 09:35 UTC
### Steps to reproduce
This is a request to display the status of the invitations sent to Attendees in the meetings. There is no indication on whether the invite has been accepted or not - neither in the UI nor via (e-mail) notifications.

1. Invite another person to an even in the calendar
2. Check the event in the calendar UI

### Expected behaviour
The invitations should status - pending, accepted, denied (or something along those lines) - either as icons or a textual description.

### Actual behaviour
There is no indication on whether the attendees accepted or rejected the invitations, or have not responded yet.

## Server configuration detail

**Operating system:** Linux 3.19.0-80-generic #88~14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.23

**PHP version:** 

7.1.21
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, sodium, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 14.0.1 - 14.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**  upgraded (since v12)

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - apporder: 0.5.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.2
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - dav: 1.6.0
 - encryption: 2.2.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.4.2
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - twofactor_totp: 1.5.0
 - updatenotification: 1.4.1
 - user_external: 0.4
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - dashboard
 - external
 - files_external
 - mail
 - ownbackup
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "siljak.next-cloud.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/siljak.next-cloud.org",
    "dbtype": "mysql",
    "version": "14.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "trashbin_retention_obligation": "1,7",
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0,
        "dbindex": 0
    },
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "session_lifetime": "3600",
    "session_keepalive": "false",
    "remember_login_cookie_lifetime": "1209600"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

**Operating system:** Windows 10

## Logs

<details><summary>Browser log</summary>

```
n/a
```
</details>

<details><summary>Nextcloud log</summary>

```
n/a
```
</details>

<details><summary>Browser log</summary>

n/a
</details>

**Comment by georgehrke** [comment] 2018-10-05 09:37
Duplicate of https://github.com/nextcloud/calendar/issues/879

**Comment by MisterY** [comment] 2018-10-05 09:38
Hm, initially I did not found anything related to attendees/participants but now I came across #879. This is probably a duplicate.

**Closed by georgehrke** 2018-10-05 09:37 UTC
