### ISSUE TITLE
Calendars colors are hidden and large content override box of the day

### ISSUE THREAD

**Issue by simmstein** [nextcloud/calendar#4337] opened 2022-06-30 14:03 UTC
### Steps to reproduce

Update calendar to 3.4.1.

### Expected behavior

Show each events with background colors depending of the calendar.
The content should be wrap in the box of the day.

### Actual behaviour

![](https://upload.deblan.org/u/2022-06/62bdad13.png)

### Calendar app version

3.4.1

### Browser

Firefox 101, Chromium 99

### Client operating system

Debian 11

### Server operating system

Debian 10

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.0

### Nextcloud version

24.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
- accessibility: 1.10.0
- activity: 2.16.0
- admin_audit: 1.14.0
- analytics: 4.3.1
- apporder: 0.15.0
- bookmarks: 10.5.1
- breezedark: 24.0.1
- calendar: 3.4.1
- checksum: 1.1.4
- circles: 24.0.0
- cloud_federation_api: 1.7.0
- cms_pico: 1.0.19
- collectives: 1.2.1
- comments: 1.14.0
- contacts: 4.1.1
- contactsinteraction: 1.5.0
- cookbook: 0.9.12
- cospend: 1.4.8
- dashboard: 7.4.0
- dav: 1.22.0
- deck: 1.7.1
- drawio: 1.0.3
- emlviewer: 1.0.2
- external: 4.0.0
- extract: 1.3.5
- federatedfilesharing: 1.14.0
- federation: 1.14.0
- files: 1.19.0
- files_downloadactivity: 1.13.0
- files_external: 1.16.1
- files_mindmap: 0.0.26
- files_pdfviewer: 2.5.0
- files_readmemd: 1.2.2
- files_rightclick: 1.3.0
- files_sharing: 1.16.2
- files_trashbin: 1.14.0
- files_versions: 1.17.0
- files_videoplayer: 1.13.0
- firstrunwizard: 2.13.0
- forms: 2.5.1
- groupfolders: 12.0.1
- groupquota: 0.1.8
- guests: 2.2.0
- health: 1.5.1
- impersonate: 1.11.0
- integration_discourse: 1.0.2
- integration_github: 1.0.2
- integration_mastodon: 1.0.2
- integration_reddit: 1.0.4
- jsloader: 1.5.0
- logreader: 2.9.0
- lookup_server_connector: 1.12.0
- nextcloud_announcements: 1.13.0
- notes: 4.3.1
- notifications: 2.12.0
- notify_push: 0.4.0
- oauth2: 1.12.0
- password_policy: 1.14.0
- passwords: 2022.7.20-build4507
- phonetrack: 0.7.0
- photos: 1.6.0
- polls: 3.7.0
- printer: 0.0.4-deblan
- privacy: 1.8.0
- provisioning_api: 1.14.0
- quota_warning: 1.14.0
- ransomware_protection: 1.13.0
- registration: 1.5.0
- richdocuments: 6.1.0
- riotchat: 0.13.1
- serverinfo: 1.14.0
- settings: 1.6.0
- sharebymail: 1.14.0
- side_menu: 2.4.0
- spreed: 14.0.2
- support: 1.7.0
- survey_client: 1.12.0
- suspicious_login: 4.2.0
- systemtags: 1.14.0
- tasks: 0.14.4
- text: 3.5.1
- theming: 1.15.0
- theming_customcss: 1.11.0
- twofactor_backupcodes: 1.13.0
- twofactor_nextcloud_notification: 3.4.0
- twofactor_totp: 6.4.0
- updatenotification: 1.14.0
- user_status: 1.4.0
- user_usage_report: 1.8.0
- viewer: 1.8.0
- weather_status: 1.4.0
- workflowengine: 2.6.0
```

### Web server error log

```Text
None.
```

### Log file

```Text
None.
```

### Browser log

```Text
None.
```

**Comment by ChristophWurst** [comment] 2022-06-30 14:08
Duplicate of https://github.com/nextcloud/calendar/issues/4332

**Closed by ChristophWurst** 2022-06-30 14:08 UTC
Labels: bug, 0. to triage
