### ISSUE TITLE
Calender Dashboard Widget kills Browser Tab

### ISSUE THREAD

**Issue by Nuube** [nextcloud/calendar#5063] opened 2023-03-15 23:00 UTC
### Steps to reproduce

1. Activate Calendar Tab
2. Call Dashboard

### Expected behavior

Display Calendar Events

### Actual behaviour

In spite of showing calendar entries the widget completely kills the browser tab. You can not navigate away from the dashboard, go backwards, even closing the tab does not work. You have to completely exit the browser.

Same behaviour has been observed with Vivaldi, Firefox on Linx Mint, Edge om W11 and Vivaldi on Android.

Firefox ask after a while if you want to "stop" the webpage.

The only exit form here is after login to fast enough enter the dashboard setting page and disable the calendar app, which I only managed to do by slowing down the browser by opening the debugger console.

Calendar app itself  works fine.

### Calendar app version

4.2.4

### Browser

Firefox, Vivaldi, Edge

### Client operating system

Linux and Windows

### Server operating system

Linux Mint, Windows 11

### Web server

Other

### Database engine version

Other

### PHP engine version

Other

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
nabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - externalportal: 1.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.4
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - vdirsyncerui: 0.0.8
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - encryption: 2.13.0
  - external: 5.0.2
  - survey_client: 1.13.0
  - twofactor_totp
  - user_ldap
www-data@acef1b80fa4d:~/html
```

### Nextcloud configuration

```Text
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.88.11:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.4.1",
        "overwrite.cli.url": "https:\/\/nc2.mashnet.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritehost": "nc2.mashnet.de",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "app_install_overwrite": [
            "vdirsyncerui"
        ]
    }
}
```

### Log file

```Text
Nothing relevant:

{"reqId":"1g1ewnYG1YxvxH3dNP6z","level":2,"time":"2023-03-15T22:40:03+00:00","remoteAddr":"79.238.35.142","user":"michael","app":"suspicious_login","method":"REPORT","url":"/remote.php/dav/calendars/michael/calendar~9-w6P8vSE9jZkfqHxtQCLzS/","message":"Could not predict suspiciousness: No models found","userAgent":"vdirsyncer/0.16.8","version":"25.0.4.1","data":{"app":"suspicious_login"}}
{"reqId":"5kzDMZuCRwIBnpmFyFC4","level":2,"time":"2023-03-15T22:55:02+00:00","remoteAddr":"79.238.35.142","user":"michael","app":"suspicious_login","method":"PROPFIND","url":"/remote.php/dav/calendars/michael/calendar~9-w6P8vSE9jZkfqHxtQCLzS/","message":"Could not predict suspiciousness: No models found","userAgent":"vdirsyncer/0.16.8","version":"25.0.4.1","data":{"app":"suspicious_login"}}
{"reqId":"alFU5ChsCOcFqszXe7LS","level":2,"time":"2023-03-15T22:55:02+00:00","remoteAddr":"79.238.35.142","user":"michael","app":"suspicious_login","method":"PROPFIND","url":"/remote.php/dav/calendars/michael/calendar~L-uiwYd1rN5zM-jHf3q8lrU/","message":"Could not predict suspiciousness: No models found","userAgent":"vdirsyncer/0.16.8","version":"25.0.4.1","data":{"app":"suspicious_login"}}
{"reqId":"iKe2Xk5okUtD62dhJE2d","level":2,"time":"2023-03-15T22:55:02+00:00","remoteAddr":"79.238.35.142","user":"michael","app":"suspicious_login","method":"PROPFIND","url":"/remote.php/dav/calendars/michael/calendar:bsjRScBrBHAJgMo717KWJA1/","message":"Could not predict suspiciousness: No models found","userAgent":"vdirsyncer/0.16.8","version":"25.0.4.1","data":{"app":"suspicious_login"}}
{"reqId":"GivuCRuTjOFrJAAWwFdk","level":2,"time":"2023-03-15T22:55:02+00:00","remoteAddr":"79.238.35.142","user":"michael","app":"suspicious_login","method":"PROPFIND","url":"/remote.php/dav/calendars/michael/calendar~XIaheL9GWilkx_yfdN4nylk/","message":"Could not predict suspiciousness: No models found","userAgent":"vdirsyncer/0.16.8","version":"25.0.4.1","data":{"app":"suspicious_login"}}
{"reqId":"siVbWOv7fi5bwWAdIWx9","level":2,"time":"2023-03-15T22:55:03+00:00","remoteAddr":"79.238.35.142","user":"michael","app":"suspicious_login","method":"PUT","url":"/remote.php/dav/calendars/michael/calendar~9-w6P8vSE9jZkfqHxtQCLzS/2c76bc28-7b70-43d3-b4e2-93584dfb1064.ics","message":"Could not predict suspiciousness: No models found","userAgent":"vdirsyncer/0.16.8","version":"25.0.4.1","data":{"app":"suspicious_login"}}
```

### Additional info

This is a dockerized nextcloud using the latest image from nextcloud.

**Comment by tcitworld** [comment] 2023-03-16 13:03
Browser (console) logs would be nice

**Comment by joshtrichards** [comment] 2024-02-11 22:51
Hi @Nuube -

- Is this still occurring for you?
- Can you get the browser console output immediately prior to this event?
- Are you able to reproduce this behavior in a clean test account on your instance?

**Comment by joshtrichards** [comment] 2024-02-11 23:14
If there are a lot of calendars or items, might be similar to #4758 & #4736

**Comment by joshtrichards** [comment] 2024-07-20 02:21
Closing due to lack of further follow-up info received.

**Closed by joshtrichards** 2024-07-20 02:21 UTC
Labels: bug, needs info, 0. to triage, Feature: Dashboard, performance 🚀
