### ISSUE TITLE
Deleting a single entry from events that repeat deletes them all

### ISSUE THREAD

**Issue by digitaljessica** [nextcloud/calendar#1424] opened 2019-08-28 00:36 UTC
### Steps to reproduce
1. Create an event with repeating entry
2. Delete single entry
3. All entries are deleted

### Expected behaviour
It should be possible for the calendar to ask "Do you want to delete single event , all future events or all?"
It works from calendars on Android which sync with DAVx5, it just puts a cross through the deleted single event.

### Actual behaviour
It deletes all events.

### Server configuration

**Operating system**:
Ubuntu Server 18.04.3

**Web server:**
Apache 2.4.29

**Database:**
MySQL

**PHP version:**
7.2

**Server version:** (see your admin page)
15.0.11

**Calendar version:** (see the apps page)
 1.6.5

Edit: Corrected some info of my environment. This is my first issue on github, I hope I have done this correctly. Please advise if this is incorrect or in the wrong place. Thanks :)

**Comment by georgehrke** [comment] 2019-08-28 07:15
Duplicate of #7

**Closed by georgehrke** 2019-08-28 07:15 UTC
