### ISSUE TITLE
Feature Request: Specify a Repeating Event By the Nth Day of the Week

### ISSUE THREAD

**Issue by charlescurley** [nextcloud/calendar#1218] opened 2019-04-05 02:39 UTC
Currently one can specify a repeating event as being on the Nth day of the month, e.g. the fourth day of the month.

I would also like to specify events on the Nth day of the week, e.g. every third Thursday.

Negative numbers should be treated as counting from the end of the month. E.g.: the -2nd Wednesday is the Wednesday before the last Wednesday of the month.

It should also be possible to specify the last day of the week. E.g.: every last Tuesday.

Currently running Calendar 1.6.4 on Nextcloud 14.0.6.

I can create an event on Nextcloud, then edit it on my iPhone to recur every first Thursday. Thereafter Nextcloud displays it correctly on the first Thursday. So it would appear the calculation and display side of things may be already done.

Thank you.

**Comment by tcitworld** [comment] 2019-04-05 07:20
I guess it's a duplicate of https://github.com/nextcloud/calendar/issues/10. Thanks anyway !

**Closed by tcitworld** 2019-04-05 07:20 UTC

**Comment by charlescurley** [comment] 2019-04-05 18:39
On Fri, 05 Apr 2019 07:20:45 +0000 (UTC)
Thomas Citharel <notifications@github.com> wrote:

> I guess it's a duplicate of
> https://github.com/nextcloud/calendar/issues/10. Thanks anyway !

Thanks.

Not entirely a duplicate. I did not see anything in 10 about entering
negative numbers (e.g. the last Thursday of the month or the penultimate
Wednesday). I've had use for those more than once. E.g. a meeting to
review the month.

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com
