### ISSUE TITLE
Feature request: Separate calendar for different contact groups

### ISSUE THREAD

**Issue by khlschrnk** [nextcloud/calendar#639] opened 2017-10-20 13:55 UTC
I am using nextcloud and the calendar/contacts apps a lot to organise my contacts and meetings.

Sometimes I have rather old contacts for people I don't expect to need any more but still dont want to delete them. They still show up with their birthdays in the calender app which is sometimes more a spam than helpful. With the latest contacts app update I can now move them to some "Archive" contacts group. The birthdays of these contacts still show in calendar.

It would be awesome to have the possibility to disable these birthdays in calendar or maybe have different calendars for the different contact groups.

**Comment by georgehrke** [comment] 2017-10-20 13:57
@skjnldsv Can u give me some insights how the archive was implemented? 
Is it a dedicated address book? Is it a custom property?

**Comment by georgehrke** [comment] 2017-10-20 14:02
Ah, there is no archive feature but you simply created a group called Archive, got it.

**Comment by georgehrke** [comment] 2017-10-20 14:04
> The birthdays of these contacts still show in calendar.

Well, that's kind of the expected behavior because they are still in your address book.

> It would be awesome to have the possibility to disable these birthdays in calendar or maybe have different calendars for the different contact groups.

How big is this issue really? I think it's a pretty big overkill to make it possible for each group to select whether or not to include it on the birthday calendar? 

cc @jancborchardt @tcitworld

**Comment by jancborchardt** [comment] 2017-10-20 16:15
Yeah, agree with @georgehrke here. If you

> have rather old contacts for people I don't expect to need any more but still dont want to delete them

you could simply remove their birthdays from the contact entry?

**Comment by skjnldsv** [comment] 2017-10-20 16:38
@georgehrke Where did you see me using the archive? :)

**Comment by khlschrnk** [comment] 2017-10-20 16:43
There are several other workflows that would solve this situation, I agree.

If it's not possible, a too big change or if there are other reasons to not implement this it's also fine for me. I thought that this feature would also be of interest in other use cases. For example if you manage a huge amount of contacts or if you are organising different (rather big) teams and need a better overview.

Removing the birthday might solve the issue short hand but might increase effort or lead to confusion if these contacts are of relevance again. Same if you move the birthday to the notes field.

Another handy advantage is that you could assign a special group (e.g. family and/or close friends) a certain color. This might also not be critical but nice to keep focus on the most important birthdays.

**Comment by georgehrke** [comment] 2017-10-27 09:43
There is one thing I could imagine: 

Instead of offering an option for each group we could just have a pre-defined group called `Exclude from birthday calendar` that works like a blacklist.

@jancborchardt @skjnldsv What do you think about this idea?

**Comment by jancborchardt** [comment] 2017-10-27 11:43
Sorry it sounds like too much of a specific usecase. Don't forget we need to maintain and test every single setting we introduce.

We could look into it when it comes up more often. Closing meanwhile.

**Closed** 2017-10-27 11:44 UTC
Labels: enhancement-proposed
