### ISSUE TITLE
Change steps of time picker to 5 minutes

### ISSUE THREAD

**Issue by klemens-u** [nextcloud/calendar#2002] opened 2020-02-17 18:31 UTC
The new datetime picker in Calendar 2.0 has some serious usability issues compared to the old version.

### How to reproduce

Open the calendar 2.0 app, click on any date to enter a new event.

### Observations / Problems

- It is not possible to set only the time part by clicking on it.
One has to select the date first, which makes no sense, as it was already selected.
- Then the actual time select widget starts by displaying the hours from 0 to 6, which are hardly ever used. Scrolling per mousewheel does not work.
- Finally the minute widget does not allow to select the commonly used 15 and 45 minutes values.

### Solution

Please provide a widget with comparable ease of use as the old version, which had none of these issues and worked very well.

![grafik](https://user-images.githubusercontent.com/1863743/74678442-47967b80-51bb-11ea-83ff-c95b0e7b2cdf.png)

### Specs

- Firefox 72 on Ubuntu 16.04
- Nextcloud 17.0.3
- Calendar 2.0.1

**Comment by georgehrke** [comment] 2020-02-17 18:37
> It is not possible to set only the time part by clicking on it.
One has to select the date first, which makes no sense, as it was already selected.

This part has already been discussed in detail here: https://github.com/nextcloud/calendar/issues/1928

> Then the actual time select widget starts by displaying the hours from 0 to 6, which are hardly ever used. Scrolling per mousewheel does not work.

Can you please create a small screencast of that? I'm not able to reproduce it in Firefox on macOS.
(or any other browser i have tried so far)

> Finally the minute widget does not allow to select the commonly used 15 and 45 minutes values.

That's indeed an important point, let's change it to steps of 5.

**Comment by georgehrke** [comment] 2020-02-17 18:41
I would furthermore like to point out that we are planning on updating to version 3 of the vue component used as a date picker, which comes with many improvements regarding its time picker.
https://github.com/mengxiong10/vue2-datepicker

Progress can be tracked here: https://github.com/nextcloud/nextcloud-vue/pull/783

**Comment by klemens-u** [comment] 2020-02-17 18:57
Thanks for the information.

It would be very nice if the hours and minutes widget would display all sensible values (all hours, 5minute intervals) without scrolling.

>> Scrolling per mousewheel does not work.
> Can you please create a small screencast of that? I'm not able to reproduce it in Firefox on macOS.
(or any other browser i have tried so far)
I've created a separate issue for that: #2003

**Comment by georgehrke** [comment] 2020-02-18 10:45
This seems to be a regression either the vue component:

We are already setting the steps to 5 according to the documentation: 
https://github.com/mengxiong10/vue2-datepicker/tree/2.x#props

https://github.com/nextcloud/calendar/blob/master/src/components/Shared/DatePicker.vue#L31
https://github.com/nextcloud/calendar/blob/master/src/components/Shared/TimePicker.vue#L31

Version 2 of that vue component is no longer maintained, so we will have to update it to 3 before proceeding here. nextcloud/nextcloud-vue#783

**Comment by georgehrke** [comment] 2020-02-21 13:44
There is a fix for the minute step bug in https://github.com/nextcloud/nextcloud-vue/pull/861

**Comment by georgehrke** [comment] 2020-03-08 19:04
This issue will be resolved once we merged https://github.com/nextcloud/calendar/pull/2060

**Closed** 2020-03-11 14:35 UTC
Labels: 1 - to develop, bug, upstream
