### ISSUE TITLE
Sync existing iCloud calendar with NC

### ISSUE THREAD

**Issue by Niclas-sol** [nextcloud/calendar#1317] opened 2019-04-19 15:43 UTC
**Is your feature request related to a problem? Please describe.**
I want to add my existing iCloud calendar with an ical link to my nextcloud to view and edit my calendar in NC and on my iPhone. But since Apple uses app specific passwords for things like the calendar I can't enter the password because NC doesn't open the requested login.

**Describe the solution you'd like**
I want to add my existing iCloud calendar with an ical link to my nextcloud to edit my calendar in NC and on my iPhone.

**Describe alternatives you've considered**
Publish my calendar with iCloud. Gives me only read permissions and is accessible from the internet.

**Comment by wiswedel** [comment] 2019-06-12 20:17
CC @georgehrke

**Comment by georgehrke** [comment] 2019-06-12 20:21
> I want to add my existing iCloud calendar with an ical link to my nextcloud to view and edit my calendar in NC and on my iPhone

Editing will never work when using an ical link. They are read only.

Duplicate of https://github.com/nextcloud/calendar/issues/70
(Supporting ical links with password)

Duplicate of https://github.com/nextcloud/server/issues/252
(External CalDAV, would allow edits)

**Comment by georgehrke** [comment] 2019-06-12 20:22
@wiswedel Server Repo was correct btw. The calendar app repo is only for the actual webinterface. Everything that's related to the CalDAV server and CalDAV sharing, etc. belongs in the server.

**Closed by georgehrke** 2019-06-12 20:21 UTC

**Comment by wiswedel** [comment] 2019-06-12 20:22
> @wiswedel Server Repo was correct btw. The calendar app repo is only for the actual webinterface. Everything that's related to the CalDAV server and CalDAV sharing, etc. belongs in the server.

roger. thanks for clarifying
