### ISSUE TITLE
Misleading information on ics mail invitation for recurring event

### ISSUE THREAD

**Issue by quentinDupont** [nextcloud/calendar#4356] opened 2022-07-07 10:23 UTC
### Steps to reproduce

1. Create a recurrent event
2. Change date for 2nd event

### Expected behavior

- Receive a first mail for the recurring event :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/9005817/177751373-0065e7c0-fc91-4500-a60a-0c4712ecf2da.png)
- Receive a new mail for this 2nd event that has been changed :heavy_check_mark: 
- This mail should indicate new dates of the 2nd event :x: 

### Actual behaviour

- The mail is exactly the same as the first one : it indicates the former dates of the 1st event  

### Calendar app version

3.4.1

### Browser

Firefox

### Client operating system

Linux Ubuntu

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

23.0.6

### Additional info

If i download ics attachements, and try to open on Evolution, i can see that the ICS file is well done. So the probleme is about the sended mail I guess.

![image](https://user-images.githubusercontent.com/9005817/177752066-a1fc69b9-bc9b-4fbc-9c66-ea85bbb00f31.png)

**Comment by miaulalala** [comment] 2022-07-07 10:35
Right, this is one issue with the recurrences in emails.

We only ever send emails for the next event as we don't allow accepting all recurring events in one email from iMIP, which probably also causes this bug.

**Comment by ChristophWurst** [comment] 2022-07-07 10:55
Duplicate of https://github.com/nextcloud/calendar/issues/3919

**Closed by ChristophWurst** 2022-07-07 10:55 UTC
Labels: 1 - to develop, bug
