### ISSUE TITLE
Calendly-like feature to book appointments

### ISSUE THREAD

**Issue by dgsiegel** [nextcloud/calendar#1116] opened 2019-02-13 17:40 UTC
More a feature request than a bug. I'd love to have the opportunity to let people book meetings via my Nextcloud instance. There are several services available, like Calendly or WhenWorks, but they all are closed-source and require your calendar to be sent to their servers in order to check for a free time slot.

It would be great to have a feature in Nextcloud calendar, that allows the following:

1. Provide a public link for every user/calendar which shows available time slots (Probably to be configurable, e.g. 1hr slots only Mo-Fr between 8am and 5pm)
2. Show visitors the remaining free time slots and allow them to choose a day and time to "book" a meeting
3. This should result in a normal calendar entry, filled out with the visitors data (e.g. email and name). Notifications will be sent automatically, like in the current version

Is a feature like this possible?

**Comment by georgehrke** [comment] 2019-02-14 08:28
Please look for duplicates before creating new issues. Thx

Duplicate of https://github.com/nextcloud/calendar/issues/1023

**Closed by georgehrke** 2019-02-14 08:28 UTC

**Comment by jancborchardt** [comment] 2019-02-19 13:22
Sorry, I pointed @dgsiegel to open an issue – wasn’t aware of the open issue. I do think it’s a really useful feature though. :)

**Comment by georgehrke** [comment] 2019-02-19 13:27
> I do think it’s a really useful feature though. :)

Absolutely! But it's best to do it incrementally imo:
- allow editing public calendars
- allow sharing public calendars as free/busy only

If we have those two, implementing #1023 should be fairly easy :)
