### ISSUE TITLE
.ics DTEND is wrong (all day events)

### ISSUE THREAD

**Issue by omocinteractive** [nextcloud/calendar#888] opened 2018-08-13 18:53 UTC
### Steps to reproduce
1. Add a event 1.11-4.11.2018
2. Download iCal-Data
3. Output:

DTSTART;VALUE=DATE:20181101
DTEND;VALUE=DATE:20181105

### Expected behaviour
Output the correct DTEND 20181104

### Actual behaviour
.ics output the wrong DTEND. When i use CalDav everything okay. But i need the .ics for 6 different portals like booking.com and the show all the enddate +1.
![image 031](https://user-images.githubusercontent.com/20245225/44051578-86e48924-9f3a-11e8-9f5b-7baf8d979c8e.png)
![image 032](https://user-images.githubusercontent.com/20245225/44051586-8c9156ae-9f3a-11e8-8c91-82563207566e.png)

### Server configuration

Ubuntu 16.04

Apache

MySQL

PHP 7

**Calendar version:** 1.61

**Updated from an older installed version or fresh install:** update

**Signing status (ownCloud/Nextcloud 9.0 and above):** 13.04

**Comment by georgehrke** [comment] 2018-08-13 18:58
This is the expected behavior:
See https://tools.ietf.org/html/rfc5545#section-3.6.1

> The following is an example of the "VEVENT" calendar component used to represent a multi-day event scheduled from June 28th, 2007 to July 8th, 2007 inclusively.  Note that the "DTEND" property is set to July 9th, 2007, since the "DTEND" property specifies the non-inclusive end of the event.

> ```
> BEGIN:VEVENT
> UID:20070423T123432Z-541111@example.com
> DTSTAMP:20070423T123432Z
> DTSTART;VALUE=DATE:20070628
> DTEND;VALUE=DATE:20070709
> SUMMARY:Festival International de Jazz de Montreal
> TRANSP:TRANSPARENT
> END:VEVENT
> ```


Or am i misunderstanding your bugreport?

**Comment by georgehrke** [comment] 2018-08-13 19:09
Closing, because that's the expected behavior.
Please comment if i understood your bug report wrong.

**Comment by omocinteractive** [comment] 2018-08-13 19:09
Ah, sorry, you are right.

**Closed by georgehrke** 2018-08-13 19:09 UTC
