### ISSUE TITLE
[Feature request] Edit single events apart from their series

### ISSUE THREAD

**Issue by Sherl0ck007** [nextcloud/calendar#908] opened 2018-09-18 07:18 UTC
It would be nice if there was an option when clicking on an event of a series to choose between editing the whole series or just the single event. 

For example, having a the status of a series on tentative (because I don't know whether or not I can make it every week) and then marking single events in that series as confirmed.
Or deleting or editing an event within the series because it has been cancelled or moved to a different time slot or location.

Note: when using Google Calendar on Android to sync the calendar, there is alway an option for events in series to delete "all events", "only this event" or "this and all following events". But editing that, it doesn't sync to Nextcloud.

**Comment by RDominique** [comment] 2018-09-30 14:35
This is a dupplicate of:
[#801](https://github.com/nextcloud/calendar/issues/801) and [#7](https://github.com/nextcloud/calendar/issues/7)

jospoortvliet has put a bounty of $85 on this issue...

**Comment by georgehrke** [comment] 2018-10-07 08:38
Duplicate of #7

**Closed by georgehrke** 2018-10-07 08:38 UTC
