### ISSUE TITLE
ical link with veiled titles - only availability

### ISSUE THREAD

**Issue by ScreamingDev** [nextcloud/calendar#725] opened 2018-02-11 08:10 UTC
### Steps to reproduce
1. Create a new calendar
2. Add an appointment
3. ...
4. Profit

### Expected behaviour

I am searching for an ICAL-URL of that particular calendar which shows my "availability".
It has all my appointments listed but without any details and the title is just "not available" or something like that.
So no details leak at all.

This way I can give this to customers and other web services for further processing.

### Actual behaviour

No link like that exists.
Issue could also be that I don't find it.

### Server configuration

**Operating system**: Unknown

**Web server:** nginx

**Database:** Unknown

**PHP version:** Unknown

**Server version:** No admin access

**Calendar version:** No admin access

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):** What?

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by phlegx** [comment] 2019-03-28 23:32
Yes, this is exactly what I need too. NX can do it same as OX do it. There is a setting: Visibility -> Private. The question is, visible for the complete shared calendar, or for some users? All events of the calendar or only events with visibility private?

![screen](https://user-images.githubusercontent.com/111506/55199219-9a3d0280-51b9-11e9-9606-d7f390219baf.png)

**Comment by georgehrke** [comment] 2019-09-13 10:44
Duplicate of https://github.com/nextcloud/server/issues/11214

**Closed by georgehrke** 2019-09-13 10:44 UTC
Labels: enhancement-proposed
