### ISSUE TITLE
Configure the first day of the week

### ISSUE THREAD

**Issue by vince-from-nice** [nextcloud/calendar#1486] opened 2019-09-13 15:12 UTC
It would be nice if user could define the first day of the week.

For french people (maybe all european people?) it is very disturbing to have weeks which begins on sunday.

It is a common option in advanced calendars such as Thunderbird, KOrganizer, Google, etc.

Thanks, Vincent.

**Comment by tcitworld** [comment] 2019-09-13 17:15
Since Nextcloud 14 we have a locale user setting in server that we rely on to determine which day is the first of the week.

Closing as duplicate of https://github.com/nextcloud/calendar/issues/384

**Closed by tcitworld** 2019-09-13 17:15 UTC

**Comment by vince-from-nice** [comment] 2019-09-13 19:50
Thanks for the info and sorry for the duplicate.

**Comment by masterwishx** [comment] 2022-03-18 16:11
> Since Nextcloud 14 we have a locale user setting in server that we rely on to determine which day is the first of the week.
> 
> Closing as duplicate of #384

If I choose Hebrew for local I'm getting first day Sunday but also some text in Hebrew in nextcloud.
But I need all nextcloud in my first language where first day is Monday. But in Israel I need first day Sunday.
Please fix it
