### ISSUE TITLE
Calendar Cannot Save Event in Android Firefox (new Design)

### ISSUE THREAD

**Issue by florom** [nextcloud/calendar#2563] opened 2020-09-07 08:14 UTC
Hi Devs,

unformatunatly with the new Firefox Design the Save (or Update) Button ist now hidden (overlapped) by the new Firefox Adress bar which stays now at the botton.

It would be nice to fix it.

Here a Picture:

Unable to add  Screenshot so Adding Link to help.nextcloud Issue (where there is a Screenshot)

https://help.nextcloud.com/t/calendar-cannot-save-event-in-android-firefox-new-design/91626

Thanks,
Florom

Nextcloud 19.0.2 Calendar 2.0.4

**Comment by SamuelBlickle** [comment] 2020-10-16 14:21
As a workaround it helps to [move the navigation bar](https://support.mozilla.org/en-US/kb/move-navigation-bar?redirectslug=move-firefox-preview-navigation-bar-top-or-bottom&redirectlocale=en-US) back to the top. But this doesn't fix the underlying problem of course.

**Comment by florom** [comment] 2020-10-17 12:24
Hi @SamuelBlickle ,

Thanks for the hint. I tried not to use it :)
That is still a good workaround,
hopefully that will get fixed cause bar at the bottom has its advantages.

Thank you.

**Comment by szaimen** [comment] 2021-09-30 13:06
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-09-30 13:06 UTC
Labels: bug, 0. to triage

**Comment by florom** [comment] 2021-09-30 15:30
Hi @szaimen ,
Could not reproduce it either. Did not use bottom Navigation bar anymore and got used to it.
But it is good to know that it got fixed.

Thanks.
