### ISSUE TITLE
Feature Request: Mini-Calendar on top left, instead of the left-right buttons

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/calendar#919] opened 2018-10-05 13:04 UTC
Currently, the top left corner looks like this:
![image](https://user-images.githubusercontent.com/15927695/46536530-16135d80-c8af-11e8-8c78-de487beb2eeb.png)

It would be cool to have a mini-calendar instead of these buttons. I thought of something like this:
![image](https://user-images.githubusercontent.com/15927695/46536488-f5e39e80-c8ae-11e8-8f91-b850fb4bba47.png)

The mini calendar would have to act like in Outlook calendar, where it selects a whole month, a whole week or a single day, according to what the user selected below.

Extra-cool would be to be able to click on the current showed year ("February 2012" in this case) and then all years appear, like in this example:
![image](https://user-images.githubusercontent.com/15927695/46536785-d39e5080-c8af-11e8-938f-76db645ef14a.png)

**Comment by georgehrke** [comment] 2018-10-05 13:05
Have you tried clicking on "October 2018"? 😉

**Comment by georgehrke** [comment] 2018-10-05 13:05
Duplicate of #881

**Closed** 2018-10-05 13:05 UTC

**Comment by AmonBune** [comment] 2018-10-05 13:08
Wow. Now I feel really dumb. Thanks for pointing it out.

The idea with the years still stands though :)

**Comment by georgehrke** [comment] 2018-10-05 13:09
There is also a ticket about this: https://github.com/nextcloud/calendar/issues/703 :)

**Comment by AmonBune** [comment] 2018-10-05 13:12
I admit defeat :( Thanks for your quick answers.
