### ISSUE TITLE
New invitation to participants after deleting unique date of periodic event

### ISSUE THREAD

**Issue by mokkin** [nextcloud/calendar#2307] opened 2020-06-05 10:58 UTC
### Steps to reproduce
I have deleted a single event via Thunderbird Lightning of a periodic event that is occuring every two weeks. In this event one participant is included. After deleting the event the other participant received an new invitation to the beginning of the periodic event in the past.

### Expected behaviour
No new invitation.

### Actual behaviour
see above

## Server configuration detail

**Operating system:** Linux 4.9.0-0.bpo.11-amd64 #1 SMP Debian 4.9.189-3+deb9u1~deb8u1 (2019-09-30) x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, gmp, SPL, iconv, session, json, mbstring, pcntl, standard, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, mysqlnd, cgi-fcgi, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, sodium, ldap, tidy, pdo_sqlite, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** since OC 4

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - documentserver_community: 0.1.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_markdown: 2.2.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.6
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notes: 3.4.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.7
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - passwords: 2020.5.0
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - qownnotesapi: 20.1.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - deck
 - encryption
 - files_readmemd
 - mail
 - maps
 - phonetrack
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
    

    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app.mail.server-side-cache.enabled": true,
    "theme": "",
    "loglevel": 2,
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "mysql.utf8mb4": true,
    "htaccess.RewriteBase": "\/"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** doesn't matter here

**Operating system:** doesn't matter here

## Logs

<details><summary>Web server error log</summary>

```
n/a
```
</details>

<details><summary>Nextcloud log</summary>

```
n/a
```
</details>

<details><summary>Browser log</summary>

n/a
</details>

**Comment by georgehrke** [comment] 2020-06-05 11:01
Duplicate of https://github.com/nextcloud/server/issues/21220

**Closed by georgehrke** 2020-06-05 11:01 UTC
Labels: 0. to triage, bug
