### ISSUE TITLE
Entries which are entered in a shared calendar disappear

### ISSUE THREAD

**Issue by razorfall** [nextcloud/calendar#126] opened 2016-10-13 11:29 UTC
Heyy guys,

First of all, English is not my native language =)

I hope you can help me with my issue!

### Steps to reproduce
1. User A creates a calendar and shares it with user B, who is in the same group.
2. User B creates a calendar entry in this shared calendar.
3. After a few seconds, the entry for user B disappears and is displayed at user A at the same time.
4. User A creates an entry in his calendar, which is not displayed to user B.

### Expected behaviour
It should be possible to create an entry in a shared calendar and both sides should be able to see this entry.

### Actual behaviour
The owner of the shared calendar is always given the entries while the shared users can not see the entries.
It does not matter with which user I try this.
Info: none of the two users has admin rights.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
7.0

**Server version:** (see your admin page)
Nextcloud 10.0.1 (stable)

**Calendar version:** (see the apps page)
1.4.0

**Updated from an older installed version or fresh install:**
Fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
USER@HOST:~$ sudo -u www-data php occ app:list
Could not open input file: occ

```
Manually copied:
```
Activity - 2.3.2
Auditing / Logging - 1.0.0
Collaborative tags - 1.0.2
Comments - 1.0.0
Default encryption module - 1.3.1
Deleted files - 1.0.0
Federation - 1.0.1
File sharing - 1.0.0
First run wizard - 1.1
Gallery - 15.0.0
Notifications - 0.3.0
Password policy - 1.0.0
PDF viewer - 0.8.1
Provisioning API - 1.0.0
Server info - 1.1.1
Text editor - 2.1
Theming - 1.0.1
Update notification - 1.0.1
Usage report - 0.1.5
Versions - 1.3.0
Video player - 0.9.8
Bookmarks - 0.9.0
Calendar - 1.4.0
Contacts - 1.4.0.0
Tasks - 0.9.3
```
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'PRIVATE',
  'passwordsalt' => 'PRIVATE',
  'secret' => 'PRIVATE',
  'trusted_domains' => 
  array (
    0 => 'MYDOMAIN',
  ),
  'datadirectory' => '/home/CLOUDFOLDER/data',
  'overwrite.cli.url' => 'https://MYDOMAIN/NEXTCLOUD',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'CLOUDDATABASE',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'DATABASEPREFIX',
  'dbuser' => 'DATABASEUSER',
  'dbpassword' => 'PRIVATE',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0.0,
  ),
  'loglevel' => 3,
  'versions_retention_obligation' => 'auto',
  'appcodechecker' => true,
  'updatechecker' => true,
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
);
```

**Are you using external storage, if yes which one:**
/home/Cloudfolder/data

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:**
Webdav

### Client configuration
**Browser:**
Firefox
Android Browser

**Operating system:**
Win7 64Bit
Android 5 and 6

**CalDAV-clients:**
DavDroid 1.3.2.2

#### Web server error log
```
This log is too big (about 6500 lines) to upload @ pastebin.org
```

#### Log file (data/owncloud.log)
```
{"reqId":"oQMHwd3XXtIIczPsm8ye","remoteAddr":"IPADRESS","app":"PHP","message":"mkdir(): No such file or directory at \/var\/www\/html\/CLOUDFOLDER\/lib\/private\/Setup.php#289","level":3,"time":"2016-10-10T20:58:31+00:00","method":"POST","url":"\/CLOUDFOLDER\/index.php","user":"--"}
{"reqId":"aC5pWneMfRyb+SP2cGL8","remoteAddr":"IPADRESS","app":"PHP","message":"mkdir(): No such file or directory at \/var\/www\/html\/CLOUDFOLDER\/lib\/private\/Setup.php#289","level":3,"time":"2016-10-10T21:00:11+00:00","method":"POST","url":"\/CLOUDFOLDER\/index.php","user":"--"}
{"reqId":"NEULxRLP2NxZdKXG52ou","remoteAddr":"IPADRESS","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_USER\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'CLOUDFOLDERuser'@'localhost' for table 'user'","level":3,"time":"2016-10-10T21:00:47+00:00","method":"POST","url":"\/CLOUDFOLDER\/index.php","user":"--"}
{"reqId":"NEULxRLP2NxZdKXG52ou","remoteAddr":"IPADRESS","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `CLOUDFOLDER` . * TO 'CLOUDFOLDERuser'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'CLOUDFOLDERuser'@'localhost' to database 'CLOUDFOLDER'","level":3,"time":"2016-10-10T21:00:47+00:00","method":"POST","url":"\/CLOUDFOLDER\/index.php","user":"--"}

```

#### Browser log
```
I don't know how to get this, sry =/
```

#### Edit:

I've added all the protocols that I could find.

I realized that my server runs on 4 GB RAM! o.O
This is the maximum of my vserver!
Any ideas what's going on?

I've also noticed that my weblog in nextcloud is only the following error:
```
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:01:04+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:01:04+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:01:02+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:54+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:53+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:52+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:51+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:50+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:49+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:48+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:47+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:46+00:00	USER
Error	PHP	Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85	2016-10-14T05:00:45+00:00	USER
```

Greetz
razorfall

**Comment by georgehrke** [comment] 2016-10-15 17:53
please provide the logs :)

**Comment by razorfall** [comment] 2016-10-15 19:43
I've added everything possible =)

**Comment by MariusBluem** [comment] 2016-10-16 08:35
> Web server error log

If it is too big, could you please only paste "relevant" parts here 😁 ...this would help 😅 

> Browser log

To open the Browser Console, select "Browser Console" from the Web Developer submenu in the Firefox Menu (or Tools menu if you display the menu bar or are on Mac OS X).
(https://developer.mozilla.org/de/docs/Tools/Browser_Console)

**Comment by razorfall** [comment] 2016-10-17 19:04
Sorry for the late response, but I had to do a lot of stuff =/

Browser Log:
```
GET 
XHR 
https://nc.0point0.de/nextcloud/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 214ms]
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIX509Cert.equals]ssl-observatory.js:472
GET 
XHR 
https://nc.0point0.de/nextcloud/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 200ms]
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIX509Cert.equals]
```

The complete web server log:
```
[http://www.file-upload.net/download-12023987/webinterface-nextcloud.log.html]
```

**Comment by georgehrke** [comment] 2016-10-17 19:06
> The complete web server log

Please post only the relevant logs. Digging thru 2.7MB of logs won't happen.

Delete the nextcloud.log
Reproduce the issue as described above
check the nextcloud.log

Thx

**Comment by razorfall** [comment] 2016-10-17 19:08
@georgehrke 
Thats the info I needed!
Give me a few minutes =D

**Comment by razorfall** [comment] 2016-10-17 20:36
All entries with "Undefined index: MemAvailable" arrive according to the log at a distance of one second.
I have deleted this so the rest of the relevant information is visible.
```
http://pastebin.com/gAbQNmZE
```

**Comment by rfc2822** [comment] 2016-10-18 10:07
May this be because of the "Privacy" setting in the Android calender event? "Default" was mapped to `CLASS:PRIVATE` in previous DAVdroid versions. Does it work with "Privacy: public"?

**Comment by Grot4x** [comment] 2016-10-18 19:05
@rfc2822 you are right. I had the same problem with one of my clients. Changing the privacy setting in the Android app to public solved it for me. This also explains why another client didn't have this problem (older davdroid).

I am not sure if this default setting is an good idea but i guess thats not a problem of the nextcloud calendar app.

@razorfall the logs you provided are not related to this issue, I think you should open a new one if you still have a problem.

So I think this issue can be closed.

**Comment by razorfall** [comment] 2016-10-18 20:09
@ Rfc2822 I can't find a setting of this kind in DavDroid =/
Can you tell me where I can change this setting?

@ Grot4x This problem can not be closed because my problem is not resolved yet!
These protocols are the ones I was asked for.
If you see another problem with my logs, please tell me what it is and I will open another problem, as far as I can not solve it myself.

**Comment by georgehrke** [comment] 2016-10-18 20:11
Ah, the events mentioned in the reproduction steps were creating in DavDroid?
That's an important piece of information ;)

**Comment by razorfall** [comment] 2016-10-18 20:14
@georgehrke I mentioned before, that I use DavDroid:
```
CalDAV-clients:
DavDroid 1.3.2.2
´´´
But I'm not sure where the source of this problem lies.

**Comment by georgehrke** [comment] 2016-10-18 20:16
But I didn't know that you created the events with DavDroid ;)

@rfc2822 's theory about the PRIVACY its very plausible. It explains why user B can't see his own event, but user A does and why user B can't see events created by user A.

**Comment by georgehrke** [comment] 2016-10-18 20:17
Apparently this was fixed in DavDroid 1.3.3
Please update
https://forums.bitfire.at/post/7378

**Comment by razorfall** [comment] 2016-10-18 20:20
Ok, I'll try it!
At the time I posted this issue the version 1.3.2 was the newest ^^

**Comment by rfc2822** [comment] 2016-10-18 20:28
It hasn't been "fixed", because it was not a bug. In iCalendar, there simply is no " server default", but in Android, there is. So it's a question of default mapping - the previous approach was not to set any event to "public" which hasn't been declared "public" explicitly, whereas the new (1.3.3) approach is that "server default" just doesn't send a CLASSification, but this means "public" by default. So the default behaviour has changed, but it's not a fix. If you want events to be public, the best idea is to set it to public explicitly.

**Comment by georgehrke** [comment] 2016-10-18 20:29
>  because it was not a bug.

It was a bug. The standard says, that the default is `PUBLIC` 😉 
https://tools.ietf.org/html/rfc5545#section-3.8.1.3

**Comment by razorfall** [comment] 2016-10-18 20:32
Ok, the calendar sync issue is solved!

Thanks for all your help!

I'll open another issue with my memory issue =)

**Comment by rfc2822** [comment] 2016-10-18 20:33
No, it was not. The standard says the default is public, which means that if you don't send a CLASS, its value is PUBLIC by default. It does not say anything about mappings of Android "server default" values. In iCalendar, there is not CLASS:SERVER-DEFAULT or something like that. So it's a matter of interpretation how you map the Android "server default" value to an iCalendar value. In previous versions, it was mapped to PRIVATE, and now its mapped to <no CLASS>, which means PUBLIC (as you have quoted).

**Comment by georgehrke** [comment] 2016-10-18 20:33
If you are referring to `Error   PHP Undefined index: MemAvailable at /var/www/html/nextcloud/apps/serverinfo/lib/SystemStatistics.php#85    2016-10-14T05:00:52+00:00   USER`, please report it in https://github.com/nextcloud/serverinfo

But this is only a very minor issue.

**Closed** 2016-10-18 20:33 UTC
Labels: 1 - to develop, bug, needs info

**Comment by razorfall** [comment] 2016-10-18 20:40
@georgehrke 
I thought that the nextcloud server consumes quite a bit of memory, since I see the use of 4 GB RAM, which my host only temporarily provides me, is quite high!

Since I only pay for 2 GB of RAM and can only temporarily use the 4 GB of RAM for free, this is for me a rather big problem = /

Thanks for the info, I will try my luck there!

**Comment by georgehrke** [comment] 2016-10-18 20:53
@rfc2822 yes, if there is no class, it's supposed to be public. And I expect clients to use that default value as long as users didn't explicitly changed some configuration for it. That's why I consider it a bug. 

Please excuse my brevity and typos.
