### ISSUE TITLE
Option to zoom in/out the timeGrid

### ISSUE THREAD

**Issue by doitux** [nextcloud/calendar#1892] opened 2020-01-24 08:48 UTC
After the NC Update from 17.0.2 to 18.0.0 (Calendar version 2.0.1) i realized the timeGrid is divided into quarter hours now. I think it was half hours before. But now i have to scroll a lot to have an overview of all dates of a day/week which is a bit annoying. 

It would be useful to have an option to zoom in/out the grid to have e.g. the whole day from 0:00 to 23:59 on the screen without scrolling. The zoom state should be remembered by the software. 

Another option would be to optionally set the grid divided into half hours as it was (imho) before.

**Comment by georgehrke** [comment] 2020-01-24 09:48
Duplicate of #577

**Closed by georgehrke** 2020-01-24 09:48 UTC
Labels: 0. to triage, enhancement-proposed
