### ISSUE TITLE
mouse scroll wheel

### ISSUE THREAD

**Issue by 1ucay** [nextcloud/calendar#620] opened 2017-10-02 09:09 UTC
It will be possible to add scrolling via mouse wheel? For example, if I have cursor in calendar month view and there is no inner scrollbar ( browser height is optimal ) and I scroll via mouse wheel, than calendar jump to next month.

Some logic for this:
".fc-scroller" if has overflow-y than do nothing. If has no overflow-y, than trigger event click on ".datepicker-heading .button.last".

Thanks

**Comment by georgehrke** [comment] 2017-10-02 09:11
> than calendar jump to next month.

Are u referring to this?
https://github.com/nextcloud/calendar/issues/6

**Comment by 1ucay** [comment] 2017-10-02 09:14
Ahh sorry. It is possible to add this functionality to nextcloud calendar instead of fullcalendar?

**Comment by georgehrke** [comment] 2017-10-02 09:16
> It is possible to add this functionality to nextcloud calendar instead of fullcalendar?

The Nextcloud calendar uses fullcalendar. If we implement it on our own instead of fullcalendar, it's likely to break with any major (or maybe even minor) update of fullcalendar. That's why we want to have it in upstream.

**Comment by georgehrke** [comment] 2017-10-02 09:16
closing as duplicate of #6

**Closed by georgehrke** 2017-10-02 09:16 UTC
