### ISSUE TITLE
WebCal-URL should be empty after subscribing to a remote calendar

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/calendar#73] opened 2016-09-20 12:10 UTC
### Steps to reproduce
1. Click New Subscription
2. Insert URL and click create
3. Click New Subscription to add another remote calendar

### Expected behaviour
WebCal-URL should be empty
### Actual behaviour
previously added WebCal-Url is still shown inside the input filed

### Server configuration
**Calendar version:** 1.4.0

**Comment by tcitworld** [comment] 2016-09-20 12:10
Duplicate of https://github.com/nextcloud/calendar/issues/58

**Closed by tcitworld** 2016-09-20 12:10 UTC
Labels: bug

**Comment by juliushaertl** [comment] 2016-09-20 12:13
Ah sorry, forgot to have a look for existing issues. :see_no_evil:
