### ISSUE TITLE
Creating event dialogue box goes off screen

### ISSUE THREAD

**Issue by dcrobertson01** [nextcloud/calendar#1434] opened 2019-08-30 03:57 UTC
### Steps to reproduce
1. Go to calendar
2. click on a date
3. Add Event dialogue opens

### Expected behaviour
Entire Add Event dialogue should be visible
### Actual behaviour
Top of the Add Event dialogue is not visible. Unable to add Title, cannot save without title.

### Server configuration

**Operating system**:
Nethserver 7.6
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
Nethserver
**Signing status:**
<details>
<summary>Signing status</summary>

```
Lot of extra files from the news app in the cache. Cache should really be somewhere else.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - apporder: 0.7.1
  - bookmarks: 1.1.1
  - calendar: 1.7.0
  - circles: 0.17.7
  - cloud_federation_api: 0.2.0
  - cms_pico: 0.9.8
  - comments: 1.6.0
  - contacts: 3.1.3
  - dashboard: 6.0.0
  - dav: 1.9.2
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - groupfolders: 4.1.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.16.0
  - news: 13.1.6
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.1
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.8.1
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.1
  - theming: 1.7.0
  - theming_customcss: 1.3.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "server.rnet.duckdns.org",
            "10.0.0.2",
            "10.0.1.2",
            "cloud.rnet.duckdns.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.rnet.duckdns.org",
        "dbtype": "mysql",
        "version": "16.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "overwriteprotocol": "https",
        "loglevel": 0,
        "defaultapp": "mail",
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 3600,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logfile": "\/var\/lib\/nethserver\/nextcloud\/nextcloud.log",
        "mail_smtpsecure": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "tasks"
        ]
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------------+
| Configuration                 | s01                                                                           |
+-------------------------------+-------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                             |
| homeFolderNamingRule          |                                                                               |
| lastJpegPhotoLookup           | 0                                                                             |
| ldapAgentName                 | ldapservice@RNET.DUCKDNS.ORG                                                  |
| ldapAgentPassword             | ***                                                                           |
| ldapAttributesForGroupSearch  |                                                                               |
| ldapAttributesForUserSearch   |                                                                               |
| ldapBackupHost                |                                                                               |
| ldapBackupPort                |                                                                               |
| ldapBase                      | dc=rnet,dc=duckdns,dc=org                                                     |
| ldapBaseGroups                | dc=rnet,dc=duckdns,dc=org                                                     |
| ldapBaseUsers                 | dc=rnet,dc=duckdns,dc=org                                                     |
| ldapCacheTTL                  | 600                                                                           |
| ldapConfigurationActive       | 1                                                                             |
| ldapDefaultPPolicyDN          |                                                                               |
| ldapDynamicGroupMemberURL     |                                                                               |
| ldapEmailAttribute            | userPrincipalname                                                             |
| ldapExperiencedAdmin          | 0                                                                             |
| ldapExpertUUIDGroupAttr       |                                                                               |
| ldapExpertUUIDUserAttr        |                                                                               |
| ldapExpertUsernameAttr        |                                                                               |
| ldapExtStorageHomeAttribute   |                                                                               |
| ldapGidNumber                 | gidNumber                                                                     |
| ldapGroupDisplayName          | cn                                                                            |
| ldapGroupFilter               | (&(objectClass=group)(groupType:1.2.840.113556.1.4.803:=2))                   |
| ldapGroupFilterGroups         | Domain Users;Users;family;webdev                                              |
| ldapGroupFilterMode           | 0                                                                             |
| ldapGroupFilterObjectclass    | group                                                                         |
| ldapGroupMemberAssocAttr      | member                                                                        |
| ldapHost                      | ldaps://rnet.duckdns.org                                                      |
| ldapIgnoreNamingRules         |                                                                               |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(|(sAMAccountName=%uid)(userPrincipalName=%uid))) |
| ldapLoginFilterAttributes     |                                                                               |
| ldapLoginFilterEmail          | 0                                                                             |
| ldapLoginFilterMode           | 0                                                                             |
| ldapLoginFilterUsername       | 1                                                                             |
| ldapNestedGroups              | 0                                                                             |
| ldapOverrideMainServer        |                                                                               |
| ldapPagingSize                | 500                                                                           |
| ldapPort                      | 636                                                                           |
| ldapQuotaAttribute            |                                                                               |
| ldapQuotaDefault              |                                                                               |
| ldapTLS                       | 0                                                                             |
| ldapUserAvatarRule            | default                                                                       |
| ldapUserDisplayName           | displayName                                                                   |
| ldapUserDisplayName2          | samaccountname                                                                |
| ldapUserFilter                | (&(|(objectclass=person)))                                                    |
| ldapUserFilterGroups          |                                                                               |
| ldapUserFilterMode            | 0                                                                             |
| ldapUserFilterObjectclass     | person                                                                        |
| ldapUuidGroupAttribute        | auto                                                                          |
| ldapUuidUserAttribute         | auto                                                                          |
| turnOffCertCheck              | 1                                                                             |
| turnOnPasswordChange          | 0                                                                             |
| useMemberOfToDetectMembership | 0                                                                             |
+-------------------------------+-------------------------------------------------------------------------------+

```
</details>

### Client configuration
**Browser:**
Vivaldi
**Operating system:**
Kubuntu
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by georgehrke** [comment] 2019-08-30 09:18
Duplicate of https://github.com/nextcloud/calendar/issues/1323

**Closed by georgehrke** 2019-08-30 09:18 UTC
