### ISSUE TITLE
List view should scroll to the current day when opened

### ISSUE THREAD

**Issue by lectrician1** [nextcloud/calendar#5027] opened 2023-02-27 16:19 UTC
### Is your feature request related to a problem? Please describe.

When you select the list view, it always brings you to the start of the month. This makes the list view basically pointless if the current date is something past the first day as you have to scroll a lot to get to the current date in order to see your events for that day in a list view.

### Describe the solution you'd like

The list view when opened should automatically scroll to the current day.

### Describe alternatives you've considered

Some other alternatives could be to provide a dedicated current day list view.

**Comment by tcitworld** [comment] 2023-02-28 14:13
Duplicate of https://github.com/nextcloud/calendar/issues/2632

**Closed by tcitworld** 2023-02-28 14:13 UTC
Labels: enhancement, 0 - to triage
