### ISSUE TITLE
UX suggestions: Importing events

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/calendar#4212] opened 2022-05-13 20:03 UTC
### Steps to reproduce

1. Export a list of events from an old Nc 16 instances
2. Import the list of events in NC 24
3. Wait 10 seconds without any feedback and then refresh the page

### Expected behavior

Calendar is fully loaded and the import is fast.

### Actual behaviour

Calendar is only partially loaded. The issue is that because there was no feedback, I refreshed the page. 

Retrying later on with the network tab of the web inspector open, I found out that every events is sent individually and this create 2400 HTTP requests. I had to wait until they all finished (~5min) before reloading the page. What I would expect is that there is a progression bar indicating the progress of the upload. Or even better (but not sure if technically feasible ) that not every single is sent to the server in two requests but all in one go and the import operation is done in the server.

### Calendar app version

latest 3.3.0

### CalDAV-clients used

webui

### Browser

firefox 99

### Client operating system

Manjaro

### Server operating system

raspberry pi with raspbian

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 7.4

### Nextcloud version

24.0.0

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
fresh install
```

### Nextcloud configuration

```Text
fresh install + redis installed
```

**Comment by mthld** [comment] 2022-07-01 09:02
Hi,

I'm encountering the same issue, trying to import a 2,4 MB ICS Google export into a new calendar. I didn't believed at first there can be one single HTTP request per event, but looking at the network monitor of my web browser shows @CarlSchwan was obviously right.

There is 10 years of daily events in this ICS file, how long will it take to import everything? As said before the absence of UI feedback makes it really unusable. Most people will just close their browser tab after a minute or two, believing it simply isn't working.

**Comment by mthld** [comment] 2022-07-01 15:24
> I think there is actually a progress bar in the bottom left settings?

I'm doing this right now on a Nextcloud v24.0.2 instance and I assure you there is not.

**Comment by szaimen** [comment] 2022-07-01 15:25
> > I think there is actually a progress bar in the bottom left settings?
> 
> I'm doing this right now on a Nextcloud v24.0.2 instance and I assure you there is not.

all right! I only remembered that I've seen something like that before in the settings section on the bottom left. But I seem to be wrong here...

**Comment by szaimen** [comment] 2022-07-01 17:44
Thr settings section gets closed when you start the import. If you open it again it should display this progress bar

**Comment by szaimen** [comment] 2022-07-01 17:46
See https://github.com/nextcloud/calendar/issues/1859

**Comment by mthld** [comment] 2022-07-01 17:48
> Thr settings section gets closed when you start the import. If you open it again it should display this progress bar

Thank you for the hint, there was indeed no specific error in the console and the progress bar was always there, just hidden! Maybe @CarlSchwan can confirm on his end? But surely this issue can be closed in favour of #1859

Thanks for your time @szaimen! :)

**Comment by szaimen** [comment] 2022-07-01 17:50
All right!

Duplicate of https://github.com/nextcloud/calendar/issues/1859 then

**Closed by szaimen** 2022-07-01 17:50 UTC
Labels: 1 - to develop, bug, enhancement

**Comment by szaimen** [comment] 2022-07-01 21:30
Hello, I just found #2155, rebased it, fixed lint, tested it and it seems like it fixes the issue.

If you have docker installed locally, you can test this with:

```
docker run -it \
-e CALENDAR_BRANCH=bugfix/1859/keep_settings_open_during_import \
-p 127.0.0.1:8443:443 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```
