### ISSUE TITLE
[Feature Request] Change or delete only one appointment of a reccuring appointment

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/calendar#1824] opened 2020-01-16 12:50 UTC
If I have a series of appointments (reccuring appointment) it could happen, that only one of this appointments must be changed or deleted, and not the whole series.

Example;
Every week I have a meeting at the same day and time. But sometimes one of this meeting must be moved or canceld. Now this is not possible. I can't move on of this appointments, and if I try to delete it an create the modified one, then the whole series is gone.

**Comment by georgehrke** [comment] 2020-01-16 14:13
Duplicate of #7

**Closed by georgehrke** 2020-01-16 14:13 UTC
Labels: 0. to triage, enhancement-proposed
