### ISSUE TITLE
webcal link to subscribe is wrong

### ISSUE THREAD

**Issue by sebilasse** [nextcloud/calendar#3050] opened 2021-04-30 03:37 UTC
**Describe the bug**
The links

**To Reproduce**
1. Go to 'Calendar' e.g. https://cloud.w3c.social/apps/calendar/p/GzxsDfE6CKtp9MHX/dayGridMonth/now
2. Click on 'The dots menu -> copy subscription link' (“Abonnements-Link kopieren” here)
3. See error

**Expected behavior**
The link should begin `webcal:` but it begins `webcals:`

**Comment by tcitworld** [comment] 2021-04-30 09:06
Why is it wrong? `webcals` is as valid as `webcal`. Do you have a client that doesn't support this scheme?

**Comment by sebilasse** [comment] 2021-05-03 07:56
hm, not sure if it is the client, 
e.g. try to subscribe at https://cloud.w3c.social/apps/calendar/p/GzxsDfE6CKtp9MHX/dayGridMonth/now iCal (?)

**Comment by Gunnar-GO** [comment] 2021-05-03 08:04
i copied the link.
i tried `webcal://` and `webcals://` links. Both works flawless in link/import in one of my nextcloud installations. Maybe you use an other client?

Only thing i recognised is, that `CTRL + V` can not be used in the inputfield, but right click and insert does the job.

**Comment by sebilasse** [comment] 2021-05-03 08:12
I tested again now …
It is about the UI in the screenshot …
<img width="389" alt="Bildschirmfoto 2021-05-03 um 10 09 40" src="https://user-images.githubusercontent.com/750300/116854317-cd071f80-abf7-11eb-915b-ba719c113973.png">

It says “copy subscribe link” …
If I click there, the link results in 
`webcals://cloud.w3c.social/remote.php/dav/public-calendars/GzxsDfE6CKtp9MHX/?export`
but I can't subscribe.

However, if I click “download”, it is fine …

**Comment by tcitworld** [comment] 2021-05-03 08:22
So the issue is iCal not accepting `webcals` links, only `webcal` when you paste the link into iCal, correct?

**Comment by Gunnar-GO** [comment] 2021-05-03 12:01
Und über Kalender hinzufügen kannst du es deiner bekanntmachen

![image](https://user-images.githubusercontent.com/24938625/116873406-eddf6d00-ac17-11eb-92fb-e3ebbabc0239.png)

Das Problem ist also der Client, nicht die App oder der Server.

**Comment by tcitworld** [comment] 2021-06-14 07:10
Closed by #3212

**Closed by tcitworld** 2021-06-14 07:10 UTC
Labels: 0. to triage, bug
