### ISSUE TITLE
Notification of mail to the owner of an appointment, shows the time in format of the time zone of the applicant instead of the time zone of the owner

### ISSUE THREAD

**Issue by nonfreegithub** [nextcloud/calendar#5198] opened 2023-05-04 23:23 UTC
### Steps to reproduce

1. Config an appointment
2. Request an appointment with diferent time zone
3. Check the mail (to the owner)

### Expected behavior

Notification of mail to the owner of an appointment, shows the time in format of the owner's time zone

### Actual behaviour

Notification of mail to the owner of an appointment, shows the time in format of the applicant's time zone

### Calendar app version

4.3.3

### Browser

Firefox

### Client operating system

GNU/Linux

### Server operating system

GNU/Linux

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 7.4

### Nextcloud version

25.0.6

### Updated from an older installed version or fresh install

Fresh install

**Comment by mukil** [comment] 2023-09-20 12:56
I wonder if I have the same issue but to reproduce, can somebody tell me how to do  this?

> Request an appointment with diferent time zone

I would suspect the nextcloud webpage on which guests can choose a date and a timeslot in my calendar **does not** attempt to calculate some timezone client-side, or _does it_?

I am currently trying to figure out how a guest user - no authenticated HTTP session with my nextcloud - who booked an appointment in my calendar - via nextcloud calendar appointment feature - has a calendar entry which starts one hour later then the entry in my nextcloud calendar? Is it maybe the scope of this issue is not only about the "notification mail" but also affects the .ics/event data sent out by nextcloud. 

Sadly, I was unable to reproduce the issue? Therefore it would be helpful if somebody could tell me how to request an appointment with a different timezone.

**Comment by SebastianKrupinski** [comment] 2024-04-15 13:35
Confirmed.

Both the requestee and requester get a email with the exact same time, even tho the requestee's calendar time zone and requester's appointment time zone are different. Additionally the requestee gets a gui notification with the requester's time zone adjusted time and NOT their own calendar time zone.

**Comment by SebastianKrupinski** [comment] 2024-04-16 18:20
Issue addressed in PR #5924

**Closed** 2024-05-27 11:15 UTC
Labels: 2. developing, bug, Feature: Appointments
