### ISSUE TITLE
Unicode characters in event titles break moving events between calendars

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#4419] opened 2022-08-12 08:19 UTC
We ran into this bug and after figuring out how to reproduce, we tried NC 24.0.4rc1 with the merged fix. Unfortunately it didn't fix the error, we can still reproduce broken events by switching between calenders.

Edit: It seems this only happens if the title of the event in question has some unicode character or emoji. We can 100% reproduce it by using the white heavy check mark (U+2705 | \xE2\x9C\x85 | WHITE HEAVY CHECK MARK)

_Originally posted by @kartoffelheinz in https://github.com/nextcloud/server/issues/30120#issuecomment-1210763778_

**Comment by st3iny** [comment] 2022-08-12 08:19
Ref https://github.com/nextcloud/calendar/issues/3325

**Comment by berndschimmer** [comment] 2022-08-16 08:00
Plus 1

**Comment by berndschimmer** [comment] 2022-08-17 09:47
As my previous post was marked as spam, I will write a little more. This issue is a really annoying. If you create a calendar item and add a ✅ to the title and than change the calendar the item is gone and you have no suitable chance to get it back (data loss).

**Comment by tcitworld** [comment] 2022-10-02 09:48
I can't reproduce this on server master and calendar main, can you @st3iny ?

**Comment by berndschimmer** [comment] 2022-10-11 15:28
It seems that 24.0.4 (final) or 24.0.5 fixed it. All versions from 22. up to 24.0.4 are affected.

**Comment by st3iny** [comment] 2022-10-16 21:13
Awesome! Please let us know if the error persists. I'll close the issue in the meantime.

**Closed** 2022-10-16 21:13 UTC
Labels: bug, 0 - to triage
