### ISSUE TITLE
Allow Ajax popup windows to be closed by [Esc]

### ISSUE THREAD

**Issue by rookey** [nextcloud/calendar#4164] opened 2022-04-19 09:22 UTC
### Describe the solution you'd like

It would be UI-friendly and help usability (especially during stressing times) when the popup calendar entry window could be closed by using the [Esc] key in the browser (= not saving anything).

**Comment by szaimen** [comment] 2022-04-19 10:01
duplicate of https://github.com/nextcloud/calendar/issues/1964

**Closed by szaimen** 2022-04-19 10:01 UTC
Labels: enhancement, 0. to triage
