### ISSUE TITLE
[Feature request] clickable link url

### ISSUE THREAD

**Issue by michelwend** [nextcloud/calendar#928] opened 2018-10-19 17:11 UTC
Hello
I would like to put a clickable link in an event of the nextcloud calendar. Is it possible? If yes, how. Thanking you for your help

**Comment by georgehrke** [comment] 2018-10-22 13:58
Duplicate of https://github.com/nextcloud/calendar/issues/674

**Closed by georgehrke** 2018-10-22 13:58 UTC
