### ISSUE TITLE
importing a large-ish calendar (.ics)  takes a long time withou UI feedback

### ISSUE THREAD

**Issue by flo-dhalluin** [nextcloud/calendar#2288] opened 2020-05-27 13:29 UTC
### Steps to reproduce
1. import a large calendar file ( mine as a few 100s events )

### Expected behaviour
some sort of visual feedback ( a spinner, or progress bar ? ) showing that work is being done 

### Actual behaviour
nothing is visible, if you leave the page, import stops ( I initially though import was not working at all, until I checked the dev-tools to see that it was actually importing the events one by one ...)

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** web-client

### Client configuration
**Browser:** Firefox 75.0
**Operating system:**  debian linux testing

### Server configuration

**Operating system**: debian 10

**Web server:** nginx

**Database:** maria

**PHP version:** 7.3

**Nextcloud Version:** 18

**Nextcloud configuration:**
storage is swift object storage

**Comment by georgehrke** [comment] 2020-05-27 13:35
Duplicate of #1859 

Fix is work in progress in #2155

**Closed by georgehrke** 2020-05-27 13:35 UTC
Labels: 0. to triage, bug
