### ISSUE TITLE
the oldest calender entry appears first when searching

### ISSUE THREAD

**Issue by MaikOlive** [nextcloud/calendar#4919] opened 2023-01-24 09:48 UTC
### Steps to reproduce

1. use the search function
2. look at the results

### Expected behavior

the latest entry should be at the top of the list when searching calendar entries

### Actual behaviour

the oldest entry is at the top of the list

### Calendar app version

4.2.1

### Browser

Firefox 109.0

### Client operating system

Debian Linux

### Server operating system

Debian Linux

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 7.3

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by tcitworld** [comment] 2023-01-24 09:53
Duplicate of https://github.com/nextcloud/server/issues/27353

**Closed by tcitworld** 2023-01-24 09:53 UTC
Labels: bug, 0 - to triage
