### ISSUE TITLE
Password for public calendar resource

### ISSUE THREAD

**Issue by rullzer** [nextcloud/calendar#2630] opened 2020-10-06 13:34 UTC
Sometimes the calendars you subscribe to have a username+password.
Right now you can already set this in the URL. But this is not very intuitive for non technical users.

**Comment by tcitworld** [comment] 2020-10-06 16:47
Duplicate of #70 and it shouldn't work anyway https://github.com/nextcloud/3rdparty/pull/143 :thinking:

**Closed by tcitworld** 2020-10-06 16:47 UTC
Labels: 0. to triage, enhancement-proposed
