### ISSUE TITLE
public calendar export - links missing

### ISSUE THREAD

**Issue by ilippert** [nextcloud/calendar#740] opened 2018-02-24 21:40 UTC
Until the last update of the calendar app to 1.6.0, I was able to export a public calendar with

`<iframe` id="Cal"; width="850" height="365" `src="https://domain/index.php/apps/calendar/public'/ID"></iframe>`

and then get a nice cal display as well as two links for downloading the cal. After the recent update, these links disappear.
It would be nice if one could configure the app so that it shows such links again.

**Comment by georgehrke** [comment] 2018-02-24 22:17
I'm not sure I completely understand what you mean, but we moved the links into the upper right corner:
![9222683e-f13f-4715-88fc-0d60c57ee513](https://user-images.githubusercontent.com/1250540/36635623-caab6856-19b8-11e8-9261-82fbd2b82fbb.jpg)

**Comment by ilippert** [comment] 2018-02-25 00:55
Thank you for the immediate response. I get the view, which the screenshot indicates, when I open the URL directly. However, embedding the same URL in another page with the iframe, generates a view without the blue top bar (and its two links).

**Comment by georgehrke** [comment] 2018-02-25 08:11
We want to redesign the embed page with 1.6.2.
I added the subscribe / download button to the list of things we need to take care of https://github.com/nextcloud/calendar/issues/741

Closing as Duplicate of https://github.com/nextcloud/calendar/issues/741

**Closed by georgehrke** 2018-02-25 08:11 UTC
