### ISSUE TITLE
Invitation mail not sent when creating events in a shared calendar

### ISSUE THREAD

**Issue by rmeissn** [nextcloud/calendar#5081] opened 2023-03-22 10:16 UTC
### Steps to reproduce

1. Some user A shares a calendar with a group, which contains user B
2. User B creates an event on the shared calendar, inviting an external mail address

In my case: the admin account (A) shares a calendar with a group. My account (B) creates the event in the shared calendar.

### Expected behavior

An invitation is sent to the external mail address

### Actual behaviour

No invitation is sent to the external mail address.

If the admin account (A) creates the same event in the same shared calendar, an email is sent.
If my user account (B) creates an event in one of my personal calendars, an email is sent.
So email is working and addresses are correct.

### Calendar app version

4.3.0

### Browser

111.0

### Client operating system

Fedora 37

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.4

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
Enabled:
  - activity: 2.17.0
  - announcementcenter: 6.5.1
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - external: 5.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - groupfolders: 13.1.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.17.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.8.0
  - photos: 2.0.1
  - polls: 4.1.8
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_saml: 5.1.2
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard: 2.14.0
  - nextcloud_announcements: 1.14.0
  - password_policy: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - twofactor_totp
```

### Nextcloud configuration

```Text
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "dbtype": "mysql",
        "version": "25.0.4.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "default_language": "de",
        "default_phone_region": "DE",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false
    }
}
```

### Additional info

I see some failing (404) requests for the user status in the browser log, which come up if the external mail address is added. Nextcloud seems to expect that this is a user record, where a status is available. This shouldn't be relevant for this issue, as it also happens in the working cases (described above).

**Comment by tcitworld** [comment] 2023-03-22 10:39
Duplicate of https://github.com/nextcloud/server/issues/26668

**Closed by tcitworld** 2023-03-22 10:39 UTC
Labels: bug, 0 - to triage
