### ISSUE TITLE
Add an option to limit number of push requests when importing ics

### ISSUE THREAD

**Issue by smihael** [nextcloud/calendar#897] opened 2018-08-25 23:48 UTC
If the Nexcloud installation is hosted on a limited plan, importing calendar events from an ICS file will often fail. There should be an option to limit number of concurrent push requests to prevent 508 error response from server.  Current workaround to split ics into several smaller files (each containing 10-20 events) and then importing each separately is extremely user unfriendly.

**Comment by georgehrke** [comment] 2018-08-25 23:54
Duplicate of #445

**Closed by georgehrke** 2018-08-25 23:54 UTC
