### ISSUE TITLE
Change sort order for calendar items found in global search

### ISSUE THREAD

**Issue by beccon4** [nextcloud/calendar#5285] opened 2023-06-03 07:36 UTC
### Is your feature request related to a problem? Please describe.

When searching for appointments using the global Nextcloud search (the looking glass above), the calendar app finds items but unfortunately sorts them in an ascending order i.e. the oldest first. (when sorted at all - it looks a bit chaotic at the second glance)

### Describe the solution you'd like

When I search for an appointment, I'm most likely to be interested in the most recent occurence - not in the oldest one. So please change the sort order.

### Additional context

Nextcloud Version ist 26.0.2
Calendar the most recent stable 4.3.4

**Comment by tcitworld** [comment] 2023-06-04 14:34
Duplicate of https://github.com/nextcloud/server/issues/27353

**Closed by tcitworld** 2023-06-04 14:34 UTC
Labels: enhancement, 0 - to triage
