### ISSUE TITLE
No way to delete event in calendar web UI

### ISSUE THREAD

**Issue by cu** [nextcloud/calendar#2851] opened 2021-01-28 11:31 UTC
I just upgraded my nextcloud instance to 20 and there no longer seems to be a button or any other way to delete events in the calendar web UI.

### Steps to reproduce
1. Create an event
2. Decide you don't want it anymore
3. Click on the event
4. Click More
5. No Delete button to be found

### Expected behaviour
There used to be a Delete button, next to the Update button in the More view. I'm pretty sure of it.

### Actual behaviour
There is no Delete button, nor any other way to delete an event that I can see. I can still delete events from my phone's native calendar app.

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** Firefox 84.0.2

**Operating system:** Ubuntu

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7.2

**Nextcloud Version:** 20.0.6

**Updated from an older installed version or fresh install:** Updated from older version

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.1.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - files_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "cloud.example.net"
        ],
        "share_folder": "\/Shared",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": "1048576",
        "defaultapp": "calendar",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/cloud.example.net"
    }
}

```

**Comment by tcitworld** [comment] 2021-01-28 12:53
See the following screenshots:

![Screenshot_2021-01-28 January 2021 - Calendar - Mon petit nuage](https://user-images.githubusercontent.com/2197836/106141302-2d597180-6170-11eb-839f-b0d01795a568.png)
![Screenshot_2021-01-28 January 2021 - Calendar - Mon petit nuage(1)](https://user-images.githubusercontent.com/2197836/106141304-2d597180-6170-11eb-9ced-9eeafa2e0cee.png)

**Comment by tcitworld** [comment] 2021-11-02 15:16
You need to click on « More » first, it's in the event full edition mode. Having it in the simple editor is a duplicate of https://github.com/nextcloud/calendar/issues/2893 and will be fixed in 2.4.

**Closed by tcitworld** 2021-11-02 15:16 UTC
Labels: bug, 0. to triage

**Comment by DagNygren** [comment] 2022-01-11 16:12
I would like to reopen this as I do not have a drop down for the event - Only a download button - even after pressing more. So there is no way to delete the event. Also see no way to modify the start and end time of the event. As a matter of fact I just noticed that there are no edit possibilities at all ??? Something in my config? Some nonintuitive thing to do to get into edit mode?

**Comment by sekurarj** [comment] 2022-01-15 23:25
I also see this issue. There is no delete option - only download. I saw it when syncing an appt with attendees from outlook calendar using caldav and also in nextcloud when using the appointment app for clients to create their own appts, which also has attendees
![No Delete](https://user-images.githubusercontent.com/57014279/149640919-0d0f9eb9-3e76-48e5-9967-fc03ca78e8dc.PNG)
.

**Comment by sekurarj** [comment] 2022-01-15 23:39
Trying to be more clear - I can delete an appointment created in Calendar but not one created using the public link to the appointment app for external users to create an appointment. 
![Can Delete](https://user-images.githubusercontent.com/57014279/149641163-cc56c8f3-f923-4f19-b32a-3d5aede59163.PNG)
![No Delete](https://user-images.githubusercontent.com/57014279/149641165-6017386d-1084-4c42-bbfa-47962e6089f1.PNG)

**Comment by sekurarj** [comment] 2022-01-15 23:47
Just trying to be more clear - There is a delete option when creating an appointment in calendar. There is no delete option (Only Download) when the appointment is created by an external user with the appointments add on application. And no delete when an appt with attendees is synced from an outlook calendar. Actually no ability to Edit the appointment at all.
![Can Delete](https://user-images.githubusercontent.com/57014279/149641305-957f483b-d3de-47ac-81ff-df68ef0f18d8.PNG)
![No Delete](https://user-images.githubusercontent.com/57014279/149641308-1ab53f73-44c2-4701-b57d-be73c38edf3b.PNG)

**Comment by spectroscopist** [comment] 2022-01-18 17:52
> Just trying to be more clear - There is a delete option when creating an appointment in calendar. There is no delete option (Only Download) when the appointment is created by an external user with the appointments add on application. And no delete when an appt with attendees is synced from an outlook calendar. Actually no ability to Edit the appointment at all. ![Can Delete](https://user-images.githubusercontent.com/57014279/149641305-957f483b-d3de-47ac-81ff-df68ef0f18d8.PNG) ![No Delete](https://user-images.githubusercontent.com/57014279/149641308-1ab53f73-44c2-4701-b57d-be73c38edf3b.PNG)

I also see this issue, identical behaviour as described by sekurarj for a series of events received as invitation.
Was able to delete a single event from the series only in Korganizer. Sync then updated also the server.

**Comment by tcitworld** [comment] 2024-06-18 15:40
Please open a new issue with all issue template details filled.
