### ISSUE TITLE
public shared calender: timezone error on opening public link

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/calendar#2264] opened 2020-05-11 10:06 UTC
### Steps to reproduce
1. Create a share link for a calendar
2. Open the share link in (different) browser (without login)

### Expected behaviour
Calendar is shown

### Actual behaviour
Error Message "Die konfigurierte Zeitzone ({timezoneId}) wurde nicht gefunden. Rückfall auf UTC.
Bitte die Zeitzone in den Einstellungen ändern und melden dieses Problem melden.", no calendar is shown

Changing the timezone in the settings (with the user which shares the calendar) does not change everything. I didn't found a setting to change the timezone for unauthenticated users.

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** none

### Client configuration
**Browser:** Chrome 81 (Firefox 75 also)

**Operating system:** WIndows 10

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 18.0.4

**Updated from an older installed version or fresh install:** Update

**List of activated apps:**

  - accessibility: 1.4.0
  - activity: 2.11.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.0
  - drop_account: 0.2.1
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.3.0
  - files_downloadactivity: 1.7.0
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - gpxedit: 0.0.13
  - guests: 1.4.6
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - notes: 3.3.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - photos: 1.0.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - quotaadmin: 0.0.2
  - recommendations: 0.6.0
  - richdocuments: 3.5.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - spreed: 8.0.8
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "installed": true,
        "default_language": "de",
        "updatechecker": true,
        "has_internet_connection": true,
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "appstoreenabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "cloud.tu-ilmenau.de",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.tu-ilmenau.de",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/data\/nextcloud_skel",
        "theme": "tui",
        "activity_expire_days": 14,
        "integrity.check.disabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "knowledgebaseenabled": false,
        "defaultapp": "apporder",
        "sharing.minSearchStringLength": 4,
        "sharing.maxAutocompleteResults": 5,
        "maintenance": false,
        "debug": false,
        "htaccess.RewriteBase": "\/",
        "proxy": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.release.channel": "stable",
        "lookup_server": "",
        "app_install_overwrite": [
            "files_upload_mtime",
            "quotaadmin",
            "drop_account"
        ],
        "preview_max_x": 800,
        "preview_max_y": 800,
        "preview_max_scale_factor": 1,
        "tempdirectory": "\/data\/tmp\/nextcloud"
    }
}

#### Web server error log (e.g. /var/log/apache)

no messages in apache log or in nextcloud.log

#### Browser log
```
Insert your browser log here, this could for example include:

ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2
ConsoleLogger.js:54 [ERROR] calendar: VTimezoneNamedTimezoneImpl: Timezone null not found, falling back to UTC. Object
value @ calendar.js?v=862e8306:2

**Comment by georgehrke** [comment] 2020-05-11 10:07
> I didn't found a setting to change the timezone for unauthenticated users.

Duplicate of #2173

**Closed by georgehrke** 2020-05-11 10:07 UTC
Labels: 0. to triage, bug

**Comment by alx-tuilmenau** [comment] 2020-05-11 10:11
Isn't there a way to avoid the error, so public calendars can be used until 2.2.0 is out ? Maybe a lobal default ?

**Comment by georgehrke** [comment] 2020-05-11 10:15
> Isn't there a way to avoid the error,

The error is most likely a configuration issue on your side. I'm seeing that you are using a custom theme. The template for public pages is most likely missing essential code. (`IInitialStateService`)

If you don't know how to fix that, please ask at https://help.nextcloud.com

**Comment by tcitworld** [comment] 2020-05-11 10:25
For reference, the setting [is set here](https://github.com/nextcloud/calendar/blob/32c1e9e95a486a06f334b58cccd4bc05523d058e/lib/Controller/PublicViewController.php#L121) and is controlled by
```bash
php occ config:app:set calendar timezone --value "%value%"
```

**Comment by alx-tuilmenau** [comment] 2020-05-11 10:35
@georgehrke Thanks a lot, found the error in the theme layout.public.php and it works now.
