### ISSUE TITLE
Make Details text selectable in read-only events

### ISSUE THREAD

**Issue by tobip** [nextcloud/calendar#917] opened 2018-10-04 10:09 UTC
### Steps to reproduce
1. Subscribe to a read-only calendar, e.g. Facebook-Events
2. Click on an event of this calendar, then click on More...
3. See the Description text

### Expected behaviour
I would like to select and copy the text of the event Description.

### Actual behaviour
Text field is blocked, I can read but not select the text.

### Server configuration

**Server version:** (see your admin page)
14.0.1

**Calendar version:** (see the apps page)
1.6.2

**Comment by georgehrke** [comment] 2018-10-04 10:09
Duplicate of #641

**Closed by georgehrke** 2018-10-04 10:09 UTC
