### ISSUE TITLE
Optional update notification if a event was changed

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#2564] opened 2020-09-07 08:23 UTC
If an event was changed there is no update info sent to the attendees.
It would be nice to send an optional update after the event was changed.

**Comment by georgehrke** [comment] 2020-09-07 08:32
Duplicate of https://github.com/nextcloud/server/issues/5222

**Closed by georgehrke** 2020-09-07 08:32 UTC
Labels: 0. to triage, enhancement-proposed

**Comment by jakobroehrl** [comment] 2020-09-07 08:48
Sorry, it's unclear to me what's the right repo: calendar or server

**Comment by georgehrke** [comment] 2020-09-07 08:49
In this case Server, because sending out invitation emails is part of the dav app, which is in the server repo.
