### ISSUE TITLE
Time display

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#1919] opened 2020-01-26 21:06 UTC
### Steps to reproduce
1. Create a new appointment in the calendar.
2. Set the time, e.g. 17:00.
3. Save the date.

### Expected behaviour
Displaying the time as 17:00.

### Actual behaviour
The time displayed is only 17.

![obraz](https://user-images.githubusercontent.com/47037905/73141734-afa7e500-4087-11ea-876e-d0fca77e23be.png)

In my opinion, the time should be displayed along with 00 minutes.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.1

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.0

**Comment by georgehrke** [comment] 2020-01-26 21:12
Duplicate of https://github.com/nextcloud/calendar/issues/1736

**Closed by georgehrke** 2020-01-26 21:12 UTC
Labels: 0. to triage, bug
