### ISSUE TITLE
Unable to add new events or edit existing in Firefox v66

### ISSUE THREAD

**Issue by andyforceno** [nextcloud/calendar#1683] opened 2019-11-25 22:31 UTC
** This is unique to Firefox, it doesn't occur in Chrome. I disabled all content blocking in Firefox as well as any add-ons that may prevent js from loading, but it didn't resolve the issue. I can also reproduce the issue in a private window in Firefox **

### Steps to reproduce:
1. In Firefox v66 desktop application, click the New Event button in Calendar app or click on an existing event to edit it

### Expected behaviour
When clicking to add a new event or edit an existing, I expect to be shown a properties dialog/popout window to enter/modify event title, location, start and end times, etc. 

### Actual behaviour
Popout window with loading indicator circle displays, but the window with text fields for event info never actually loads. There are no errors in the log when this happens. 

### Calendar app
Version 1.7.1 

**CalDAV-clients used:** I use Thunderbird Lightning, but in this case it's not applicable to the issue

### Client configuration
**Browser:** Firefox v66.0.3

**Operating system:** Ubuntu Linux 14.04

### Server configuration

**Operating system**: Ubuntu Server 18.04

**Web server:** nginx

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud Version:** 17.0.1

**Updated from an older installed version or fresh install:** Fresh install, though the database was migrated from Nextcloud 13 (or maybe 14)

**List of activated apps:**
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - calendar: 2.0.0-beta2
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 0.19.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.0.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***DOMAIN REMOVED***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "***DOMAIN REMOVED***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}

#### Browser log
When I click the New Event button, I see this error in dev console:
```TypeError: "t.$store.dispatch(...).then(...).catch(...).finally is not a function" in calendar.js:933:11636```

On loading the Calendar app page, I see the following warnings: 
```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://DOMAIN-REMOVED/nextcloud/apps/calendar/js/calendar.js?v=4001480d-29
Source Map URL: calendar.js.map
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://DOMAIN-REMOVED/nextcloud/core/js/dist/main.js?v=4001480d-29
Source Map URL: main.js.map```

**Comment by georgehrke** [comment] 2019-11-28 10:08
> TypeError: "t.$store.dispatch(...).then(...).catch(...).finally is not a function" in calendar.js:933:11636

Are you absolutely sure you are using Calendar 1.7.1 and not the beta version of Calendar 2?

**Comment by georgehrke** [comment] 2019-11-28 10:09
In case you are running the beta, this is a duplicate of https://github.com/nextcloud/calendar/issues/1633

**Comment by andyforceno** [comment] 2019-11-28 12:47
> > TypeError: "t.$store.dispatch(...).then(...).catch(...).finally is not a function" in calendar.js:933:11636
> 
> Are you absolutely sure you are using Calendar 1.7.1 and not the beta version of Calendar 2?

That's what Nextcloud reports as the version number. I recall downloading it manually from https://apps.nextcloud.com/apps/calendar (I think). For the record, here's what my issue looks like: 

![nextcloud-cal](https://user-images.githubusercontent.com/3803896/69807340-0d689f80-11b3-11ea-8e0e-0788f04c7685.png)

It just appears to load like that forever, so I can not set the event information. Calendar otherwise works fine.

**Comment by georgehrke** [comment] 2019-11-28 12:48
Looking at the screenshot you are definitely running Version 2 beta

Duplicate of #1633 in that case.

**Closed by georgehrke** 2019-11-28 12:48 UTC
Labels: 0. to triage, bug

**Comment by andyforceno** [comment] 2019-11-28 12:56
This may be a duplicate of that issue, but I am certain I am using calendar v1.7.1 as I just reinstalled it and I'm still having the problem. I cannot reproduce it in Firefox 71, though. It's not a big deal for me personally, I usually access the calendar through Thunderbird and mobile apps.

**Comment by georgehrke** [comment] 2019-11-28 13:02
I'm sorry, but looking at that screenshot I'm 100% sure, absolutely no doubt, that you are running Calendar 2 beta. Version 1 looks completely different in dark mode.

I also double checked that we didn't accidentally release Calendar 2 beta on the stable channel.

Did you possibly test 2 beta in between, downgrade to 1 but now the javascript files of 2 beta are still cached in your browser?

**Comment by andyforceno** [comment] 2019-11-28 13:10
I don't recall doing that, but it's not out of the realm of possibility. I will defer to your expertise in this case and keep the issue closed. Thanks for looking into it.
