### ISSUE TITLE
Color Information for Calendars not saved

### ISSUE THREAD

**Issue by ematow** [nextcloud/calendar#1506] opened 2019-10-02 14:25 UTC
Hi,

It seems that with the last update a new bug was introduced — all colors changed, and the app does not seem to be able to save non-standard colors (those chosen from the color picker).

Best,
Ematow

**Comment by georgehrke** [comment] 2019-10-02 14:26
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

I will reopen when you filed the issue template

**Comment by tcitworld** [comment] 2019-10-02 14:27
It's probably a duplicate of #1446 anyway.

**Closed by georgehrke** 2019-10-02 14:26 UTC
