### ISSUE TITLE
Recurring events 

### ISSUE THREAD

**Issue by mattiaaeternity** [nextcloud/calendar#1927] opened 2020-01-28 15:14 UTC
**Is your feature request related to a problem? Please describe.**
This feature request is related to a problem in the calendar / event creation. 

**Describe the solution you'd like**
I like to have more options when creating recurring events. 
– Monthly on the second [day]
– Every weekday [Mon – Fri]
– Pick the days of a week
– Skip a specific day of the interval
– Move a single event, while keeping the initial interval the same
Ability to enter a specific end date
– 
**Describe alternatives you've considered**
A nice alternative is Google's calendar creation. This is essentially what I'm aiming for.

**Additional context**
Screenshot attached.

<img width="641" alt="Screenshot 2020-01-28 at 16 13 47" src="https://user-images.githubusercontent.com/43239393/73276555-2c9ea000-41e9-11ea-839b-2ef2ee556f58.png">

**Comment by georgehrke** [comment] 2020-01-28 15:15
Please update to Calendar 2.0

**Comment by georgehrke** [comment] 2020-01-28 15:15
Duplicate of #10

**Closed** 2020-01-28 15:14 UTC
Labels: 0. to triage, enhancement-proposed

**Comment by mattiaaeternity** [comment] 2020-01-29 11:30
I can't find the feature on Nextcloud. It hasn't been fixed. Therefore, I don't understand why my request has been closed.

**Comment by georgehrke** [comment] 2020-01-29 11:31
@mattiaaeternity The screenshot you provided is from Calendar 1.x. Please update to the latest version of Calendar 2

**Comment by mattiaaeternity** [comment] 2020-01-29 11:33
Okay, I can see it now. Thank you very much! :-)
