### ISSUE TITLE
UI option to create talk room for every booked appointment

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/calendar#4024] opened 2022-03-07 13:04 UTC

**Comment by schiessle** [comment] 2022-03-15 09:26
Some thoughts how this feature could look like:

Create a room after the appointment was confirmed (otherwise a lot of unnecessary rooms could be created), attach it to the calendar invite and resend it to the participants.

I would configure the room the following way:

1. Set the name to `booked appointment by <user who requested the appointment>`
2. Put in the room description what the person put into the "Please share anything that will help prepare for our meeting" so that the organizer can see directly what the meeting is about when opening the room.
3. Set the lobby to the start date of the requested appointment date


Probably this functionality needs to be a setting people can enable/disable in the appointment setup because not every Nextcloud instance comes with Talk and some people might use this feature to schedule phone meetings, on-site meetings, etc. In this case a generic location for everyone can make sense.

**Comment by ChristophWurst** [comment] 2022-03-15 09:26
See https://github.com/nextcloud/calendar/issues/3480

**Comment by ChristophWurst** [comment] 2022-05-23 07:55
Resetting status due to staleness.

**Comment by ChristophWurst** [comment] 2023-02-03 15:02
Closing this empty ticket. Let's continue in https://github.com/nextcloud/calendar/issues/3480.

**Closed by ChristophWurst** 2023-02-03 15:02 UTC
Labels: 1 - to develop
