### ISSUE TITLE
Event modal window resizes itself out of the screen.

### ISSUE THREAD

**Issue by piiskop** [nextcloud/calendar#2692] opened 2020-11-11 20:57 UTC
### Steps to reproduce
1. Enter a new event with at least six rows in description using the screen resolution of 1366*768 px!
2. Reopen that event!
3. See that the event's modal window resizes itself so that the closing "x" doesn't fit to screen and the description box is large as hell although it only contains these six rows of text. Sometimes the event's modal window just jumps around the screen.

### Expected behaviour
The event's modal window should open and not jump around and not resize itself. It could make use of a vertical scrollbar. Please see how it works in Google Calendar - that's so convenient and the Nextcloud's calendar just tries to bully.

### Actual behaviour
Actual behaviour is that the window sometimes jumps around and every time it resizes itself so that the closing "x" is unseen.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.4
### Client configuration
**Browser:** (e.g. Firefox 48)
Google Chrome
Version 86.0.4240.183 (Official Build) (64-bit)
**Operating system:** (e.g. Arch Linux)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

### Server configuration

**Operating system**: (e.g. Debian 8)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Web server:** (e.g. Apache, Nginx,...)
Apache and Nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0.3)
PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.7, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
Nextcloud 19.0.4
**Updated from an older installed version or fresh install:**
updated
**List of activated apps:**
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - audioplayer: 2.12.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.1.2
  - drawio: 0.9.7
  - drop_account: 0.2.1
  - emlviewer: 0.0.18
  - external: 3.6.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_automatedtagging: 1.9.0
  - files_external: 1.10.0
  - files_external_gdrive: 0.4.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.0.4
  - gpxmotion: 0.0.11
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - metadata: 0.12.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 2.1.2
  - password_policy: 1.9.1
  - photos: 1.1.0
  - polls: 1.5.7
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - registration: 0.5.0
  - richdocuments: 3.7.8
  - scanner: 0.1.9
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.5
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - weather: 1.7.3
  - wopi: 3.5.6
  - workflowengine: 2.1.0
Disabled:
  - dicomviewer
  - encryption
  - ojsxc
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.tennis24.ee"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "https:\/\/test.tennis24.ee\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "onlyoffice",
            "dashboard",
            "files_external_gdrive",
            "dicomviewer"
        ],
        "tempdirectory": "\/projektid\/nextcloud\/data",
        "overwriteprotocol": "https",
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "has_rebuilt_cache": true
    }
}

**Comment by szaimen** [comment] 2021-09-28 09:14
Most likely duplicate of #2200

**Closed by szaimen** 2021-09-28 09:14 UTC
Labels: 1 - to develop, bug
