### ISSUE TITLE
Public calendar is not loading events

### ISSUE THREAD

**Issue by blaiseju** [nextcloud/calendar#4041] opened 2022-03-10 17:17 UTC
### Steps to reproduce

I'm running a personnal nextcloud instance and I would like share calendars with other people who don't have nextcloud's account.
So I'm using public link fonctionnality which generate an URL properly. But when I try to display calendar through public link, calendar displays month but no events and is loading indefinitely.
I have no errors in server's log but there are two errors on client's side (tested on firefox and Brave) : 
 - Could not find initial state hide_event_export of calendar
 - Files_PDFViewer: But this does not appear to be a public page

You could access test calendar on : https://blaiseju.ddns.net/apps/calendar/p/MPyko3cZA7SF32YE to reproduce problem.
![2022-03-10_17h59_34](https://user-images.githubusercontent.com/101351677/157715455-e7f03981-4dcb-4ed2-98c6-1cf0849c90eb.png)

### Expected behavior

Public calendar should load events and functionnality without errors.

### Actual behaviour

Public calendar only loads the month without the associated events. Furthermore, calendar stays loading indefinitely.

### Calendar app version

3.2.0

### Browser

Firefox 93.0 and Brave 1.36.111

### Client operating system

Windows 7

### Server operating system

Docker

### Nextcloud version

23.0.2

### List of activated apps

```Text
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - mail: 1.11.7
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.10.100:32680",
            "cloud.blaiseju.duckdns.org",
            "blaiseju.ddns.net",
            "82.65.11.70"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "http:\/\/192.168.10.100:32680",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "overwriteprotocol": "https",
        "default_phone_region": "FR",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Log file

```Text
{"reqId":"qapYocPzxSfz4LF3gSVI","level":1,"time":"2022-03-10T16:03:42+00:00","remoteAddr":"172.17.0.1","user":"Julien","app":"no app in context","method":"PROPFIND","url":"/remote.php/dav/files/Julien/","message":"Unable to generate a URL for the named route \"contacts.contacts.directcircle\" as such route does not exist.","userAgent":"Mozilla/5.0 (Windows) mirall/3.4.1stable-Win64 (build 20211221) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"23.0.2.1","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"contacts.contacts.directcircle\" as such route does not exist.","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Route/Router.php","line":365,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["contacts.contacts.directcircle",{"singleId":"BS5OCRSKxvuo5PLRNy77EUGV65EKo8C"},1]},{"file":"/var/www/html/lib/private/Route/CachingRouter.php","line":59,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["contacts.contacts.directcircle",{"singleId":"BS5OCRSKxvuo5PLRNy77EUGV65EKo8C"},false]},{"file":"/var/www/html/lib/private/URLGenerator.php","line":91,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["contacts.contacts.directcircle",{"singleId":"BS5OCRSKxvuo5PLRNy77EUGV65EKo8C"}]},{"file":"/var/www/html/apps/circles/lib/Model/ModelManager.php","line":560,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["contacts.contacts.directcircle",{"singleId":"BS5OCRSKxvuo5PLRNy77EUGV65EKo8C"}]},{"file":"/var/www/html/apps/circles/lib/Model/Circle.php","line":703,"function":"generateLinkToCircle","class":"OCA\\Circles\\Model\\ModelManager","type":"->","args":["BS5OCRSKxvuo5PLRNy77EUGV65EKo8C"]},{"file":"/var/www/html/apps/circles/lib/Model/Circle.php","line":820,"function":"getUrl","class":"OCA\\Circles\\Model\\Circle","type":"->","args":[]},{"function":"jsonSerialize","class":"OCA\\Circles\\Model\\Circle","type":"->","args":[]},{"file":"/var/www/html/apps/circles/lib/Service/FederatedUserService.php","line":1225,"function":"json_encode","args":[{"__class__":"OCA\\Circles\\Model\\Circle"}]},{"file":"/var/www/html/apps/circles/lib/Service/FederatedUserService.php","line":999,"function":"cacheSingleCircle","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":[{"__class__":"OCA\\Circles\\Model\\FederatedUser"},{"__class__":"OCA\\Circles\\Model\\Circle"}]},{"file":"/var/www/html/apps/circles/lib/Service/FederatedUserService.php","line":911,"function":"getSingleCircle","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":[{"__class__":"OCA\\Circles\\Model\\FederatedUser"},true]},{"file":"/var/www/html/apps/circles/lib/Service/FederatedUserService.php","line":489,"function":"fillSingleCircleId","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":[{"__class__":"OCA\\Circles\\Model\\FederatedUser"},true]},{"file":"/var/www/html/apps/circles/lib/ShareByCircleProvider.php","line":553,"function":"getLocalFederatedUser","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/lib/private/Share20/Manager.php","line":1375,"function":"getSharedWith","class":"OCA\\Circles\\ShareByCircleProvider","type":"->","args":["*** sensitive parameter replaced ***",7,null,-1,0]},{"file":"/var/www/html/apps/files_sharing/lib/MountProvider.php","line":90,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->","args":["*** sensitive parameter replaced ***",7,null,-1]},{"file":"/var/www/html/lib/private/Files/Config/MountProviderCollection.php","line":118,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Storage\\StorageFactory"}]},{"file":"/var/www/html/lib/private/Files/Filesystem.php","line":429,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Mount\\Manager"}]},{"file":"/var/www/html/lib/private/Files/Filesystem.php","line":354,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/lib/private/legacy/OC_Util.php","line":326,"function":"init","class":"OC\\Files\\Filesystem","type":"::","args":["*** sensitive parameter replaced ***","/Julien/files"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Auth.php","line":123,"function":"setupFS","class":"OC_Util","type":"::","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php","line":103,"function":"validateUserPass","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Auth.php","line":252,"function":"check","class":"Sabre\\DAV\\Auth\\Backend\\AbstractBasic","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Auth.php","line":154,"function":"auth","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":182,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":137,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":143,"CustomMessage":"--"}}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Circles\\Cron\\Maintenance job with ID 663","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:01+00:00","remoteAddr":"","user":"--","app":"","method":"","url":"--","message":"[debug] running maintenance (1)","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Circles\\Cron\\Maintenance job with ID 663 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 14","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 14 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\DAV\\BackgroundJob\\EventReminderJob job with ID 404","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\DAV\\BackgroundJob\\EventReminderJob job with ID 404 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 15","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating session tokens older than 2022-03-09T16:05:04+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating remembered session tokens older than 2022-02-23T16:05:04+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating session tokens older than 2022-03-09T16:05:04+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating remembered session tokens older than 2022-02-23T16:05:04+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 15 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:06+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 501","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:06+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 501 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:06+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 4","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:06+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 4 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 164","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating session tokens older than 2022-03-09T16:05:07+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating remembered session tokens older than 2022-02-23T16:05:07+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating session tokens older than 2022-03-09T16:05:07+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating remembered session tokens older than 2022-02-23T16:05:07+00:00","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 164 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Log\\Rotate job with ID 165","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:07+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Log\\Rotate job with ID 165 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:08+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 723","userAgent":"--","version":"23.0.2.1"}
{"reqId":"apEYdgnGEYdLbuNRATX4","level":0,"time":"2022-03-10T16:05:08+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 723 in 0 seconds","userAgent":"--","version":"23.0.2.1"}
```

### Browser log

```Text
No OC found index.js:46:12
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:708
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
[DEBUG] @nextcloud/vue: Using version 2.2019c of the timezone database 
Object { app: "@nextcloud/vue" }
ConsoleLogger.js:29:16
@nextcloud/calendar-js app is using version 2.2019c of the timezone database index.esm.js:14165:2
Error: Could not find initial state hide_event_export of calendar
    loadState index.js:24
    e Calendar.vue:221
    u dist.js:1
    _invoke dist.js:1
    S dist.js:1
    XF AppointmentConfigList.vue:127
    o AppointmentConfigList.vue:127
    tx AppointmentConfigList.vue:127
    tx AppointmentConfigList.vue:127
    beforeMount Calendar.vue:207
    VueJS 27
    <anonymous> main.js:76
    <anonymous> main.js:83
    <anonymous> main.js:83
vue.runtime.esm.js:1897:4
session heartbeat polling started session-heartbeat.js:101:9
[DEBUG] Files_PDFViewer: Initializing for public page 
Object { app: "Files_PDFViewer", isPublicPage: false, canDownload: true, isSecureViewerAvailable: false }
ConsoleLogger.js:42:18
[ERROR] Files_PDFViewer: But this does not appear to be a public page 
Object { app: "Files_PDFViewer" }
ConsoleLogger.js:54:18
    value ConsoleLogger.js:54
    value ConsoleLogger.js:80
    <anonyme> public.js:74
[INFO] calendar: Updated moment locale: fr 
Object { app: "calendar" }
ConsoleLogger.js:33:16
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 164 globals.js:62:15
OC.requestToken changed ONJW4yljS+NIK8BaESbKstjDNS/21Ne46o1A4Lt7reU=:DaQYlWMHBLYuU/MAaESvio/3RVi1sIDPr+URl9oozKg= index.js:321:9
OC.requestToken changed nDW067ngmdiypxdiZ6Z5JCoPtWJPSd1qPpQBwmwVN2E=:qUP6nfOE1o3U3yQ4HsQcHH07xRUMLYode/xQtQ1GViw= index.js:321:9
```

**Comment by max65482** [comment] 2022-03-10 17:32
Seems like a duplicate of #4033.

**Closed** 2022-03-10 18:38 UTC
Labels: bug, 0. to triage
