### ISSUE TITLE
IE11: No date fields with NC16

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/calendar#1399] opened 2019-08-13 15:39 UTC
### Steps to reproduce
1. Open NC16 Calendar
2. IE11: **No** date fields shown. OS Win 10/7 with IE11. See Screenshot
3. Edge Browser/FF show date fields

### Expected behaviour
IE11 should show date fields.

### Server configuration
Server Debian 10 with Nextcloud 16.0.3 (latest) / Calendar 17.0

**PHP version:**
PHP 7.3

**Updated from an older installed version or fresh install:**
System was updated! Old configuration was ok
Debian 9 to Debian 10
Nextcloud 15 to Nextcloud 16
PHP 7.0 to 7.3

Hello.

**After upgrade** i can not see the date fields with IE11 Browser. All other parts/modules/apps of nextcloud work as expected with IE11.
Is it a bug of nextcloud 16 or calendar 1.7.0?
Is a PHP Module missing?
Is there a workaround?

No hint in logfiles.

Can someone please check/confirm this please.

Thanks.
![ie11nc16calendar](https://user-images.githubusercontent.com/47995430/62955148-e0090900-bdf0-11e9-92c2-fc041666a2a7.png)

**Comment by tcitworld** [comment] 2019-08-13 16:37
Logs that OP didn't provide:
```
only one instance of babel-polyfill is allowed
vendor.ie.min.js (1,523)
« angular » is undefined
app.min.js (1,2)
```
I'm guessing babel-polyfill is brought in by another app or core somehow.
Also there's a (probably) unrelated CORS redirection issue.

**Comment by georgehrke** [comment] 2019-08-13 18:13
Duplicate of https://github.com/nextcloud/calendar/issues/1286

**Closed by georgehrke** 2019-08-13 18:13 UTC
