### ISSUE TITLE
Events not shown correctly in day and week view

### ISSUE THREAD

**Issue by arshubham** [nextcloud/calendar#794] opened 2018-04-08 05:50 UTC
### Steps to reproduce
1. Create an event spanning 1/2 hr or more say 1 - 1:30 (Event 1)
2. Create another event above it spanning 1/2 hr (12:30-1)  (Event 2)
3. Event 2 spans the whole width while Event 1 only half on the right.

### Expected behaviour
Both events should span the whole width of the row.

### Actual behaviour
Both events should do not span the whole width of the row. 
![image](https://user-images.githubusercontent.com/14235191/38463631-82311a28-3b1c-11e8-8669-6692ebdd1011.png)

### Server configuration

**Operating system**:
`Ubuntu 16.04`  
kernel: `4.4.0-119-generic`

**Web server:**
`apache 2.4.18-2ubuntu3.5 amd64`

**Database:**
`mysql 5.7.21-0ubuntu0.16.04.1 amd64`

**PHP version:**
`php 7.0.28-0ubuntu0.16.04.1`

**Server version:** (see your admin page)
`13.0.1`

**Calendar version:** (see the apps page)
` 1.6.1`

**Updated from an older installed version or fresh install:**
`fresh install`

**Signing status (ownCloud/Nextcloud 9.0 and above):**
`No errors have been found.`

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.5
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_twitter: 1.0.2
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - files_external
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "shubhamarora.in"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/shubhamarora.in\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
`Firefox 61.0a1 20180407220122`

**Operating system:**
`elementary os 0.4.1 Loki`

**Comment by georgehrke** [comment] 2018-04-23 09:56
Duplicate of #767

**Closed by georgehrke** 2018-04-23 09:56 UTC
