### ISSUE TITLE
Delete an event - spare some clicks

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/calendar#2247] opened 2020-05-09 13:58 UTC
**Is your feature request related to a problem? Please describe.**
Do delete an event I need to:
1. click on the event (okay)
2. click at "more"
3. click at "..."
4. click at delete

**Describe the solution you'd like**
Give me the the ability to delete an event on overview of an event or latest at sidebar (which is without hiding behind "...".

**Additional context**
While testing appointments app I figured out it's actually a lot of clickwork to delete an event, and it becomes vastly annoying if you delete a bunch of them.

**Comment by georgehrke** [comment] 2020-05-09 13:59
Duplicate of #1570

**Closed by georgehrke** 2020-05-09 13:59 UTC
Labels: 0. to triage, enhancement-proposed
